Замена селекторов тегов на селекторы классов
VKCOM/VKUI pull request #1021
Opened 2020-09-16 20:09 UTC by mikhin

Приветствую!

Заменил селекторы тегов на селекторы классов в компонентах `Select` и `Textarea`.

Мотивация — более полноценное следование методологии БЭМ, которая не позволяет использовать селекторы тегов.

> В БЭМ не используют селекторы тегов и идентификаторов. Стили блоков и элементов описываются через селекторы классов. - https://ru.bem.info/methodology/css/#%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D1%8B

Следовать этому правило помогает правило линтера Stylelint `selector-max-type` со значением `0`.

В текущем состоянии проекта правило также находит ошибки в следующих компонентах:
- src/styles/styles.css
```
  95:1  ✖  Expected "html" to have no more than 0 type selectors       selector-max-type
  96:1  ✖  Expected "body" to have no more than 0 type selectors       selector-max-type
  97:1  ✖  Expected "div#root" to have no more than 0 type selectors   selector-max-type
 109:1  ✖  Expected "body" to have no more than 0 type selectors       selector-max-type
 113:1  ✖  Expected "input" to have no more than 0 type selectors      selector-max-type
 114:1  ✖  Expected "textarea" to have no more than 0 type selectors   selector-max-type
 115:1  ✖  Expected "select" to have no more than 0 type selectors     selector-max-type
 116:1  ✖  Expected "button" to have no more than 0 type selectors     selector-max-type
 124:1  ✖  Expected "a:focus" to have no more than 0 type selectors    selector-max-type
```
Возможное решение — не использовать глобальные стили и селекторы тегов. На уровне библиотеки определить текущие правила во всех нужных компонентах точечно. К примеру, правило `button { font-family: inherit; }`, кажется, нужно определить только для элемента `Snackbar__action`, и, конечно, для компонента `Tappable`.

- src/components/Alert/Alert.css
```
  72:5  ✖  Expected ".Alert--ios .Alert__content h2" to have no more than 0 type selectors          selector-max-type
  79:5  ✖  Expected ".Alert--ios .Alert__content p" to have no more than 0 type selectors           selector-max-type
 216:5  ✖  Expected ".Alert--android .Alert__content h2" to have no more than 0 type selectors      selector-max-type
 223:5  ✖  Expected ".Alert--android .Alert__content p" to have no more than 0 type selectors       selector-max-type
 227:5  ✖  Expected ".Alert--android .Alert__content p + p" to have no more than 0 type selectors   selector-max-type
```
Возможное решение — создать компонент `AlertContent` и именно на его уровне определить текущие CSS-правила, отключив для него правило линтера `selector-max-type`. Таким образом получится разделить ответственность между компонентами, следуя [принципу единственной ответственности](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8)

- src/components/FormStatus/FormStatus.css
```
 29:5  ✖  Expected ".FormStatus__content b" to have no more than 0 type selectors   selector-max-type
```
Возможное решение — определить дополнительный Реакт-компонент для сущности БЭМ-элемента `<FormStatus__HighlightedPhrase>`, вызывая при этом компонент `FormStatus` в рабочем проекте следующим образом:

```
<FormStatus header="Некорректный мобильный номер" mode="error">
  <FormStatus__HighlightedPhrase>
    Необходимо корректно ввести номер в международном формате
  </FormStatus__HighlightedPhrase>
</FormStatus>
```

Не смотря на то, что вызов получится чуть более многословным, API компонента станет более выразительным. При этом пропс `dangerouslySetInnerHTML` в API компонента вероятно получится упразднить (возможно, я ошибаюсь).

- src/components/Gradient/Gradient.css
```
  1:1  ✖  Expected "body[scheme='bright_light'] .Gradient--md-tint.Gradient--to-top" to have no more than 0 type selectors      selector-max-type
  5:1  ✖  Expected "body[scheme='bright_light'] .Gradient--md-tint.Gradient--to-bottom" to have no more than 0 type selectors   selector-max-type
  9:1  ✖  Expected "body[scheme='space_gray'] .Gradient--md-tint.Gradient--to-top" to have no more than 0 type selectors        selector-max-type
 13:1  ✖  Expected "body[scheme='space_gray'] .Gradient--md-tint.Gradient--to-bottom" to have no more than 0 type selectors     selector-max-type
```
Возможное решение — определить стили в классах модификаторов компонента.

- src/components/Spinner/Spinner.css
```
 30:3  ✖  Expected ".Spinner__self svg" to have no more than 0 type selectors   selector-max-type
```

Возможное решение — перенести CSS-правило (transform: scale(1)) в библиотеку `@vkontakte/icons`, добавив возможность при этом использовать его через вызов компонентов пиктограмм с соответствующим пропсом.

Если какое-то из предложенных решений покажется справедливым и привлекательным, я могу внести эти правки в этом или следующих ПР.

Буду рад предложениям, замечаниям и комментариям.

2020-09-28 17:21 UTC, ArthurStam commented
Привет. Спасибо за MR, он правда полезный) есть один нюанс — мы пока не принимаем MR в master, так как разрабатываем v4 и там уже есть сильные расхождения. Поэтому, если у тебя есть ресурсы на то, чтобы сделать чекаут от v4 и внести свои фиксы там, то мы с радостью вольем твои фиксы.

2020-09-28 17:22 UTC, ArthurStam requested changes
Привет. Спасибо за MR, он правда полезный) есть один нюанс — мы пока не принимаем MR в master, так как разрабатываем v4 и там уже есть сильные расхождения. Поэтому, если у тебя есть ресурсы на то, чтобы сделать чекаут от v4 и внести свои фиксы там, то мы с радостью вольем твои фиксы.

2020-09-30 15:15 UTC, mikhin commented
> чтобы сделать чекаут от v4 и внести свои фиксы там

@ArthurStam, готово

2020-09-30 18:05 UTC, ArthurStam commented
Спасибо. По поводу почти всех остальных предложений могу сказать, что отступление от методологии БЭМ дает больше плюсов, чем минусов.

2020-09-30 18:08 UTC, ArthurStam approved these changes

2020-09-30 18:08 UTC, merged