Выравнивание текста по центру
VKCOM/VKUI pull request #1035
Opened 2020-09-28 19:12 UTC by AdvTechnoKing

2020-09-28 19:24 UTC, ArthurStam commented
Привет. Спасибо, чекнем.

2020-09-28 19:31 UTC, fedorov-xyz requested changes

2020-09-28 19:31 UTC, fedorov-xyz commented on src/components/UsersStack/UsersStack.css
> +  line-height: 32px;
Привет! Спасибо за PR. Кажется, здесь можно вообще убрать с 19 по 21 строку и оставить просто

```css
text-align: center;
line-height: 32px;
```

2021-07-15 09:14 UTC, ArthurStam commented
Текст сейчас и так выравнивается по центру за счет `flex` и `align-items`

2021-07-15 09:14 UTC, closed without merging