Disabled fields hover
VKCOM/VKUI pull request #1050
Opened 2020-10-02 04:33 UTC by danakt

Отключено изменение цвета бордера при наведении у disabled форм

2020-10-02 07:26 UTC, ArthurStam requested changes

2020-10-02 07:26 UTC, ArthurStam commented on src/components/FormField/FormField.css
> +.FormField.ChipsInput:not(.ChipsInput--disabled) .ChipsInput__container ~ .FormField__border.FormField__border--hover {
для чего тут увеличения веса `.FormField__border.FormField__border--hover`? Нельзя просто `.FormField__border--hover`?

2020-10-05 12:37 UTC, danakt commented on src/components/FormField/FormField.css
> +.FormField.ChipsInput:not(.ChipsInput--disabled) .ChipsInput__container ~ .FormField__border.FormField__border--hover {
Ты прав

2020-10-15 09:57 UTC, ArthurStam approved these changes

2020-10-15 09:57 UTC, merged