Fix autocomplete form styles
VKCOM/VKUI pull request #1051
Opened 2020-10-02 05:39 UTC by danakt

Фикс стилей полей формы при автокомплите и саджестах

2020-10-02 07:24 UTC, ArthurStam requested changes

2020-10-02 07:24 UTC, ArthurStam commented on src/components/FormField/FormField.css
> +  border-radius: 10px;
Не проще ли всем вложенным в `FormField` элементам сделать `border-radius: inherit`? Не понимаю, почему только для `.Input__el` явно указывается скругление. Что на счет `Select` или `Textarea`

2020-10-05 13:17 UTC, danakt commented on src/components/FormField/FormField.css
> +  border-radius: 10px;
Думаю что поправил

2020-10-08 03:51 UTC, NekR commented on src/components/FormField/FormField.css
> +}
А в чём фикс? По задаче не нужно править background и форсить всегда наш. Пусть меняется при автокомплите. Юзер должен знать что происходит.

2020-10-09 15:51 UTC, danakt commented on src/components/FormField/FormField.css
> +}
Да, так и есть, фон применяется к инпуту и оверрайдит наш. Но ты прав, этот код ничего не делает, не могу сказать зачем я его оставил

2020-10-13 08:59 UTC, ArthurStam commented on src/components/FormField/FormField.css
> +.FormField--vkcom.Input,
Чекни стили у vkcom полей. Там 6 радиус.

2020-11-17 12:34 UTC, ArthurStam commented
Другая реализация в #1138

2020-11-17 12:34 UTC, closed without merging