VKUI-35: Panel header and nested
VKCOM/VKUI pull request #1058
Opened 2020-10-05 09:46 UTC by urffin

2020-10-05 11:22 UTC, wayshev commented
1) Не совпадает отступ над третичной кнопкой
![image](https://user-images.githubusercontent.com/61538408/95073718-fe794480-0715-11eb-8538-5f0f27fe2b12.png)
2) Не совпадает отступ справа внутри кнопки (что-то с самой кнопкой, видимо)
![Screen Shot 2020-10-05 at 14 22 10](https://user-images.githubusercontent.com/61538408/95073817-29639880-0716-11eb-9a24-a46343954852.png)

2020-10-05 12:01 UTC, urffin commented
> 1. Не совпадает отступ над третичной кнопкой
>    ![image](https://user-images.githubusercontent.com/61538408/95073718-fe794480-0715-11eb-8538-5f0f27fe2b12.png)
> 2. Не совпадает отступ справа внутри кнопки (что-то с самой кнопкой, видимо)
>    ![Screen Shot 2020-10-05 at 14 22 10](https://user-images.githubusercontent.com/61538408/95073817-29639880-0716-11eb-9a24-a46343954852.png)

В кнопке просто шрифт другой, либо межбуквенное расстояние, поэтому текст чуть длиннее/короче, кнопка соответственно тоже, по контенту

2020-10-08 11:22 UTC, danakt approved these changes

2020-10-09 14:29 UTC, ArthurStam requested changes
![image](https://user-images.githubusercontent.com/5061840/95595576-f93d3200-0a54-11eb-92c4-7cfbe0cc9a87.png)
тут сепаратор появился и он прили

2020-10-09 14:29 UTC, ArthurStam commented on src/components/PanelHeaderButton/PanelHeaderButton.tsx
> +  const labelComponent = isPrimitiveLabel && platform === VKCOM ? <Text weight="regular">{label}</Text> : label;
А зачем `label` оборачивать в `Text`? Это свойство используется для передачи `Counter` и `Badge` (его ещё нет)

2020-10-09 14:29 UTC, ArthurStam commented on src/components/PanelHeaderButton/PanelHeaderButton.css
> +.PanelHeaderButton--vkcom:not(.PanelHeaderButton--primitive):not(.PanelHeaderButton--withLabel) {
Такие селекторы сложно перебить. Лучше внизу написать зануление `border-radius` для этих модификаторов.

2020-10-09 14:29 UTC, ArthurStam commented on src/components/Search/Search.css
> +.PanelHeader--vkcom .Search--vkcom .Search__input {
А вне `PanelHeader` `Search` иначе выглядит? Если нет, то предлагаю перенести эти стили в `Search.css`

2020-10-09 14:29 UTC, ArthurStam commented on src/components/TabsItem/TabsItem.css
> +  .PanelHeader--vkcom .TabsItem--vkcom {
Только для PanelHeader эти стили актуальны?

2020-10-09 14:33 UTC, urffin commented
> ![image](https://user-images.githubusercontent.com/5061840/95595576-f93d3200-0a54-11eb-92c4-7cfbe0cc9a87.png)
> тут сепаратор появился и он прилип

Да, дизайнер сказал так и должно быть

2020-10-09 14:34 UTC, urffin commented on src/components/PanelHeaderButton/PanelHeaderButton.css
> +.PanelHeaderButton--vkcom:not(.PanelHeaderButton--primitive):not(.PanelHeaderButton--withLabel) {
там не зануление, там используется значение которое уже установлено до этого

2020-10-09 14:36 UTC, urffin commented on src/components/PanelHeaderButton/PanelHeaderButton.tsx
> +  const labelComponent = isPrimitiveLabel && platform === VKCOM ? <Text weight="regular">{label}</Text> : label;
Я в него текст передал, в примере вместо `addon` который удалился🤔

2020-10-09 14:40 UTC, ArthurStam commented on src/components/PanelHeaderButton/PanelHeaderButton.tsx
> +  const labelComponent = isPrimitiveLabel && platform === VKCOM ? <Text weight="regular">{label}</Text> : label;
Текст передается отдельным `PanelHeaderButton` в `left` или `right` шапки. `label` для этого не предназачен. Можешь заодно в доке указать.

2020-10-09 14:41 UTC, ArthurStam commented on src/components/PanelHeaderButton/PanelHeaderButton.css
> +.PanelHeaderButton--vkcom:not(.PanelHeaderButton--primitive):not(.PanelHeaderButton--withLabel) {
Энивей, этот тяжелый селектор можно распилить на два легких

2020-10-09 14:45 UTC, urffin commented on src/components/PanelHeaderButton/PanelHeaderButton.tsx
> +  const labelComponent = isPrimitiveLabel && platform === VKCOM ? <Text weight="regular">{label}</Text> : label;
Так, а тогда не получится, что текст часть кнопки, как в дизайне

2020-10-12 11:32 UTC, ArthurStam commented on src/components/PanelHeader/Readme.md
> +            <PanelHeader left={<PanelHeaderBack onClick={() => this.setState({ modalPanel: 'modal-panel1' })} label={this.props.platform === 'vkcom' ? 'Назад' : undefineds} />}>
undefineds

2020-10-12 11:40 UTC, ArthurStam approved these changes

2020-10-12 18:47 UTC, merged