add onSwipeBackStartEndAnimation callback
VKCOM/VKUI pull request #1094
Opened 2020-10-27 19:05 UTC by NOCELL

Callback onSwipeBackStartEndAnimation нужен, чтобы отключить жесты внутри панели, чтобы не было конфликтов.

2020-10-28 09:55 UTC, ArthurStam commented
1. От названия нагревается мозг.
2. Не очень понятно, что с чем конфликтует.

2020-10-28 10:37 UTC, ArthurStam reviewed
1. От названия нагревается мозг.
2. Не очень понятно, что с чем конфликтует.

2020-10-28 13:12 UTC, NOCELL commented
1. Максимально точно отображает для чего нужно
2. С onscroll на window для жестов внутри панели

2020-10-28 15:51 UTC, ArthurStam commented
Го живой пример, пока непонятно о чем речь

2020-10-28 21:15 UTC, NOCELL commented
window.onscroll конфликтует со свайпом при анимации

2020-11-06 12:40 UTC, ArthurStam requested changes
Вместо текущего решения, предлагаю в методе `View` `onSwipeBackCancel` добавить вызов нового свойства с тем же названием

2020-11-06 16:50 UTC, ArthurStam requested changes

2020-11-06 16:50 UTC, ArthurStam commented on src/components/View/View.tsx
> +   * callback начала анимации завершения свайпа назад.
Этот коллбэк вызывается, когда **завершилась** анимация отмененного пользователем свайпа.

2020-11-06 16:50 UTC, ArthurStam commented on src/components/View/View.tsx
>    onSwipeBack?(): void;
Сюда бы я тоже добавил аналогичный коммент

2020-11-11 18:14 UTC, ArthurStam approved these changes

2020-11-11 18:14 UTC, merged

2020-11-14 02:48 UTC, NekR commented
По идее вообще либа должна это обрабатывать и во время свайпа отключать скролл.