[Header] fix baseline-aligning firefox bug
VKCOM/VKUI pull request #1098
Opened 2020-10-29 18:08 UTC by ElForastero

Решение проблемы #738.
В Firefox есть проблема с выравниванием по baseline при задании элементу вертикальных пэддингов.

В багтрекере нашел несколько похожих багов, но не идентичных этому. Инфы практически нет, и единственное что сработало без создания дополнительных элементов разметки - это изменение padding на margin.

Наиболее близкое из того что нашел:
https://github.com/webcompat/web-bugs/issues/12629

2020-10-30 02:10 UTC, NekR approved these changes

2020-10-30 08:01 UTC, ArthurStam requested changes
Здесь использовать margin опасно из-за их способности схлапываться. Предлагаю посмотреть на то, как подобное выравнивание реализовано в SimpleCell и сделать по аналогии

2020-10-30 13:53 UTC, eolme commented
Попробуй вынести просто `padding` из `.Header__content` в `.Header__in`.

2020-10-31 08:41 UTC, ElForastero commented
> Попробуй вынести просто `padding` из `.Header__content` в `.Header__in`.

Если вынести на .Header_in, высота блока увеличится из-за правых контролов, которые чуть выше по высоте.

![image](https://user-images.githubusercontent.com/5102818/97774919-4ce2fd00-1b75-11eb-8b60-b9219da3e506.png)

2020-11-10 07:32 UTC, ElForastero commented
> Здесь использовать margin опасно из-за их способности схлапываться. Предлагаю посмотреть на то, как подобное выравнивание реализовано в SimpleCell и сделать по аналогии

Есть второй МР без margin. Но выглядит сильно хуже.
Технически здесь проблем не будет, потому что во флекс-контексте они не схлопываются. Тесты пройдены.

2020-11-10 08:37 UTC, NekR approved these changes

2020-11-17 10:51 UTC, ArthurStam approved these changes

2020-11-17 10:51 UTC, merged