Implementation of new component: ContentCard
VKCOM/VKUI pull request #1100
Opened 2020-10-30 02:49 UTC by gbowsky

# Все платформы
![image](https://user-images.githubusercontent.com/36237725/97654204-787dbe80-1a73-11eb-9952-600cdabeaa83.png)
![image](https://user-images.githubusercontent.com/36237725/97654224-86cbda80-1a73-11eb-9bef-721cdcb9a890.png)
Свёрстано по подобию [@vk](https://www.figma.com/@vk) в Figma.

2020-10-30 12:00 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +  <div style={{ padding: '12px 16px' }}>
Мы избегаем использования инлайновых стилей. Здесь и ниже их нужно убрать и перенести в ContentCard.css

2020-10-30 12:00 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +export interface ContentCardInfoProps {
После импортов лучше оставить пробел, чтобы читалось лучше

2020-10-30 12:00 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +const ContentCardInfo: (props: ContentCardInfoProps) => JSX.Element = (props: ContentCardInfoProps) => (
`FC<ContentCardInfoProps>` вместо `(props: ContentCardInfoProps) => JSX.Element`

2020-10-30 12:00 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +    <Div>
`Div` тут лишний, потому что кому-то компонент может понадобиться без отступов.

2020-10-30 12:00 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +          <ContentCardInfo {...props} />
Свойства компонента неочевидным для пользователя образом проваливаются вовнутрь. Вот [тут](https://github.com/VKCOM/VKUI/blob/v4.0.0-beta.30/src/components/Group/Group.tsx#L21) есть валидный пример реализации концепции `..restProps`

2020-10-30 12:00 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +      <Card style={{ overflow: 'hidden' }} mode={props.mode ? props.mode : 'shadow'}>
`overflow: hidden` — зло, которого мы стараемся избегать. Тут явно можно без него

2020-10-30 12:00 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +      <Card style={{ overflow: 'hidden' }} mode={props.mode ? props.mode : 'shadow'}>
Почему бы не использовать механику defaultProps тут?

2020-10-30 12:52 UTC, ArthurStam requested changes
Посмотрел

2020-10-30 14:44 UTC, ArthurStam requested changes

2020-10-30 14:44 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +        {image && <img src={image} alt={alt} className="ContentCard--img" style={{ objectFit: 'cover', maxHeight: props.maxHeight }} width="100%" {...restProps} />}
А почему именно сюда `{...restProps}` повесил? Почему не на рутовый элемент?

2020-10-30 14:44 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +    <Card mode={mode} size="l" className={classNames(className, getClassname('ContentCard', platform))}>
У разработчика обязательно должна быть возможность указать `style` и `className` (который не затрет классы компонента) на корневом элементе

2020-10-30 14:44 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +    {props.subtitle && <Caption weight="semibold" level="3" caps style={{ marginBottom: 4, color: 'var(--text_secondary)' }}>{props.subtitle}</Caption>}
Тут и ниже нужно использовать утилиту `hasReactNode`

2020-10-30 14:44 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +    {props.subtitle && <Caption weight="semibold" level="3" caps style={{ marginBottom: 4, color: 'var(--text_secondary)' }}>{props.subtitle}</Caption>}
Опять инлайновые стили :( Все стили нужно переносить в .css

2020-10-30 14:46 UTC, ArthurStam requested changes
И не надо резолвить замечания. Я посмотрю и зарезолвлю сам.

2020-10-30 14:46 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.css
> +.ContentCard--ios > .Card__in > .Tappable > .ContentCard--img {
Зачем такие лютые селекторы здесь и ниже? `.ContentCard--ios .ContentCard--img` должно быть достаточно

2020-10-30 14:46 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.css
> +.ContentCard--android > .Card__in > .Tappable,
Навесь на `Tappable` класс и обращайся тут к нему

2020-10-30 14:54 UTC, gbowsky commented on src/components/ContentCard/ContentCard.tsx
> +        {image && <img src={image} alt={alt} className="ContentCard--img" style={{ objectFit: 'cover', maxHeight: props.maxHeight }} width="100%" {...restProps} />}
Дабы была возможность повесить onError и прочие event

2020-10-30 14:56 UTC, gbowsky commented on src/components/ContentCard/ContentCard.tsx
> +    <Card mode={mode} size="l" className={classNames(className, getClassname('ContentCard', platform))}>
style добавил, а className мне перенести после getClassName?

2020-10-30 15:40 UTC, ArthurStam requested changes

2020-10-30 15:40 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.css
> +.ContentCard--body {
Почему используешь тут селектор модификатора? Должно быть `.ContentCard__body`. Тут и ниже везде.

2020-10-30 15:40 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +  mode?: 'tint' | 'shadow' | 'outline';
Еще лучше будет взять прописать `CardProps['mode']`, чтобы не дублировать

2020-10-30 15:40 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +    <Card mode={mode} size="l" className={classNames(className, getClassname('ContentCard', platform))} style={style}>
Забыл упомянуть, что тут нужен еще [`getRootRef`](https://github.com/VKCOM/VKUI/blob/v3.12.8/src/components/Button/Button.tsx#L40)

2020-10-30 15:40 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +const ContentCardInfo: FC<ContentCardInfoProps> = (props: ContentCardInfoProps) => (
А зачем вообще это как отдельный компонент реализовано? Оно только путает. Обычно что-то выносят в компонент, когда подразумевается его отдельное использование. А он только тут нужен.

2020-10-30 16:26 UTC, ArthurStam requested changes

2020-10-30 16:26 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +        {image && <img src={image} alt={alt} className="ContentCard__img" style={{ objectFit: 'cover', maxHeight: props.maxHeight }} width="100%" {...restProps} />}
А сюда тогда `ref={getRef}` нужно

2020-10-30 16:26 UTC, ArthurStam commented on src/components/ContentCard/Readme.md
>          <Div>
Лучше использовать `CardGrid`. Тогда `marginBottom` у `ContentCard` будут не нужны

2020-10-30 16:27 UTC, ArthurStam requested changes

2020-10-30 16:27 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +        {image && <img src={image} alt={alt} className="ContentCard__img" style={{ objectFit: 'cover', maxHeight: props.maxHeight }} width="100%" {...restProps} />}
`object-fit` тоже можно унести в .css

2020-10-30 16:29 UTC, gbowsky commented on src/components/ContentCard/ContentCard.tsx
> +        {image && <img src={image} alt={alt} className="ContentCard__img" style={{ objectFit: 'cover', maxHeight: props.maxHeight }} width="100%" {...restProps} />}
`{image && <img...` так и оставить?

2020-10-30 16:30 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +        {image && <img src={image} alt={alt} className="ContentCard__img" style={{ objectFit: 'cover', maxHeight: props.maxHeight }} width="100%" {...restProps} />}
можешь так и оставить, да

2020-10-30 16:42 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +        {image && <img src={image} alt={alt} className="ContentCard__img" style={{ objectFit: 'cover', maxHeight: props.maxHeight }} width="100%" {...restProps} />}
Еще тут `restProps` надо в начало. Иначе `restProps.src`, например, перебьет `src={image}`

2020-10-30 16:52 UTC, gbowsky commented on src/components/ContentCard/ContentCard.tsx
> +        {image && <img src={image} alt={alt} className="ContentCard__img" style={{ objectFit: 'cover', maxHeight: props.maxHeight }} width="100%" {...restProps} />}
Card не принимает ref

2020-11-02 10:31 UTC, wayshev commented
1) Отступ между изображением и первым текстовым блоком должен быть 12 точек, сейчас 15. Отсюда расхождения по всем отступам ниже

![image](https://user-images.githubusercontent.com/61538408/97857645-1f31bb80-1d0f-11eb-9643-60bcd6e7d632.png)


2) Отступ между двумя разными Card хотелось бы сделать 12 точек на iOS и 16 на Android, сейчас очень тесно

2020-11-02 13:45 UTC, gbowsky commented
@wayshev отступ между соседними Card устанавливает CardGrid, который не имеет отношения к ContentCard. (Это по второму пункту)

По первому сейчас будет коммит.

2020-11-03 15:34 UTC, ArthurStam approved these changes

2020-11-03 15:34 UTC, merged

2020-11-03 15:34 UTC, ArthurStam commented
Благодарю!