Fix button typings
VKCOM/VKUI pull request #1101
Opened 2020-10-30 13:20 UTC by eolme

2020-10-30 13:23 UTC, ArthurStam requested changes
Тестики упали

2020-10-30 13:24 UTC, eolme commented
Вижу

2020-10-30 14:02 UTC, eolme commented
Починил

2020-10-30 14:08 UTC, ArthurStam requested changes
Два вопроса:
1. Если фикс вносится для Button, то почему бы его не внести везде, где могут быть использованы href и target.
2. Как быть с тем, что у нас такие свойства убираются из доки?

2020-10-30 14:48 UTC, eolme commented
Почему вы не используете [react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript)?

1. Могу в типы вынести, но вроде там те, которые должны экспортироваться наружу?
2. По-моему как-то можно было фильтровать

2020-10-30 14:51 UTC, ArthurStam commented
> Почему вы не используете [react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript)?
> 
> 1. Могу в типы вынести, но вроде там те, которые должны экспортироваться наружу?
> 2. По-моему как-то можно было фильтровать

У styleguidist появилась нативная поддержка ts
1. Ты не понял вопрос, кажется. Либо я не понял ответ. Не у одного Button есть способность превращаться в ссылку. Но ты поправил почему-то только там. Обычное такое либо везде к единому стилю приводят, либо не трогают, пока не бесит.
2. Все типы из нод модулей игнорируются. Поэтому у нас есть и используется (правда не везде почему-то) наш интерфейс HasLinkProps

2020-10-30 15:38 UTC, eolme commented
Не похоже что HasLinkProps подхватывается styleguidist'ом.

2020-10-30 15:46 UTC, ArthurStam commented
И правда( будем разбираться. Но к MR всё ещё есть вопросы. Надо либо везде одинаково сделать подмешивание этих свойств, либо не вижу смысла править в одном месте.

2020-10-30 16:18 UTC, eolme commented
Кстати, сейчас попробовал, с react-docgen-typescript все работает нормально и типы все нормально отображаются (может все же стоит перейти/вернуться?)

2020-10-30 16:22 UTC, ArthurStam commented on src/types.ts
> +export type MorphButtonLink = Omit<ButtonHTMLAttributes<HTMLButtonElement> & AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
Не везде, где используется href, нужно экстендиться от кнопочных стилей

2020-10-30 16:32 UTC, eolme commented on src/components/TabbarItem/TabbarItem.tsx
> +  const Component: ElementType = restProps.href ? 'a' : 'button';
Да. действительно поехало немного, но может лучше оставить кнопку? Ведь это по сути кнопка. Докинуть стилей
```css
border: none;
background: none;
outline: none;
padding: 0;
```

2020-10-30 16:34 UTC, eolme commented on src/types.ts
> +export type MorphButtonLink = Omit<ButtonHTMLAttributes<HTMLButtonElement> & AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
Там везде Tappable

2020-10-30 16:34 UTC, ArthurStam commented on src/components/TabbarItem/TabbarItem.tsx
> +  const Component: ElementType = restProps.href ? 'a' : 'button';
Нет, сейчас я точно не хочу с этим разбираться и вообще не уверен, что так надо делать.

2020-10-30 16:37 UTC, eolme commented on src/components/TabbarItem/TabbarItem.tsx
> +  const Component: ElementType = restProps.href ? 'a' : 'button';
Кнопка с сбросом:
<img src="https://user-images.githubusercontent.com/11076888/97732139-840ecb00-1aef-11eb-87e8-5e735a8b9c1e.png" width="200" />

div (прод):
<img src="https://user-images.githubusercontent.com/11076888/97732185-97ba3180-1aef-11eb-8958-a19e6d0312b2.png" width="200" />

2020-10-30 16:41 UTC, ArthurStam commented on src/components/TabbarItem/TabbarItem.tsx
> +  const Component: ElementType = restProps.href ? 'a' : 'button';
Не нужно это править сейчас.

2020-10-30 16:50 UTC, eolme commented on src/components/TabbarItem/TabbarItem.tsx
> +  const Component: ElementType = restProps.href ? 'a' : 'button';
> везде одинаково сделать

Ладно, подождем, когда у тебя появится время.

2020-10-30 22:10 UTC, eolme commented on src/components/TabbarItem/TabbarItem.tsx
> +  const Component: ElementType = restProps.href ? 'a' : 'button';
Обычно если сделать не везде, оно потом висит годами и затем отклоняется по принципу "работает - не трогай". Если вносить изменения, то значит надо это делать.

Никаких конфликтов нет, если удалите, то удалите, просто хозяин - барин. Я уже понял, что DRY/KISS это не про VKUI.

2021-04-08 15:04 UTC, ArthurStam commented
В итоге везде теперь экстендимся от `TappableProps`, который в свою очередь экстендится от `AllHTMLAttributes`

2021-04-08 15:04 UTC, closed without merging