Implemented HorizontalCell component
VKCOM/VKUI pull request #1103
Opened 2020-10-30 20:27 UTC by gbowsky

![image](https://user-images.githubusercontent.com/36237725/97753669-31410d80-1b07-11eb-89a3-1547928dcb61.png)

* Принимает валидные для платформы отступы.
* В блоке с альбомами используется img с стилями описанными в примере для stylguidist'а.

2020-10-31 09:35 UTC, ArthurStam requested changes

2020-10-31 09:35 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.css
> +.HorizontalCell--sz-small {
мы уходим от составных классов, поэтому можно просто `.HorizontalCell--small`

2020-10-31 09:35 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  size?: 'small' | 'medium' | 'large';
Я бы перешел на `'s' | 'm' | 'l'`, так как эти значения потом перетекают в css, где размер селектора имеет влияет на размер бандла

2020-10-31 09:35 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +export interface HorizontalCellProps extends HTMLAttributes<HTMLDivElement>{
Нужен пробел между `>{`

2020-10-31 09:35 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  image?: ReactNode;
В этой ячейке, картинка — основной компонент. Почему бы её не передавать в качестве `children`? Минус одно самописное свойство. Более интуитивный DX.

2020-10-31 09:35 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.css
> +  margin-right: 12px;
Такой margin будет коллапситься. Это видно, если сжать окно с примером до 320px и прокрутить до конца.
![image](https://user-images.githubusercontent.com/5061840/97775838-dba34a00-1b74-11eb-8a95-b80d91724689.png)

2020-10-31 09:58 UTC, ArthurStam reviewed
![image](https://user-images.githubusercontent.com/5061840/97776407-bc0e2080-1b78-11eb-9e41-f518eec5e3de.png)
Еще слева ломается выравнивание. Явно что-то не так с отступами

2020-11-01 21:02 UTC, gbowsky commented
![image](https://user-images.githubusercontent.com/36237725/97815387-b6125f80-1c9e-11eb-8fb0-4349f2a4b5ff.png)

Практический пример.

2020-11-02 10:18 UTC, ArthurStam requested changes

2020-11-04 21:16 UTC, gbowsky commented on src/components/HorizontalCell/HorizontalCell.tsx
> +      <div className="HorizontalCell__left" />
Давно решено, нужны ли ещё какие-нибудь изменения?

2020-11-05 10:42 UTC, ArthurStam requested changes
По стилям. Обычно мы сначала описываем общие стили, ниже — специфичные для конкретных платформ. Пример: [Alert.css](https://github.com/VKCOM/VKUI/blob/v4/src/components/Alert/Alert.css)

2020-11-05 10:42 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  title?: string;
`title` — зарезервированный html-атрибут. Переименуй в `header`

2020-11-05 10:42 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +    <div className={classNames(getClassName('HorizontalCell', platform), `HorizontalCell--${size}`, className)} style={style}>
Нужен `ref={props.getRootRef}`

2020-11-05 10:42 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +      <Tappable {...restProps}>
Нужен `getRootRef={props.getRef}`

2020-11-05 10:42 UTC, ArthurStam commented on src/components/HorizontalCell/Readme.md
> +* При `size='small'` рекомендуется `<Avatar size={56}/>` или же любой компонент шириной 56 пикс.
Тут и ниже нужно пофиксить названия размеров на s, m и l

2020-11-05 10:42 UTC, ArthurStam commented on src/components/HorizontalCell/Readme.md
> +Рекомендуется для использования в HorizontalScroll, автоматически ставит отступы по бокам в зависимости от платформы.
Непонятная формулировка. Кто/что рекомендуется?

2020-11-05 10:49 UTC, ArthurStam commented
Ещё ждём дизайн-ревью

2020-11-05 10:52 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.css
> +.HorizontalCell.HorizontalCell--ios:first-child::before,
Здесь и ниже можно облегчить селеткор до `HorizontalCell--ios:first-child::before`

2020-11-05 10:52 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.css
> +.HorizontalCell--ios:first-child.HorizontalCell--s,
У нас пока это не регламентировано линтером, но прошу здесь и ниже переписать на 
`.HorizontalCell--ios.HorizontalCell--s:first-child`

2020-11-05 13:40 UTC, ArthurStam requested changes

2020-11-05 13:40 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  header?: string;
`header`, `subtitle` и `secondTitle` должны быть типа `ReactNode`

2020-11-05 13:40 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  title: 'Title',
Во-первых, не `title`, а `header`. Во-вторых — зачем вообще такое дефолтное значение?

2020-11-05 13:40 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  secondSubtitle?: string;
А для чего нужен `secondTitle`, если добиться двух подзаголовков можно простым <br /> в `subtitle`? Имхо, свойство лишнее.

2020-11-05 13:45 UTC, fedorov-xyz commented on src/components/HorizontalCell/HorizontalCell.tsx
> +export default HorizontalCell;
Предлагаю использовать именованный экспорт.

```js
export const HorizontalCell = () => {}
```

2020-11-05 13:56 UTC, gbowsky commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  title: 'Title',
Следовал CONTRIBUTING.md

2020-11-05 13:58 UTC, gbowsky commented on src/components/HorizontalCell/HorizontalCell.tsx
> +export default HorizontalCell;
![image](https://user-images.githubusercontent.com/36237725/98250126-20215200-1f88-11eb-8d5c-901205110241.png)

Получаем некрасивый warning.

2020-11-05 14:00 UTC, gbowsky commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  secondSubtitle?: string;
![image](https://user-images.githubusercontent.com/36237725/98250311-552da480-1f88-11eb-9085-e31b8b09c29c.png)

По дизайну посчитал нужным.

2020-11-05 14:04 UTC, gbowsky commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  secondSubtitle?: string;
Теоретически можно обойтись line-height.

2020-11-05 14:17 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +export default HorizontalCell;
Это отличный ворнинг. Скорее всего ты в index.ts не поправил экспорт

2020-11-05 14:18 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  title: 'Title',
Но какой-то мистический `Title` — это некорректно)

2020-11-05 14:53 UTC, ArthurStam requested changes

2020-11-05 14:53 UTC, ArthurStam commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  header: 'Header',
Это дефолтное значение не нужно

2020-11-05 14:54 UTC, ArthurStam requested changes

2020-11-05 14:54 UTC, ArthurStam commented on src/index.ts
> +export { default as HorizontalCell } from './components/HorizontalCell/HorizontalCell';
Там уже нет дефолтного экспорта. Тут должно быть просто `export { HorizontalCell } from ...`

2020-11-05 15:48 UTC, ArthurStam commented
Отлично. Осталось дождаться дизайн-ревью.

2020-11-09 09:50 UTC, ArthurStam requested changes
Дизайн-ревью
1. При размере `m` рекомендуется `Avatar` размера не 96, а 88
2. В размере `l` изображения так же пример больше макета. В примере — 144, в макете — 128

2020-11-10 19:46 UTC, ArthurStam approved these changes

2020-11-10 19:46 UTC, ArthurStam commented
Благодарю!

2020-11-10 19:47 UTC, merged