Fix popout backdrop height on desktop
VKCOM/VKUI pull request #1106
Opened 2020-11-02 09:47 UTC by ElForastero

Пролема исходит вот от сюда:

https://github.com/VKCOM/VKUI/blob/85d3ba3e107c382ded673015dff3d49893d4a757/src/styles/styles.css#L109-L114

Высота `<body>` и  `#root` всегда равна высоте viewport.
И все абсолютно-спозиционированные внутри body блоки с `width: 100%; height: 100%` (как например PopoutRoot--absolute), по высоте будут равны высоте `<body />`. То есть высоте и ширине вьюпорта.

Выглядит это вот так:

![image](https://user-images.githubusercontent.com/5102818/97853189-3671a880-1d11-11eb-9987-715d687e542a.png)

`.PopoutRoot--absolute`, который должен ловить `click` и закрывать `<ActionSheet />`, не тянется вниз и из-за этого появляется возможность клинуть на нижестоящие элементы. 

Изначально пытался решить проблему с высотой `<body>`, но решение предусматривает использование `min-height: 100vh` что сломает мобильную Safari. Возможно можно поправить при помощи https://github.com/postcss/postcss-100vh-fix. Однако проще рендерить `PopoutRoot__popout`  всегда через `position: fixed`.

Может кто-нибудь помнит, для чего использовалось абсолютное позиционирование в popout на десктопе?

2020-11-04 21:49 UTC, NekR commented
Можно попробовать призвать @lekzd, но выглядит норм.

Только если они не задевает кейс, что сам попап должен быть спозиционирован абсолютно, что бы скролиться вместе со страницей.

2020-11-04 21:52 UTC, NekR approved these changes
Посмотрел демку. Вроде норм работает.

2020-11-04 22:09 UTC, NekR requested changes
Хотя гоню, там же в тест кейсе проблема показывается.
Попробовал в проекте. Действительно с фикседом оно ездит, а не зависает на месте.
Нужно поискать другое решение.

Но не с изменением размера `<body>`. Там специально так сделано.

2020-11-05 03:06 UTC, eolme commented
Можно сделать fixed подложу и на ней ловить onclick, а сам popout с absolute.

2020-11-05 08:53 UTC, ElForastero commented
@NekR @eolme 

Сделал через дополнительную подложку `.PopoutWrapper__overlay`. Фиксированная и ловит клик вместе с `.PopoutWrapper__container`.

overlay на десктопе, container на мобилках

Они друг другу не мешают, поэтому не стал дополнительных рендер-условий ставить (десктоп/не десктоп).

2020-11-05 09:24 UTC, NekR commented
> @NekR @eolme
> 
> Сделал через дополнительную подложку `.PopoutWrapper__overlay`. Фиксированная и ловит клик вместе с `.PopoutWrapper__container`.
> 
> overlay на десктопе, container на мобилках
> 
> Они друг другу не мешают, поэтому не стал дополнительных рендер-условий ставить (десктоп/не десктоп).

Там уже есть некий параметр hasMask, который используется для ActionSheet для мобилок. Можно это как-то универсализировать, что бы не было слишком много разных подложек? 

![Uploading image.png…]()

2020-11-05 13:16 UTC, ElForastero commented
> > @NekR @eolme
> > Сделал через дополнительную подложку `.PopoutWrapper__overlay`. Фиксированная и ловит клик вместе с `.PopoutWrapper__container`.
> > overlay на десктопе, container на мобилках
> > Они друг другу не мешают, поэтому не стал дополнительных рендер-условий ставить (десктоп/не десктоп).
> 
> Там уже есть некий параметр hasMask, который используется для ActionSheet для мобилок. Можно это как-то универсализировать, что бы не было слишком много разных подложек?
> 
> ![image](https://user-images.githubusercontent.com/1189265/98222403-d45bb200-1f61-11eb-8561-268ac53d58a1.png)

Сделал один блок вместо двух. Классы тогглятся - для десктопа невидимый, для мобилок - паранджа.

2020-11-06 22:23 UTC, NekR requested changes

2020-11-06 22:23 UTC, NekR commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +        onClick={onClick}
А почему onClikc и тут на оверлее? Вроде на оверлее получается достаточно

2020-11-06 22:23 UTC, NekR commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +            'PopoutWrapper__overlay': !hasMask,
Давай сделаем ещё одну итерацию тут и сделаем так:
- Аргумент hasMask, который просто добавляет цвет к overlay. Класс становится модификтором (`PopoutWrapper__mask`)
- Аргумент который делает компонент фиксированным или нет. Получается модификтор PopoutWrapper--fixed, по которому так же меняется поведение оверлея

2020-11-07 09:04 UTC, ElForastero commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +            'PopoutWrapper__overlay': !hasMask,
Что-то вроде этого?

```
<Popout hasMask={!isDesktop} fixed={isDesktop} />
```

2020-11-09 07:17 UTC, ElForastero commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +            'PopoutWrapper__overlay': !hasMask,
@NekR Отрефакторил немного.

1. Завел `PopoutWrapper__overlay` и модификатор `PopoutWrapper__overlay--mask`.
2. По модификатору `PopoutWrapper--fixed` меняется поведение оверлея.

Нужен ли тут действительно еще один пропс вроде `isFixed={!isDesktop}`?

Я думаю что не стоит, потому что если его случайно забыть передать, то на desktop сломается overlay. Это больше такое, внутреннее, обусловеленное нюансами реализации (позиционирование блоков). Боюсь что откноем дыру на десктопе и всякие ActionSheet, длинные модалки и др. продолжат ловить этот баг с закрытием по клику на оверлей.

2020-11-09 10:38 UTC, NekR commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +            'PopoutWrapper__overlay': !hasMask,
Модификатор `--mask` должен быть на блоке, а не на элементе. Как и в остальных кейсах.

Отдельный параметр на `fixed` нужен потому, что при выставлении hasMask, никак не подразумевается его появление. hasMask это не какой-то "десктоп" режим, это просто добавление цвета оверлею.

Про уязвимость не очень понятно, но если речь про выстреливание в ногу  -- то там можно пытаться учесть все кейсы, а то кто-то вдруг может выстрелить себе в ногу или ещё что. А на самом деле, те люди которые будут потом разрабатывать -- умеют думать и определённо смогут воспользоваться нужными параметрами.

Так же, разделяя параметры, мы получаем дополнительную свободу в реализации: можно будет делать absolute позиционирование не только без маски, но и с ней. И наоборот, fixed позиционирование без маски. Например, в мобильном размера тоже понадобится inline ActionSheet и там оно должно быть fixed.

2020-11-09 12:11 UTC, ElForastero commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +            'PopoutWrapper__overlay': !hasMask,
@NekR Сделал отдельный пропс. 👍

Со стилями сложнова-то немного получается, но иначе ничего не придумал. В случае если не fixed, то overlay должен тянуться на всю страницу, поэтому пришлось `:not(--fixed)` заюзать. Могу в компоненте разрулить вместо стилей, если так лучше.

2020-11-10 09:23 UTC, ElForastero commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +        onClick={onClick}
В итоге оставил второй `onClick`, потому что не смог победить мобилку - не ловит на мобилке клик.

Там как-то связано со вторым компонентом - с PopoutRoot. Он на десктопе абсолютный, на мобилках фиксед. Какая-то лажа с z-индексами случается и клик по overlay не срабатывает.

2020-11-11 04:01 UTC, NekR commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +        onClick={onClick}
Ну надо бы поправить. А что за второй PopoutRoot?

2020-11-11 04:03 UTC, NekR commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +            'PopoutWrapper__overlay': !hasMask,
Можно, например, по умолчанию overlay position: fixed; сделать, а при PopoutWrapper--fixed уже overlay на абсолют переключать.

Вообще там рефакторить по хорошему надо (не в этой задаче).

2020-11-11 12:04 UTC, ElForastero commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +            'PopoutWrapper__overlay': !hasMask,
Сделал по дефолту overlay `fixed`, и переключаю на `absolute`.

Вспомнил почему не получается одним обработчиком, когда начал снова копать - на мобилке `container` тянется во все стороны, из-за чего перекрывает все что только можно, включая оверлей. Просто так убрать эту резину не выходит. На ней завязан, например ActionSheet который снизу выезжает. Там внутри него рассчеты через `width: calc(100% - 20px)`. Все ломается в таком случае.

![image](https://user-images.githubusercontent.com/5102818/98809211-9ca7ab00-2436-11eb-974b-6cde549066c6.png)

2020-11-11 23:25 UTC, NekR commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +            'PopoutWrapper__overlay': !hasMask,
Чет сложно. Можно на родителе тогда достаточно? Или там через pointer-events поиграться. Если обработчик будет 2 раза срабатывать, то будет странно. Например, если клик попадает на overlay, то он и на родителя попадает получается.

2020-11-12 06:36 UTC, ElForastero commented on src/components/PopoutWrapper/PopoutWrapper.tsx
> +            'PopoutWrapper__overlay': !hasMask,
@NekR Файнали. Наконец-то угодил всем кейсам сразу. Добавил еще одну обертку для контента, и listener переместил на `overlay`.

Проверил на `ActionSheet`, `Alert`, `Spiner`. Не заметил разницы с прежней версией. По ощущениям работает так же. Надо бы конечно в проекте где-то на модалках всяких проверить еще для уверенности.

Но listener зато один теперь.

2020-12-21 09:15 UTC, merged