[WriteBar] Base vkcom styles
VKCOM/VKUI pull request #1114
Opened 2020-11-05 17:13 UTC by fedorov-xyz

2020-11-05 18:32 UTC, ArthurStam requested changes

2020-11-05 18:32 UTC, ArthurStam commented on src/components/WriteBarIcon/WriteBarIcon.css
> +.WriteBarIcon--vkcom {
Правила идентичны android, я бы их не дублировал

2020-11-05 19:49 UTC, fedorov-xyz commented on src/components/WriteBarIcon/WriteBarIcon.css
> +.WriteBarIcon--vkcom {
Если сейчас делать пары `WriteBarIcon--android` + `WriteBarIcon--vkcom`, есть шанс, что потом придётся снова разносить их.

2020-11-06 09:20 UTC, ArthurStam commented on src/components/WriteBarIcon/WriteBarIcon.css
> +.WriteBarIcon--vkcom {
Да вроде не проблема потом разнести. Щас все компоненты так написаны.

2020-11-06 10:27 UTC, ArthurStam approved these changes

2020-11-06 10:28 UTC, merged