vkcom/vkui#1093: Move Snackbar above modal & popouts
VKCOM/VKUI pull request #1217
Opened 2020-12-08 16:52 UTC by thoughtspile

2020-12-19 20:09 UTC, NekR commented
Давайте не будем переделывать API Snackbar сейчас уже. Переделаем с общей системой модалок и view.

2020-12-19 20:10 UTC, NekR requested changes
Давайте не будем переделывать API Snackbar сейчас уже. Переделаем с общей системой модалок и view.

2020-12-19 20:11 UTC, NekR commented
Обычный CSS фикс есть в этом ПРе #1160

2020-12-22 18:20 UTC, ArthurStam requested changes
Лучше сделать как обсуждали. В Root, View и PopoutWrapper добавить свойство snackbar по аналогии с modal и popout

2020-12-26 10:32 UTC, thoughtspile commented
закрываю — альтернативное решение в #1160

2020-12-26 10:32 UTC, closed without merging