Gallery: scrollable и left/right arrows
VKCOM/VKUI pull request #1220
Opened 2020-12-09 13:41 UTC by ewgenius

2020-12-10 14:29 UTC, wayshev commented
Design Review:

1) Не отображаются стрелки, сафари макос биг сюр

В остальном ок :)

2020-12-10 14:35 UTC, ewgenius commented
Сафари, Биг Сюр все ок - может какой-то Стейт (типа нет мышки) был включен?

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/827338/101785641-0dadb180-3b0e-11eb-903a-408c0d54f7d9.png">

2020-12-17 22:59 UTC, NekR requested changes

2020-12-17 22:59 UTC, NekR commented on src/components/Gallery/Gallery.tsx
> +  onWheel = (e: WheelEvent<HTMLElement>) => {
А откуда вдруг появилось что оно должно на wheel реагировать как-то?

2020-12-17 22:59 UTC, NekR commented on src/components/Gallery/Gallery.tsx
> +    e.persist();
Лучше до 17го реакта обновиться, что бы без эти костылей

2020-12-17 22:59 UTC, NekR commented on src/components/Gallery/Gallery.tsx
> +        const dX = (typeof s.deltaX === 'number' ? s.deltaX : 0) - e.deltaX;
Мне кажется он сходу так не будет кросс-браузерным нормально. Если делать такое, то стоит взять какой-то уже существующий код в vk.com для этого. Но непонятно зачем.

2020-12-17 22:59 UTC, NekR commented on src/components/Gallery/Gallery.tsx
> +import HorizontalScrollArrow from '../HorizontalScroll/HorizontalScrollArrow';
Кажется название должно быть другое у такого компонента, если оно не только для HorizontalScroll используется

2020-12-18 18:43 UTC, ewgenius commented on src/components/Gallery/Gallery.tsx
> +  onWheel = (e: WheelEvent<HTMLElement>) => {
Да, это было не надо - оставил только стрелки

2020-12-19 20:04 UTC, NekR approved these changes

2020-12-20 10:07 UTC, merged