#1287 Cell имеет отличимые отступы в разных режимах
VKCOM/VKUI pull request #1295
Opened 2021-01-13 14:43 UTC by eugpoloz

Фикс https://github.com/VKCOM/VKUI/issues/1287: поправила паддинги IconButton для компактного sizeY, чтобы они больше не превращали его в некомпактный.

2021-01-13 15:51 UTC, ArthurStam requested changes

2021-01-13 15:51 UTC, ArthurStam commented on src/components/IconButton/IconButton.css
> +  height: 44px;
Можно переписать этот селектор на `.IconButton--sizeY-compact`, тем самым его облегчив

2021-01-13 15:51 UTC, ArthurStam commented on src/components/IconButton/IconButton.css
> +  border-radius: 22px;
можно сделать просто 50%, чтобы не писать его для каждой высоты

2021-01-15 14:50 UTC, wayshev commented
Design Review: OK

2021-01-18 09:43 UTC, ArthurStam approved these changes

2021-01-18 09:43 UTC, merged