PanelHeaderContext: adopt for desktop
VKCOM/VKUI pull request #1298
Opened 2021-01-15 13:25 UTC by ewgenius

iOS

<img width="776" alt="image" src="https://user-images.githubusercontent.com/827338/104732329-1a957480-574e-11eb-87b4-56cf7418bc87.png">

Android

<img width="775" alt="image" src="https://user-images.githubusercontent.com/827338/104732349-241edc80-574e-11eb-98e1-980bf4d68752.png">

VKCOM

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/827338/104732374-300a9e80-574e-11eb-8afc-7425b743b269.png">

2021-01-15 13:38 UTC, wayshev commented
Design Review: OK

2021-01-21 12:19 UTC, ArthurStam commented
![image](https://user-images.githubusercontent.com/5061840/105350301-fc22f380-5bfb-11eb-83d9-7a1ee2ca9a22.png)
Не хотим ли мы пофиксить закругление при ховерах ячеек внутри? Кажется, что относится к этому компоненту

2021-01-21 12:27 UTC, ArthurStam commented
![image](https://user-images.githubusercontent.com/5061840/105351054-13161580-5bfd-11eb-858b-a277dd1eee42.png)
Тач зона точно так должна подсвечиваться? По бокам как будто не хватает паддингов.

2021-01-21 12:35 UTC, ArthurStam requested changes
Задал пару вопросов в комментах

2021-01-21 18:40 UTC, ewgenius commented
> Не хотим ли мы пофиксить закругление при ховерах ячеек внутри? Кажется, что относится к этому компоненту

Добавил стиль для отмены скругления у вложенных SimpleCell

<img width="597" alt="image" src="https://user-images.githubusercontent.com/827338/105396515-090e0a00-5c31-11eb-818e-b52e26fa7c60.png">


> Тач зона точно так должна подсвечиваться? По бокам как будто не хватает паддингов.

Тач зона это отдельный компонент, фикс в #1304 ждет дизайн ревью

2021-01-21 18:52 UTC, ArthurStam approved these changes

2021-01-21 18:52 UTC, merged