#626 Компонент Badge
VKCOM/VKUI pull request #1306
Opened 2021-01-18 15:13 UTC by eugpoloz

resolves #626: добавить возможность вставлять иконку или бейдж справа от заголовка.

- добавляет компонент `<Badge/>` с двумя модами - `new` и `prominent`
- добавляет в `<SimpleCell/>` возможность вставить бейджик справа от текста заголовка (иконку размером 12|16 или `<Badge/>`)
- добавляет `<Badge/>` в `<TabsItem/>`
- добавляет `<Badge/>` в `<TabbarItem/>`

2021-01-18 15:14 UTC, fedorov-xyz commented on src/components/Badge/Badge.tsx
> +export default Badge;
В новом коде мы не используем экспорты по-умолчанию.

2021-01-21 13:05 UTC, ArthurStam requested changes

2021-01-21 13:05 UTC, ArthurStam commented on src/components/SimpleCell/SimpleCell.css
> +  display: inline-flex;
Если тут перейти на flex, то вроде ничего не поменяется

2021-01-21 13:05 UTC, ArthurStam commented on src/components/TabbarItem/TabbarItem.tsx
> +  badge?: boolean;
Ещё кстати, если label и badge не могут существовать одновременно, то возможно всё вообще стоит схлопнуть до одного свойства `label` и в стилях обращаться к .Badge и .Counter для выравниваний. Стоит спросить у дизайна. Потому что в противном случае, у нас добавляется еще одно свойство, что делает API сложнее.

2021-01-21 13:08 UTC, eugpoloz commented on src/components/Badge/Badge.css
> +  background-color: #5c9ce6; /* blue_200 */
Я как раз спрашивала насчет этого места у Вани, он говорил, что тут случай, где цвет статический и не зависит от темы. Поэтому хардкод.

2021-01-21 13:10 UTC, eugpoloz commented on src/components/SimpleCell/SimpleCell.css
> +  color: #5c9ce6; /* blue_200 */
Выше ответила!)

2021-01-21 13:17 UTC, eugpoloz commented on src/components/Badge/Badge.css
> +  display: flex;
Упс, забыла прибрать!

2021-01-21 14:15 UTC, wayshev commented
Design Review: OK

2021-01-22 14:38 UTC, ArthurStam approved these changes

2021-01-22 14:38 UTC, merged