ModalRoot: onPageTouchMove now not prevents horizontal scrolling
VKCOM/VKUI pull request #1309
Opened 2021-01-19 15:12 UTC by gbowsky

Превью на видео: 
https://user-images.githubusercontent.com/36237725/105053318-d671df00-5a81-11eb-8572-50f385bc1aff.mov

2021-01-20 07:24 UTC, fedorov-xyz requested changes

2021-01-20 07:24 UTC, fedorov-xyz commented on src/components/ModalRoot/ModalRoot.tsx
> -      return originalEvent.preventDefault();
`preventDefault` всё же был здесь не просто так. На iOS он помогал не пробрасывать скролл на содержимое под модальной страницей. Как это работает сейчас?

2021-01-20 07:24 UTC, fedorov-xyz commented on src/components/ModalRoot/Readme.md
> +                <HorizontalCell size='s' header='Промокот'>
Некритично, но мы используем двойные кавычки для свойств в JSX.

2021-01-20 13:48 UTC, gbowsky commented on src/components/ModalRoot/ModalRoot.tsx
> -      return originalEvent.preventDefault();
Пересмотрел, да. Вернул на место, добавил проверку позволяющую делать скролл только в HorizontalScroll.

2021-01-20 13:48 UTC, gbowsky commented on src/components/ModalRoot/Readme.md
> +                <HorizontalCell size='s' header='Промокот'>
Сделано.

2021-01-20 13:49 UTC, fedorov-xyz commented on src/components/ModalRoot/ModalRoot.tsx
> -      return originalEvent.preventDefault();
Ещё момент. Сколл не работает также во всяких textarea.

2021-01-20 14:45 UTC, gbowsky commented on src/components/ModalRoot/ModalRoot.tsx
> -      return originalEvent.preventDefault();
> Ещё момент. Сколл не работает также во всяких textarea.

iOS?

2021-01-20 14:57 UTC, gbowsky commented on src/components/ModalRoot/ModalRoot.tsx
> -      return originalEvent.preventDefault();
Вижу.

2021-01-20 15:33 UTC, gbowsky commented on src/components/ModalRoot/ModalRoot.tsx
> -      return originalEvent.preventDefault();
Включил в проверки textarea

2021-01-21 18:18 UTC, ArthurStam approved these changes

2021-01-21 18:26 UTC, ArthurStam approved these changes

2021-01-21 18:28 UTC, fedorov-xyz approved these changes

2021-01-21 18:51 UTC, merged