#1077 Switch: фикс цвета подложки
VKCOM/VKUI pull request #1313
Opened 2021-01-20 14:01 UTC by eugpoloz

fixes #1077: цвет подложки для Android теперь — accent с прозрачностью, как в [дизайне](https://www.figma.com/file/lLXmjJhnJa4OhgZXzcNJD9/VKUI-Android-Library?node-id=69%3A5521).

2021-02-03 10:07 UTC, thoughtspile requested changes

2021-02-03 10:07 UTC, thoughtspile commented on src/components/Switch/Switch.css
> +  background: #c6c5c5;
раз уж мы тут, может и выключенный сделаем как в дизайне?

2021-02-03 10:07 UTC, thoughtspile commented on src/components/Switch/Switch.css
> +  background: #f1f1f1;
да и сюда можно --background_light

2021-02-03 10:08 UTC, thoughtspile commented
подчищание цсс 🤗

2021-02-03 10:20 UTC, eugpoloz commented on src/components/Switch/Switch.css
> +  background: #c6c5c5;
Да, я сюда жду новые цвета, чтобы они хорошо смотрелись и на темной теме.)

2021-04-08 15:04 UTC, eugpoloz commented
Жду другие переменные цветов для knob и для трека, чтобы они хорошо смотрелись и на темной теме тоже.

2021-04-26 16:55 UTC, Lihachyov commented
@eugpoloz предлагаю сейчас закрыть эту таску, тут всё ОК. До токена и значения в тёмной теме доберёмся чуть позже

2021-04-26 18:05 UTC, ArthurStam submitted a review, later dismissed

2021-04-26 18:14 UTC, ArthurStam approved these changes

2021-04-26 18:15 UTC, merged