Типографические компоненты
VKCOM/VKUI pull request #1326
Opened 2021-01-25 15:39 UTC by eugpoloz

Убирает максимум возможного хардкода типографических стилей (font-size, font-weight, line-height) для компонентов, где это еще не было сделано, в пользу типографических компонентов.

В некоторых местах размер шрифта для компонентов в VKUI отличался от текущего дизайна в фигме. Тогда за истину я брала дизайн.

**Измененные компоненты:**
- [x] `<Cell/>`: убраны font-size и line-height, без них как будто ничего не поменялось
- [x] `<Checkbox/>`: убран line-height, без него как будто ничего не поменялось
- [x] `<Chip/>`
- [x] `<ChipsSelect/>`: также убран font-size для CustomSelectOption
- [x] `<Counter/>`
- [x] `<CustomSelect/>`: убран font-size для CustomSelectOption
- [x] `<CustomSelectOption/>`
- [x] `<Footer/>`
- [x] `<HorizontalCell/>`: убрано пустое правило
- [x]  `<ModalPageHeader/>`: убрано пустое правило
- [x] `<NativeSelect/>`
- [x] `<PanelHeader/>`: захардкоженные стили теперь более специфичные, чтобы не задевать содержимое `<PanelHeaderContent/>`
- [x] `<PanelHeaderButton/>`
- [x] `<PanelHeaderContent/>`
- [x] `<Search/>` (в плейсхолдере)
- [x] `<Select/>`: margin пофикшен под новый line-height
- [x] `<SelectMimicry/>`
- [x] `<SimpleCell/>`
- [x] `<SliderSwitch/>`: margin заменен на transform
- [x] `<SliderSwitchButton/>`
- [x] `<Tabs/>`: добавлен контекст, чтобы пробросить mode табов непосредственно в кнопку
- [x] `<TabsItem/>`: используется контекст TabsMode, чтобы определить правильный типографический компонент
- [x] `<Tooltip/>`
- [x] `<UsersStack/>`
- [x] `<WriteBar/>`: убраны пустые правила

**Где остается хардкод:**
-  `<Alert/>`: кнопки для iOS
-  `<Cell/>`: кнопка "Удалить" для iOS
-  `<ChipsInput/>`: для input
-  `<FormStatus/>`: хак для html, который приходит с бэка
-  `<HorizontalCell/>`: line-height остается для subtitle
-  `<Input/>`: для input
-  `<ModalPageHeader/>`: не стала трогать, т.к. есть план от него избавиться
-  `<PanelHeader/>`: кастомные стили для заголовка (23/28 Android, 21/26 iOS, VK Display Title 2)
-  `<PanelHeaderButton/>`: часть стилей для кнопок
-  `<PanelHeaderContent/>`: кастомные стили для заголовка (23/28 Android, 21/26 iOS, VK Display Title 2)
-  `<RichCell/>`: обнуления стилей
-  `<Search/>`: для input
- `<Select/>`: font-size остается для нативного select
- `<TabbarItem/>`: собственные уникальные стили
- `<Textarea/>`: для textarea
- `<WriteBar/>`: для textarea

2021-01-27 12:39 UTC, ArthurStam requested changes

2021-01-27 12:39 UTC, ArthurStam commented on src/components/PanelHeaderButton/PanelHeaderButton.css
> -  line-height: 48px;
Этот `line-height` нужен в тех случаях, когда кнопка является ссылкой. Пушта у `button` есть дефолтное вертикальное выравнивание содержимого, а у `a` — нет
![image](https://user-images.githubusercontent.com/5061840/105991997-94662000-60b5-11eb-9215-a9b640b0bb73.png)

2021-01-27 12:39 UTC, ArthurStam commented on src/components/PanelHeaderButton/PanelHeaderButton.css
> -  line-height: 48px;
То же замечание

2021-01-27 12:39 UTC, ArthurStam commented on src/components/SliderSwitch/SliderSwitch.css
> +  transform: translateX(100%) translateX(4px);
Перейти к calc

2021-01-27 12:39 UTC, ArthurStam commented on src/components/SimpleCell/SimpleCell.tsx
> +          <Title level="3" weight="regular" className="SimpleCell__children">{children}</Title>
Удостоверится, что мы удовлетворяем дизайну. Прежняя логика учитывала разный `before` (см. стили)

2021-01-27 14:33 UTC, wayshev commented
Design Review: WOW & also OK

2021-01-27 15:03 UTC, ArthurStam approved these changes

2021-01-28 10:38 UTC, ArthurStam approved these changes

2021-01-28 10:39 UTC, merged