Alert: replaced max-width with width
VKCOM/VKUI pull request #1387
Opened 2021-02-10 14:26 UTC by gbowsky

## Before:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/36237725/107522684-fef28200-6bc4-11eb-8b0b-26fb90c08447.png">

## After:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/36237725/107522767-1467ac00-6bc5-11eb-82be-56d6316699e9.png">

2021-02-10 15:17 UTC, ewgenius requested changes

2021-02-10 15:17 UTC, ewgenius commented on src/components/Alert/Alert.css
> +  width: 416px;
нет, это надо только под десктоп, на мобильных устройствах будет некорректно вести себя

2021-02-11 15:20 UTC, wayshev commented
design review: ok

2021-02-12 06:24 UTC, ewgenius requested changes

2021-02-12 06:24 UTC, ewgenius commented on src/components/Alert/Alert.tsx
> +            'Alert--desktop': canShowCloseButton,
iOS тоже может быть isDesktop, но там нет кнопки закрытия по дизайну.
Давай выделим отдельную переменную 
`const isDesktop = viewWidth >= ViewWidth.SMALL_TABLET`

2021-02-19 14:15 UTC, ewgenius approved these changes

2021-02-19 16:35 UTC, merged