Spacing component
VKCOM/VKUI pull request #1415
Opened 2021-02-19 13:29 UTC by ewgenius

более гибкая альтернатива Separator

2021-02-19 15:14 UTC, fedorov-xyz requested changes

2021-02-19 15:14 UTC, fedorov-xyz commented on src/index.ts
> +export { default as Spacing } from './components/Spacing/Spacing';
В новом коде мы только именованные экспорты используем.

2021-02-19 16:31 UTC, ewgenius commented on src/index.ts
> +export { default as Spacing } from './components/Spacing/Spacing';
Поправил 👍

2021-02-19 18:10 UTC, fedorov-xyz commented on src/components/Spacing/Spacing.tsx
> +    ...style,
Если в props.style передать height, то это перезатрёт наше значение.

2021-02-19 18:14 UTC, fedorov-xyz commented on src/components/Spacing/Spacing.tsx
> +   * <br />separator=false (default) - без сепаратора
Здесь можно markdown использовать в виде списка, будет выглядеть поприятнее в доке.

```
Настройка положения сепаратора:

* separator=false (default) - без сепаратора
* separator=true | separator='center'
* сепаратор располагается по серединеs
* separator='top'
* separator='bottom'
```

2021-02-19 18:50 UTC, ewgenius commented on src/components/Spacing/Spacing.tsx
> +   * <br />separator=false (default) - без сепаратора
Похоже что styleguidist не умеет

<img width="1454" alt="image" src="https://user-images.githubusercontent.com/827338/108547690-e3415700-72fb-11eb-8105-216617ca2f05.png">

Хотя в самом комментарии все норм, vscode правильно отображает

<img width="755" alt="image" src="https://user-images.githubusercontent.com/827338/108548080-62368f80-72fc-11eb-8b6f-18b6ee0b591f.png">

2021-02-19 19:03 UTC, fedorov-xyz commented on src/components/Spacing/Spacing.tsx
> +   * <br />separator=false (default) - без сепаратора
Глянь в Banner, там есть пример списка.

2021-02-19 19:12 UTC, ewgenius commented on src/components/Spacing/Spacing.tsx
> +    ...style,
Я об этом думал, и считаю что так правильнее:
- ситуация `<Spacing size={8} style={{ height: 10 }} />` весьма сомнительна (ну как бы какой смысл?), и даже если случится то вряд-ли вызовет вопросы: разработчик хотел указанную высоту, 
- с другой стороны вариант `<Spacing style={{ height: "100%" }} />` в теории может иметь место

2021-02-19 19:16 UTC, ewgenius commented on src/components/Spacing/Spacing.tsx
> +   * <br />separator=false (default) - без сепаратора
Пустой строчки не хватало, спасибо!

2021-02-20 12:17 UTC, fedorov-xyz approved these changes

2021-02-22 14:29 UTC, merged