README.md: updated minimal app example
VKCOM/VKUI pull request #1457
Opened 2021-03-11 14:42 UTC by gbowsky

Добавлен AppRoot в пример, в styleguide уже давно так.

2021-04-02 08:59 UTC, ArthurStam requested changes

2021-04-02 08:59 UTC, ArthurStam commented on README.md
> +      <SplitLayout>
Смущает тако обновление примера тем, что у него на больших width будет колонка, прилипающая к краям.

2021-04-07 07:35 UTC, ArthurStam approved these changes

2021-04-08 14:18 UTC, thoughtspile approved these changes

2021-04-09 06:52 UTC, merged