[Bug] #1527 Cell с атрибутом removable не обрезает children, от чего after и indicator выходят за рамки блока
VKCOM/VKUI pull request #1540
Opened 2021-04-13 18:41 UTC by eugpoloz

Фикс для Cell и Removable: 

fixes #1527.

2021-04-14 07:40 UTC, ArthurStam requested changes

2021-04-14 07:40 UTC, ArthurStam commented on src/components/Removable/Removable.tsx
> +            vkuiClass="Removable__control Removable__indicator"
Два элемента на одной ноде? Так не бывает :)

2021-04-14 07:40 UTC, ArthurStam commented on src/components/Removable/Removable.tsx
> +            vkuiClass="Removable__control Removable__remove"
Два элемента на одной ноде? Так не бывает :)

2021-04-14 12:00 UTC, ArthurStam requested changes

2021-04-14 12:00 UTC, ArthurStam commented on src/components/Removable/Removable.css
> +.Removable__action.Removable__action {
Зачем два раза?

2021-04-14 13:50 UTC, eugpoloz commented on src/components/Removable/Removable.css
> +.Removable__action.Removable__action {
Увеличиваю специфичность, чтобы цвет IconButton перебить. Почему-то для просто `.Removable__action` перебиваться он не захотел.

2021-04-15 05:58 UTC, ArthurStam commented on src/components/Removable/Removable.css
> +.Removable__action.Removable__action {
Я бы поднял `IconButton` выше `Removable` в `components.css`. Потому что первый является частью второго, наоборот вроде быть не может.

2021-04-15 17:56 UTC, ArthurStam approved these changes

2021-04-15 17:58 UTC, merged