[Bug] #1184 ChipsInput Удаляется чип, если ввести его еще раз
VKCOM/VKUI pull request #1541
Opened 2021-04-13 19:52 UTC by eugpoloz

Fixes #1184: чип теперь не удаляется, если ввести его еще раз, а переносится в конец.

- Оптимизировала под это решение проходку по массиву опций,
- Добавила юнит-тесты для ChipsInput,
- Пофиксила передачу пропа option в Chip. 😄

2021-04-14 07:22 UTC, ArthurStam requested changes
Заметил, что в последнем [примере](https://vkcom.github.io/VKUI/pull/1541/#/ChipsInput), который типа readOnly, на самом деле можно удалить элементы, если сфокусироваться на поле и нажать backspace. Можешь глянуть, в чем дело, раз в контексте компонента щас? Если там долго фиксить, то забей, сделаем отдельным тикетом.

2021-04-14 11:59 UTC, ArthurStam submitted a review, later dismissed

2021-04-14 14:28 UTC, thoughtspile commented on src/components/ChipsInput/ChipsInput.test.tsx
> +    expect(getChipsContainer()).toContainElement(chipRed);
вот эти штуки я бы писал как `expect(getChip()).not.toBeNull()`

2021-04-14 14:28 UTC, thoughtspile commented on src/components/ChipsInput/ChipsInput.test.tsx
> +const getChip = (label: string) => screen.getByText(label).parentElement;
а собственно почему `parentElement`?

2021-04-14 14:28 UTC, thoughtspile commented on src/components/ChipsInput/ChipsInput.test.tsx
> +    const chipRed = getChip('Красный');
вообще я бы это тестировал через onChange, без залезания в дом — у нас ведь уже есть тест, что  value корректно рендерится

2021-04-14 14:28 UTC, thoughtspile commented on src/components/ChipsInput/ChipsInput.test.tsx
> +    expect(chipRed).toContainElement(chipRedRemove);
а существование ремува это уже тест на чип, а не на ЧипсИнпут

2021-04-14 14:28 UTC, thoughtspile commented on src/components/ChipsInput/ChipsInput.test.tsx
> +  it('checks focus and blur', () => {
тут мы кажется тестируем стандартные браузерные функции

2021-04-15 16:40 UTC, thoughtspile requested changes

2021-04-15 16:40 UTC, thoughtspile commented on src/components/Chip/Chip.test.tsx
> +    expect(getChip()).not.toBeNull();
мы тут протестировали, что на экране есть текст "белый"? Это не кажется очень полезным (и ничего не говорит про before / after). Я бы покрыл это скриншотами (но потом)

2021-04-15 16:40 UTC, thoughtspile commented on src/components/Chip/Chip.test.tsx
> +    expect(getChip()).toBeNull();
достаточно `expect(onRemove).toHaveBeenCalled()`, меньше дома = лучше

2021-04-15 16:40 UTC, thoughtspile commented on src/components/ChipsInput/ChipsInput.test.tsx
> +      renderChip={undefined}
а что делает этот undefined?

2021-04-15 16:40 UTC, thoughtspile commented on src/components/ChipsInput/ChipsInput.test.tsx
> +    expect(getChip()).not.toBeNull();
смотри, я предлагал чуть иначе
```
let value;
render(<ChipsInputTest value={[]} onChange={v => value = v} />);
... делаем что-то ...
expect(value).toEqual({ label: 'Красный', value: 'Красный' })
```

2021-04-15 16:42 UTC, eugpoloz commented on src/components/ChipsInput/ChipsInput.test.tsx
> +    expect(getChip()).not.toBeNull();
О, ага! Сделаю.)))

2021-04-15 16:43 UTC, eugpoloz commented on src/components/Chip/Chip.test.tsx
> +    expect(getChip()).not.toBeNull();
Как тогда лучше, совсем выпилить?)

2021-04-15 17:06 UTC, thoughtspile commented on src/components/Chip/Chip.test.tsx
> +    expect(getChip()).not.toBeNull();
я бы выпилил (ну вряд ли мы забыли чилдрен пробросить)

2021-04-15 18:20 UTC, thoughtspile approved these changes

2021-04-15 18:24 UTC, merged