feat: aria-label и role у компонентов
VKCOM/VKUI pull request #1611
Opened 2021-05-19 14:05 UTC by eugpoloz

- Добавила aria-метки и роли там, где они нужны, в компонентах и в документации,
- Изменила некоторые div на более подходящие теги.

2021-05-19 14:10 UTC, fedorov-xyz commented on src/components/WriteBarIcon/WriteBarIcon.tsx
> +      ariaLabel = 'Прикрепить файл';
Мы не можем в библиотеке использовать русскоязычные строки.

2021-05-19 15:40 UTC, ArthurStam commented on src/components/MiniInfoCell/MiniInfoCell.tsx
> +      <div vkuiClass="MiniInfoCell__icon" role="presentation">
Если на иконке будет `role="presentation"`, то тут можно и убрать

2021-05-19 15:40 UTC, ArthurStam commented on src/components/ModalCard/ModalCard.tsx
> +          {hasReactNode(icon) && <div vkuiClass="ModalCard__icon" role="presentation">{icon}</div>}
Если на иконке будет role="presentation", то тут можно и убрать

2021-05-19 15:40 UTC, ArthurStam commented on src/components/PanelHeaderBack/PanelHeaderBack.tsx
> +  'sizeX': true,
кажется не нужно)

2021-05-19 15:40 UTC, ArthurStam commented on src/components/PanelHeaderButton/PanelHeaderButton.tsx
> +  'primary': false,
тут тоже кавычки можно опустить

2021-05-19 15:40 UTC, ArthurStam commented on src/components/PopoutWrapper/PopoutWrapper.tsx
>            <div
`role="button"` => `<button />`

2021-05-19 15:40 UTC, ArthurStam commented on src/components/Progress/Progress.tsx
> +      aria-label={`${value}%`}
думаю для этого компонента стоит юзать [более специфичный role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_progressbar_role).
Но можно не в этом MR, а отдельно.

2021-05-19 15:40 UTC, ArthurStam commented on src/components/PullToRefresh/PullToRefreshSpinner.tsx
> +      aria-label="Пожалуйста, подождите..."
А ридер не будет его читать, даже если щас никакого процесса загрузки данных нет?

2021-05-19 20:57 UTC, eugpoloz commented on src/components/Banner/Banner.tsx
> +          <div role="button" aria-label="Скрыть" vkuiClass="Banner__dismissIcon" onClick={onDismiss}>
Ага, у меня там какие-то проблемы со стилями были, поэтому на скорую руку так делала. Поправлю. 👍🏻

2021-05-19 20:58 UTC, eugpoloz commented on src/components/PullToRefresh/PullToRefreshSpinner.tsx
> +      aria-label="Пожалуйста, подождите..."
О, проверю, не подумала об этом.

2021-05-19 21:00 UTC, eugpoloz commented on src/components/PanelHeaderBack/PanelHeaderBack.tsx
> +  'sizeX': true,
о, у меня они и тут, и [ниже](https://github.com/VKCOM/VKUI/pull/1611#discussion_r635359008) автоматом подобавлялись, посмотрю, отчего так.

2021-05-20 08:44 UTC, thoughtspile commented on src/components/Banner/Banner.tsx
> +          <div role="button" aria-label="Скрыть" vkuiClass="Banner__dismissIcon" onClick={onDismiss}>
у меня плохие новости, button не всегда может быть флексом https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers

2021-05-20 09:17 UTC, ArthurStam requested changes
В PR довольно много мест, где aria-label зашит внутри компонента без возможности его переопределить. Учитывая, что наши приложения переводятся на разные языки, мы не можем себе такой хардкод позволить. 

Поэтому я предлагаю компоненты вроде Checkbox, Search и Cell фиксить отдельно в рамках нашей задачи по доступности. У react-aria есть специальные хуки для большинства кейсов. И эта либа так же решает проблему локализации.

2021-05-20 14:03 UTC, eugpoloz commented on src/components/Banner/Banner.tsx
> +          <div role="button" aria-label="Скрыть" vkuiClass="Banner__dismissIcon" onClick={onDismiss}>
в таких ситуациях нам не слишком принципиально, кмк, там же внутри только иконка будет.)

2021-05-20 17:27 UTC, eugpoloz commented on src/components/PanelHeaderButton/PanelHeaderButton.tsx
> +  'primary': false,
тут без кавычек линтер ругается:
> Inconsistently quoted property 'primary' found. eslint(quote-props)

не ругается на:

`  'primary': false,
  'aria-label': 'Закрыть',` (первый вариант)

`  primary: false,
  ['aria-label']: 'Закрыть',` (второй вариант)

второй лучше?

2021-05-20 18:40 UTC, fedorov-xyz commented on src/components/PanelHeaderButton/PanelHeaderButton.tsx
> +  'primary': false,
> тут без кавычек линтер ругается:
> 
> > Inconsistently quoted property 'primary' found. eslint(quote-props)
> 
> 
> 
> не ругается на:
> 
> 
> 
> `  'primary': false,
> 
>   'aria-label': 'Закрыть',` (первый вариант)
> 
> 
> 
> `  primary: false,
> 
>   ['aria-label']: 'Закрыть',` (второй вариант)
> 
> 
> 
> второй лучше?

Кажется, вычисляемое свойство в сильно больший код сгенерируется, я бы предложил первый вариант оставить.

2021-05-21 15:39 UTC, eugpoloz commented on src/components/PopoutWrapper/PopoutWrapper.tsx
>            <div
тут по идее вообще должна быть role="dialog", так что лучше тоже отложим до более сложных компонентов.

2021-05-26 07:48 UTC, ArthurStam commented on src/components/Root/Root.tsx
> +      <main {...restProps} vkuiClass={classNames(baseClassName, {
Так. А вот это, наверное, пока не стоит делать. Потому что у приложений может быть разная структура. У кого-то не будет Root. У кого-то Root — не главный элемент на странице. Давай это в рамках других задач по доступности делать.

2021-05-26 07:48 UTC, ArthurStam commented on src/components/UsersStack/UsersStack.tsx
> +      <div vkuiClass="UsersStack__photos" role="presentation">
А вот тут я бы использовал [`role="img"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Role_Img)

2021-05-26 07:48 UTC, ArthurStam commented on src/components/UsersStack/UsersStack.tsx
> +          <Caption weight="medium" level="1" vkuiClass="UsersStack__photo UsersStack__photo--others" aria-hidden="true">
А это почему решили скрыть?

2021-05-26 07:48 UTC, ArthurStam commented on src/components/WriteBarIcon/WriteBarIcon.tsx
> +      {icon ? icon : children}
Как будто проще не стало :D

2021-05-31 07:37 UTC, eugpoloz commented on src/components/Root/Root.tsx
> +      <main {...restProps} vkuiClass={classNames(baseClassName, {
Логично, ок!

2021-05-31 07:41 UTC, eugpoloz commented on src/components/WriteBarIcon/WriteBarIcon.tsx
> +      {icon ? icon : children}
Проще — нет, но как будто поочевиднее, что куда присваивается в итоге.))) Но могу тоже ревертнуть, если не нужно.

2021-05-31 07:45 UTC, eugpoloz commented on src/components/UsersStack/UsersStack.tsx
> +      <div vkuiClass="UsersStack__photos" role="presentation">
Я старалась подумать: а какой смысл эта картинка несет для человека, который пользуется скринридером? Мы же потом текстом пишем, что "Иван и ещё 2 ваших друга подписаны", а этим аватаркам не присваиваем ни ссылок на профили, ни alt. По сути выходит элемент чисто для красоты.

2021-05-31 07:46 UTC, eugpoloz commented on src/components/UsersStack/UsersStack.tsx
> +          <Caption weight="medium" level="1" vkuiClass="UsersStack__photo UsersStack__photo--others" aria-hidden="true">
Тот же коммент, что выше: какой смысл информация "картинка, +2" несет для человека, который пользуется скринридером, если мы потом текстом прописываем, что "Иван и ещё 2 ваших друга подписаны"?

2021-05-31 09:16 UTC, ArthurStam commented on src/components/WriteBarIcon/WriteBarIcon.tsx
> +      {icon ? icon : children}
Ну давай `icon || children` тогда) Компромисс!

2021-05-31 09:33 UTC, ArthurStam submitted a review, later dismissed

2021-05-31 10:02 UTC, merged

2021-07-30 19:58 UTC, alekssamos commented
А посмотрите, пожалуйста, как можно исправить подобные случаи? Приложение Люди рядом (userlocation), около имени и фамилии есть значок отправить уведомление. Он никак в отдельную кнопку не выделяется и даже клавиатурный фокус на неё не попадает.