Adaptivity: dedicated isDesktop flag
VKCOM/VKUI pull request #1638
Opened 2021-05-27 06:51 UTC by ewgenius

resolves #1637 

codesandbox example https://codesandbox.io/s/f5n2j?resolutionWidth=1000&resolutionHeight=675

2021-05-27 06:58 UTC, ArthurStam requested changes
Не хотим тут же определять isDesktop как true, если VKCOM?

2021-05-27 07:28 UTC, ewgenius commented
> Не хотим тут же определять isDesktop как true, если VKCOM?

Тут надо отдельно подумать. Сейчас AdaptivityProvider не зависит от платформы и ConfigProvider.
Давайте это оставим на отдельный пр

2021-05-27 08:34 UTC, ArthurStam commented
Ваще `AdaptivityProvider` идет после `ConfigProvider`. У нас в доке так, как минимум. То есть мы можем использовать внутри `AdaptivityProvider` `usePlatform`, кмк

2021-06-03 07:17 UTC, ewgenius commented
Вообще `isDesktop` не очень ложится в концепцию текущей адаптивности - она не говорит какой у нас девайс (desktop/mobile) а основное что предоставляет это `SizeX`, `SizeY` параметры.

isDesktop нужен, но я думаю его нужно располагать в другом месте. Возможно какой-то вспомогательный hook/HOC, которые бы уже зависел от адаптивности, но без провайдера. Вобщем тут еще надо подумать, пока сделал отдельный фикс для PopoutRoot #1647

2021-09-09 11:02 UTC, closed without merging