Доступность: Button
VKCOM/VKUI pull request #1652
Opened 2021-06-06 13:54 UTC by eugpoloz

Завезла в `Button` aria-метки и доступность с клавиатуры.

**AppRoot**: добавила реализацию добавления/удаления класса `.AppRoot--focus-visible` (аналогично классу `.tabbing` в mvk).

**Tappable**: добавила обработчики событий `onClick` и `onKeyDown`, которые отслеживают, нужно ли вызывать кастомное событие `onPress` ([как в react-aria](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/button/src/useButton.ts#L106)). 
`onClick` для компонентов на базе `Tappable` теперь deprecated. Сработать сработает, но VKUI выведет в консоль варнинг, предлагающий использовать `onPress`.

**Button**:

- Добавила accessibility props: если компонент в основе не `<button/>` и не `<a/>`, я прокидываю компоненту `tabIndex="0"` и `role="button"`. Дала возможность переопределять эти свойства снаружи — на всякий случай.
- Добавила стили для `:focus-visible` с [клевой анимацией, которую предложил Миша](https://twitter.com/argyleink/status/1387072095159406596). Пока только для `Button`, потом хорошо будет это перенести в общий css и экстраполировать на все интерактивные компоненты.
- Вынесла классы для `Counter` внутри кнопки в сам `Counter`.

### Notes:

- Сначала я пробовала интегрировать-таки `react-aria`, чтобы не писать это все руками, но потом наткнулась на сразу несколько проблем, так что после обсуждения с Артуром решили попробовать пока сделать сами.

- Хотела также вместо нашего решения использовать [обернутый в хук полифилл для :focus-visible](https://codesandbox.io/s/usefocusvisible-qy01w?file=/src/FocusVisibleManager.js), но в итоге пока не рискнула: кажется, что запихивание такого хука в каждый интерактивный элемент (если не реализовывать его на уровне Tappable) может быть накладно для производительности и чревато ростом бандла, а так мы можем прописать всю логику в одном месте и прокинуть css.

- Аналог реализации на mvk по совету Артура писала так, будто `AppRoot` у нас есть всегда — даже в `partial`-режиме.

2021-06-08 10:34 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +      console.warn('[VKUI] onClick is deprecated! Please use onPress');
думаю, это засрет всю консоль всех аппов ворнингами, потому что даже у нас используется `onClick`

2021-06-08 10:39 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +      console.warn('[VKUI] onClick is deprecated! Please use onPress');
да, мы это обсуждали с Артуром, для button и a я это приберу.)

2021-06-08 13:25 UTC, ArthurStam requested changes

2021-06-08 13:25 UTC, ArthurStam commented on src/components/Button/Button.tsx
> +const ButtonTypography: FC<ButtonTypographyProps> = (props: ButtonTypographyProps) => {
Есть сомнения по поводу этого компонента. Раньше была функция, которая просто возвращает нужный jsx, а тут целый компонент, который используется один раз. Не слишком ли сложно?

2021-06-08 13:25 UTC, ArthurStam commented on src/components/Button/Button.tsx
> +  Component?: TappableProps['Component'];
Вижу, что туда всегда передаётся span. Зачем нужно это свойство и почему его тип ссылается на TappableProps?

2021-06-08 13:25 UTC, ArthurStam commented on src/components/Button/Button.css
> +.AppRoot--focus-visible .Button:not([disabled]):focus {
Смущает протекание селекторов `AppRoot` в `Button`. Предлагаю написать логику так, чтобы хук использовался внутри Button (или вообще Tappable) и там же навешивал класс.

2021-06-08 13:25 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +    if (!!onClick) {
безопаснее будет `typeof onClick === 'function'`

2021-06-08 13:25 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +        (this.props.getRootRef as RefObject<HTMLElement>).current.click();
А если getRootRef не передан, то всё взорвется?

2021-06-08 13:25 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +      if (this.props.Component !== 'button') {
А если `a`?

2021-06-08 13:49 UTC, ArthurStam requested changes

2021-06-08 13:49 UTC, ArthurStam commented on src/components/Button/Button.tsx
> +  const ref = useExternRef(getRootRef);
useExternRef нужен в тех случаях, когда ref нужен и внутри компонента, и передан в качестве getRootRef. Тут ref внутри компонента никак не используется, так что можно просто пробрасывать getRootRef в Tappable

2021-06-08 14:07 UTC, thoughtspile commented on src/components/Button/Button.tsx
> +const ButtonTypography: FC<ButtonTypographyProps> = (props: ButtonTypographyProps) => {
не слишком, лучше стандартная реакт-декомпозиция

2021-06-08 14:09 UTC, thoughtspile commented on src/components/Button/Button.css
> +.AppRoot--focus-visible .Button:not([disabled]):focus {
с текущей реализацей будет не очень хорошо, потому что в хуке глобальные подписки

2021-06-08 14:16 UTC, thoughtspile commented on src/hooks/useFocusVIsible.ts
> +  const addFocusVisible = useCallback(({ key }: KeyboardEvent) => {
тут наверное проще будет завести стрелки внутри useEffect

2021-06-08 14:16 UTC, thoughtspile commented on src/hooks/useFocusVIsible.ts
> +    document.addEventListener('mousedown', removeFocusVisible, eventOptions);
это не тот документ)

2021-06-08 14:16 UTC, thoughtspile commented on src/hooks/useFocusVIsible.ts
> +  }, [toggleFocusVisible]);
и кстати FYI у useState сеттер стабильный

2021-06-08 14:16 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +  onClick: MouseEventHandler = (e: MouseEvent<HTMLElement>) => {
я еще не совсем понимаю, почему тут не было `onClick` и вдруг появился

2021-06-08 14:23 UTC, eugpoloz commented on src/components/Button/Button.tsx
> +const ButtonTypography: FC<ButtonTypographyProps> = (props: ButtonTypographyProps) => {
Я пыталась сделать попроще, чтобы меньше кода дублировалось и чтобы подход был одинаковый везде, потому что в других местах у нас для определения нужного типографического компонента как раз компоненты и используются. Вот в [Counter](https://github.com/VKCOM/VKUI/blob/master/src/components/Counter/Counter.tsx#L14), например.

2021-06-08 14:23 UTC, eugpoloz commented on src/components/Button/Button.tsx
> +  Component?: TappableProps['Component'];
Дефолтный `Component` для типографических компонентов у нас сейчас или `div`, или разнообразные заголовки, а в кнопках ничего, кроме `span`, мы не можем использовать. (% А вот тип должен быть ElementType, спасибо, поправлю!

2021-06-08 14:25 UTC, eugpoloz commented on src/hooks/useFocusVIsible.ts
> +    document.addEventListener('mousedown', removeFocusVisible, eventOptions);
точно, спасибо!

2021-06-08 14:34 UTC, eugpoloz commented on src/components/Button/Button.css
> +.AppRoot--focus-visible .Button:not([disabled]):focus {
в идеале я хочу вообще убрать эту строчку и оставить в глобальных стилях что-то вроде `.AppRoot--focus-visible *:not([disabled]):focus`. Но это лучше делать потом, там в некоторых элементах для того, чтобы это завелось и красиво работало, нужно будет подшаманивать стили.

мы могли бы оставить подписки в одном месте, а значение `isFocusVisible` запихнуть в контекст — и дергать класс на уровне конкретного компонента. Допустим, мы делаем это в `Tappable`. Тогда у каждого `Tappable` на активной вьюхе при переключении с мышки на навигацию через Tab — и наоборот — будет тогглиться класс `Tappable--focus-visible`. Звучит как что-то, что может просадить перформанс, если Tappable будут в количестве. Поэтому я вместо полифилла взяла mvk-решение.)

2021-06-08 16:38 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +      if (this.props.Component !== 'button') {
почитала [спеку wai-aria для ссылок](https://w3c.github.io/aria-practices/examples/link/link.html) и вообще переделала это место в итоге. 😄

2021-06-08 20:02 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +  onClick: MouseEventHandler = (e: MouseEvent<HTMLElement>) => {
я вот уже несколько часов думаю над этим комментарием и все еще не уверена, что правильно его поняла, так что давай уточню: тебя смущает, что мы здесь обрабатываем `onClick` теперь вместо того, чтобы эту логику по `onMouseDown`/`onTouchStart` распихать? Или что-то другое?

2021-06-09 13:35 UTC, ArthurStam commented on src/components/Button/Button.css
> +.AppRoot--focus-visible .Button:not([disabled]):focus {
Опишу желаемое поведение конкретнее: я хочу, чтобы на `Tappable` навешивался класс `.Tappable--focusVisible` в том случае, если пользователь сфокусировался табом на нём. Тогда не будет никаких перерендеров всех `Tappable` при табуляции.

2021-06-09 13:48 UTC, eugpoloz commented on src/components/Button/Button.css
> +.AppRoot--focus-visible .Button:not([disabled]):focus {
поняла тебя, попробую.

2021-06-09 13:49 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +    if (!!onClick) {
о, я потеряла эту проверку в переписываниях, да.
давай, договорились!

2021-06-10 00:37 UTC, eolme commented on src/components/Button/Button.css
> +@media (prefers-reduced-motion: no-preference) {
Что-то по [поддержке](https://caniuse.com/mdn-css_at-rules_media_prefers-reduced-motion) сомнительно. Может все же по-умолчанию включить, а по `reduce` отлючать?

2021-06-10 09:40 UTC, eugpoloz commented on src/components/Button/Button.css
> +@media (prefers-reduced-motion: no-preference) {
привет! С точки зрения доступности так правильнее: мы не будем нагружать анимацией человека, который, допустим, хотел бы, но не может ее отключить из-за технических ограничений. Зато покажем тем, кому точно это окей.

2021-06-10 11:10 UTC, ArthurStam requested changes

2021-06-10 11:10 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +    if (this.state.hasFocusVisible) {
А разве при блюре не будет `hasFocusVisible: false`?

2021-06-10 11:36 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +          props.tabIndex = restProps.tabIndex !== undefined ? restProps.tabIndex : 0;
а мы там [на несколько строчек выше](https://github.com/VKCOM/VKUI/pull/1652/files/378ed64a7c6807f80f897d148506da0d616e4935#diff-cf932bacbe1ad5b939bfcd5edf83c3dad7fb23e7017dd34def52caf6f1a99d4bR423) проверяем на `if (!restProps.disabled)`. 😉

2021-06-10 12:28 UTC, ArthurStam requested changes

2021-06-10 12:28 UTC, ArthurStam commented on src/components/Button/Button.css
> +.Tappable--focus-visible.Button:not([disabled]):focus {
Так же, мне кажется, `:not([disabled])` можно упразднить.

2021-06-10 13:34 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +    if (this.state.hasFocusVisible) {
у меня периодически не скидывается этот стейт на кастомных ссылках, если я сначала понажимаю Enter, а потом тыкаю в кнопку мышкой (где-то случается race condition?), такая проверка помогает его точно скинуть.

2021-06-10 13:58 UTC, ArthurStam requested changes

2021-06-10 13:58 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +        'Tappable--focus-visible': propsHasFocusVisible && hasFocusVisible,
Давай state.hasFocusVisible переименуем в isFocusVisible, чтобы имена не пересекались

2021-06-10 13:58 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +    if (this.state.hasFocusVisible) {
Не скидывается, потому что onBlur не вызывается? Давай выясним, почему так происходит.

2021-06-10 13:58 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +  onKeyDown: KeyboardEventHandler = (e: KeyboardEvent<HTMLElement>) => {
Читал код этого компонента и запутался в триггерах. Может лучше как-то так?

```js
if (['button', 'a', 'input'].includes(this.props.Component)) {
  return this.props.onKeyDown(e);
} else if (this.props.role === 'link') {
  e.key.toUpperCase() === 'ENTER' && this.container.click();
} else {
  ['Enter', 'SPACE', ' '].includes(e.key.toUpperCase()) && this.container.click();
}
return this.props.onKeyDown(e);
```

2021-06-10 14:07 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +  onKeyDown: KeyboardEventHandler = (e: KeyboardEvent<HTMLElement>) => {
сейчас подумаю, как упростить!

2021-06-10 16:10 UTC, eolme commented
Меня смущает, что и без того сложный компонент становится еще сложнее, может все же декомпозировать функционал? Условно, предлагаю вынести логику с волнами и тп., не в рамках этой задачи конечно.

2021-06-10 16:39 UTC, eugpoloz commented
> Меня смущает, что и без того сложный компонент становится еще сложнее, может все же декомпозировать функционал? Условно, предлагаю вынести логику с волнами и тп., не в рамках этой задачи конечно.

Согласна, меня тоже этот момент начинает беспокоить. Насколько я помню, у нас планируется рефакторинг Tappable (как минимум переписывать с классов на функциональный компонент будем). @ArthurStam, подскажешь?

2021-06-10 17:21 UTC, ArthurStam commented
Tappable — действительно довольно сложный компонент. Я согласен, что логику с волнами можно вынести. Но чтобы рефакторить компонент, нужны более конкретные цели. Слишком много пропсов? Слишком медленный код? Есть явно отделяемые куски логики? Как только появятся ответы на эти вопросы, так и станет понятно, как и зачем этот компонент трогать.

2021-06-10 22:52 UTC, eolme commented
> Есть явно отделяемые куски логики?
Те же волны

> Слишком медленный код?
#1442 #1443

2021-06-11 05:26 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +  onClick: MouseEventHandler = (e: MouseEvent<HTMLElement>) => {
все, я осознала. У меня там раньше была логика проверки клика, которая переехала в `onKeyDown`. 😆 Спасибо, выкинула!

2021-06-15 13:37 UTC, thoughtspile requested changes

2021-06-15 13:37 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +  onFocus: FocusEventHandler = (e: FocusEvent<HTMLElement>) => {
я супер извиняюсь, но придется все таки вернуть как было — перевесить активность клавиатуры на AppRoot и пропихнуть через css. С меня винцо / тортик / здоровое питание на ваш выбор.

Мотивация для истории:

1. Сейчас мы как раз в ситуации, когда по табу перерендериваются все Tappable
4. Сделать полностью локальный хук / хок _клавиатурности_ не получится, потому что все равно по каждому табу в документе нужно проверить, в каком Tappable мы находимся
3. При инкапсуляции _клавиатурности_ в AppRoot вся логика уходит в CSS и мы убираем ненужные перерендеры по фокусу
2. Масштабировать копипасту onFocus / onBlur по компонентам при расширении доступности не хочется
5. Протекание CSS существует, но в данном случае решает реальную проблему и я лично благословил его

2021-06-15 14:13 UTC, eugpoloz commented on src/components/Button/Button.tsx
> +    role={restProps.role ? restProps.role : accessibleRole}
ой.)))

2021-06-15 16:35 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +      switch (Component) {
мне кажется, if будет гораздо проще

2021-06-15 16:35 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +        [focusVisibleMode]: hasFocusVisible && !isPresetFocusVisibleMode,
нам точно необходим тут класс без `.Tappable`?

2021-06-15 16:35 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +    switch (e.nativeEvent.key.toUpperCase()) {
почему не `code`? там точно будет `Space` на пробел и вроде нет проблем с uppercase

2021-06-15 16:35 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +    switch (e.nativeEvent.key.toUpperCase()) {
ну и иф будет проще кажется

2021-06-15 16:35 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +  hasFocusVisible?: boolean;
может, снесем этот проп? будет кейс для уникальной-кнопки-без-фокуса — добавим

2021-06-15 16:35 UTC, thoughtspile commented on src/components/Tappable/Tappable.css
> +@media (prefers-reduced-motion: no-preference) {
кажется, нужно как-то более кроссбраузерно это сделать https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
например, перетащить это в базу и в `prefers-reduced-motion: reduce` убрать

см https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

2021-06-15 16:35 UTC, thoughtspile commented on src/components/Tappable/Tappable.css
> +@media (prefers-reduced-motion: no-preference) {
хотя мб я чего то не понимаю уже

2021-06-15 17:12 UTC, eugpoloz commented on src/components/Tappable/Tappable.css
> +@media (prefers-reduced-motion: no-preference) {
я чуть выше отвечала на этот вопрос, процитирую:

> привет! С точки зрения доступности так правильнее: мы не будем нагружать анимацией человека, который, допустим, хотел бы, но не может ее отключить из-за технических ограничений. Зато покажем тем, кому точно это окей.

2021-06-15 17:15 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +  hasFocusVisible?: boolean;
по плану он временный, пока что он нам нужен, чтобы не показывать фокус на элементах, которые не готовы (например, в SimpleCell если в after запихнуть IconButton — аутлайн будет рисоваться кривовато). Дописать об этом коммент, может?

2021-06-15 17:20 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +    switch (e.nativeEvent.key.toUpperCase()) {
просто `code` вроде не существует? Я не вижу такого. А что [keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode), что [charCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode) deprecated уже достаточно давно.

почему не иф: я пока не уверена, что нам не нужно будет тут поддерживать другие кнопки. На Tappable реализован, например, компонент `Radio`, для его доступности по идее нужно стрелочки отслеживать, например.

2021-06-15 17:25 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +        [focusVisibleMode]: hasFocusVisible && !isPresetFocusVisibleMode,
нам нет, а вот разработчикам приложений — да. Это чтобы стилизовать hover/active (и теперь focus-visible) моды в прилке, не завязываясь на vkui-классы.

2021-06-16 10:37 UTC, thoughtspile commented on src/components/Tappable/Tappable.css
> +@media (prefers-reduced-motion: no-preference) {
а, я понял, это не сам аутлайн а супер эффект

2021-06-16 10:37 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +    switch (e.nativeEvent.key.toUpperCase()) {
мм https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code?

2021-06-16 10:37 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +        [focusVisibleMode]: hasFocusVisible && !isPresetFocusVisibleMode,
с нашей прагмой это будет `vkuioutline` =( У меня 2 идеи куда это пихнуть:
1. В className — и возможно огрести, потому что `.outline` кажется популярным классом
2. В `data-vkui-focus="outline"`, кажется безопасным хотя не очень красиво

2021-06-16 10:37 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +  hasFocusVisible?: boolean;
так нет, это плохое апи потому что разрабу аппа нужно руками проставлять какие-то непонятные пропы и синхронизировать их с нашей разработкой. Давай упихнем в цсс с комментом?

2021-06-16 10:39 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +    switch (e.nativeEvent.key.toUpperCase()) {
Слабо представляю, что мы тут сможем сделать по стрелочке, учитывая что другие опции будут в другом компоненте

2021-06-16 10:48 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +          props.onKeyDown = this.onKeyDown;
а может ли быть такое, что внутри Tappable находится какой-то инпут (или что-то с клавиатурным управлением), из которого взбаблится keydown и все сломает?

2021-06-16 10:48 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +        [focusVisibleMode]: hasFocusVisible && !isPresetFocusVisibleMode,
по идее там добавится не `outline`, а что-то другое, что юзер прокинет: там проверка на то, что нет предустановленного мода. Предустановленный (у нас это как раз `outline`) отдельным классом `Tappable--focus-visible-${mode}` добавляется чуть выше. 
хочется как-то и этот код подшаманить, чтобы он попроще для понимания был, конечно...

мне больше нравится вариант с `data-vkui-focus`, `outline` правда популярный класс наверняка.
а для hover и active-состояний тоже стоит подпилить тогда?

2021-06-16 10:49 UTC, thoughtspile requested changes
почти

2021-06-16 10:52 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +    switch (e.nativeEvent.key.toUpperCase()) {
> мм https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code?
... вот это я не очень внимательная.)))

> Слабо представляю, что мы тут сможем сделать по стрелочке, учитывая что другие опции будут в другом компоненте
перемещаться внутри группы кнопок: https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/radio/radio-1/radio-1.html

2021-06-16 10:53 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +  hasFocusVisible?: boolean;
почему разрабам? Tappable же вроде чисто наша внутренняя штука?

2021-06-16 11:05 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +          props.onKeyDown = this.onKeyDown;
подскажи, почему может сломать? Мы [вызываем props.onKeyDown внутри this.onKeyDown](https://github.com/VKCOM/VKUI/pull/1652/files/74df4590c2245d800ba82abd75ffee426039a31d#diff-cf932bacbe1ad5b939bfcd5edf83c3dad7fb23e7017dd34def52caf6f1a99d4bR171), если он существует, в самом конце, после того, как нашу логику доступности выполняем.

2021-06-16 14:49 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +    switch (e.nativeEvent.key.toUpperCase()) {
> перемещаться внутри группы radio-кнопок
это похвально, но из одного Radio=Tappable мы не залезем в стейт / дом другого Radio=Tappable без цирка

2021-06-16 14:52 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +  hasFocusVisible?: boolean;
У нас сейчас есть места, где можно передать в проп / чилдрен `Button` с аутлайном, но будет плохо по дизайну?

В примере с `IconButton` — нужно же будет всегда писать `<SimpleCell after={<IconButton hasFocusVisible={false} />}>`, потому что сам `IconButton` не знает что он в неготовом месте — разве нет?

2021-06-16 14:53 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +          props.onKeyDown = this.onKeyDown;
Я печатаю какой-то текст в инпуте, нажимаю пробел, что-то внезапно фокусируется / кликается

2021-06-16 14:58 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +  hasFocusVisible?: boolean;
я это вижу так:
- `hasFocusVisible` в `Tappable` по дефолту `false`,
- мы сейчас сделали его `true` для `Button`, потому что `Button` к этому полностью готов,
- когда поправим все места с `IconButton` — так же, как для `Button`, в `IconButton.tsx` пропишем `hasFocusVisible`,
- для остальных компонентов схема такая же.

2021-06-16 15:07 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +        [focusVisibleMode]: hasFocusVisible && !isPresetFocusVisibleMode,
сделала `data-vkui-focus-visible`. ✅

2021-06-16 15:08 UTC, eugpoloz commented
я предлагаю начать делать ставки, будет 100+ комментариев или нет!

2021-06-16 15:41 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +  hasFocusVisible?: boolean;
а, там просто была речь про SimpleCell и я немного запутался

тогда ок

2021-06-21 12:07 UTC, thoughtspile requested changes

2021-06-21 12:07 UTC, thoughtspile commented on src/components/Tappable/Tappable.css
> +    transition: top .15s ease, left .15s ease, right .15s ease, bottom .15s ease;
выглядит гораздо лучше! только мне кажется, что анимации не-композита немного дерганые. Может, стоит попробовать сделать top/left etc 2px по дефолту, но добавить `scale3d(0.9, 0.9, 1)`? (и лучше позвать дизайнера чтобы он помог сравнить)

2021-06-21 12:07 UTC, thoughtspile commented on src/lib/accessibility.ts
> +  const { target, key } = e.nativeEvent;
а зачем тут `NativeEvent`?

2021-06-21 12:17 UTC, eugpoloz commented on src/lib/accessibility.ts
> +  const { target, key } = e.nativeEvent;
я передаю реактовый `KeyboardEvent` и из него достаю уже нативный.) Могу в принципе и сразу `nativeEvent` передавать, чтобы сюда уже только `KeyboardEvent` обычный падал — и все.

2021-06-21 12:21 UTC, eugpoloz commented on src/components/Tappable/Tappable.css
> +    transition: top .15s ease, left .15s ease, right .15s ease, bottom .15s ease;
`scale()` здесь выглядит как немного опасная штука, потому что кнопки не квадратные и такой ровный прыжок, как нам нужен, не получится. Подумаю, какие еще у вас есть варианты.

2021-06-21 12:29 UTC, thoughtspile commented on src/components/Tappable/Tappable.css
> +    transition: top .15s ease, left .15s ease, right .15s ease, bottom .15s ease;
(а луче оставить этот ::before только при :focus и сделать animation вместо transition)

2021-06-21 12:30 UTC, thoughtspile commented on src/lib/accessibility.ts
> +  const { target, key } = e.nativeEvent;
а в синтетическом нет тех же target и key?

2021-06-21 12:35 UTC, thoughtspile commented on src/components/Tappable/Tappable.css
> +    transition: top .15s ease, left .15s ease, right .15s ease, bottom .15s ease;
больше никаких вариантов) Я понимаю, что анимация sclae начнется из-под кнопки, а не прямо от края, но мне кажется что это визуально это незаметно (ну как-то выросла и выросла за 150ms) — главное, финальная обводка ровная и четкая. Но конечно тут нужна помощь человека с тренированными глазами

2021-06-21 12:43 UTC, eugpoloz commented on src/components/Tappable/Tappable.css
> +    transition: top .15s ease, left .15s ease, right .15s ease, bottom .15s ease;
В теории можно отцентровать и анимировать `max-width` и `max-height` со 100% до 
`calc(100% + 4px)`, нестареющая классика, так сказать. 

Но вариант, при котором мы вообще before только при фокусе с клавиатуры добавляем, мне больше нравится. Как сделаю тогда — призову к нам на помощь дизайн, пусть тренированными глазами поглядят, пойдет ли такая анимация. ❤️

2021-06-21 12:45 UTC, eugpoloz commented on src/lib/accessibility.ts
> +  const { target, key } = e.nativeEvent;
нет, все в `nativeEvent` попрятано.

2021-06-21 13:11 UTC, thoughtspile commented on src/components/Tappable/Tappable.css
> +    transition: top .15s ease, left .15s ease, right .15s ease, bottom .15s ease;
> В теории можно отцентровать и анимировать max-width и max-height со 100% до calc(100% + 4px)

Я почти уверен, что плавная субпиксельность будет только у композита через transform

2021-06-21 13:35 UTC, thoughtspile commented on src/lib/accessibility.ts
> +  const { target, key } = e.nativeEvent;
точно? https://codesandbox.io/s/strange-newton-mr5tf?file=/src/App.js

2021-06-29 12:56 UTC, ArthurStam commented on src/components/AppRoot/AppRoot.tsx
> +      'AppRoot--focus-visible': isKeyboardInputActive,
Я бы назвал его `AppRoot--keyboard-input`

2021-06-29 12:56 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +   * @ignore Временное свойство для работы над доступностью. Указывает, должен ли компонент показывать focus ring при навигации с клавиатуры.
Указать, почему оно временное

2021-06-29 12:56 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +  focusVisibleMode?: 'outline' | string;
Напомни плз, зачем мы это свойство игнорим?

2021-06-29 12:56 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +                    data-vkui-focus-visible={hasFocusVisible && !isPresetFocusVisibleMode ? focusVisibleMode : null}
Это нужное свойство? Не нашел использований.

2021-06-29 13:07 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +  focusVisibleMode?: 'outline' | string;
Это временно, пока мы в процессе работы, когда все компоненты на Tappable подшаманим — перестанем игнорить.)
Тоже допишу.

2021-06-29 15:44 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +                    data-vkui-focus-visible={hasFocusVisible && !isPresetFocusVisibleMode ? focusVisibleMode : null}
Договорились пока выпилить возможность кастомизации focus-visible состояния, так как текущее решение с `.AppRoot--focus-visible [data-vkui-focus-visible="customFocusVisibleMode"]` кажется громоздким и неинтуитивным.

2021-06-29 15:45 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +  focusVisibleMode?: 'outline' | string;
Договорились выпилить это свойство до тех пор, пока не понадобится кастомизация отображения этого состояния

2021-06-30 13:05 UTC, ArthurStam commented on src/components/Button/Button.test.tsx
> +  it('a11y: custom button has role="button" and tabindex', () => {
Хорошо бы ещё проверить, что корректно проставляется переданный `tabIndex`. У нас там довольно сложная логика вычисления итогового значения.

2021-06-30 13:05 UTC, ArthurStam commented on src/components/Button/Readme.md
> +    <Group header={<Header mode="secondary">Доступность кнопок</Header>}>
А читателю нужен этот блок? Кнопки и так повсюду станут доступными. Тут мы как будто просто рисуем ещё две кнопки, которые ничем не отличаются от остальных. А на console.log никто не посмотрит.

2021-07-01 13:23 UTC, ArthurStam approved these changes

2021-07-01 14:14 UTC, merged