Added disable prop to datepicker
VKCOM/VKUI pull request #1668
Opened 2021-06-11 00:44 UTC by Fsss126

- Добавила прокидывание пропса disabled на child инпуты

2021-06-11 07:53 UTC, ArthurStam commented
Спасибо за MR! Можешь убрать оттуда изменения `.gitignore`?

2021-06-11 07:54 UTC, ArthurStam requested changes
Спасибо за MR! Можешь убрать оттуда изменения .gitignore?

2021-06-11 08:02 UTC, Fsss126 commented
> Спасибо за MR! Можешь убрать оттуда изменения .gitignore?

Да, но у меня там создавались доп файлы. Ну и вообще файлы IDE же обычно игнорятся, у вас намеренно лишь часть исключена?

2021-06-11 08:03 UTC, ArthurStam commented
Ага, намеренно. Мы можем обсудить 

> > Спасибо за MR! Можешь убрать оттуда изменения .gitignore?
> 
> Да, но у меня там создавались доп файлы. Ну и вообще файлы IDE же обычно игнорятся, у вас намеренно лишь часть исключена?

Ага, намеренно. Мы можем обсудим целесообразность частичного исключения за пределами этого MR)

2021-06-18 11:05 UTC, Fsss126 commented
> > > Спасибо за MR! Можешь убрать оттуда изменения .gitignore?
> > 
> > 
> > Да, но у меня там создавались доп файлы. Ну и вообще файлы IDE же обычно игнорятся, у вас намеренно лишь часть исключена?
> 
> Ага, намеренно. Мы можем обсудим целесообразность частичного исключения за пределами этого MR)

Вернула

2021-06-21 11:25 UTC, thoughtspile approved these changes

2021-06-21 12:12 UTC, merged