Added disabled prop & supported anchor attrs
VKCOM/VKUI pull request #1692
Opened 2021-06-22 07:01 UTC by gbowsky

* Добавил проп `disabled`;
* Добавил поддержку пропов `href`, `target` — #1592;
* Добавил ссылку на HorizontalScroll в документации.

2021-06-22 07:31 UTC, eolme commented
Может пора? #1586

2021-06-22 08:55 UTC, thoughtspile requested changes

2021-06-22 08:55 UTC, thoughtspile commented on src/components/HorizontalCell/HorizontalCell.tsx
> +  HTMLAttributes<HTMLElement>,
`interface AnchorHTMLAttributes<T> extends HTMLAttributes<T>`, так что этот можно убрать

2021-06-22 08:55 UTC, thoughtspile commented on src/components/HorizontalCell/HorizontalCell.tsx
> +    children = <Avatar size={56} />,
пожалуйста, верни `defaultProps` или перенеси это в аргумент, а то дока [немного поломалась](https://github.com/VKCOM/VKUI/issues/1586#issuecomment-865709818)

2021-06-22 08:55 UTC, thoughtspile commented on src/components/HorizontalCell/HorizontalCell.tsx
> +    <RootComponent vkuiClass={classNames(getClassName('HorizontalCell', platform), `HorizontalCell--${size}`)} ref={getRootRef} {...restProps}>
уверен, что мы можем просто так перевесить пропы на другой элемент и ничего не сломать?

2021-06-22 09:33 UTC, gbowsky commented on src/components/HorizontalCell/HorizontalCell.tsx
> +    <RootComponent vkuiClass={classNames(getClassName('HorizontalCell', platform), `HorizontalCell--${size}`)} ref={getRootRef} {...restProps}>
немного не уверен в том как правильно выносить anchor пропы, маякни если можно лучше 🐙

2021-06-22 09:50 UTC, thoughtspile commented on src/components/HorizontalCell/HorizontalCell.tsx
> +    <RootComponent vkuiClass={classNames(getClassName('HorizontalCell', platform), `HorizontalCell--${size}`)} ref={getRootRef} {...restProps}>
кошмар какой-то, и чего сразу не сделали обертку=Tappable. Сейчас подумаю

2021-06-22 09:57 UTC, thoughtspile commented on src/components/HorizontalCell/HorizontalCell.tsx
> +    <RootComponent vkuiClass={classNames(getClassName('HorizontalCell', platform), `HorizontalCell--${size}`)} ref={getRootRef} {...restProps}>
мне кажется, сейчас лучший варик — прокинуть `Component={RootComponent}` в `Tappable`, он все равно полностью занимает Cell. И это будет работать с #1652 Видишь какие-нибудь проблемы?

2021-06-22 10:07 UTC, gbowsky commented on src/components/HorizontalCell/HorizontalCell.tsx
> +    <RootComponent vkuiClass={classNames(getClassName('HorizontalCell', platform), `HorizontalCell--${size}`)} ref={getRootRef} {...restProps}>
> и чего сразу не сделали обертку=Tappable

если ты про корневой элемент, то нельзя — компонент сам расставляет себе отступы по бокам

2021-06-22 18:45 UTC, gbowsky commented on src/components/HorizontalCell/HorizontalCell.tsx
> +    <RootComponent vkuiClass={classNames(getClassName('HorizontalCell', platform), `HorizontalCell--${size}`)} ref={getRootRef} {...restProps}>
RootComponent в Tappable прокинул

2021-06-22 18:49 UTC, thoughtspile commented on src/components/HorizontalCell/HorizontalCell.tsx
> +    <RootComponent vkuiClass={classNames(getClassName('HorizontalCell', platform), `HorizontalCell--${size}`)} ref={getRootRef} {...restProps}>
теперь нужно убрать `anchorProps` и вернуть `style / className` на обертку)

2021-06-22 19:00 UTC, gbowsky commented on src/components/HorizontalCell/HorizontalCell.tsx
> +    <RootComponent vkuiClass={classNames(getClassName('HorizontalCell', platform), `HorizontalCell--${size}`)} ref={getRootRef} {...restProps}>
Дошло, тупняк по жаре вышел. Почему-то казалось, что если `href`, `target`, ...etc, не будут проброшены в корневой элемент, то не сработает переход. My bad.

2021-06-22 19:32 UTC, thoughtspile commented on src/components/HorizontalCell/HorizontalCell.tsx
> +    <RootComponent vkuiClass={classNames(getClassName('HorizontalCell', platform), `HorizontalCell--${size}`)} ref={getRootRef} {...restProps}>
таак, у нас теперь RootComponent обернут в RootComponent

2021-06-23 09:49 UTC, thoughtspile approved these changes

2021-06-24 17:18 UTC, merged