Убирает дублирование рендера свойства after в компоненте RichText
VKCOM/VKUI pull request #1700
Opened 2021-06-24 14:22 UTC by s-pivovarov

Связанные проблемы:
- #1699
- #1059

2021-06-24 14:25 UTC, ArthurStam requested changes

2021-06-24 14:25 UTC, ArthurStam commented on src/components/RichCell/RichCell.css
> -.RichCell__top > :first-child:not(.RichCell__content) {
Этот рендер там был неслучайно. Посмотри на следующее правило. Это хак, чтобы на уровне css определить, что было передано в after

2021-06-24 14:56 UTC, s-pivovarov commented on src/components/RichCell/RichCell.css
> -.RichCell__top > :first-child:not(.RichCell__content) {
Да, ты прав. Подумаю что можно сделать

2021-06-24 15:06 UTC, thoughtspile commented on src/components/RichCell/RichCell.css
> -.RichCell__top > :first-child:not(.RichCell__content) {
`!important` конечно же

2021-06-24 17:34 UTC, s-pivovarov commented on src/components/RichCell/RichCell.css
> -.RichCell__top > :first-child:not(.RichCell__content) {
Не хотелось, но придется)
Поменяю описание PR и сделаю отдельный коммит. На всякий добавлю коммент в css

2021-06-24 17:41 UTC, thoughtspile commented on src/components/RichCell/RichCell.css
> -.RichCell__top > :first-child:not(.RichCell__content) {
современные проблемы требуют современных решений

2021-06-29 12:32 UTC, ArthurStam commented
Привет. Спасибо за MR. Мы уже поправили проблему появившегося after.

2021-06-29 12:32 UTC, closed without merging