Доступность: Banner
VKCOM/VKUI pull request #1718
Opened 2021-07-07 20:34 UTC by eugpoloz

У Banner оказалось достаточно много всего, так что я и его вынесла отдельной веткой.

**Что сделала по доступности:**
- Поменяла `<div/>` на `<section/>` в обертке;
- Добавила пропсы `role` и `Component` для `Tappable` внутри баннера;
- Добавила текстовые компоненты вместо `div` для текстового контента баннера;
- Поменяла для кнопки скрытия баннера `<button/>` на `IconButton` и добавила ей `dismissLabel`;
- Добавила `aria-hidden="true"` для бэкграунда.

Дополнительно:
- вынесла обнаружившиеся стили для `Button` в `Button`;
- порефакторила код и подчистила css.

2021-07-08 12:36 UTC, ArthurStam requested changes
Я бы расширил скриншотные тесты, раз был рефакторинг. Как минимум хочется убедиться, что разные `asideMode` рисуются корректно.

2021-07-08 12:36 UTC, ArthurStam commented on src/components/Banner/Banner.tsx
> +    <section
Как на счёт [role="banner"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role)? Уместно тут его использовать?

2021-07-08 16:05 UTC, eugpoloz commented on src/components/Banner/Banner.tsx
> +    <section
Насчет тестов согласна, докину!

А вот `role="banner"` тут 100% не подходит, потому что это [landmark роль для шапки всего сайта](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role):

> A `banner` role **represents general and informative content frequently placed at the beginning of the page**. This usually includes a logo, company name, search icon, photo related to the page, or slogan.

> By default, the HTML5 `<header>` element has an identical meaning to the banner landmark, unless it is a descendant of `<aside>`, `<article>`, `<main>`, `<nav>`, or `<section>`.

2021-07-09 15:21 UTC, ArthurStam approved these changes

2021-07-09 15:24 UTC, merged