refactor: Типографические компоненты
VKCOM/VKUI pull request #1732
Opened 2021-07-14 12:39 UTC by eugpoloz

Подчистила типографические компоненты:
- упростила то, как задаются weight и Component, передоверила упрощения стилей для андроида css;
- проставила для `Text` и `Caption` в качестве дефолтного компонента `span` с `display: block;` в стилях;
- добавила скриншотные тесты (и, кажется, отловила ошибку в `Title`);
- выкинула лишние `Component="span"`. 😄

2021-07-14 12:44 UTC, eolme commented
Напоминаю про #1586

2021-07-14 12:47 UTC, eugpoloz commented
@eolme 

> Напоминаю про #1586

Спасибо, упустила этот момент! Поправлю.

2021-07-15 06:41 UTC, ArthurStam requested changes
Предлагаю вынести отсюда тесты, замержить их отдельно в master и потом обновить этот MR, чтобы быть уверенными, что после рефакторинга ничего не сломалось.

2021-07-15 12:28 UTC, eugpoloz commented
@ArthurStam

> Предлагаю вынести отсюда тесты, замержить их отдельно в master и потом обновить этот MR, чтобы быть уверенными, что после рефакторинга ничего не сломалось.

Готово!

Остался только вопрос с `<Title level="1" weight="semibold" />` для андроида, но я тут уверена, что MRом пофиксила наше оставшееся незамеченным несоответствие дизайну, поэтому апдейтнула скриншоты руками.

2021-07-19 15:49 UTC, ArthurStam commented on src/components/Typography/Caption/Caption.tsx
> -  let captionWeight: CaptionProps['weight'] = weight;
Нужна пояснительная бригада. У `Caption` в Android нет жирности `semibold`, есть `medium`. Чтобы разработчики не страдали, мы делаем конвертацию `semibold` в `medium` за них. Тут эта конвертация выпилена и добавлен стиль в css. Какова цель?

2021-07-19 15:49 UTC, ArthurStam commented
Аналогичные комментарии ко всем компонентам, которые подвергнулись экзекуции

2021-07-19 16:00 UTC, eugpoloz commented on src/components/Typography/Caption/Caption.tsx
> -  let captionWeight: CaptionProps['weight'] = weight;
Решаем ту же проблему через стили, чтобы не делать эти конвертации. То есть если у нас `Caption` с жирностью `semibold`, мы не делаем ничего непосредственно с жирностью, просто сбрасываем стиль `.Caption--android.Caption--semibold` до такого же, как `.Caption--android.Caption--medium`.

Это неправильный подход? Нам нужно, чтобы был прямо проп?

2021-07-19 16:09 UTC, ArthurStam commented on src/components/Typography/Caption/Caption.tsx
> -  let captionWeight: CaptionProps['weight'] = weight;
А зачем?

2021-07-19 16:11 UTC, eolme commented on src/components/Typography/Caption/Caption.tsx
> -  let captionWeight: CaptionProps['weight'] = weight;
Так разве не проще?

2021-07-19 16:19 UTC, eugpoloz commented on src/components/Typography/Caption/Caption.tsx
> -  let captionWeight: CaptionProps['weight'] = weight;
Меньше кода, читать и поддерживать проще, должна быть получше производительность. У нас в каждом типографическом компоненте было дополнительное вычисление для решения проблемы, которую можно без лишних телодвижений переложить на css. Сейчас мы от него избавились.

Расскажи, что именно тебе не нравится в этом решении?

2021-07-19 17:16 UTC, ArthurStam commented on src/components/Typography/Caption/Caption.tsx
> -  let captionWeight: CaptionProps['weight'] = weight;
Не понимаю, в чем простота. Решали на JS, теперь решили на CSS. Сомневаюсь, что выросла производительность от выпиливание ифа. Меня это решение не смущает, просто выглядит как рефакторинг без профита.

2021-07-19 17:30 UTC, ArthurStam approved these changes

2021-07-20 10:03 UTC, ArthurStam approved these changes

2021-07-20 10:10 UTC, merged