CustomSelect: removed document click handler
VKCOM/VKUI pull request #1759
Opened 2021-07-26 11:30 UTC by ArthurStam

Кажется, тут этот обработчик не нужен, так как `onBlur` на `Input/SelectMimicry` успешно скрывает список опций когда надо

2021-07-26 12:55 UTC, thoughtspile commented
по изменениям всё ок, пара моментов:
1. Сейчас onBlur вызывается до onClick по опции, это кажется опасным
2. почему на Input не вызывается onFocus?
3. `state.focused` кажется не используется
4. трюк с синтетическим focus / blur это кошмар, потому что на самом деле селект не сфокусирован
5. `props.options` и поиск скорее всего конфликтуют

2021-07-26 13:37 UTC, ArthurStam commented
1. Кек в том, что это работает из-за label-обертки. Забегая вперед скажу, что намерения по её выпиливанию есть.
2. Потому что Input появляется, когда фокус уже был. Нет смысла короче на нём этот фокус держать.
3. Да, выпилю.
4. Да.
5. А?

> по изменениям всё ок, пара моментов:
> 
> 1. Сейчас onBlur вызывается до onClick по опции, это кажется опасным
> 2. почему на Input не вызывается onFocus?
> 3. `state.focused` кажется не используется
> 4. трюк с синтетическим focus / blur это кошмар, потому что на самом деле селект не сфокусирован
> 5. `props.options` и поиск скорее всего конфликтуют

2021-07-26 14:06 UTC, thoughtspile commented
> 5. А?
> > 5. `props.options` и поиск скорее всего конфликтуют

`state.options` сеттится при input change и при изменении `props.options`, и если во время поиска проп изменится, поиск сбросится

2021-07-27 11:31 UTC, ArthurStam commented
> > 1. А?
> > 
> > > 1. `props.options` и поиск скорее всего конфликтуют
> 
> `state.options` сеттится при input change и при изменении `props.options`, и если во время поиска проп изменится, поиск сбросится

Да и норм. А какое поведение ты ожидаешь?

2021-07-29 09:13 UTC, thoughtspile requested changes

2021-07-29 09:13 UTC, thoughtspile commented on src/components/CustomSelect/CustomSelect.tsx
> +        warn('This filtration method is deprecated. Return value of onInputChange will' +
warn нужно оборачивать в `if(process.env.NODE_ENV === 'development')`, чтобы он выпиливался из прода

2021-07-29 09:13 UTC, thoughtspile commented on src/components/CustomSelect/CustomSelect.tsx
>          selectedOptionIndex: this.findSelectedIndex(this.props.options, value),
при searchable неправильно вычисляется индекс, потому что ищем по неотфильтрованному

2021-07-29 12:37 UTC, ArthurStam commented on src/components/CustomSelect/CustomSelect.tsx
>          selectedOptionIndex: this.findSelectedIndex(this.props.options, value),
Исправил и сделал тест для этого случая

2021-07-29 12:56 UTC, ArthurStam commented on src/components/CustomSelect/CustomSelect.tsx
> +        warn('This filtration method is deprecated. Return value of onInputChange will' +
fixed

2021-07-29 13:12 UTC, thoughtspile approved these changes

2021-07-29 13:14 UTC, merged