Доступность кнопок и ссылок: фиксы Tappable
VKCOM/VKUI pull request #1760
Opened 2021-07-26 11:33 UTC by eugpoloz

- Обнаружила, что в `Tappable` могли неправильно проставляться `role` и `type`. Подправила логику их проставления; заодно перенесла туда же выбор `Component` в зависимости от наличия/отсутствия `href`.

- Отрефакторила компоненты на базе `Tappable`, убрав ставший лишним код.

- Обновила юнит-тесты для `Tappable`.

2021-07-26 12:14 UTC, thoughtspile commented on src/components/Tappable/Tappable.test.tsx
> +    userEvent.tab();
непонятно, почему это теперь дублируется между тестами

2021-07-26 12:14 UTC, thoughtspile commented on src/components/Tappable/Tappable.test.tsx
> +    rerender(<TappableTest role="link" tabIndex={-1}>custom link has tabIndex {-1}</TappableTest>);
обязятельно ли завязываться на rerender, а не просто отрендерить по разу для каждого кейса?

2021-07-26 12:14 UTC, thoughtspile commented on src/components/ContentCard/ContentCard.tsx
> +        disabled={!!onClick === false || disabled}
какое смешное выражение

2021-07-26 12:14 UTC, thoughtspile commented on src/components/Button/Button.test.tsx
> +    expect(button().tagName.toLowerCase()).toMatch('a');
а старый тест не работает больше?

2021-07-26 12:14 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +      props.Component = restProps.href
кстати я считаю что href не должен побеждать явный `Component` (сейчас уже поздно то менять, просто зафиксируйте)

2021-07-26 12:14 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +        props.tabIndex = tabIndex ?? 0;
а мы точно никогда не проглотим явный `tabIndex`?

2021-07-26 12:14 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +        props.type = type ?? 'button';
если `Component !== button`, мы проглатываем `type`?

2021-07-26 12:20 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +        props.tabIndex = tabIndex ?? 0;
По идее nullish coalescent сравнивает только с null и undefined, то есть явный `-1` (который в другом случае был бы приравнен к `false`) он не должен сожрать. Плюс на это есть тест, тест проходит.

2021-07-26 12:23 UTC, eugpoloz commented on src/components/Tappable/Tappable.test.tsx
> +    userEvent.tab();
Почему дублируется?) Я проверяю отдельно кастомные ссылки и кастомные кнопки.

2021-07-26 12:28 UTC, eugpoloz commented on src/components/Button/Button.test.tsx
> +    expect(button().tagName.toLowerCase()).toMatch('a');
Работает, это я затупила.)))

2021-07-26 13:01 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +        props.type = type ?? 'button';
Спасибо, пофиксила и докинула тест!

2021-07-26 13:02 UTC, eugpoloz commented on src/components/Tappable/Tappable.test.tsx
> +    rerender(<TappableTest role="link" tabIndex={-1}>custom link has tabIndex {-1}</TappableTest>);
Не обязательно, поправила!

Чем меньше ререндеров, тем быстрее тесты проходят, верно?

2021-07-26 14:13 UTC, thoughtspile commented on src/components/Tappable/Tappable.test.tsx
> +    rerender(<TappableTest role="link" tabIndex={-1}>custom link has tabIndex {-1}</TappableTest>);
нет, просто 1 кейс = 1 тест, а проходить наверное будут чуть дольше. Если сломался `tabIndex` ссылки, то пусть взорвется сразу тест "role=link labIndex" а не общий tabIndex чтобы его еще дебажить. + от первой части теста может остаться какой-то неожилданный стейт

2021-07-26 14:14 UTC, thoughtspile commented on src/components/Tappable/Tappable.tsx
> +        props.tabIndex = tabIndex ?? 0;
не, я про то что мы достаем tabIndex из пропов и кладем на место только здесь

2021-07-26 19:13 UTC, eugpoloz commented on src/components/Tappable/Tappable.test.tsx
> +    rerender(<TappableTest role="link" tabIndex={-1}>custom link has tabIndex {-1}</TappableTest>);
Поняла тебя и раскидала их совсем.)

2021-07-26 19:26 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> -      const nativeComponents: ElementType[] = ['a', 'button', 'input', 'textarea', 'label'];
Все-таки убрала этот массив в принципе, потому что `input` и `textarea` мы за базу `Tappable` взять не можем (у `input` не может быть детей по html-спеке, [у textarea они не предусмотрены реактом](https://reactjs.org/docs/forms.html#the-textarea-tag)), а отдельно стоящий `label` потребует как минимум `tabIndex`.

2021-07-26 22:07 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +        props.tabIndex = tabIndex ?? 0;
для выключенного `Tappable` и для нативных элементов он нам и не нужен, это план. 😉

2021-07-28 15:25 UTC, ArthurStam requested changes

2021-07-28 15:25 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +      props.Component = restProps.href
Предлагаю прямо щас поменять эту логику. Если передан `Component`, то берем его, если не передан, но передан `href` — резолвим как `a`

2021-07-28 15:25 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +      props.type = !type && props.Component === 'button'
Если пользователь явно передаёт type, tabIndex и role, то нужно прям так эти атрибуты и сеттить. Щас если передать undefined, то сработает наш фоллбэк.

2021-07-28 15:28 UTC, eugpoloz commented on src/components/ContentCard/ContentCard.tsx
> +        disabled={typeof onClick !== 'function' || disabled}
Это я пыталась сохранить не мой код, но так даже лучше, сейчас выпилю!

2021-07-28 15:44 UTC, eugpoloz commented on src/components/ContentCard/ContentCard.tsx
> +        disabled={typeof onClick !== 'function' || disabled}
+

2021-07-29 13:52 UTC, ArthurStam commented on src/components/ActionSheetItem/ActionSheetItem.test.tsx
> +    expect(screen.getByRole('link')).toBe(item());
А чем такая проверка отличается от `expect(item().tagName.toLowerCase()).toMatch('a');`?

2021-07-29 13:52 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +        disabled={disabled}
Я дико извняюсь за вчерашний сумбур. Раз логика уже была такой, то давайте её оставим. Уверен, кто-то закладывался на то, что по умолчанию `ContentCard` некликабельный. Предлагаю тут оставить пометку о том, что возможно в v5 стоит пересмотреть это место. Ещё раз сорян.

2021-07-29 13:52 UTC, ArthurStam commented on src/components/Link/Link.test.tsx
> +    expect(screen.getByRole('button')).toBe( link());
Пробельчик)

2021-07-29 13:52 UTC, ArthurStam commented on src/components/Button/Button.tsx
> +      Component={restProps.href ? 'a' : 'button'}
Пример: `<Button href="#"  Component="div" />`

В 4.12.1 будет так:
`<a href="#" />`

В этой ветке так:
`<div href="#" />`

Нужен тестик, который проверит, что мы не ломаем текущее поведение.

2021-07-30 07:09 UTC, eugpoloz commented on src/components/ActionSheetItem/ActionSheetItem.test.tsx
> +    expect(screen.getByRole('link')).toBe(item());
По идее ничем. Хочешь более конкретную, чтобы сразу было понятно, чего мы ожидаем?

2021-07-30 07:27 UTC, ArthurStam commented on src/components/ActionSheetItem/ActionSheetItem.test.tsx
> +    expect(screen.getByRole('link')).toBe(item());
Не критично, можешь оставить. Я для ясности спросил) `getByRole` немного вводит в заблуждение, потому что из названия кажется, что он ищет по атрибуту `role`, которого у нативной ссылки быть не должно.

В случае с `item().tagName` понятно, что идёт проверка тега отрисованного элемента. В случае со `screen.getByRole` такого ясного понимания нет. Как-то так.

2021-07-30 07:38 UTC, eugpoloz commented on src/components/ActionSheetItem/ActionSheetItem.test.tsx
> +    expect(screen.getByRole('link')).toBe(item());
`screen.getByRole` действительно ищет по роли элемента. То есть он пройдет, если у нас будет `div` с `role="link"`. Но для нативной ссылки он тоже работает, потому что это в семантику элемента заложено. Чтобы проверить, есть ли у элемента именно заданная через атрибуты `role`, надо использовать `.toHaveAttribute('role')`.

Пожалуй, все-таки поправлю, проверка на тег выглядит уместнее.

2021-07-30 08:45 UTC, eugpoloz commented on src/components/Button/Button.tsx
> +      Component={restProps.href ? 'a' : 'button'}
✔️

2021-07-30 08:45 UTC, eugpoloz commented on src/components/Link/Link.test.tsx
> +    expect(screen.getByRole('button')).toBe( link());
✔️

2021-07-30 10:11 UTC, ArthurStam approved these changes

2021-07-30 11:59 UTC, merged