[WIP] Bottom inset of ModalCard behaviour
VKCOM/VKUI pull request #1768
Opened 2021-07-29 10:31 UTC by gbowsky

2021-08-11 18:51 UTC, ilyapishchulin commented
Когда фикс поедет в релиз?

2021-09-16 10:13 UTC, ArthurStam requested changes

2021-09-16 10:13 UTC, ArthurStam commented on src/hooks/useKeyboard.ts
> +    setTimeout(() => {
Может стоит сбрасывать таймаут? А то кажется, что при быстром focusin focusout могут начаться

2021-09-20 09:07 UTC, ArthurStam submitted a review, later dismissed

2021-09-20 09:25 UTC, ArthurStam requested changes

2021-09-20 09:25 UTC, ArthurStam commented on src/hooks/useKeyboard.ts
> +import { useEffect, useRef, useState } from 'react';
Мы пришли к `import * as React from 'react'`

2021-09-20 09:25 UTC, gbowsky commented on src/hooks/useKeyboard.ts
> +import { useEffect, useRef, useState } from 'react';
Такс, что-то пошло не так)

2021-09-20 09:28 UTC, gbowsky commented on src/hooks/useKeyboard.ts
> +import { useEffect, useRef, useState } from 'react';
+

2021-09-20 09:29 UTC, ArthurStam approved these changes

2021-09-20 09:56 UTC, merged