Доступность: focus visible у всех кнопок и ссылок
VKCOM/VKUI pull request #1771
Opened 2021-07-30 13:25 UTC by eugpoloz

- Перенесла стили для аутлайна при фокусе с клавиатуры в новый компонент `FocusVisible`,
- Добавила мод `inside`, который нужен нам в большинстве компонентов для красивой подсветки, которая не уходит за границы элемента (например, для разнообразных ячеек),
- Отрефакторила `Tappable`, чтобы использовать `FocusVisible`.
- Убрала временный `hasFocusVisible`.

Должны работать все кликабельные кнопки и ссылки, включая кликабельные ячейки, **кроме**:
- `WriteBarIcon` — будет отдельно,
- Кнопка удаления чипа в `Chip` — будет поправлена в рамках задачи по доступности `ChipsInput`/`ChipsSelect`.

2021-07-30 13:57 UTC, ArthurStam commented on src/components/Tappable/Tappable.tsx
> +  focusVisibleOutline?: FocusVisibleOutline;
Не хотим назвать это свойство `focusVisibleMode`? Потому что есть вероятность, что однажды количество вариков будет больше двух.

2021-07-30 13:57 UTC, ArthurStam commented on src/components/TabsItem/TabsItem.tsx
> +      <TypographyComponent Component="h3" vkuiClass="TabsItem__in" weight="medium">{children}</TypographyComponent>
А почему `h3`?

2021-07-30 13:57 UTC, ArthurStam commented on src/components/RichCell/RichCell.css
> +  margin: 0 -4px;
Объяснитес)
Тут исправляется какая-то проблема?

2021-07-30 13:57 UTC, ArthurStam commented on src/components/Removable/Removable.tsx
> +      setTimeout(() => removeButton.focus(), 150);
Без таймаута не фурычит? Может `useLayoutEffect` бахнуть тогда? Или таймер для других целей тут?

2021-07-30 14:11 UTC, eugpoloz commented on src/components/RichCell/RichCell.css
> +  margin: 0 -4px;
Да, чтобы у кнопок внутри аутлайн виден был. 😏

2021-07-30 14:12 UTC, ArthurStam commented on src/components/FocusVisible/FocusVisible.css
> +.AppRoot--keyboard-input *:focus > .FocusVisible {
Эта звездочка меня слегка пугает. Может сделаем `.Tappable` вместо неё?

2021-07-30 14:12 UTC, eugpoloz commented on src/components/Removable/Removable.tsx
> +      setTimeout(() => removeButton.focus(), 150);
Без таймаута фурычит, но есть проблемка с производительностью анимации тогда.

2021-07-30 14:16 UTC, eugpoloz commented on src/components/FocusVisible/FocusVisible.css
> +.AppRoot--keyboard-input *:focus > .FocusVisible {
В теории эта штука будет не только в Tappable, я хочу и на всякие инпуты-селекты ее накинуть (даже задачка в эпике на это есть), чтобы виднее было, какой сейчас активен. Поэтому и звездочка.

2021-07-30 14:18 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +  focusVisibleOutline?: FocusVisibleOutline;
Я как раз сначала его так и назвала, а потом поменяла, уже даже не помню, почему. 🤣 Переименую, да.

2021-07-30 14:26 UTC, eugpoloz commented on src/components/TabsItem/TabsItem.tsx
> +      <TypographyComponent Component="h3" vkuiClass="TabsItem__in" weight="medium">{children}</TypographyComponent>
Сейчас там получается разный `Component`: берется тот, который лежит в основе типографческого компонента, а их тут аж три — меняются в зависимости от платформы и `mode`. Кмк, это не очень правильно и лучше бы он был какой-то один, раз мы не даем юзерам либы его кастомизировать. 

(Я бы, кстати, предложила дать его кастомизировать, чтобы все в своих приложениях могли выстраивать правильную иерархию заголовков.)

2021-07-30 14:27 UTC, ArthurStam commented on src/components/FocusVisible/FocusVisible.css
> +.AppRoot--keyboard-input *:focus > .FocusVisible {
А как на инпуты можно такое накинуть, если фокус ловится на нативном элементе у которого не может быть дочерних?

2021-07-30 14:28 UTC, ArthurStam commented on src/components/TabsItem/TabsItem.tsx
> +      <TypographyComponent Component="h3" vkuiClass="TabsItem__in" weight="medium">{children}</TypographyComponent>
Окей, почему именно `h3` выбрали, а не какой-нибудь `span`?

2021-07-30 14:29 UTC, eugpoloz commented on src/components/FocusVisible/FocusVisible.css
> +.AppRoot--keyboard-input *:focus > .FocusVisible {
Хм. Да, ты прав, там сиблинга придется выбирать все равно…

Хорошо, тогда поправлю!

2021-07-30 14:29 UTC, ArthurStam commented on src/components/Removable/Removable.tsx
> +      setTimeout(() => removeButton.focus(), 150);
Типа что одна анимация на другую накладывается?

2021-07-30 15:50 UTC, ArthurStam requested changes
Случайно увидел, что у `RichCell` поменялось позиционирование иконки `after`

2021-07-30 15:54 UTC, ArthurStam reviewed
Заметил, что если зафорсить состояние :focus-visible через браузер, то будет вот такая стилизация. Выглядит, как не наша
![image](https://user-images.githubusercontent.com/5061840/127679302-29d16f61-7d42-41b7-a0be-c1ece8c16a69.png)
![image](https://user-images.githubusercontent.com/5061840/127679340-7c29a652-2037-411d-8387-fa9cfbe3f8e2.png)

2021-07-30 16:06 UTC, eugpoloz commented on src/components/TabsItem/TabsItem.tsx
> +      <TypographyComponent Component="h3" vkuiClass="TabsItem__in" weight="medium">{children}</TypographyComponent>
У `Headline` как дефолтный компонент проставлен `h3`.

2021-07-30 16:18 UTC, eugpoloz commented on src/components/FocusVisible/FocusVisible.css
> +.AppRoot--keyboard-input *:focus > .FocusVisible {
✔️

Коммит: https://github.com/VKCOM/VKUI/pull/1771/commits/e4146fe16d0bf16672046c54e85a4a4dcf4f859e

2021-07-30 16:19 UTC, eugpoloz commented on src/components/Tappable/Tappable.tsx
> +  focusVisibleOutline?: FocusVisibleOutline;
✔️ 

Коммиты:
- https://github.com/VKCOM/VKUI/pull/1771/commits/e6b774e5b198a8eb2741890d643c7af4b89b3cc0
- https://github.com/VKCOM/VKUI/pull/1771/commits/5b279ec3752627e7ec6128e5e89ce28839f5857f
- https://github.com/VKCOM/VKUI/pull/1771/commits/07d4f80d3a04afbb783cce58466ab9a3348147f1

2021-07-30 16:19 UTC, ArthurStam commented on src/components/TabsItem/TabsItem.tsx
> +      <TypographyComponent Component="h3" vkuiClass="TabsItem__in" weight="medium">{children}</TypographyComponent>
Но мы ж вольны табы сделать какими угодно. Я про табы спрашиваю. С точки зрения семантики, каждый таб должен быть `h3`?

2021-07-30 18:06 UTC, eugpoloz commented on src/components/TabsItem/TabsItem.tsx
> +      <TypographyComponent Component="h3" vkuiClass="TabsItem__in" weight="medium">{children}</TypographyComponent>
Нет, конечно, он действительно каким угодно может быть.

2021-07-30 18:09 UTC, eugpoloz commented on src/components/Removable/Removable.tsx
> +      setTimeout(() => removeButton.focus(), 150);
FYI, немного подправила: подогнала таймаут под выполнение анимации сдвига и поставила кнопке "Удалить" `focusVisibleMode="outside"`, чтобы синее на красное не накладывалось.
(коммит https://github.com/VKCOM/VKUI/pull/1771/commits/fa92fde1e9eabf39d56300edd978262d065c7196).

2021-07-30 18:11 UTC, eugpoloz commented
@ArthurStam 
> Заметил, что если зафорсить состояние :focus-visible через браузер, то будет вот такая стилизация. Выглядит, как не наша

Спасибо, подфиксила! Туть:
- https://github.com/VKCOM/VKUI/pull/1771/commits/d194901212766b4f7ab5120b84ea83da9b623832
- https://github.com/VKCOM/VKUI/pull/1771/commits/0ca517a56407f3cf9d9155e6553ffc2d23fa9093

2021-08-07 08:32 UTC, ArthurStam commented on src/components/FocusVisible/FocusVisible.tsx
> +  <span aria-hidden="true" vkuiClass={`FocusVisible FocusVisible--${mode}`} />
Давай использовать `classNames`

2021-08-07 08:32 UTC, ArthurStam commented on src/components/FocusVisible/FocusVisible.css
> +.AppRoot--keyboard-input .Tappable:focus-visible > .FocusVisible {
Псевдокласс `:focus-visible` и так подразумевает, что был фокус по табу, поэтому тут ниже предлагаю убрать `.AppRoot--keyboard-input`

2021-08-07 08:32 UTC, ArthurStam commented on src/components/MiniInfoCell/MiniInfoCell.css
> +  padding: 4px;
Я всё же не понимаю, как нам помогает такое перепозиционирование. Расскажи плз)

2021-08-07 08:32 UTC, ArthurStam commented on src/components/Removable/Removable.tsx
> +      setTimeout(() => removeButton.focus(), 61);
Два вопроса:
1. Нужно ли нам ваще париться об автоматическом фокусе на выехавшей кнопке удаления?
2. Можем ли мы тут использовать событие `transitionend` вместо таймаута?

2021-08-07 08:32 UTC, ArthurStam commented on src/components/Removable/Removable.tsx
>              tabIndex={isRemoveActivated ? null : -1}
Раз уж мы тут. Если мы рисуем кнопку, то вроде не нужны эти ручные манипуляции с `tabIndex`. В заблокированном состоянии таб пройдет мимо неё

2021-08-07 08:32 UTC, ArthurStam commented on src/components/Tabs/Tabs.tsx
> +  mode?: TabsMode;
Ииии в доке юзер теперь увидит не union с расписанными значениями, а загадочный `TabsMode`, внутри которого непонятно что

2021-08-09 18:19 UTC, eugpoloz commented on src/components/FocusVisible/FocusVisible.tsx
> +  <span aria-hidden="true" vkuiClass={`FocusVisible FocusVisible--${mode}`} />
Всегда про него забываю, штош.)))

2021-08-09 18:37 UTC, eugpoloz commented on src/components/MiniInfoCell/MiniInfoCell.css
> +  padding: 4px;
Смотри.

Вот у нас есть компонент внутри `.MiniInfoCell__content` (скажем, `Link`) и есть необходимость его подсветить при навигации с клавиатуры. Казалось бы, все просто: берем и подсвечиваем. Но. На `.MiniInfoCell__content` накинут `overflow: hidden;`. Получается такая штука:

- мы рисуем аутлайн вокруг `Link`, чтобы его подсветить,
- этот аутлайн выходит за границы `.MiniInfoCell__content`,
- из-за `overflow: hidden;` юзер либы аутлайн не увидит либо частично, либо целиком.

Поэтому, чтобы его таки показать, я добавляю внутрь `.MiniInfoCell__content` паддинг.

2021-08-09 18:48 UTC, eugpoloz commented on src/components/Tabs/Tabs.tsx
> +  mode?: TabsMode;
😞 

Вернула как было: https://github.com/VKCOM/VKUI/pull/1771/commits/e1a8bb1464463145359a3f142b925b15bf7df8dc

2021-08-09 18:48 UTC, eugpoloz commented on src/components/FocusVisible/FocusVisible.css
> +.AppRoot--keyboard-input .Tappable:focus-visible > .FocusVisible {
➕ https://github.com/VKCOM/VKUI/pull/1771/commits/a03d2155edf3cf9babaf993b851e02ce1082bb3c

2021-08-09 18:49 UTC, eugpoloz commented on src/components/FocusVisible/FocusVisible.tsx
> +  <span aria-hidden="true" vkuiClass={`FocusVisible FocusVisible--${mode}`} />
➕ https://github.com/VKCOM/VKUI/pull/1771/commits/a03d2155edf3cf9babaf993b851e02ce1082bb3c

2021-08-09 18:50 UTC, eugpoloz commented on src/components/TabsItem/TabsItem.tsx
> +      <TypographyComponent Component="h3" vkuiClass="TabsItem__in" weight="medium">{children}</TypographyComponent>
Будем тут все-таки менять на `span`?

2021-08-09 19:20 UTC, eugpoloz commented on src/components/Removable/Removable.tsx
> +      setTimeout(() => removeButton.focus(), 61);
1. Да, потому что иначе табать до нее мы будем через все поля. Плюс она назад заедет, как только фокус сместится в эти самые поля.
2. Проверим. :)

2021-08-10 08:00 UTC, eugpoloz commented on src/components/Removable/Removable.tsx
> +      setTimeout(() => removeButton.focus(), 150);
Предлагаю эту ветку зарезолвить, раз она продолжается [в другом месте](https://github.com/VKCOM/VKUI/pull/1771#discussion_r684603945). 😃

2021-08-10 08:06 UTC, eugpoloz commented on src/components/Removable/Removable.tsx
>              tabIndex={isRemoveActivated ? null : -1}
➕ https://github.com/VKCOM/VKUI/pull/1771/commits/4a4eceaecfe5d9adc741af9c4d200349884860bf

2021-08-10 08:18 UTC, eugpoloz commented on src/components/RichCell/RichCell.css
> +  margin: 0 -4px;
Кажется, эту ветку тоже можно зарезолвить, продолжаем [https://github.com/VKCOM/VKUI/pull/1771#discussion_r684603800](здесь с более подробными пояснениями).

2021-08-10 08:56 UTC, ArthurStam commented on src/components/TabsItem/TabsItem.tsx
> +      <TypographyComponent Component="h3" vkuiClass="TabsItem__in" weight="medium">{children}</TypographyComponent>
Давай поменяем

2021-08-10 08:58 UTC, ArthurStam commented on src/components/MiniInfoCell/MiniInfoCell.css
> +  padding: 4px;
Получается, что у нас два пути:
1. Забить на то, что часть аутлайна уйдет за оверфлоу и не усложнять систему отступов.
2. Наоборот.
Учитывая, что щас в соседнем MR Вова пытается реализовать компоненты без отступов и там каждый такой кейс с нетипичными отступами приходится мучительно раскупировать, я бы всё-таки забил на то, что аутлайн частично уезжает за пределы.

2021-08-10 08:59 UTC, ArthurStam commented on src/components/MiniInfoCell/MiniInfoCell.css
> +  padding: 4px;
Можешь показать, как выглядит пример с Link внутри, если не манипулировать отступами?

2021-08-10 09:04 UTC, ArthurStam requested changes

2021-08-10 09:04 UTC, ArthurStam commented on src/components/Removable/Removable.tsx
> +      removeButton.ontransitionend = () => removeButton.focus();
Я бы переехал на `addEventListener('transitionend')`, пушто такой способ задания событий исключает перезатирание других слушателей.

2021-08-10 09:04 UTC, ArthurStam commented on src/components/Removable/Removable.tsx
> +      removeButton.ontransitionend = () => removeButton.focus();
Не забыли тут `removeEventListener`?

2021-08-10 09:11 UTC, eugpoloz commented on src/components/MiniInfoCell/MiniInfoCell.css
> +  padding: 4px;
Договорились, что забиваем.

2021-08-10 10:03 UTC, eugpoloz commented on src/components/Removable/Removable.tsx
> +      setTimeout(() => removeButton.focus(), 61);
➕ https://github.com/VKCOM/VKUI/pull/1771/commits/eb6ee466d8fabb8bb3a178635ae63b5a9508e593

2021-08-10 10:06 UTC, eugpoloz commented on src/components/Removable/Removable.tsx
> +      removeButton.ontransitionend = () => removeButton.focus();
А посмотри вот тут, пожалуйста: https://github.com/VKCOM/VKUI/pull/1771/commits/eb6ee466d8fabb8bb3a178635ae63b5a9508e593

Других слушателей там по идее быть не может, мы ничего такого не даем прокидывать в кнопку, но я переделала. 😄

2021-08-10 10:08 UTC, eugpoloz commented on src/components/MiniInfoCell/MiniInfoCell.css
> +  padding: 4px;
➕ 
Прибрала те два коммита.

2021-08-10 10:09 UTC, eugpoloz commented on src/components/TabsItem/TabsItem.tsx
> +      <TypographyComponent Component="h3" vkuiClass="TabsItem__in" weight="medium">{children}</TypographyComponent>
➕ 
[В коммите вот тут](https://github.com/VKCOM/VKUI/pull/1771/commits/e285d1b246f0017fcbe83ececef56fd162ae0505#diff-8467db8467f4148cbcdf659bd52ac0f0c9c4f12285e434fa4e12dee21084bd6dR44).

2021-08-11 09:04 UTC, ArthurStam approved these changes

2021-08-11 09:11 UTC, merged