refactor: ContentCard
VKCOM/VKUI pull request #1772
Opened 2021-07-30 13:34 UTC by eugpoloz

По мотивам комментария Артура к #1726: перекинула `{...restProps}` на `Tappable` вместо `<img />`.

Заодно предлагаю задепрекейтить проп `image` и выкинуть его в v5, а пока использовать наравне с классическим `src`.

2021-07-30 15:58 UTC, ArthurStam reviewed
Предлагаю в доке описать, что у этого компонента свойства разносятся между `img`, `Tappable` и root-элементом. Можно или в свойствах, или в readme. Как угодно)

2021-07-30 15:58 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
>    image?: string;
У нас во всех остальных местах используется `src`? Я за такое переименование, но хочется тогда уж везде разом придти к одному неймингу. Если это последний такой компонент, то отлично

2021-07-30 16:01 UTC, eugpoloz commented on src/components/ContentCard/ContentCard.tsx
>    image?: string;
Последний, я не вижу других таких.

2021-07-30 16:03 UTC, eugpoloz commented
@ArthurStam 
> Предлагаю в доке описать, что у этого компонента свойства разносятся между `img`, `Tappable` и root-элементом. Можно или в свойствах, или в readme. Как угодно)

О, суперская идея! Допишу тогда и сделаю PR больше-не-черновиком.

2021-08-07 08:20 UTC, ArthurStam requested changes

2021-08-07 08:20 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.tsx
> +        {(image || src) && (
Два момента:
1. Если передан `srcSet`, то тоже нужно рисовать картинку.
2. Не все свойства учтены. Вот [тут](https://github.com/VKCOM/VKUI/pull/1788/files#diff-5bde686e06876f3828b15fa207e4300b2947e5e520e076ce0f7de9e5fcc1bc2eR86-R99) более широкий список

2021-08-07 08:20 UTC, ArthurStam commented on src/components/ContentCard/Readme.md
> +- `img`
Не забыть тут упомянуть полный список свойств img

2021-08-09 10:33 UTC, eugpoloz commented on src/components/ContentCard/Readme.md
> +- `img`
➕ 
Коммит https://github.com/VKCOM/VKUI/pull/1772/commits/2324300ea76b0c820fc5dc0ff73110d22eb41d25

2021-08-09 10:35 UTC, eugpoloz commented on src/components/ContentCard/ContentCard.tsx
> +        {(image || src) && (
1. ➕ 
https://github.com/VKCOM/VKUI/pull/1772/commits/f9b9b1a19c61597e53d048995d629d7dfed95ed4

2. ➕ 
https://github.com/VKCOM/VKUI/pull/1772/commits/7104201a5247c8290b6f83ce856a76480b44ef85

2021-08-09 13:53 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.test.tsx
>  describe('ContentCard', () => {
Добавь сюда плез тест на проброс картинок как в Avatar. MR с инфрой для этого уже в мастере

2021-08-09 18:11 UTC, eugpoloz commented on src/components/ContentCard/ContentCard.test.tsx
>  describe('ContentCard', () => {
Готово!

Я заодно над ними подумала и упростила тесты (особенно тот, что на атрибуты), теперь должно быть понятнее, что происходит. Соответственно:
- [новые тесты для ContentCard](https://github.com/VKCOM/VKUI/pull/1772/commits/278a786c1424654c799d2f8a0eeaf7520c902f5a)
- [апдейт тестов для Avatar](https://github.com/VKCOM/VKUI/pull/1772/commits/7f723281bbbaed0227c3a6d48b7f5b7c752bde11)

По поводу `rerender` вспомнила, что Вова писал: лучше проверять без него (чтобы потом еще юниты не дебажить), поэтому от него тут тоже избавилась в пользу двух отдельных тестов для `src`.

2021-08-10 05:20 UTC, ArthurStam approved these changes

2021-08-10 05:20 UTC, ArthurStam commented on src/components/ContentCard/ContentCard.test.tsx
>  describe('ContentCard', () => {
Офигенно

2021-08-10 07:44 UTC, merged