feat: Clean Checkbox without paddings and children
VKCOM/VKUI pull request #1782
Opened 2021-08-04 07:46 UTC by russll

Сделан `mode='clean'` для компонента Checkbox без отступов и `children` для случаев, когда надо использовать компонент без текста, например, в таблицах настроек

![image](https://user-images.githubusercontent.com/6906898/128142358-2b42916b-e6dd-4f8f-9f0f-75b6af16e112.png)

2021-08-04 08:06 UTC, ewgenius reviewed
В мобильном отображении тень съехала https://codesandbox.io/s/vkui-default-example-forked-9u8b3?file=/example.tsx&resolutionWidth=320&resolutionHeight=675

<img width="324" alt="CleanShot 2021-08-04 at 11 02 10@2x" src="https://user-images.githubusercontent.com/827338/128145336-7bb94026-853f-4279-9e9c-b8d4a8df24fc.png">

2021-08-04 08:06 UTC, ewgenius commented on src/components/Checkbox/Checkbox.tsx
> +  mode?: 'clean';
может стоит сделать булевым флагом, если только один режим будет кроме дефолтного

2021-08-04 13:04 UTC, ArthurStam requested changes
А может сделаем его отдельным компонентам? Уж очень много ресетов на CSS приходится делать, чтобы превратить обычный чекбокс в чистый.

2021-08-07 07:59 UTC, ArthurStam requested changes

2021-08-07 07:59 UTC, ArthurStam commented on src/components/SimpleCheckbox/Readme.md
> +```jsx
Го делать упрощенные примеры. Можно посмотреть на то, как выглядит Readme Spinner

2021-08-07 07:59 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.css
> +.SimpleCheckbox--ios {
А зачем эти стили дублировать? Тот же вопрос про android

2021-08-09 08:56 UTC, eolme commented
У стиля vkcom ховер эффект поехал

![image](https://user-images.githubusercontent.com/11076888/128681855-b7b58756-b10e-4cdd-a508-2788270cbe8e.png)

2021-08-09 08:58 UTC, russll commented
Погодите пока смотреть, я хочу в codesandbox потыкать, еще не разобрался до конца как нормально протестить все темы без него

2021-08-09 10:17 UTC, russll commented
Все, разобрался как с конфигами играться

https://codesandbox.io/s/vkui-default-example-forked-fcbug

Теперь все по центру в случае ховеров для всех платформ и типоразмеров

2021-08-09 10:38 UTC, ArthurStam commented
> Погодите пока смотреть, я хочу в codesandbox потыкать, еще не разобрался до конца как нормально протестить все темы без него

В доке есть переключателю тем и платформ, проще кажется в ней

2021-08-09 11:31 UTC, russll commented
> > Погодите пока смотреть, я хочу в codesandbox потыкать, еще не разобрался до конца как нормально протестить все темы без него
> 
> В доке есть переключателю тем и платформ, проще кажется в ней

Да, он очень удобен, но почему-то у меня никак не выключается режим sizeY-compact - он же по идее завязан на ширину экрана, но я ставил 1280 и что то ничего не выходило

Возможно это связано с состоянием по умолчанию для этого чекбокса (withAdaptivity где sizeY: true ), но я че то пока не понял как мне в демо нормально это выключать через настройки) Скорее всего я что-то еще пока не знаю, поэтому сделал через сендбокс)

2021-08-09 11:32 UTC, russll commented
Перед мерджем сделаю сквош

2021-08-09 17:06 UTC, ArthurStam requested changes

2021-08-09 17:06 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +import { withAdaptivity, AdaptivityProps, SizeType } from '../../hoc/withAdaptivity';
Импортни сюда плез стили. У нас буквально с сегодняшнего дня появилась сборка с импортами css в js.

2021-08-09 17:08 UTC, ArthurStam requested changes

2021-08-09 17:08 UTC, ArthurStam commented on src/components/SimpleCheckbox/Readme.md
> +<div style={{ display: 'flex', alignItems: 'center', flexDirection: 'row' }}>
Добавь плез паддингов или высоты какой-то. А то пример сплющенный получился.

2021-08-09 17:14 UTC, russll commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +import { withAdaptivity, AdaptivityProps, SizeType } from '../../hoc/withAdaptivity';
Ага, самое время еще и сделать ребейз!

2021-08-10 12:17 UTC, ArthurStam requested changes
У платформы vkcom должны быть другие hover и active состояния. В PR рисуется круг, а в макетах его нет. Там просто затемнение внутренностей.
![image](https://user-images.githubusercontent.com/5061840/128865297-0854f1d3-98a2-4d7d-9e95-51f71dc3c7cf.png)
![image](https://user-images.githubusercontent.com/5061840/128865319-f485ec05-c069-4f2b-94d5-1e91a7e3da2d.png)

2021-08-11 07:32 UTC, russll commented
> У платформы vkcom должны быть другие hover и active состояния. В PR рисуется круг, а в макетах его нет. Там просто затемнение внутренностей.
> ![image](https://user-images.githubusercontent.com/5061840/128865297-0854f1d3-98a2-4d7d-9e95-51f71dc3c7cf.png)
> ![image](https://user-images.githubusercontent.com/5061840/128865319-f485ec05-c069-4f2b-94d5-1e91a7e3da2d.png)

Мда, что-то я не заметил это, мне надо было уточнить в начале

Может тогда еще сделать indeterminate-состояние? Или пока не планировалось?

2021-08-11 08:58 UTC, ArthurStam commented
> > У платформы vkcom должны быть другие hover и active состояния. В PR рисуется круг, а в макетах его нет. Там просто затемнение внутренностей.
> > ![image](https://user-images.githubusercontent.com/5061840/128865297-0854f1d3-98a2-4d7d-9e95-51f71dc3c7cf.png)
> > ![image](https://user-images.githubusercontent.com/5061840/128865319-f485ec05-c069-4f2b-94d5-1e91a7e3da2d.png)
> 
> Мда, что-то я не заметил это, мне надо было уточнить в начале
> 
> Может тогда еще сделать indeterminate-состояние? Или пока не планировалось?

а спроси у ребят, которые просили этот чекбокс, нужен ли им щас indeterminate

2021-08-16 13:36 UTC, russll commented
Если что, все обновил)

2021-08-16 13:43 UTC, ewgenius approved these changes

2021-08-18 17:50 UTC, russll commented
@ArthurStam чекни плиз)

2021-08-18 18:48 UTC, ArthurStam requested changes

2021-08-18 18:48 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.css
> +.SimpleCheckbox--vkcom .vkuiTappable__hoverShadow {
Такой каст стилей может привести к поломке при неопределенном порядке подключения css. Я предлагаю сделать кастомный `hoverMode` для `vkcom` и описать стили в получившемся селекторе.

2021-08-18 19:05 UTC, ArthurStam requested changes
Предлагаю такую логику `indeterminate` и `checked`:
Это два флага, управляющие состоянием. Они управляются с помощью `onChange`. Поэтому они не могут быть оба `true`. В таком случае нужно кидать ворнинг пользователю, потому что скорее всего что-то идёт не так. 

C дефолтами та же логика: оба не могут быть `true`.

2021-09-07 08:17 UTC, ArthurStam requested changes

2021-09-07 08:17 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +      hoverShadowClassName="SimpleCheckbox__hoverShadow"
Меня беспокоит, что ради уменьшенного радиуса блока с ховером мы добавляем новое свойство для Tappable. Я уверен, что этого же эффекта можно добиться стилизацией SimpleChecbox. Иначе мы усложняем API Tappable и в частности способы кастомизации ховера.

2021-09-07 08:17 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.css
> +  display: none;
Скринридеры загрустят, когда увидят, как скрыт нативный чекбокс. Точнее они ничего не увидят. У Макеева хорошо объясняется, почему так скрывать элементы форм не стоит https://www.youtube.com/watch?v=E6kLaaQFctU&t=413s

2021-09-16 11:35 UTC, russll commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +      hoverShadowClassName="SimpleCheckbox__hoverShadow"
@ArthurStam Я тоже так хотел сделать, но там была проблема в том, что из-за анимаций возникала ситуация когда этот элемент вылезал за границы чекбокса в конце анимации)) Думаю лучше добавить это свойство, к тому же это обычная практика как мне кажется, добавлять возможность кастомизации.

2021-09-16 11:37 UTC, eugpoloz commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +      hoverShadowClassName="SimpleCheckbox__hoverShadow"
@russll возможно, тебе тогда подойдет уже имеющееся свойство `hoverMode`?

2021-09-16 11:40 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +      hoverShadowClassName="SimpleCheckbox__hoverShadow"
Хочется понять, какая конечная задача. Добавление свойства — это не всегда обычная практика. Тут я пока вижу, что задумку дизайнера можно реализовать уже с имеющимся API Tappable.

2021-09-16 11:47 UTC, russll commented on src/components/SimpleCheckbox/SimpleCheckbox.css
> +  display: none;
Спасибо за видос) Закинул правки)

2021-09-16 12:07 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +      hoverShadowClassName="SimpleCheckbox__hoverShadow"
Пока я вижу, что компонент — это label с `Icon` и `Tappable`, который торчит наружу.

2021-09-16 23:01 UTC, russll commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +      hoverShadowClassName="SimpleCheckbox__hoverShadow"
> @russll возможно, тебе тогда подойдет уже имеющееся свойство `hoverMode`?

`hoverMode` нас не спасает - выше в обсуждении, когда Артур предложил его использовать я уже экспериментировал с ним, и проблема, из-за которой я и добавил свойство в Tappable, заключается в том, что при пропадании ховера мы видим пост-эффект на .15 с выступающим на границы компонента ховером.

Я пока не вижу более удобного способа как реализовать "ужатие" ховер-элемента под размеры "квадратика" кроме как добавлением простого свойства с пробросом класса. Но если вы подскажете, может я чего-то не вижу. Просто я привык обычно прокидывать классы через пропсы и попадаю в ловушку своего подхода)) Но про hoverMode я думал и делал так! - не сработало(( Поэтому я и пришел к текущему решению...

2021-09-17 06:23 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +      hoverShadowClassName="SimpleCheckbox__hoverShadow"
Наш подход сегодня — давать прокидывать классы на рутовый компонент и всё. Остальную реализацию разметки компонента мы стараемся скрыть, чтобы потом не страдать, когда захотим как-то её поменять. Твой класс на внутренний элемент этот принцип нарушает. Теперь все будут расчитывать на то, что hover shadow мы реализуем именно за счет html-элемента, на который можно накинуть свой класс при случае. То есть мы мало того что усложняем API, мы ещё и светим наружу реализацию компонента.

2021-09-17 06:23 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +      hoverShadowClassName="SimpleCheckbox__hoverShadow"
Вот такой разметки недостаточно?

```jsx
<label style={{ width: 20, height: 20, display: 'block' }}>
  <Tappable
    style={{
      width: 44,
      height: 44,
      position: "relative",
      left: -12,
      top: -12,
      borderRadius: '50%'
    }}
  >
    <Icon20CheckBoxOff />
  </Tappable>
</label>
```

2021-09-17 06:29 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +      hoverShadowClassName="SimpleCheckbox__hoverShadow"
Мы можем обновить `Tappable` так, чтобы `<span vkuiClass="Tappable__hoverShadow" />` рисовался не когда `hasHover === true`, а когда `hasHover === true && hoverMode === 'shadow'`. Потому что судя по css, ни при каком другом hoverMode этот блок не нужен. И ты уже реализуешь свой ховер так же, как сделал с active.

2021-09-17 07:14 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +      hoverShadowClassName="SimpleCheckbox__hoverShadow"
Создал PR в твою ветку с пропозалом #1903

2021-09-17 09:50 UTC, russll commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +      hoverShadowClassName="SimpleCheckbox__hoverShadow"
Замерджил, думаю теперь все вопросы мы решили) Я что-то упустил момент, что можно было просто добавить условие внутри Tappable а не добавлять новое свойство xD

2021-09-17 11:13 UTC, russll commented
@ArthurStam @eugpoloz ребята, кажется мы все обсудили, мей би катнем?)) Что там дальше по флоу надо делать у нас?

2021-09-17 11:18 UTC, ArthurStam requested changes
`<SimpleCheckbox defaultIndeterminate style={{ margin: '0 10px' }} checked={false} indeterminate={false}  />`

При таком вызове чекбокс будет пустым, а он должен быть в состоянии indeterminate из-за `defaultIndeterminate`

2021-09-17 11:28 UTC, ArthurStam requested changes

2021-09-17 11:28 UTC, ArthurStam commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +import { InputHTMLAttributes, FC, useEffect, useCallback } from 'react';
Мы недавно переехали на импорт React вида `import * as React from 'react'`
Переделай плз. Это нужно для elephize.

2021-09-17 14:40 UTC, russll commented on src/components/SimpleCheckbox/SimpleCheckbox.tsx
> +import { InputHTMLAttributes, FC, useEffect, useCallback } from 'react';
@ArthurStam  done!  👌

2021-09-17 17:29 UTC, ArthurStam approved these changes

2021-09-20 09:07 UTC, ArthurStam commented
Предлагаю мержить

2021-09-20 09:19 UTC, merged

2021-09-20 09:22 UTC, russll commented
@ArthurStam @eugpoloz засквошил и замерджил ✌️