fixed Cell in FormItem
VKCOM/VKUI pull request #1855
Opened 2021-09-01 14:05 UTC by ArthurStam

2021-09-01 14:06 UTC, ArthurStam commented on src/components/Cell/Cell.css
> -  width: 100%;
Тут нам ограничение на 100% не нужно.

2021-09-01 14:06 UTC, ArthurStam commented on src/components/Cell/Cell.css
> +.FormItem .Cell .SimpleCell {
Нужно будет распихать по другим .css файлам

2021-09-01 14:35 UTC, eugpoloz commented
@ArthurStam заберешь мастер, чтобы скриншоты `RichCell` пофиксились?

2021-09-02 09:26 UTC, eugpoloz requested changes
`Cell` `draggable` внутри `FormItem` уполз на iOS:

![image](https://user-images.githubusercontent.com/22026957/131819176-bb6aebc1-5881-4419-b8f8-ab2921aae9e8.png)

2021-11-12 09:47 UTC, eugpoloz commented
Починили в #2003.

2021-11-12 09:47 UTC, closed without merging