FLEX-4317: using new tokens design system for Button
VKCOM/VKUI pull request #1964
Opened 2021-10-11 10:50 UTC by gbowsky

## What is it?
- Слияние VKUI с новыми [токенами](https://github.com/VKCOM/vkui-tokens), на примере компонента Button.
## TODO
- [x] Проставить todo'шки там, где недостаёт определённых токенов;
- [x] Дополнить фоллбеки;
- [x] Починить тесты.
- [x] Вынести управление источником токенов из ConfigProvider (чтобы можно было ими управлять на уровне стайлгайда, в аппах будет работать иначе, но вполне аналогично простому подключению стилей);
- [x] Дождаться изменений со стороны ребят занимающимися новыми токенами, поскольку есть несоответствия из макетов.
- [ ] Написать док по использованию новых токенов с VKUI
## How can I try it?
- Открываем раздел кнопок в [styleguide](https://vkcom.github.io/VKUI/pull/1964/#/Button);
- Cмотрим на интерактивный пример с кнопками.

2021-11-09 15:33 UTC, ArthurStam reviewed
Нужен док про новые токены, чтобы люди понимали, как ими пользоваться. Учитывая, что для их подключения щас нужно немного поплясать

2021-11-09 15:33 UTC, ArthurStam commented on src/components/Button/Button.tsx
> +      hoverMode={!isFallback && 'Button--hover'}
Раньше `hoverMode` брался дефолтным из `Tappable`. Щас если `!isFallback === false` он не слетит?

2021-11-09 15:33 UTC, ArthurStam commented on src/components/File/File.tsx
> +  Omit<VKUIButtonProps, 'size' | 'type' | 'color'>,
Тут вроде `color` уже не нужен

2021-11-11 05:27 UTC, gbowsky commented on src/components/File/File.tsx
> +  Omit<VKUIButtonProps, 'size' | 'type' | 'color'>,
➕

2021-11-11 05:27 UTC, gbowsky commented on src/components/Button/Button.tsx
> +      hoverMode={!isFallback && 'Button--hover'}
➕, починил

2021-12-02 13:30 UTC, wayshev commented
Design Review: OK

2021-12-03 16:20 UTC, gbowsky commented on src/components/Button/Button.tsx
> +   Значения `commerce`, `destructive`, `overlay_...` будут упразднены в 5.x.x
Может за одно опишем больше пропов, чтобы раздел с кнопкой не был таким пустым?

2021-12-03 16:21 UTC, ArthurStam commented on src/components/Button/Button.tsx
> +   Значения `commerce`, `destructive`, `overlay_...` будут упразднены в 5.x.x
Опишем где?

2021-12-04 15:09 UTC, gbowsky commented on src/components/Button/Button.tsx
> +   Значения `commerce`, `destructive`, `overlay_...` будут упразднены в 5.x.x
Имел ввиду, что хотел описать пропсы кнопок, хоть они и весьма тривиальные.

2021-12-04 15:10 UTC, gbowsky commented on src/components/ConfigProvider/ConfigProviderContext.tsx
> +  tokensTheme?: string;
➕

2021-12-04 15:10 UTC, gbowsky commented on src/components/Button/Button.tsx
> +   Значения `commerce`, `destructive`, `overlay_...` будут упразднены в 5.x.x
➕

2021-12-06 09:13 UTC, ArthurStam requested changes
![image](https://user-images.githubusercontent.com/5061840/144819155-3b980e20-6e28-4a3f-99c3-44cd7eb49a1d.png)
Тут точно у каунтера всё ок?

2021-12-06 09:13 UTC, ArthurStam commented on src/components/Button/Button.tsx
> +  const isFallback: boolean = appearance === undefined;
Кажется, этот флаг уже не нужен

2021-12-06 11:41 UTC, gbowsky commented on src/components/Button/Button.tsx
> +  const isFallback: boolean = appearance === undefined;
➕

2021-12-06 11:41 UTC, gbowsky commented
> у каунтера всё ок?

не ок, поправил вхождения Counter в Button по макетам

2021-12-06 11:43 UTC, gbowsky commented
Также завёл кейс, когда в кнопке есть before и after, но отсутствует текст. Воспроизвёл его в примере без возможности оставить кнопку без контента.

2021-12-06 12:56 UTC, gbowsky commented
Ещё завёл кейсы с одной иконкой.

2021-12-06 13:29 UTC, ArthurStam reviewed
Мы не хотим дать возможность текст кнопки удалять/менять? Чтобы можно было в доке посмотреть, как выглядит кнопка, состоящая только из иконки

2021-12-06 13:31 UTC, ArthurStam approved these changes

2021-12-06 13:35 UTC, merged