feat(OwnerAvatar): create OwnerAvatar component
VKCOM/VKUI pull request #2044
Opened 2021-11-03 09:18 UTC by k-egor-smirnov

#2034

2021-11-03 09:20 UTC, gbowsky commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +   * Ограниченный сет размеров, так как под каждый выбирается определенный размер шрифты
шрифта

2021-11-03 09:28 UTC, gbowsky commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +OwnerAvatar.defaultProps = {
https://github.com/VKCOM/VKUI/issues/1586#issuecomment-865709818

2021-11-03 09:31 UTC, gbowsky commented on src/components/OwnerAvatar/Readme.md
> +          description="VKontakte"
тут корректнее просто VK)

2021-11-03 09:31 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +OwnerAvatar.defaultProps = {
Хотел так сделать, но спред чет не заводится в TS при наличии условных объектов (type text и type default) 🤔

2021-11-03 09:32 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/Readme.md
> +          description="VKontakte"
Скопоировал из Avatar ячейки) Поправлю тогда

2021-11-03 09:38 UTC, gbowsky commented on src/components/OwnerAvatar/Readme.md
> +Обертка для `<Avatar />`. Используется для показа информации об онлайне, либо рендеринге текстового аватара
Обёртка над `<Avatar />`, позволяющая отображать статус онлайна и рендерить текстовый аватар;

Кажется одно другому явно не мешает.

![image](https://user-images.githubusercontent.com/36237725/140037169-8bc97b8f-1631-423c-aac7-d87fee31797b.png)

2021-11-03 12:45 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +OwnerAvatar.defaultProps = {
Поправил и оставил тудушку, если у кого-нибудь руки дойдут

2021-11-03 12:45 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/Readme.md
> +          description="VKontakte"
+

2021-11-03 12:45 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/Readme.md
> +Обертка для `<Avatar />`. Используется для показа информации об онлайне, либо рендеринге текстового аватара
+

2021-11-03 13:14 UTC, gbowsky commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +  OwnerAvatar,
экспорт [должен быть](https://github.com/VKCOM/VKUI/blob/master/CONTRIBUTING.md#%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B5) в `src/index.ts`

2021-11-03 13:27 UTC, gbowsky commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +import React from 'react';
`import * as React from 'react';`

2021-11-03 14:00 UTC, gbowsky commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +export type OwnerAvatarProps = OwnerAvatarBaseProps & OwnerAvatarModeDefault & OwnerAvatarModeText;
давай расширим тип ещё на `Omit<AvatarProps, 'mode' | 'src' | 'size'>`, как никак передаём в Avatar `...restProps`

2021-11-03 14:02 UTC, gbowsky commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +const OwnerAvatar: React.FC<OwnerAvatarProps> = ({ mode, online, size, src, gradientColor, text, ...restProps }) => {
а здесь заменим конструкцию `... = ({ ...props }) => ...` на `... = (props: OwnerAvatarProps) => ...`

2021-11-03 14:02 UTC, fedorov-xyz commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +const OwnerAvatar: React.FC<OwnerAvatarProps> = ({ mode, online, size, src, gradientColor, text, ...restProps }) => {
Нельзя заменять, иначе стайлгайдист не пережуёт.

2021-11-03 14:06 UTC, gbowsky commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +const OwnerAvatar: React.FC<OwnerAvatarProps> = ({ mode, online, size, src, gradientColor, text, ...restProps }) => {
> Нельзя заменять, иначе стайлгайдист не пережуёт.

А, да. Не заметил что дефолтные значения уйдут.

2021-11-03 14:11 UTC, gbowsky commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +const OwnerAvatar: React.FC<OwnerAvatarProps> = ({ mode, online, size, src, gradientColor, text, ...restProps }) => {
Тогда так:
```
const OwnerAvatar: React.FC<OwnerAvatarProps> = ({
  mode = 'default',
  online = false,
  size = 48,
  src,
  gradientColor,
  text,
  ...restProps
}: OwnerAvatarProps) => { 
```

И в стайлгайде появятся все пропы с дефолтными значениями.

2021-11-03 14:21 UTC, gbowsky commented on src/components/OwnerAvatar/OwnerAvatar.css
> +  background-color: var(--owner-avatar-online-pane, var(--background_content));
А что за токен `--owner-avatar-online-pane`?

2021-11-07 23:39 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.css
> +  --owner-avatar-size-192-font-size: 69px;
Выпилил

2021-11-07 23:39 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.css
> +  background-color: var(--owner-avatar-online-pane, var(--background_content));
убрал

2021-11-07 23:39 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +const OwnerAvatar: React.FC<OwnerAvatarProps> = ({ mode, online, size, src, gradientColor, text, ...restProps }) => {
\+

2021-11-12 07:03 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +  OwnerAvatar,
добавил

2021-11-15 15:58 UTC, eugpoloz requested changes

2021-11-15 15:58 UTC, eugpoloz commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +    status = <div vkuiClass="OwnerAvatar__status">{online}</div>;
Получается, мы позволяем свою кастомную иконку сюда прокидывать, правильно?

2021-11-15 15:58 UTC, eugpoloz commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +type OwnerAvatarBaseProps = {
Заметила, что styleguidist почему-то не подтягивает описания пропсов ниже, а хотелось бы, чтобы он подтягивал. Попробуешь починить?

2021-11-15 15:58 UTC, eugpoloz commented on src/components/OwnerAvatar/OwnerAvatar.css
> +.OwnerAvatar {
Можно удалить, мы выше уже задали `position: relative` для `.OwnerAvatar`. 😉

2021-11-15 15:58 UTC, eugpoloz commented on src/components/OwnerAvatar/OwnerAvatar.css
> +  float: left;
Хотелось бы обойтись тут без флоата: он слишком непредсказуемый и по-хорошему после него нужно делать clear, чтобы у нас внезапно не сломалась верстка в неожиданных местах.

Я немного поэкспериментировала, вот так вроде выходит все то же самое плюс можно избавиться от классов вида `.OwnerAvatar__gridAvatar--2`:

```css
.OwnerAvatar__grid {
  display: flex;
  flex-flow: column wrap;
  height: 100%;
  width: 100%;
  overflow: hidden;
  border-radius: inherit;
}

.OwnerAvatar__gridAvatar {
  width: calc(50% - var(--owner-avatar-image-offset) / 2);
  height: 100%;
  background-size: cover;
  background-position: center;
  background-color: var(--placeholder_icon_background);
}

.OwnerAvatar--images-1 .OwnerAvatar__gridAvatar {
  width: 100%;
}

.OwnerAvatar--images-3 .OwnerAvatar__gridAvatar:nth-child(1n + 2),
.OwnerAvatar--images-4 .OwnerAvatar__gridAvatar {
  height: calc(50% - var(--owner-avatar-image-offset) / 2);
}

.OwnerAvatar--images-2 .OwnerAvatar__gridAvatar:nth-child(1n + 2),
.OwnerAvatar--images-3 .OwnerAvatar__gridAvatar:nth-child(1n + 2),
.OwnerAvatar--images-4 .OwnerAvatar__gridAvatar:nth-child(1n + 3) {
  margin-left: var(--owner-avatar-image-offset);
}

.OwnerAvatar--images-3 .OwnerAvatar__gridAvatar:nth-child(2),
.OwnerAvatar--images-4 .OwnerAvatar__gridAvatar:nth-child(odd) {
  margin-bottom: var(--owner-avatar-image-offset);
}
```

2021-11-15 15:58 UTC, eugpoloz commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +  let status: React.ReactElement | null = null;
Момент про доступность.

В норме мы прячем `Avatar` от ассистивных технологий, потому что особой смысловой нагрузки для пользователя скринридера он не несет, но тут мы добавляем индикатор онлайна. Это уже нужно как-то озвучить.

Я вижу решение так:
- мы докидываем блоку `role="status"`,
- добавляем проп `onlineLabel?: string` и докидываем блоку еще и `aria-label={onlineLabel}`. Дефолт может быть `"Онлайн"`, например.

А чтобы это не повторять по три раза, я бы предложила вот эту всю логику перенести вниз:

```tsx
      {hasReactNode(online) && // import { hasReactNode } from '../../lib/utils';
        <div
          vkuiClass={classNames('OwnerAvatar__status',
            {
              'OwnerAvatar__status--mobile': online === 'mobile',
              'OwnerAvatar__status--common': online === true,
            },
          )}
          role="status"
          aria-label={onlineLabel}
        >
          {online === 'mobile' && <Icon16OnlineMobile />}
          {React.isValidElement(online) && online}
        </div>
      }
```

2021-11-15 16:01 UTC, ArthurStam commented on src/components/OwnerAvatar/OwnerAvatar.css
> +  float: left;
Тут стоит конкретизировать, что именно смущает во флоатах. Он нормально работает в ряде случаев.

2021-11-15 16:02 UTC, ArthurStam commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +  let status: React.ReactElement | null = null;
Онлайн мы договорились убрать пока, пушто там может быть не только онлайн. Подождем дизайнеров.

2021-11-16 05:39 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +    status = <div vkuiClass="OwnerAvatar__status">{online}</div>;
Правильно, но, договорились выпилить, пока не будет готов дизайн к этому

2021-11-16 13:14 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.css
> +.OwnerAvatar--mode-text .OwnerAvatar__text {
Перенес в компонент InitialsAvatar

2021-11-16 13:16 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +        mode === 'text' && `OwnerAvatar--gradient-${gradientColor}`,
В новых компонентах не актуальны условия для классов

2021-11-16 13:17 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +  gradientColor: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;
Сделал и так, как ты сказала, и оставил прошлый сет, но ограничил его с 1 по 6, как в формуле нахождения градиента пользователя по id (в стайлгайде и в jsdoc про это написал)

2021-11-16 13:17 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +  text: string;
В InitialsAvatar теперь используется children

2021-11-16 13:18 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +import { isArray } from '@vkontakte/vkjs';
Больше не актуально

2021-11-16 13:18 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +    content = <div vkuiClass="OwnerAvatar__text">{text}</div>;
Сделал

2021-11-16 13:18 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +  } else if (isArray(src)) {
Разделили на два компонента, теперь моды не нужны

2021-11-16 13:18 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +type OwnerAvatarBaseProps = {
Починил

2021-11-16 13:18 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.css
> +.OwnerAvatar {
убрал

2021-11-16 13:18 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.css
> +  float: left;
Переделал на твое решение, спасибо!

2021-11-16 13:18 UTC, k-egor-smirnov commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +  let status: React.ReactElement | null = null;
Да, онлайн выпилил

2021-11-16 13:57 UTC, eugpoloz commented on src/components/GridAvatar/GridAvatar.tsx
> +    warn(`src length (${src.length}) is larger than maxiumum (${MAX_GRID_LENGTH})`);
Перепишешь на русский? Мы договорились, что т.к. дока у нас на русском, то и ворнинги тоже будут на нем.

2021-11-16 13:57 UTC, eugpoloz commented on src/components/InitialsAvatar/InitialsAvatar.css
> +.InitialsAvatar--size-30 {
Можно объединить с `.InitialsAvatar--size-32`, раз размер шрифта для них одинаковый.

2021-11-16 13:57 UTC, eugpoloz commented on src/components/InitialsAvatar/InitialsAvatar.css
> +.InitialsAvatar--size-44 {
И тут можно объединить с `.InitialsAvatar--size-46`.

2021-11-16 13:57 UTC, eugpoloz commented on src/components/InitialsAvatar/InitialsAvatar.tsx
> + * @example user.id % 6 + 1
Блин, это бомба. 👍🏻 💥

2021-11-16 13:57 UTC, eugpoloz commented on src/components/InitialsAvatar/InitialsAvatar.tsx
> +  gradientColor = 'gray',
Если дефолтный цвет у нас 'gray', может, избавимся для модификатора в стилях от него и просто пропишем `background` для `InitialsAvatar`?

2021-11-16 13:57 UTC, eugpoloz commented on src/components/InitialsAvatar/Readme.md
> +Компонент для отображения текстовых аватаров на фоне градиента (например, когда у пользователя нет установленного изображения). Для лучшего отображения, рекомендуется использовать длину текста <b>не
Кажется, вместо `<br />` должна сработать пустая строка между 1 и 2 абзацем.

2021-11-16 13:57 UTC, eugpoloz commented on src/components/InitialsAvatar/InitialsAvatar.css
> +  text-align: center;
Не стоит ли тут на всякий случай перестраховаться и добавить `text-overflow`? Чтоб 100% не развалилось, если кто-то сильно больше двух символов захочет подставить.

2021-11-16 13:59 UTC, eugpoloz commented on src/components/OwnerAvatar/OwnerAvatar.tsx
> +  gradientColor: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;
Очень круто теперь, спасибо!

2021-11-16 14:01 UTC, ArthurStam commented on src/lib/utils.ts
> +export const omit = <T extends object, K extends keyof T>(obj: T, ...keys: K[]): Omit<T, K> => {
просится юнит-тест

2021-11-16 14:03 UTC, k-egor-smirnov commented on src/components/InitialsAvatar/Readme.md
> +Компонент для отображения текстовых аватаров на фоне градиента (например, когда у пользователя нет установленного изображения). Для лучшего отображения, рекомендуется использовать длину текста <b>не
Не срабатывала у меня

2021-11-16 14:35 UTC, k-egor-smirnov commented on src/lib/utils.ts
> +export const omit = <T extends object, K extends keyof T>(obj: T, ...keys: K[]): Omit<T, K> => {
добавил простенький тест, хз что добавить еще туда

2021-11-16 14:36 UTC, k-egor-smirnov commented on src/components/InitialsAvatar/InitialsAvatar.test.tsx
> +  it('don\'t show image even if src was passed', () => {
готово

2021-11-16 14:36 UTC, k-egor-smirnov commented on src/components/GridAvatar/GridAvatar.tsx
> +  if (src.length > MAX_GRID_LENGTH) {
\+

2021-11-16 14:36 UTC, k-egor-smirnov commented on src/components/InitialsAvatar/InitialsAvatar.css
> +  text-align: center;
добавил `overflow: hidden;`

2021-11-16 14:36 UTC, k-egor-smirnov commented on src/components/InitialsAvatar/InitialsAvatar.tsx
> +  gradientColor = 'gray',
ё+

2021-11-16 14:36 UTC, k-egor-smirnov commented on src/components/InitialsAvatar/InitialsAvatar.css
> +.InitialsAvatar--size-44 {
\+

2021-11-16 14:36 UTC, k-egor-smirnov commented on src/components/InitialsAvatar/InitialsAvatar.css
> +.InitialsAvatar--size-30 {
\+

2021-11-16 14:36 UTC, k-egor-smirnov commented on src/components/GridAvatar/GridAvatar.tsx
> +    warn(`src length (${src.length}) is larger than maxiumum (${MAX_GRID_LENGTH})`);
переписал

2021-11-16 14:38 UTC, eolme commented on src/components/GridAvatar/GridAvatar.tsx
> +  restProps = omit(restProps, ...FORBIDDEN_AVATAR_PROPS_ARRAY as any);
Почему бы просто ключи не извлечь перед restProps?

2021-11-16 14:40 UTC, eolme commented on src/components/GridAvatar/GridAvatar.tsx
> +  restProps = omit(restProps, ...FORBIDDEN_AVATAR_PROPS_ARRAY as any);
Да и к тому же src там уже нет

2021-11-16 14:41 UTC, k-egor-smirnov commented on src/components/GridAvatar/GridAvatar.tsx
> +  restProps = omit(restProps, ...FORBIDDEN_AVATAR_PROPS_ARRAY as any);
а в каком именно месте?

2021-11-16 14:44 UTC, eolme commented on src/components/InitialsAvatar/InitialsAvatar.css
> +.InitialsAvatar--size-16 {
А мы не можем считать эти штуки динамически, скажем по формуле какой-нибудь определенной

2021-11-16 15:04 UTC, k-egor-smirnov commented on src/components/GridAvatar/GridAvatar.tsx
> +  restProps = omit(restProps, ...FORBIDDEN_AVATAR_PROPS_ARRAY as any);
В целом, логично, но тогда они не будут использованы

2021-11-16 15:14 UTC, k-egor-smirnov commented on src/components/GridAvatar/GridAvatar.tsx
> +  restProps = omit(restProps, ...FORBIDDEN_AVATAR_PROPS_ARRAY as any);
Не, не подходит, в типах компонента уже убраны эти пропы, придется прописывать @ts-ignore

2021-11-16 15:15 UTC, k-egor-smirnov commented on src/components/InitialsAvatar/InitialsAvatar.css
> +.InitialsAvatar--size-16 {
Отличная идея, обсудили и сделали в итоге по формуле

2021-11-16 15:31 UTC, k-egor-smirnov commented on src/lib/utils.ts
> +export const omit = <T extends object, K extends keyof T>(obj: T, ...keys: K[]): Omit<T, K> => {
Спредом можно выпилить определенные ключи, но нельзя выпилить все ключи из определенного массива

2021-11-16 17:10 UTC, eolme commented on src/components/GridAvatar/GridAvatar.tsx
> +  restProps = omit(restProps, ...FORBIDDEN_AVATAR_PROPS_ARRAY as any);
Есть детектива @ts-expect-error для таких случаев

2021-11-16 17:11 UTC, eolme commented on src/lib/utils.ts
> +export const omit = <T extends object, K extends keyof T>(obj: T, ...keys: K[]): Omit<T, K> => {
Но фактически это одно и тоже

2021-11-16 17:23 UTC, eolme commented on src/components/GridAvatar/GridAvatar.tsx
> +  restProps = omit(restProps, ...FORBIDDEN_AVATAR_PROPS_ARRAY as any);
Во всяком случае, дополнительный комментарий меньше зло, по сравнению с дополнительной работой в рантайме

2021-11-17 04:21 UTC, k-egor-smirnov commented on src/lib/utils.ts
> +export const omit = <T extends object, K extends keyof T>(obj: T, ...keys: K[]): Omit<T, K> => {
Ты предлагаешь внутри функции omit сделать спред внутри map на каждый ключ? Это еще медленнее. Я уже добавил в omit копирование объекта перед удалением ключа, этого должно хватить, думаю

2021-11-17 04:36 UTC, eolme commented on src/lib/utils.ts
> +export const omit = <T extends object, K extends keyof T>(obj: T, ...keys: K[]): Omit<T, K> => {
Нет, я про
> все ключи из массива

2021-11-17 09:04 UTC, ArthurStam submitted a review, later dismissed

2021-11-17 09:08 UTC, eolme commented
Так подождите, давайте по omit добьем

2021-11-17 09:14 UTC, k-egor-smirnov commented on src/lib/utils.ts
> +export const omit = <T extends object, K extends keyof T>(obj: T, ...keys: K[]): Omit<T, K> => {
Сори, я все еще не понимаю, как сделать красиво и без дополнительной функции. И чтобы при этом не пришлось делать три строчки, в каждой выпиливая по одному ключу, это не вариант

2021-11-17 09:21 UTC, ArthurStam commented on src/lib/utils.ts
> +export const omit = <T extends object, K extends keyof T>(obj: T, ...keys: K[]): Omit<T, K> => {
> Лучше колонировать объект без ключей, чем удалять в исходном, для рефа:
> 
> https://github.com/babel/babel/blob/87fc2e76d77b0bc78b76cced469bd64c5edf141f/packages/babel-helpers/src/helpers.ts#L554
> 
> Вообще, в месте где это используется, можно обойтись без дополнительных функций, просто спредя ключи из исходного

Чем предложенный вариант лучше?

2021-11-17 10:04 UTC, k-egor-smirnov commented on src/components/GridAvatar/GridAvatar.tsx
> +  restProps = omit(restProps, ...FORBIDDEN_AVATAR_PROPS_ARRAY as any);
Пришли в итоге к тому, что omit не будет, ограничиваем пропы только на уровне типизации на данный момент

2021-11-17 10:04 UTC, k-egor-smirnov commented on src/components/GridAvatar/GridAvatar.tsx
> +  restProps = omit(restProps, ...FORBIDDEN_AVATAR_PROPS_ARRAY as any);
https://github.com/VKCOM/VKUI/pull/2044#discussion_r751083863

2021-11-17 10:10 UTC, ArthurStam approved these changes

2021-11-17 10:11 UTC, ArthurStam approved these changes

2021-11-17 10:15 UTC, merged