fix(progress): check value range
VKCOM/VKUI pull request #2103
Opened 2021-11-21 10:33 UTC by MrZillaGold

![image](https://user-images.githubusercontent.com/42776347/142758414-c1e10ff0-aee9-4295-a4a6-58585471831e.png)

2021-11-21 14:05 UTC, fedorov-xyz requested changes

2021-11-21 14:05 UTC, fedorov-xyz commented on src/components/Progress/Progress.tsx
> +  const progress = value > PROGRESS_MIN_VALUE ?
```tsx
Math.max(0, Math.min(value, 100))
```

2021-11-22 09:10 UTC, ArthurStam approved these changes

2021-11-22 09:11 UTC, ArthurStam commented
Спасибо!

2021-11-22 09:12 UTC, fedorov-xyz approved these changes

2021-11-22 09:12 UTC, merged