[Docs] Все пропсы компонента
VKCOM/VKUI pull request #2119
Opened 2021-11-29 18:12 UTC by eugpoloz

2021-11-30 10:34 UTC, ArthurStam commented
А точно ли больше не нужен ComplexType? Может оставим его на случай, если стайлгайдист решит им воспользоваться?

2021-11-30 10:55 UTC, ArthurStam requested changes
В [ModalRoot](https://vkcom.github.io/VKUI/pull/2119/#/ModalRoot) клик по раскрытию просто скрывает кнопку. Looks like a bug. В остальном, помимо пары комментов — awesome feature!

2021-11-30 10:55 UTC, ArthurStam commented on styleguide/Components/Name/Name.css
> +  color: #818c99;
Может токен подберем, чтобы в разных темах смотрелся нормально?

2021-11-30 10:55 UTC, ArthurStam commented on styleguide/Components/Name/NameRenderer.js
> +        'Name--optional': !deprecated && !required,
А как будут выглядеть опшнал депрекейтед свойства? Такие ведь есть

2021-11-30 10:55 UTC, ArthurStam commented on styleguide/Components/Table/TableRenderer.js
> +          {!expanded && (
Может сделаем такую же кнопку, но для скрытия свойств? Причем я бы её рисовал между vkui-свойствами и свойствами из нод модулей, чтобы не приходилось скроллить вниз.

2021-11-30 10:56 UTC, fedorov-xyz commented on styleguide/Components/ReactComponent/ReactComponent.js
> +      nodeModulesProps.push(prop);
Немного странно выглядит фильтр, который заполняет другой массив. Мб здесь был бы лучше forEach, который заполнит 2 массива?

2021-11-30 10:58 UTC, ArthurStam commented on styleguide/Components/ReactComponent/ReactComponent.js
> +      nodeModulesProps.push(prop);
По факту работать будет одинаково) если только внутри этих методов нет каких-то ниндзя-оптимизаций

2021-11-30 10:58 UTC, fedorov-xyz commented on styleguide/Components/ReactComponent/ReactComponent.js
> +      nodeModulesProps.push(prop);
Да, понимаю, что одинаково.

2021-11-30 11:09 UTC, eugpoloz commented on styleguide/Components/Name/NameRenderer.js
> +        'Name--optional': !deprecated && !required,
В optional deprecated смысла нет, по тому, что они deprecated, и так понятно, что они не обязательные. Было бы странно что-то депрекейтить и при этом требовать это указывать. 😃 

Но можем облегчить условие, пусть вопросик рисуется вне зависимости от депрекейта, если тебе кажется, что так нагляднее/понятнее.

2021-11-30 11:10 UTC, eugpoloz commented on styleguide/Components/Table/TableRenderer.js
> +          {!expanded && (
Йеп, я над этим тоже думала! Сделаю. ❤️

2021-11-30 12:34 UTC, ArthurStam commented on styleguide/Components/Name/NameRenderer.js
> +        'Name--optional': !deprecated && !required,
Я думаю, что мы можем поменять компонент так, что обязательный проп станет устаревшим.

2021-11-30 14:06 UTC, eugpoloz commented on styleguide/Components/ReactComponent/ReactComponent.js
> +      nodeModulesProps.push(prop);
@fedorov-xyz работать-то будет так же, но если не очень понятно и путает при этом, то я лучше переделаю на `forEach`. Спасибо, что сказал. ❤️

2021-11-30 14:53 UTC, thoughtspile commented
возможно все-все-все пропы это немного перебор

<img width="648" alt="Снимок экрана 2021-11-30 в 17 52 36" src="https://user-images.githubusercontent.com/5262915/144070112-e94f5402-016d-43d4-890a-74eaeefe5a58.png">

2021-11-30 14:54 UTC, ArthurStam commented
> возможно все-все-все пропы это немного перебор
> 
> <img alt="Снимок экрана 2021-11-30 в 17 52 36" width="648" src="https://user-images.githubusercontent.com/5262915/144070112-e94f5402-016d-43d4-890a-74eaeefe5a58.png">

Непонятно, как отделить полезные свойства от остальных

2021-11-30 14:58 UTC, eugpoloz commented
@thoughtspile 

> возможно все-все-все пропы это немного перебор, получается MDN

Не скажу, что вижу в этом проблему. Зато так можно поиском по странице быстро чекнуть, есть ли нужный проп, и успокоиться, а не ходить в чатик или в issues гитхаба с вопросом, принимает ли этот компонент `className` или `aria-label`.

2021-11-30 15:06 UTC, ArthurStam requested changes

2021-11-30 15:06 UTC, ArthurStam commented on styleguide/config.js
> + * react-docgen-typescript performance workaround
Ещё я б унёс этот воркараунд в отдельный файл и экспортил бы propsParser, чтобы файл конфига не раздувался

2021-11-30 16:38 UTC, eugpoloz commented on styleguide/config.js
> + * react-docgen-typescript performance workaround
➕

2021-11-30 16:38 UTC, eugpoloz commented on styleguide/Components/ReactComponent/ReactComponent.js
> +      nodeModulesProps.push(prop);
➕

2021-11-30 16:38 UTC, eugpoloz commented on styleguide/Components/Table/TableRenderer.js
> +          {!expanded && (
➕

2021-11-30 16:38 UTC, eugpoloz commented on styleguide/Components/Name/NameRenderer.js
> +        'Name--optional': !deprecated && !required,
➕

2021-11-30 16:38 UTC, eugpoloz commented on styleguide/Components/Name/Name.css
> +  color: #818c99;
➕

2021-12-01 10:58 UTC, ArthurStam requested changes
![image](https://user-images.githubusercontent.com/5061840/144222422-e4d196f1-77f7-4ab2-ba57-1815b5a302e9.png)
кажется, лишний радиус появился

2021-12-01 13:10 UTC, eugpoloz commented
@ArthurStam и правда, прибрала его!

2021-12-01 13:21 UTC, ArthurStam commented on styleguide/config.js
> +    'ComplexType/ComplexTypeRenderer': path.join(__dirname, './Components/ComplexType/ComplexTypeRenderer'),
почему-то тут подсвечивается дифф, хотя вроде ничего не поменялось. Русская "с" закралась?

2021-12-01 13:21 UTC, ArthurStam approved these changes

2021-12-01 13:34 UTC, merged