Infra/upgrade postcss
VKCOM/VKUI pull request #2127
Opened 2021-12-02 15:31 UTC by thoughtspile

В мастере после установки начисто не собирается:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/vklepov/Documents/vkui/node_modules/postcss/package.json
```

- Обновил `postcss` и `css-loader` до версии с `package.json` в `exports`
- Заодно заменил `postcss-prefixer` который не очень поддерживает `postcss@8` на `postcss-modules`

2021-12-02 15:34 UTC, ArthurStam requested changes
Кайф, спасибо. Может в этом MR и от ворнинга про устаревший плагин разберемся?

2021-12-02 15:37 UTC, thoughtspile commented
> Кайф, спасибо. Может в этом MR и от ворнинга про устаревший плагин разберемся?

Мне кажется ворнинг как раз от префиксера был, сейчас его не вижу

2021-12-02 15:38 UTC, thoughtspile commented
ах, е2е упали

2021-12-03 14:42 UTC, stoope commented
@thoughtspile Привет! Спасибо за PR) e2e тесты все еще падают `11 snapshots failed from 11 test suites.`, можешь плз посмотреть?

2021-12-04 12:10 UTC, thoughtspile commented
> @thoughtspile Привет! Спасибо за PR) e2e тесты все еще падают

Знаю, просто немного занят

2021-12-04 13:18 UTC, thoughtspile commented
Все, вроде можно лить

2021-12-06 08:49 UTC, ArthurStam approved these changes

2021-12-06 08:50 UTC, merged