Add popper integration to components
VKCOM/VKUI pull request #2132
Opened 2021-12-07 15:22 UTC by stoope

2021-12-07 16:17 UTC, eolme commented
В документации при ресайзе окна, разваливаются выпадашки

<img src="https://user-images.githubusercontent.com/11076888/145066008-44002a42-4518-47bf-8abe-980a6264463b.png" width="600" />

2021-12-08 09:12 UTC, stoope commented
@eolme спасибо что нашел, выглядит как баг реализации документации а не компонента. При ресайзе ActionSheet такого не наблюдается

2021-12-08 11:31 UTC, eolme commented
@stoope они разваливаются только в этом PR, если что

2021-12-09 11:56 UTC, ArthurStam commented on src/components/ActionSheet/ActionSheetDropdownDesktop.tsx
> -      if (process.env.NODE_ENV === "development") {
ваще довольно полезный ворнинг, чтобы потом понять, что у пользователя произошло

2021-12-09 15:12 UTC, stoope commented on src/components/ActionSheet/ActionSheetDropdownDesktop.tsx
> -      if (process.env.NODE_ENV === "development") {
Вернул

2021-12-09 16:01 UTC, eolme commented on src/hooks/useEffectDev.ts
> +export const useEffectDev: typeof useEffect = (effect, deps) => {
Так не выкинится, лучше типо:
```js
export const useEffectDev = proccess.env.NODE_ENV === 'development' ? fn : noop;
```

2021-12-09 16:24 UTC, eolme commented on src/hooks/useEffectDev.ts
> +export const useEffectDev: typeof useEffect = (effect, deps) => {
Ну, по крайней мере не трогает жизненный цикл компонента

2021-12-10 11:33 UTC, ArthurStam requested changes

2021-12-10 11:33 UTC, ArthurStam commented on src/components/CustomSelect/Readme.md
> +        <Panel id="profile">
Добавь плз `PanelHeader`, а то просвечивает шапка из `SplitLayout`

2021-12-10 11:37 UTC, stoope commented on src/components/Popper/Popper.css
> +  z-index: 100;
Ага, вынуждено так как у `PopoutRoot` задано `z-index: 100;`

2021-12-10 11:52 UTC, stoope commented on src/components/CustomSelect/Readme.md
> +        <Panel id="profile">
Добавил

2021-12-10 11:53 UTC, ArthurStam commented on src/components/Popper/Popper.css
> +  z-index: 100;
Даже учитывая, что мы рендерим `ActionSheet` в `PopoutRoot`?

2021-12-10 12:05 UTC, stoope commented on src/components/Popper/Popper.css
> +  z-index: 100;
Именно в `ActionSheet` мы портал не рендерим, поэтому этот клас не применяется, а в случае селектов он нужен

2021-12-13 12:33 UTC, ArthurStam reviewed
Поигрался в codesandbox и там CustomSelect плохо
https://codesandbox.io/s/vkui-default-example-forked-mtn66
![image](https://user-images.githubusercontent.com/5061840/145813056-2d11e4be-8648-4485-968b-bd4e74e6740d.png)

2021-12-13 17:22 UTC, ArthurStam approved these changes

2021-12-13 17:23 UTC, merged