Avatar overlay
VKCOM/VKUI pull request #2145
Opened 2021-12-10 12:37 UTC by stoope

2021-12-10 16:21 UTC, ArthurStam commented on src/components/Avatar/Avatar.css
> +.Avatar.Avatar--overlay {
Растим специфичность?)

2021-12-10 16:21 UTC, ArthurStam commented on src/components/Avatar/Avatar.css
> +.Avatar--overlay:hover .Avatar__overlay_icon,
overlay-icon

2021-12-10 16:21 UTC, ArthurStam commented on src/components/Avatar/Avatar.tsx
> +  overlayColor?: "black" | "white";
Может лучше `overlayMode?: "dark" | "light"`? Чтобы к названиям конкретных цветов не было привязки

2021-12-10 16:21 UTC, ArthurStam commented on src/components/Avatar/Avatar.tsx
> +  overlayAction: hasMouse ? "hover" : "always",
Правильнее будет читать `hasMouse` из `useAdaptivity`

2021-12-13 08:40 UTC, stoope commented on src/components/Avatar/Avatar.css
> +.Avatar.Avatar--overlay {
Не заметил, тут не нужна специфичность)

2021-12-13 08:40 UTC, stoope commented on src/components/Avatar/Avatar.css
> +.Avatar--overlay:hover .Avatar__overlay_icon,
done

2021-12-13 08:42 UTC, stoope commented on src/components/Avatar/Avatar.tsx
> +  overlayColor?: "black" | "white";
done

2021-12-13 08:55 UTC, stoope commented on src/components/Avatar/Avatar.tsx
> +  overlayAction: hasMouse ? "hover" : "always",
done

2021-12-13 12:13 UTC, ArthurStam commented on src/components/Avatar/Avatar.css
> +.Avatar--overlay--always .Avatar__overlay-icon {
многословные имена элементов и модификаторов разделяются одним дефисом, то есть должно быть `.Avatar--overlay-always`

2021-12-13 12:17 UTC, ArthurStam commented on src/components/Avatar/Avatar.css
> +.Avatar--overlay--always .Avatar__overlay-icon {
многословные имена элементов и модификаторов разделяются одним дефисом, то есть должно быть `.Avatar--overlay-always`

2021-12-13 12:17 UTC, ArthurStam commented on src/components/Avatar/Avatar.tsx
> +  overlayColor?: "black" | "white";
решил оставить `overlayColor`?

2021-12-13 12:18 UTC, ArthurStam requested changes
![image](https://user-images.githubusercontent.com/5061840/145810891-34e9ab12-1e23-4492-a440-3f0175d70230.png)
Кажется, shadow и белый overlay не оч смотрятся

2021-12-13 14:37 UTC, stoope commented on src/components/Avatar/Avatar.css
> +.Avatar--overlay--always .Avatar__overlay-icon {
done

2021-12-14 15:01 UTC, ArthurStam commented on src/components/Avatar/Avatar.tsx
> +          onClick={restProps.onClick}
Обработчик события вешается и на Tappable, и на корневой элемент. В итоге он будет дважды вызван.

2021-12-14 17:05 UTC, stoope commented on src/components/Avatar/Avatar.tsx
> +          onClick={restProps.onClick}
done

2021-12-14 17:05 UTC, stoope commented on src/components/Avatar/Avatar.css
> +.Avatar_overlay {
done

2021-12-15 13:18 UTC, ArthurStam approved these changes

2021-12-15 13:20 UTC, merged