[WIP,Feature] SegmentedControl
VKCOM/VKUI pull request #2159
Opened 2021-12-15 12:01 UTC by eugpoloz

Fixes #2055.

- [ ] скриншотные тесты

2022-01-27 15:45 UTC, ArthurStam approved these changes

2022-01-28 14:31 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControl.test.tsx
> +  });
У кнопок в некоторых браузерах есть такой прикол, да (если не проставить им type="button", они могут автоматически быть признанными type="submit" и вести себя соответствующе). Я копировала все co SliderSwitch, так что и этот тест перекочевал. Но раз у нас теперь не кнопки, то надо выпилить, спасибо, что напомнил!

2022-01-28 16:07 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  >(restProps.defaultValue ?? options[0].value);
➕

2022-01-28 16:08 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControl.test.tsx
> +  });
➕ 

Убрала и покрыла нормальными тестами.

2022-01-28 16:08 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  }, [activeValue]);
➕

2022-01-28 16:08 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  options = [defaultOption],
➕

2022-01-28 16:10 UTC, eugpoloz commented
Вернула в драфт, пока ждем дизайн компонента на vkui-tokens.

2022-01-28 16:19 UTC, stoope commented on src/components/SegmentedControl/SegmentedControl.tsx
> +        {options?.map(({ value, label, ...optionProps }, idx) => (
`options` определен в интерфейсе как обязательный, можно без `?.`

2022-01-28 16:19 UTC, stoope commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  value: propsValue,
Есть какой то смысл переименовывать в `propsValue`?) Что бы не было shadow переменных?

2022-01-28 16:19 UTC, stoope commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  if (!propsValue && options?.[0]?.value) {
Можно просто `const initialValue = propsValue ?? options[0]?.value`

2022-01-28 16:21 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControl.tsx
> +        {options?.map(({ value, label, ...optionProps }, idx) => (
У меня почему-то без `?.` в тестах `SegmentedControl` отказался заводиться (валился с ошибкой, что options undefined), если подскажешь, что там могло пойти не так — буду признательна.

2022-01-28 16:24 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  value: propsValue,
Чтобы не попутать с value в options.map. А хотя щас переделаю!

2022-01-28 16:31 UTC, stoope commented on src/components/SegmentedControl/SegmentedControl.tsx
> +        {options?.map(({ value, label, ...optionProps }, idx) => (
Нужно заменить `baselineComponent((props) => <SegmentedControl options={[]} name="" {...props} />);`
`baselineComponent` не дружит с `ts`, нужно как нибудь им заняться)

2022-01-28 16:34 UTC, stoope commented on src/components/SegmentedControl/SegmentedControl.tsx
> +        {options?.map(({ value, label, ...optionProps }, idx) => (
Лучший лишний раз не писать `?.` так как бабель транспилит их в довольно длинное выражение, добавляется вес бандлу. Поэтому лучше убирать там где можно)

2022-01-28 16:35 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControl.tsx
> +        {options?.map(({ value, label, ...optionProps }, idx) => (
Аааа, вот оно что! Сейчас попробую. Спасибо! 🙏

2022-01-28 16:36 UTC, stoope commented on src/components/SegmentedControl/SegmentedControl.tsx
> +        {options?.map(({ value, label, ...optionProps }, idx) => (
<img width="1603" alt="Screenshot 2022-01-28 at 19 36 14" src="https://user-images.githubusercontent.com/17287557/151585841-5d0f32e8-5022-4472-b66d-d3125dd049e9.png">

2022-01-31 16:03 UTC, ArthurStam requested changes

2022-01-31 16:03 UTC, ArthurStam commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  name,
Не нравится, что мы вынуждаем юзеров указывать обязательно это поле, хотя как минимум в ряде случаев оно им не нужно. Понимаю, что такое решение диктуется стандартом радио кнопок. Нужно что-то придумать.

2022-01-31 16:03 UTC, ArthurStam commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  name,
То есть это удобно, когда компонент является частью формы. Но когда это просто переключатель табов, этот `name` выглядит избыточным.

2022-02-03 11:15 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx
> +      <FocusVisible mode="inside" />
Не скажется ли это на производительности? Тогглить класс как будто дешевле, чем рисовать-скрывать FocusVisible каждый раз.

2022-02-03 14:30 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.css
> +  -webkit-appearance: none;
➕

2022-02-03 14:30 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.css
> +.SegmentedControlOption {
➕

2022-02-03 14:30 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControl.tsx
> +      <div role="radiogroup" vkuiClass={classNames("SegmentedControl__in")}>
➕

2022-02-03 15:23 UTC, ArthurStam commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx
> +      <FocusVisible mode="inside" />
Я и предлагаю тоглить класс. Пусть у FocusVisible будет проп. Внутри FocusVisible в зависимости от этого пропа будет или не будет класса. И уже через него рулится, показывать или скрывать обводку.

2022-02-03 15:28 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx
> +      <FocusVisible mode="inside" />
Звучит как отдельная задача.

2022-02-08 09:05 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  name,
➕ 
Сделали name опциональным и генерим его, если он не передан.

2022-02-08 09:10 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx
> +      <FocusVisible mode="inside" />
Сделала задачку #2238
➕

2022-02-08 11:51 UTC, ArthurStam reviewed
Есть ли возможность прокинуть defaultValue?

2022-02-08 11:51 UTC, ArthurStam commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.css
> +  -webkit-tap-highlight-color: transparent;
У нас вроде он везде сделан прозрачным

2022-02-08 11:51 UTC, ArthurStam commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.css
> +.SegmentedControlOption__self {
не достаточно просто этих трех?
position: absolute;
visibility: hidden;
pointer-events: none;

2022-02-08 20:34 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.css
> +.SegmentedControlOption__self {
Все еще нет: нам нужно скрыть инпут, но оставить его доступным скринридерам. `visibility: hidden;` выкидывает компонент из древа доступности. `pointer-events: none;` опасен для экранов с тачем (там же по "клику" контролы активируются.

2022-02-08 20:58 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.css
> +  -webkit-tap-highlight-color: transparent;
➕ 
Прибрала.

2022-02-08 21:00 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.css
> +.SegmentedControlOption__self {
Мы, кстати, уже это обсуждали, когда я делала фикс для `Switch`. 😉 Вспомнив это, я сходила туда и увидела чуть другую реализацию. Подумала, как бы нам положить это в одно место, и в итоге выделила-таки `VisuallyHiddenInput` в отдельный компонент.

2022-02-08 21:03 UTC, eugpoloz commented
Добавила также доработки после дизайн-ревью:
- новый проп `size`,
- другой цвет для `hover`-состояния текста и иконок, чтобы привести в соответствие с новым макетом.

![image](https://user-images.githubusercontent.com/22026957/153075077-ea3e99b7-3b95-4b83-8599-1734f92947f1.png)

@ArthurStam, смотри, добавился пример формы!

2022-02-09 12:10 UTC, ArthurStam requested changes

2022-02-09 12:10 UTC, ArthurStam commented on styleguide/deprecated.ts
> +export const deprecated = ["SliderSwitch"];
У нас весь стайлгайд на `.js`

2022-02-09 12:10 UTC, ArthurStam commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  useIsomorphicLayoutEffect(() => {
Это я передал `defaultValue`, который не соответствует ни одному из предложенных в `options` вариантов. 

Давай его в начало уводить в таком случае?

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/5061840/153198252-611e3f75-276c-4bc1-90aa-a8019f544c87.png">

2022-02-10 14:36 UTC, Zaycevq commented
> Fixes #2055.
> 
> * [x]  добавить новый `SegmentedControl`, который принимает сколько угодно опций
> * [x]  отметить `SliderSwitch` как deprecated
> * [x]  завести на vkui-tokens
> * [ ]  дизайн-ревью

Design review: OK 👍🏽

2022-02-14 10:39 UTC, eugpoloz commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  | readonly string[]
(И тут я обнаружила, что забыла отправить комменты!)

Я копировала из того, что дают для `value`, но для нас это, наверное, правда оверкилл, не смогла ни одного юзкейса придумать.

➕

2022-02-14 10:39 UTC, eugpoloz commented on styleguide/deprecated.ts
> +export const deprecated = ["SliderSwitch"];
➕

2022-02-16 07:17 UTC, ArthurStam commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  useIsomorphicLayoutEffect(() => {
Норм

2022-02-16 07:21 UTC, ArthurStam commented on src/components/SegmentedControl/SegmentedControl.tsx
> +  extends Omit<React.HTMLAttributes<HTMLDivElement>, "onChange">,
Действительно

2022-02-16 12:01 UTC, ArthurStam approved these changes

2022-02-16 12:05 UTC, merged