FMAIL-15708: Доработать компонент CardScroll
VKCOM/VKUI pull request #2209
Opened 2022-01-25 09:30 UTC by yletamitlu

2022-01-27 11:58 UTC, 8coon commented
Версия vkui-tokens с новыми токенами для компонента https://github.com/VKCOM/vkui-tokens/releases/tag/v4.1.0

2022-01-31 05:45 UTC, ArthurStam reviewed
1. Пока не влили один MR, нужно придерживаться следующего подхода. Для `.Card` нужно назначить `border-radius: var(--vkui--size_card_border_radius--regular, 16px)`, а для `.Card--ios` и `.Card--vkcom` нужно оставить хардкодные значения. Скоро будет лучше, но пока так.
2. В режиме компонента без отступов стоит использовать лёгкие css-селекторы, чтобы разработчики могли без боли навесить свои значения внешних отступов. То есть лучше утяжелить текущие селекторы, используя `:not`.
3. В `.Group--card .CardScroll` я бы убрал отрицательные `margin` в режиме `withSpaces={false}`, так как это тоже по идее внешние отступы.

2022-01-31 05:45 UTC, ArthurStam commented on src/components/CardScroll/CardScroll.tsx
> +  showArrows,
Тут нужно прописать дефолт `true`, чтобы не сломать обратную совместимость, так как до проброса этого свойства, `showArrows` был всегда `true`

2022-01-31 05:45 UTC, ArthurStam commented on src/components/CardScroll/CardScroll.tsx
> +  showArrows?: boolean | "always";
Я б тут написал `showArrows?: HorizontalScrollProps["showArrows"]`

2022-02-01 03:04 UTC, ArthurStam requested changes

2022-02-01 03:04 UTC, ArthurStam commented on src/components/CardScroll/CardScroll.tsx
> +  size?: "s" | "m" | "l" | "false";
Лучше просто `false` вместо `"false"`. И добавь плз текстовое описание, чтобы было понятно, что этот false сделает. А то предчувствую вопросы.

2022-02-01 03:04 UTC, ArthurStam commented on src/components/CardScroll/CardScroll.tsx
> +        { ["CardScroll--withoutSpaces"]: !withSpaces }
Я тут подумал, что мы зачем-то из утверждения `withSpaces` делаем отрицание `--withoutSpaces`, а потом в CSS делаем отрицание этого отрицания через `:not`. Не проще ли сделать `--withSpaces` и уйти от `:not`? ИМХО, так будет сильно проще читаться.

2022-02-01 03:56 UTC, ArthurStam requested changes
Хардкода радиуса для `.Card--android` быть не должно.

Логика следующая: у просто `.Card` радиус должен быть задан через vkui-tokens. У ios и vkcom они должны быть переопределены путем хардкода значений в пикселях.

2022-02-01 03:56 UTC, ArthurStam commented on src/components/Card/Card.css
>    background: var(--content_tint_background);
Если мы перевозим компонент на токены, то не только размеры переводить, но и цвета, и тени

2022-02-01 18:53 UTC, 8coon commented
Обновлённые токены для компонента https://github.com/VKCOM/vkui-tokens/releases/tag/v4.2.0

2022-02-02 10:10 UTC, ArthurStam requested changes
Я бы ещё вытащил отсюда тесты и отдельным MR их заслал. Чтобы они уже были в мастере и мы видели расхождения, если такие в этом MR появятся.

2022-02-02 10:10 UTC, ArthurStam commented on src/components/Card/Card.css
> +  background: var(
Должно быть background: var(
    --content_tint_background,
    var(--vkui--color_background_secondary)
  );

2022-02-02 10:10 UTC, ArthurStam commented on src/components/Card/Card.css
> +  background: var(
Ниже в цветах тоже нужно поменять местами порядок переменных

2022-02-02 10:10 UTC, ArthurStam commented on src/components/CardScroll/CardScroll.css
> +.CardScroll--ios:is(.CardScroll--withSpaces) .CardScroll__gap {
:is не поддерживается в IE. Почему не написать просто `.CardScroll--ios.CardScroll--withSpaces`

2022-02-02 10:10 UTC, ArthurStam commented on src/components/CardScroll/CardScroll.css
> +.CardScroll--android:is(.CardScroll--withSpaces) .CardScroll__gap {
Тут следует опустить `.CardScroll--android`. Android — наша дефолтная платформа.

2022-02-04 14:51 UTC, ArthurStam approved these changes

2022-02-04 14:51 UTC, merged