Add calendar
VKCOM/VKUI pull request #2228
Opened 2022-01-31 09:53 UTC by stoope

- [ ] Перейти на токены vkui
- [ ] Проверить accessibility
- [ ] Написать тесты

2022-02-03 18:20 UTC, eolme commented on src/components/CalendarDay/CalendarDay.css
> +  border-top-right-radius: 0;
Предлагаю использовать shorthand

2022-02-03 18:26 UTC, land47 commented on src/components/CalendarTime/CalendarTime.tsx
> +          Готово
А кнопку как локализировать?

2022-02-07 13:31 UTC, stoope commented on src/components/CalendarDay/CalendarDay.css
> +  border-top-right-radius: 0;
+

2022-02-07 13:31 UTC, stoope commented on src/components/CalendarTime/CalendarTime.tsx
> +          Готово
+

2022-02-09 06:53 UTC, eolme commented on src/components/CalendarDay/CalendarDay.tsx
> +        aria-label={new Intl.DateTimeFormat(locale, {
У Intl очень скудная поддержка, да и сам он довольно тяжёлый, если можно так назвать

2022-02-16 08:50 UTC, ArthurStam requested changes

2022-02-16 08:50 UTC, ArthurStam commented on src/components/Calendar/Calendar.css
> +  border-radius: 8px;
Скругление не токенизируется?

2022-02-16 08:50 UTC, ArthurStam commented on package.json
> +    "date-fns": "^2.28.0",
Почему это дев зависимость, если она используется в рантайме компонента?

2022-02-16 08:50 UTC, ArthurStam commented on package.json
> +    "react-number-format": "^4.9.1",
Почему это дев зависимость, если она используется в рантайме компонента?

2022-02-16 08:50 UTC, ArthurStam commented on src/components/Calendar/Calendar.tsx
> +      <div {...props} ref={ref} vkuiClass="Calendar">
Сюда `getRootRef` нужен, а не `ref`, иначе мы ломаем привычный DX. Тултип какой-нибудь не навесишь на весь календарь.

2022-02-16 08:50 UTC, ArthurStam commented on src/components/Calendar/Calendar.tsx
> +export const Calendar = React.forwardRef<HTMLDivElement, CalendarProps>(
Не хотим добавить возможность передавать `defaultValue`?

2022-02-16 08:50 UTC, ArthurStam commented on src/components/Calendar/Readme.md
> +    <View activePanel="calendar">
Тут не нужен обвез в виде `View`, `Panel`, `PanelHeader` и `Group`

2022-02-16 08:50 UTC, ArthurStam commented on src/components/CalendarDay/CalendarDay.css
> +  font-size: 14px;
Почему не используем компонент типографики?

2022-02-16 08:50 UTC, ArthurStam commented on src/components/CalendarDay/CalendarDay.css
> +  color: #fff;
Тут точно нужен хардкод цвета?

2022-02-16 08:50 UTC, ArthurStam commented on src/components/CalendarDay/CalendarDay.tsx
> +        aria-label={new Intl.DateTimeFormat(locale, {
Вроде нормальная у него поддержка https://kangax.github.io/compat-table/esintl/

2022-02-16 08:50 UTC, ArthurStam commented on src/components/CalendarDay/CalendarDay.tsx
> +    React.useEffect(() => {
Не оч понял, что тут происходит

2022-02-16 08:50 UTC, ArthurStam commented on src/components/CalendarDays/CalendarDays.css
> +.CalendarDays__row__day-name {
С точки зрения БЭМ это выглядит как элемент элемента, что является нарушением методологии

2022-02-16 08:50 UTC, ArthurStam commented on src/components/CalendarHeader/CalendarHeader.css
> +  margin-bottom: 4px;
Я бы у блока не задавал такие стили. Добавил бы их там, где блок используется. Не критично, так как этот блок не торчит наружу, но всё-таки. То же про `z-index`

2022-02-16 08:50 UTC, ArthurStam commented on src/components/DateRangeInput/DateRangeInput.tsx
> +                <svg
В паке иконок нет такой иконки?

2022-02-16 08:50 UTC, ArthurStam commented on src/lib/calendar.ts
> +  const years: CustomSelectProps["options"] = [];
почему именно на этот тип ссылаемся? Обычно утилиты не импортят компоненты.

2022-02-16 08:50 UTC, ArthurStam commented on src/index.ts
> +export { Calendar } from "./components/Calendar/Calendar";
Их же добавить в `src/tokenized/index.ts` и `styleguide/tokenized.js`

2022-02-16 11:08 UTC, stoope commented on src/components/Calendar/Calendar.css
> +  border-radius: 8px;
В фигме без токена

2022-02-16 11:14 UTC, stoope commented on package.json
> +    "date-fns": "^2.28.0",
Да, ты прав, перенес

2022-02-16 11:14 UTC, stoope commented on package.json
> +    "react-number-format": "^4.9.1",
Да, ты прав, перенес

2022-02-16 11:29 UTC, stoope commented on src/components/Calendar/Calendar.tsx
> +      <div {...props} ref={ref} vkuiClass="Calendar">
+

2022-02-16 11:31 UTC, inomdzhon commented on src/components/CalendarDay/CalendarDay.tsx
> +        aria-label={new Intl.DateTimeFormat(locale, {
У [DateTimeFormat](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Intl/) поддерживается с Safari >= 10

Есть [поллифил](https://formatjs.io/docs/polyfills/intl-datetimeformat), но весит дофига ([ссылка на бандл фобию](https://bundlephobia.com/package/@formatjs/intl-datetimeformat@5.0.0))

2022-02-16 11:34 UTC, stoope commented on src/components/CalendarDay/CalendarDay.tsx
> +        aria-label={new Intl.DateTimeFormat(locale, {
Изначально я использовал для этого `date-fns` но захотел сэкономить пару килобайт). @ArthurStam у нас правда 9 сафари поддерживается?

2022-02-16 11:38 UTC, stoope commented on src/components/Calendar/Calendar.tsx
> +export const Calendar = React.forwardRef<HTMLDivElement, CalendarProps>(
Я не вижу как оно будет использоваться. Можешь привести пример как оно будет использоваться?

2022-02-16 11:42 UTC, stoope commented on src/components/CalendarDay/CalendarDay.tsx
> +    React.useEffect(() => {
Сверху спускается свойство `focused` по которому должен случаться фокус на день. Нужно для навигации по дням с помощью стрелок

2022-02-16 11:53 UTC, stoope commented on src/components/Calendar/Readme.md
> +    <View activePanel="calendar">
Убрал

2022-02-16 11:53 UTC, stoope commented on src/components/CalendarDay/CalendarDay.css
> +  color: #fff;
Спасибо, поправил)

2022-02-16 11:54 UTC, stoope commented on src/components/CalendarDay/CalendarDay.css
> +  font-size: 14px;
А какой именно компонент тут подойдет?

2022-02-16 12:45 UTC, stoope commented on src/components/CalendarDays/CalendarDays.css
> +.CalendarDays__row__day-name {
поправил

2022-02-16 12:45 UTC, stoope commented on src/components/CalendarHeader/CalendarHeader.css
> +  margin-bottom: 4px;
Перенес

2022-02-16 13:05 UTC, stoope commented on src/lib/calendar.ts
> +  const years: CustomSelectProps["options"] = [];
Убрал

2022-02-16 13:05 UTC, stoope commented on src/index.ts
> +export { Calendar } from "./components/Calendar/Calendar";
Добавил

2022-02-16 13:09 UTC, inomdzhon commented on src/components/CalendarDay/CalendarDay.tsx
> +        aria-label={new Intl.DateTimeFormat(locale, {
Про браузеры я [тут в README.md](https://github.com/VKCOM/VKUI#%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D1%8B) узнал

2022-02-21 16:43 UTC, inomdzhon commented on src/components/DateInput/Readme.md
> +            <LocaleProviderContext.Provider value={locale}>
Может перебивать локаль через св-во `locale`, а если `locale`, то брать из контекста?

2022-02-21 16:45 UTC, stoope commented on src/components/DateInput/Readme.md
> +            <LocaleProviderContext.Provider value={locale}>
Не хочу давать несколько способов сделать одно и то же, сложнее будет их поддерживать)

2022-02-25 15:01 UTC, eolme commented
По датам нельзя табом выбирать - это такая задумка или просто не работает еще?

2022-02-25 15:03 UTC, eolme commented
И еще "запрет выбора прошлых дат" при переключении, например, если стояла прошедшая дата, не сбрасывается выбранная. С "запретом выбора будущих дат" аналогично.

2022-02-25 15:43 UTC, stoope commented
> 

По датам навигация с помощью стрелок

2022-03-15 09:06 UTC, inomdzhon commented on src/components/CalendarDay/CalendarDay.tsx
> +        aria-label={new Intl.DateTimeFormat(locale, {
Понимаю, что весь компонент в `React.memo`, но может создание экземпляра `Intl` обернуть в хук `React.useMemo`?

2022-03-15 09:31 UTC, NekR commented on package.json
> +    "date-fns": "^2.28.0",
Эта штука неприемлемо много весит для зависимости в VKUI. Какой нибудь dateformat весит во много раз меньше, чем текущая зависимость.

2022-03-15 09:35 UTC, NekR commented on src/components/CalendarDay/CalendarDay.tsx
> +        aria-label={new Intl.DateTimeFormat(locale, {
Если блокер только Safari 9 -- то давайте попробуем его дропнуть. Он нужен только для мвк

2022-03-15 09:50 UTC, inomdzhon commented on src/components/InputLike/InputLike.tsx
> +        {new Array(length - (value?.length ?? 0))
Может через один цикл внутри `React.useMemo` решить задачу?
А тут мы создаём массив на N псевдо эл-ов, заполняем символами, а потом мапой проходим

2022-03-15 09:56 UTC, inomdzhon commented on src/hooks/useDateInput.ts
> +  }, [disabled, focusedElement, openCalendar, refs, window]);
Не знаю насколько это критично, но из-за того, что `refs` это массив, `useEffect` будет в каждый перерендер срабатывать
Можно выше, где мы используем `useDateInput` запихнуть `refs` в `React.useMemo`

2022-03-15 09:59 UTC, inomdzhon commented on src/components/InputLike/InputLike.tsx
> +InputLike.displayName = "InputLike";
Хорошая тема 👍 
Недавно закидывал в чат на счёт использования `displayName`, а то на проде всё обфусцируется и ничего непонятно(

2022-03-15 10:10 UTC, inomdzhon commented on src/components/Calendar/Calendar.tsx
> +import { isSameMonth, isSameDay } from "date-fns";
Ааа, эт самое, а `Intl` не умеет в тоже самое, что `date-fns`?
Правда эти функции придётся самому реализовать, но форматирование должно быть возможно

PS: вообще в коде вижу, что где-то `format` через Intl, где-то ]format] через `date-fns`

2022-03-15 10:24 UTC, stoope commented on package.json
> +    "date-fns": "^2.28.0",
Хм, dateformat и правда выигрыш в размере бандла с учетом tree shaking?

2022-03-15 10:59 UTC, NekR commented on package.json
> +    "date-fns": "^2.28.0",
На этот вопрос невозможно ответить, не зная как оно тришейкится. Если хочешь протащить ту либу и утверждаешь что тришейкинг помогает, то покажи. Потом будет сравнивать уже.

2022-03-15 11:38 UTC, eolme commented on src/components/Calendar/Calendar.tsx
> +import { isSameMonth, isSameDay } from "date-fns";
dayjs это по факту moment, а date-fns это набор утилит

2022-03-15 12:13 UTC, stoope commented on package.json
> +    "date-fns": "^2.28.0",
Если посмотреть на size-limit report то видно что date-fns тришейкается. Не вижу смысл пробовать другие либы, тратить время на переписывания компонента пока нет оснований полагать что будет большой выигрыш в размере бандла

2022-03-15 12:54 UTC, NekR commented on package.json
> +    "date-fns": "^2.28.0",
Только что убрал date-fns и получил -11kb от текущего размера в этом МРе. Это в 5 раз больше чем dateformat без тришейкинга.

К сожалению, придётся переделать, либо на библиотеку с минимальным размером, либо на Intl, если удастся дропнуть зависимости.

Напомню, что просто так добавлять разные зависимости нельзя и если что-то добавлять, то нужно выбирать с наименьшим возможным размером.

2022-03-15 12:56 UTC, NekR requested changes
Нужно разобраться с размером зависимостей. Либо использовать очень маленькую библиотеку для управления датами, такую как dateformat, либо таки использовать Intl и отказаться от блокирующих зависимостей.

2022-03-15 12:59 UTC, stoope commented on src/components/Calendar/Calendar.tsx
> +import { isSameMonth, isSameDay } from "date-fns";
А зачем писать самому все эти функции если они уже написаны?) Не думаю что мы что то выиграем от этого

2022-03-15 13:01 UTC, stoope commented on package.json
> +    "date-fns": "^2.28.0",
@NekR разве dateformat заменяет date-fns? Я посмотрел, это просто утили для форматирования дат, которое у нас делается через Intl

2022-03-15 13:02 UTC, eugpoloz commented on styleguide/tokenized.js
> +  "Title",
А как тут оказался `Title`?

2022-03-15 13:09 UTC, stoope commented on src/components/CalendarDay/CalendarDay.css
> +  border-bottom: 2px solid var(--vkui--color_stroke_contrast);
+

2022-03-15 13:09 UTC, stoope commented on src/components/Calendar/Calendar.css
> +.Calendar--size-s .CalendarDay,
+

2022-03-15 13:10 UTC, stoope commented on src/components/CalendarDay/CalendarDay.css
> +:not(.CalendarDay--hover) .CalendarDay__inner--active {
+

2022-03-15 13:10 UTC, stoope commented on src/components/CalendarRange/CalendarRange.css
> +  box-shadow: 0 0 2px rgba(0, 0, 0, 0.03), 0 2px 2px rgba(0, 0, 0, 0.06);
+

2022-03-15 13:10 UTC, stoope commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    Локаль, список -> https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
done

2022-03-15 13:10 UTC, stoope commented on src/components/DateInput/Readme.md
> +**Обратите внимание:** Данный компонент предназначен для использования на desktop. При использовании на ios/android работа компонента не гарантируется
done

2022-03-15 13:10 UTC, stoope commented on src/components/DateRangeInput/Readme.md
> +**Обратите внимание:** Данный компонент предназначен для использования на desktop. При использовании на ios/android работа компонента не гарантируется
done

2022-03-15 13:17 UTC, inomdzhon commented on src/components/DateInput/Readme.md
> +**Обратите внимание:** Данный компонент предназначен для использования на desktop. При использовании на ios/android работа компонента не гарантируется
А, вот здесь https://vkcom.github.io/VKUI/#/Modes пример, оказывается можно глянуть 

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/5850354/158385907-29e4dddd-ba7c-4d19-833e-ed5864faef87.png">

2022-03-15 13:33 UTC, inomdzhon commented on src/components/CustomSelect/CustomSelect.css
> +.CustomSelect__open.CustomSelect__SelectComponent.Select--mimicry:focus
Судя по коду `.Select--mimicry` можно убрать

2022-03-15 13:35 UTC, stoope commented on src/components/CustomSelect/CustomSelect.css
> +.Select--mimicry-plain {
done

2022-03-15 13:35 UTC, stoope commented on src/components/FormField/FormField.css
> +.Select--mimicry-plain .FormField__after,
done

2022-03-15 13:43 UTC, inomdzhon commented on src/components/Calendar/Calendar.tsx
> +import { isSameMonth, isSameDay } from "date-fns";
> А зачем писать самому все эти функции если они уже написаны?) Не думаю что мы что то выиграем от этого

Соглы 👍  
Я рассуждал исходя из того, чтобы уменьшить кол-во зависимостей, но если придётся много чего из `date-fns` самому реализовывать, то тогда это оверхед

---

> Вот тут был разговор, что [либо Intl, либо 9 сафари](https://github.com/VKCOM/VKUI/pull/2228/files/af22fe857eb7428e4dfa765a6ab5c481e06e9ee3#r802314569) (а мы коммиттимся на поддержку 9 сафари).

Если так, то, получается, вместо `new Intl().format` нужно использовать `import { format } from 'data-fns';`

2022-03-15 13:44 UTC, stoope commented on src/components/InputLike/InputLike.tsx
> +export const InputLike = React.forwardRef<HTMLSpanElement, InputLikeProps>(
done

2022-03-15 13:47 UTC, stoope commented on src/components/InputLike/InputLike.tsx
> +        {new Array(length - (value?.length ?? 0))
Я против того что бы использовать `React.useMemo` везде где это можно). Мне кажется для таких простых операций `useMemo` только замедлит производительность за счет расходов  на вызов, проверки равенства аргументов, хранения кеша предыдущих вызовов и тд

2022-03-15 13:55 UTC, inomdzhon commented on src/components/FormField/FormField.css
> +.Select--mimicry-plain .FormField__after,
Кстати, сейчас понял, что если хранить все обращение к компоненту в его же CSS файле, то он раздуется для тех, кто импортирует только этот компонент – при тришейкинге он получит лишнее.

Допустим в данный момент, если мы будем тришейкать стили, я буду при импортировании `Button` в CSS получать модификации от `Banner`, `ModalCardBase` и `RichCell`, потому что они в `Button.css`.

Но для разработки, конечно, это лучше, т.к. явно видно в зависимости от какого контекста модифицируется компонент

---

Ну это так, вброс. Учитывая, что надо решать проблему таких модификаций, возможно сейчас об этом и не надо беспокоиться

2022-03-15 14:00 UTC, eolme commented on package.json
> +    "date-fns": "^2.28.0",
@NekR @stoope больше всего весят `format` и `isMatch` из `date-fns`

<img width="288" alt="image" src="https://user-images.githubusercontent.com/11076888/158394288-2ad79a73-a9fa-4721-92d7-4a84c3c9e833.png">

<img width="288" alt="image" src="https://user-images.githubusercontent.com/11076888/158394346-6fa01643-e9f9-4e6b-bdaf-bc5a5396c1b8.png">

2022-03-15 14:03 UTC, eolme commented on package.json
> +    "date-fns": "^2.28.0",
@NekR кроме форматирования в PR из `date-fns` используются и другие утилиты

2022-03-15 14:10 UTC, stoope commented on src/hooks/useDateInput.ts
> +  }, [disabled, focusedElement, openCalendar, refs, window]);
done

2022-03-15 14:13 UTC, stoope commented on src/components/Calendar/Calendar.test.tsx
> +});
Хорошая мысль) Я покапал и понял что тестить юнит тестами такое очень сложно, поэтому протестил эти кейсы скриншотами)

2022-03-15 14:47 UTC, stoope commented on src/components/CalendarDays/CalendarDays.css
> +  font-size: 13px;
done

2022-03-15 14:47 UTC, stoope commented on src/components/CalendarHeader/CalendarHeader.css
> +  font-size: 15px;
done

2022-03-15 14:47 UTC, stoope commented on src/components/Calendar/Calendar.tsx
> +    warn("can't enable pickers when size is 's'");
done

2022-03-15 14:48 UTC, stoope commented on src/components/CalendarDay/CalendarDay.css
> +}
done

2022-03-15 14:50 UTC, stoope commented on src/components/CalendarTime/CalendarTime.tsx
> +          aria-label={closeAriaLabel}
done

2022-03-16 12:05 UTC, inomdzhon approved these changes

2022-03-16 12:08 UTC, eugpoloz approved these changes
Го в мастер, в общем! ❤️

2022-03-16 12:10 UTC, merged