Title: tokenized
VKCOM/VKUI pull request #2230
Opened 2022-02-01 13:12 UTC by ArthurStam

Перевел Title на токены

2022-02-02 11:03 UTC, eugpoloz reviewed
Надо Update Screenshots запустить, а так выглядит супер. 🔥

2022-02-04 10:57 UTC, eugpoloz requested changes

2022-02-04 10:57 UTC, eugpoloz commented on src/components/Typography/Title/Title.tsx
> +   * Начертания "heavy", "bold", "semibold", "medium" и "regular" устарели и будут удалены в 5.0.0.
И все-таки меня очень смущают 1, 2 и 3 как вес. Мне сейчас, например, в разы сложнее сориентироваться, потому что я навскидку не понимаю, каким значениям они соответствуют, потому что `font-weight` задается либо через `100`-`900`, либо через `normal`/`bold`/`lighter`/`bolder`. Старые ключи как будто лучше справлялись с задачей интуитивного использования, а мы усложняем на пустом месте. Не стоит ли тут посоветоваться еще раз с дизайнерами?

2022-02-04 10:57 UTC, eugpoloz commented on styleguide/Components/ReactComponent/ReactComponent.js
> +  console.log(tokenized.includes(visibleName));
Кажется, остался лишний лог. 😄

2022-02-04 10:57 UTC, eugpoloz commented on src/components/Search/Search.tsx
> +              <SearchPlaceholderTypography platform={platform}>
Можно задавать `vkuiClass="Search__placeholder-text"` здесь, чтобы не повторять его три раза в самом `SearchPlaceholderTypography`.

2022-02-04 11:55 UTC, ArthurStam commented on src/components/Typography/Title/Title.tsx
> +   * Начертания "heavy", "bold", "semibold", "medium" и "regular" устарели и будут удалены в 5.0.0.
Понимаю про что ты, но тут такая история. Если давать такие значения этому пропу, то мы потом окажемся в глупом положении, если захотим, допустим, на 1 пункт поднять все веса. То есть раньше 400 отражал 400, а будет так, что 400 отражает 500. Спрятавшись под обезличенные цифры, мы уберегаем себя от такой ситуации. Дизайнеры как раз эти значения и предложили.

2022-02-04 12:14 UTC, eugpoloz commented on src/components/Typography/Title/Title.tsx
> +   * Начертания "heavy", "bold", "semibold", "medium" и "regular" устарели и будут удалены в 5.0.0.
А почему нельзя оставить старые значения или как-то их переформулировать? Они как раз были достаточно абстрактны и не предполагали жесткой привязки к весам, но и совсем абстракцией не были. Мне навскидку даже непонятно, 1 — это самое жирное начертание или наоборот.

2022-02-04 13:37 UTC, ArthurStam commented on styleguide/Components/ReactComponent/ReactComponent.js
> +  console.log(tokenized.includes(visibleName));
fixed

2022-02-04 13:37 UTC, ArthurStam commented on src/components/Search/Search.tsx
> +              <SearchPlaceholderTypography platform={platform}>
fixed

2022-02-04 13:40 UTC, ArthurStam commented on src/components/Typography/Title/Title.tsx
> +   * Начертания "heavy", "bold", "semibold", "medium" и "regular" устарели и будут удалены в 5.0.0.
Старые значения отсылают к CSS

2022-02-04 13:41 UTC, ArthurStam commented on src/components/Typography/Title/Title.tsx
> +   * Начертания "heavy", "bold", "semibold", "medium" и "regular" устарели и будут удалены в 5.0.0.
Будет та же проблема при изменении реальных значений жирности. Regular будет становиться medium и т.д.

2022-02-09 09:12 UTC, ArthurStam commented on src/components/Typography/Title/Title.tsx
> +   * Начертания "heavy", "bold", "semibold", "medium" и "regular" устарели и будут удалены в 5.0.0.
В итоге приняли решение повернуть в обратную сторону счет. weight="1" — самый жирный, weight="3" — самый тонкий. Жду новую версию токенов.

2022-02-10 15:08 UTC, eugpoloz submitted a review, later dismissed

2022-02-10 15:20 UTC, eugpoloz reviewed
@ArthurStam я бы еще добавила в скриншотные тесты новые значения или вообще оставила только их сразу.

2022-02-14 07:46 UTC, merged