[refactor] Card & CardScroll
VKCOM/VKUI pull request #2242
Opened 2022-02-11 13:35 UTC by eugpoloz

`CardScroll`:

- [x] убрала `defaultProps`
- [x] перевела с `withAdaptivity` на хук `useAdaptivity()`
- [x] убрала дефолтный экспорт (#2191)
- [x] перекинула стили, относящиеся к `Card`, в Card.css
- [x] добавила экспорт в tokenized.ts
- [x] отметила в доке компонент как tokenized
- [x] немного пофиксила тексты документации и пропсов

`Card`:

- [x] убрала `defaultProps`
- [x] убрала дефолтный экспорт (#2191)
- [x] добавила экспорт в tokenized.ts
- [x] отметила в доке компонент как tokenized

2022-02-11 13:59 UTC, stoope submitted a review, later dismissed

2022-02-14 07:49 UTC, ArthurStam reviewed
MR с Title вмержен, поэтому `CardScroll` и `Card` можно добавить в styleguide/tokenized.js

2022-02-14 07:52 UTC, ArthurStam requested changes

2022-02-14 07:52 UTC, ArthurStam commented on src/tokenized/index.ts
> +export { CardScroll } from "../components/CardScroll/CardScroll";
`Card` тоже токенизирован

2022-02-14 10:37 UTC, eugpoloz commented on src/tokenized/index.ts
> +export { CardScroll } from "../components/CardScroll/CardScroll";
Думала сделать отдельно, но раз они связаны и там не очень много, то пусть будут оба сразу.
➕

2022-02-14 11:30 UTC, ArthurStam approved these changes

2022-02-14 11:34 UTC, merged