feat: Create ButtonGroup component
VKCOM/VKUI pull request #2259
Opened 2022-02-17 16:44 UTC by inomdzhon

## Описание решения

Реализовал с помощью реактовского контекста.

1. При оборачивании в `ButtonGroup`, создается контекст `ButtonGroupContext`, в котором хранится `mode`, `padding` и `stretched`. 
2. `Button` из контекста понимает находится он сейчас в группе или нет и выставляет соответсвующие классы.
    1. `stretched` из контекста приоритетнее чем `stretched` в компоненте `Button` ([ссылка на код](https://github.com/inomdzhon/VKUI/blob/feature/ButtonGroup-v1/src/components/Button/Button.tsx#L191))
    2. В случае, если у нас кнопка-иконка, то выставляем ей несколько св-в ([ссылка на код](https://github.com/inomdzhon/VKUI/blob/feature/ButtonGroup-v1/src/components/Button/Button.css#L102-L106))

## Какие ещё были варианты?

1. Изначально была идею использовать `display: flex` со св-ом `gap`, но это решение не будет совместимо с поддерживаемыми нами браузерами (ссылка на поддержку https://caniuse.com/flexbox-gap).
2. Добавлять падинги через каскад `.ButtonGroup .Button`, но ввиду того, что мы идём к CSS Modules, будет сложно подогнать под него такой каскад...пока даже не представляю как 😰

## Нюансы

1. Надо завести докены `sizeButtonGroupPaddingMedium` и `sizeButtonGroupPaddingSmall` в репе с токенами. Сейчас пока зашил их в [src/styles/constants.css](https://github.com/inomdzhon/VKUI/blob/feature/ButtonGroup-v1/src/styles/constants.css#L44-L45)
2. Надо доделать, чтобы `padding` принимал произвольное число. Сейчас принимает только `enum`. Пока идея оперировать атрибутом `style`
    1. либо меняем св-во `margin` напрямую
    2. либо в рут элементе `ButtonGroup` перебиваем токены
        ```jsx
        <div style={{ '--vkui--size_button_group--padding-medium': padding }}>...</div>
        ```
    3. либо на уровне дизайн-системы договариваемся использовать только `enum`
3. Пока не проверял в связке с компонентами `Banner`, `ModalCardBase` и `RichCell`. Вижу, что в [Button.css](https://github.com/VKCOM/VKUI/blob/master/src/components/Button/Button.css) ими 
    перебиваются отступы, которые я задаю если `Button` внутри `ButtonGroup`. Предполагаю в них может всё поломаться. Проверю позже. Сейчас хочу саму идею с контекстом показать. Вот ссылки на строчки:
    - [Banner](https://github.com/VKCOM/VKUI/blob/master/src/components/Button/Button.css#L511-L542)
    - [ModalCardBase](https://github.com/VKCOM/VKUI/blob/master/src/components/Button/Button.css#L544-L561)
    - [RichCell](https://github.com/VKCOM/VKUI/blob/master/src/components/Button/Button.css#L563-L566)

2022-02-17 22:07 UTC, stoope commented
Возможно мы идем не к чистым `CSS Modules` а к css-in-js` без рантайма по типу `linaria`.
Мне не очень нравится что мы добавили еще один способ переопределения стилей - через контекст, я считаю что нужно оставить подход `.ButtonGroup .Button` пока мы согласуем новый.
Я не говорю что подход через контекст плохой но при переходи на новое CSS решения он нам добавит overhead

2022-02-17 22:23 UTC, stoope commented on src/components/ButtonGroup/ButtonGroup.tsx
> +  padding?: "medium" | "small"; // number
Что значит `number`?)

2022-02-17 22:23 UTC, stoope commented on styleguide/config.js
> +            "../src/components/ButtonGroup/ButtonGroup.tsx",
Нужно еще добавить в `src/tokenized/index.ts` и `styleguide/tokenized.js`

2022-02-17 22:23 UTC, stoope commented on src/components/ButtonGroup/ButtonGroup.tsx
> +export default ButtonGroup;
От дефолтных экспортов мы наоборот уходим, новые компоненты лучше сразу делать через named

2022-02-17 22:23 UTC, stoope commented on src/components/ButtonGroup/ButtonGroup.tsx
> +}: ButtonGroupProps) => {
Этот тип можно опустить, он уже выводится из `React.FC<ButtonGroupProps>`

2022-02-17 22:23 UTC, stoope commented on src/components/ButtonGroup/ButtonGroup.tsx
> +      />
Мне режет глаза self closing div т.к. это не валидный html.

2022-02-18 06:22 UTC, ArthurStam requested changes
Годный MR и подход к описанию компонента в доке. Всё нравится, но есть вопросики.

2022-02-18 06:22 UTC, ArthurStam commented on src/index.ts
> +  ButtonGroupContext,
Нужно делать этот контекст экспортируемым? Как он может пригодиться пользователям?

2022-02-18 06:22 UTC, ArthurStam commented on src/components/ButtonGroup/ButtonGroup.tsx
> +      />
Да лааадно, в JSX это абсолютно валидная конструкция

2022-02-18 06:22 UTC, ArthurStam commented on src/components/ButtonGroup/ButtonGroup.tsx
> +  className?: string;
`className`, `style` и `children` можно не указывать, они уже есть при экстенде от `React.HTMLAttributes`

2022-02-18 06:22 UTC, ArthurStam commented on src/components/Button/Button.css
> +  flex-basis: 100%;
Такой проп приводит к расширению кнопки, когда мы не хотим stretched. Пример как щас:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/5061840/154628756-405fcfe8-3b05-44dc-812e-9ace51466618.png">
Пример как по идее должно быть (отключил `flex-basis: 100%`):
<img width="333" alt="image" src="https://user-images.githubusercontent.com/5061840/154628819-4ab942b3-8660-4593-b234-28482258bc45.png">

2022-02-18 06:22 UTC, ArthurStam commented on src/components/Button/Button.tsx
> +          ["Button--stretched"]: buttonGroupContext?.stretched || stretched,
Хотим ли мы строить такую связь через контекст? 

Я предлагаю такое упрощение: `stretched` на `ButtonGroup` аффектит только ширину `.ButtonGroup`. Я щас читаю код и мне сложно предсказать, как он будет работать, это, имхо, тревожный звоночек. Упрощение хорошо тем, что нас потом никто не блочит от того, чтобы вернуться к предложенному тобой решению. А вот если мы сразу так сделаем, то избавиться от такого решения уже не получится, так как breaking change.

2022-02-18 10:50 UTC, inomdzhon commented on src/components/ButtonGroup/ButtonGroup.tsx
> +}: ButtonGroupProps) => {
Спорный момент

Если опустить его, то потеряется валидация в случае, когда мы дефолтное значение определяем при деструктуризации

Вот с явным типом
<img width="709" alt="image" src="https://user-images.githubusercontent.com/5850354/154668897-2d1ca738-256f-4dbb-aceb-0917b32ef787.png">

Вот без него
<img width="482" alt="image" src="https://user-images.githubusercontent.com/5850354/154668959-93f8ee70-89a1-4edd-8973-8720cfb8f6fc.png">

2022-02-18 11:02 UTC, inomdzhon commented on src/components/Button/Button.css
> +  flex-basis: 100%;
Вчера у меня были сомнения при использовании `flex-basis: 100%`
Попробую иное решение
Спасибо)

2022-02-18 11:07 UTC, inomdzhon commented on src/components/Button/Button.tsx
> +          ["Button--stretched"]: buttonGroupContext?.stretched || stretched,
Если я правильно понял твоё предложение, то пользователю придётся самому везде раставлять `stretched` 🤔 

Хорошо ли это?

---

PS: Кстати, мне ещё дизайнер сказал, что кнопки одного размера в группе должны быть, но договорился с ним, что пользователь сам за этим будет следить, а то перебивать ещё и `size` жёстко. Мол пусть только `stretched` перебивается. Ещё была идея в режиме Dev сыпать `console.warn`, но это сомнительно, т.к. вдруг пользователь хочет разные размер задавать. Тогда встаёт вопрос `выравнивания кнопок`.

2022-02-18 11:08 UTC, fedorov-xyz commented on src/components/ButtonGroup/ButtonGroup.tsx
> +}: ButtonGroupProps) => {
Его нельзя опускать, так как стайлгайдист из него для доки типы вытаскиывает.

2022-02-18 11:15 UTC, stoope commented on src/components/ButtonGroup/ButtonGroup.tsx
> +}: ButtonGroupProps) => {
В первом случае `modeProp` становится строкой и все равно валидация сработает в месте где оно используется, что наверное правильно так как это код идентичен
`const modeProp = props.mod ?? "..."`

2022-02-18 11:16 UTC, inomdzhon commented
> Возможно мы идем не к чистым `CSS Modules` а к css-in-js`без рантайма по типу`linaria`. Мне не очень нравится что мы добавили еще один способ переопределения стилей - через контекст, я считаю что нужно оставить подход `.ButtonGroup .Button` пока мы согласуем новый. Я не говорю что подход через контекст плохой но при переходи на новое CSS решения он нам добавит overhead

1. @stoope а чем такой подход может конфликтовать с `linaria`?
2. Вообще я плохо представляю как дружить `.ButtonGroup .Button` с чистыми `CSS Modules` 🤔 ?
3. В `css-in-js` скорей всего это будет импорт JS стилей `ButtonGroup` в `Button` (или наоборот). Тоже пока не представляю как будет выглядеть реализация.
4. Контекст упрощает стилизацию вложенных `ButtonGroup`. Навскидку, использование `.ButtonGroup .Button` усложнит это.

---

PS: использование контекста не повлияет ведь на дальнейший рефактор. Артур дал верный вопрос, почему есть экспорт `ButtonGroupContext`. Убрал этот экспорт, теперь пользователь не знает про контекст.

2022-02-18 11:16 UTC, stoope commented on src/components/ButtonGroup/ButtonGroup.tsx
> +      />
Я понимаю что валидный, просто глаз зацепился)

2022-02-18 11:18 UTC, stoope commented on src/components/ButtonGroup/ButtonGroup.tsx
> +}: ButtonGroupProps) => {
@fedorov-xyz https://vkcom.github.io/VKUI/#/ActionSheet тут, например, работает дока

2022-02-18 11:20 UTC, inomdzhon commented on src/components/Button/Button.css
> +  flex-basis: 100%;
@ArthurStam хммм, слух, в любом случае нужно оставить это св-во (заменю лучше на `flex-grow: 1`). Если убрать его, то пропадает выравнивание по максимальной ширине.

В примере это же один целый блок. Добавлю в доке рамку, чтобы было нагляднее 🤔  Что думаешь?

<img width="409" alt="image" src="https://user-images.githubusercontent.com/5850354/154672919-9e07f3b5-bbf9-4352-8eaf-e2cbcb519259.png">

2022-02-18 11:21 UTC, eugpoloz commented on src/components/ButtonGroup/ButtonGroup.tsx
> +}: ButtonGroupProps) => {
@fedorov-xyz 

> Его нельзя опускать, так как стайлгайдист из него для доки типы вытаскиывает.

Мы уже вернулись на `react-docgen-typescript`, он справляется без этого типа, если что. 😏

2022-02-18 11:25 UTC, stoope commented
> 1. @stoope а чем такой подход может конфликтовать с `linaria`?
C `linaria` наоборот не будет конфликтовать, там можно реализовать подход `.ButtonGroup .Button`. Я имел ввиду что
у нас уже куча мест где так используются стили и в любом случае придется что то с этим делать, возможно из за этого мы и выберем не чистые `CSS Modules`.
А сейчас получается при переходе нам нужно будет учитывать что у нас есть еще такой подход через контекст

2022-02-18 11:26 UTC, inomdzhon commented on src/components/ButtonGroup/ButtonGroup.tsx
> +      />
Согласен со Степой, у самого такое глаз режет 😁 Ввиду того, что делал черновой вариант и на скорую руку, пропустил)
Но вы уже многое помогли поправить, спасибо 🙌 💖

2022-02-18 11:30 UTC, inomdzhon commented on src/components/ButtonGroup/ButtonGroup.tsx
> +}: ButtonGroupProps) => {
На самом деле не всегда получишь валидацию

<img width="627" alt="Снимок экрана 2022-02-18 в 14 29 55" src="https://user-images.githubusercontent.com/5850354/154674503-f2d229af-0842-4337-99c6-de4be6b35c65.png">

2022-02-18 11:34 UTC, stoope commented on src/components/ButtonGroup/ButtonGroup.tsx
> +}: ButtonGroupProps) => {
@inomdzhon в `role` можно передать строку, тут тебя даже явное указание `ButtonGroupProps` не спасет)

2022-02-18 11:38 UTC, inomdzhon commented on src/components/ButtonGroup/ButtonGroup.tsx
> +}: ButtonGroupProps) => {
> @inomdzhon в `role` можно передать строку, тут тебя даже явное указание `ButtonGroupProps` не спасет)

я для примера использовал `role` 😅  соглы, не удачный пример

---

Ну ок, больше аргументов нет почему это полезно
Удалю

2022-02-18 11:39 UTC, stoope commented on src/components/ButtonGroup/ButtonGroup.e2e.tsx
> +      </ButtonGroup>
Предлагаю `children` также менять. Разные комбинации попробовать (одна, две, nested)

2022-02-18 11:41 UTC, stoope commented on src/components/ButtonGroup/ButtonGroup.tsx
> +}: ButtonGroupProps) => {
Еще не получаешь `children` если явно указывать

2022-02-18 12:54 UTC, inomdzhon commented on src/components/ButtonGroup/ButtonGroup.e2e.tsx
> +      </ButtonGroup>
Возьму второй пример из `README.md`, там много вложений и кнопка-иконка

2022-02-18 13:37 UTC, inomdzhon commented
> > 1. @stoope а чем такой подход может конфликтовать с `linaria`?
> 
> C `linaria` наоборот не будет конфликтовать, там можно реализовать подход `.ButtonGroup .Button`. Я имел ввиду что у нас уже куча мест где так используются стили и в любом случае придется что то с этим делать, возможно из за этого мы и выберем не чистые `CSS Modules`. А сейчас получается при переходе нам нужно будет учитывать что у нас есть еще такой подход через контекст

Меня напрягает использование такого каскада. Без контекста придётся наворотить стилей ради такой простой задачи.

Это ради удобства рефактора мы должны отказываемся от реактовской фичи, которая создана как раз для данного кейса?

---

PS: Я глянул как сделано в Material-UI и оказывается я ничего нового не придумал) Тот же подход, за исключением того, что я для вложенных `ButtonGroup` беру из контекста `padding` и `stretched`.

У них под капотом CSS-in-JS, кстати. Поискал про `linaria` и наткнулся на эту статью [mui-core-v5.md](https://github.com/mui/material-ui/blob/f0f33c6038f874d2f3ecc251a8ca5bc640424992/docs/pages/blog/mui-core-v5.md#migration-from-jss-to-emotion), где они рассказывает про переход с `JSS` на `emotion`

А вот сам код с использованием `styled` + `context` (перебивают `size`, чего я постеснялся делать 🤔)
- [Button](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Button/Button.js#L284-L285)
- [ButtonGroup](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/ButtonGroup/ButtonGroup.js)

2022-02-18 13:39 UTC, inomdzhon commented on src/components/ButtonGroup/ButtonGroup.tsx
> +}: ButtonGroupProps) => {
За счёт
```
interface Button extends React.HTMLAttributes<HTMLDivElement>
```
получаешь

2022-02-18 14:53 UTC, eugpoloz commented
Про контекст хочу напомнить, у нас уже есть похожее решение для `Tabs` и `TabsItem`:

https://github.com/VKCOM/VKUI/blob/ce5f2bc9e4f7e60e14bfbe5ea190a552fe717ef3/src/components/TabsItem/TabsItem.tsx#L26

Правда, там мы не перебиваем никаких внутренних пропсов компонента.

2022-02-18 15:37 UTC, eugpoloz reviewed
Классный пулл, крутая фича, крутой Имон. ✊🏻

2022-02-18 15:37 UTC, eugpoloz commented on src/components/ButtonGroup/ButtonGroup.tsx
> +  padding?: "medium" | "small"; // number
Две мысли про naming conventions:

```suggestion
  size?: "s" | "m"; // number
```

1) Возможно, называть проп `padding` — не совсем правильно, вдруг нам в будущем понадобится аффектить не только его? Что скажешь?

2) Обычно мы не прописываем пропы размера словами целиком, а сокращаем до букв: `"s"`, `"m"` и так далее. Предлагаю и тут это сделать, чтобы наш UX был более лучше. 😉

2022-02-18 15:37 UTC, eugpoloz commented on src/components/ButtonGroup/ButtonGroup.tsx
> +          isNested && `ButtonGroup--vertical-padding-${padding}`
Предлагаю объектом:

```suggestion
          {
            "ButtonGroup--stretched": stretched,
            `ButtonGroup--${size}`: isNested,
          },
```

2022-02-18 15:37 UTC, eugpoloz commented on src/components/ButtonGroup/ButtonGroup.tsx
> +          `ButtonGroup--mode-${mode}`,
```suggestion
          `ButtonGroup--${mode}`,
```

Чтобы не усложнять. :wink:

2022-02-18 15:37 UTC, eugpoloz commented on src/components/Button/Button.tsx
> +          `Button--in-group Button--in-group-${buttonGroupContext.mode}-${buttonGroupContext.padding}`,
Я читаю эти два класса и хочу высказаться в защиту css. 😅 

```css
.ButtonGroup--horizontal.ButtonGroup--m .Button + .Button {
  margin-left: var(--vkui--size_button_group--padding-medium);
}
/* и так далее */
```

Считаю, что такая конструкция проще для понимания и дешевле (= легче) для либы, чем прокидывать здесь контекст, задавать дополнительные классы и т.д.. Для меня это выглядит как усложнение на пустом месте. Нашим медленно фиксируемым css-конвенциям оно как будто тоже не противоречит. 

Призываю к дискуссии еще @stoope и @ArthurStam.

2022-02-18 15:37 UTC, eugpoloz commented on src/components/Button/Button.tsx
> +          ["Button--stretched"]: buttonGroupContext?.stretched || stretched,
@inomdzhon 

> Кстати, мне ещё дизайнер сказал, что **кнопки одного размера в группе должны быть**, но договорился с ним, что пользователь сам за этим будет следить

Это достойно пометки в доке для `ButtonGroup`. 😉  Пример можно в [Alert](https://vkcom.github.io/VKUI/#/Alert) подглядеть.

2022-02-21 05:42 UTC, ArthurStam commented on src/components/Button/Button.tsx
> +          ["Button--stretched"]: buttonGroupContext?.stretched || stretched,
Я считаю, что мы чересчур усложняем код контекстами. Задача довольно простая: сделать контейнер для кнопок с отступами между ними. Нет ничего страшного в том, что пользователи будут сами выставлять `stretched` там, где им это нужно. Я уже проходил путь такого "домысливания" за пользователя, когда думал, что надо по максимуму за них делать работу. В итоге в ряде мест имеем серьезное переусложнение кода, а профит туманный. Давайте попробуем без контекста и с ручным выставлением `stretched`. Усложнить всегда успеем.

2022-02-21 05:53 UTC, ArthurStam commented on src/components/ButtonGroup/ButtonGroup.css
> +.ButtonGroup--vertical-padding-medium:not(:first-child) {
Внешний отступ на блоке в какой-то момент начинает мешать. Мы можем обойтись без него?

2022-02-21 05:53 UTC, ArthurStam commented on src/components/ButtonGroup/ButtonGroup.tsx
> +  padding?: "medium" | "small"; // number
Я бы сначала задал этот вопрос Валере Сироткину, который описывал нейминг в фигме.

2022-02-21 05:55 UTC, ArthurStam commented on src/components/Button/Button.tsx
> +          `Button--in-group Button--in-group-${buttonGroupContext.mode}-${buttonGroupContext.padding}`,
Я щас может совсем дичь предложу, но что если сделать так:
```css
.ButtonGroup--horizontal.ButtonGroup--m > *:not(:last-child) {
  margin-left: var(--vkui--size_button_group--padding-medium);
}
```

И контекст не нужен, и обращения к другому блоку нет.

2022-02-21 14:00 UTC, inomdzhon commented on src/components/Button/Button.tsx
> +          ["Button--stretched"]: buttonGroupContext?.stretched || stretched,
Ок, на уровне документации можно добавить инфу про `streched` 👌  Перебивать всегда успеем)

А вот как без контекста решить вопрос с отступами, которые задали в ручную?

```
<ButtonGroup padding={11}>
```

Вижу пока так, что пользователи и `style` будут сами выставлять =/

---

PS: про контекст [тут](https://github.com/VKCOM/VKUI/pull/2259#issuecomment-1044539289) писал, что ничего нового не придумал, это обычная практика для таких компонентов, которые вкладываются и должны реагировать на это

2022-02-21 14:02 UTC, inomdzhon commented on src/components/ButtonGroup/ButtonGroup.tsx
> +  padding?: "medium" | "small"; // number
Спасибо за заметку 🙏
Предложил Валере использовать `gap` вместо `padding` и сокращения `s`/`m`, жду ответа

2022-02-21 14:17 UTC, inomdzhon commented on src/components/ButtonGroup/ButtonGroup.tsx
> +          isNested && `ButtonGroup--vertical-padding-${padding}`
Стоит обсудить этот момент
Если есть возможность использовать `boolean && string`, то я бы так писал вместо создания объекта с динамичным ключом
Выглядит как экономия на спичках, но в сумме профит будет

## Benchmark

Сделал тест для сравнения https://jsbench.me/obkzwrzoti/1

Скриншот с результатом на моей машинке
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/5850354/154972107-bc772dc2-5d16-45b3-9b0c-7d2488f5b807.png">

2022-02-21 14:48 UTC, inomdzhon commented on src/components/Button/Button.tsx
> +          `Button--in-group Button--in-group-${buttonGroupContext.mode}-${buttonGroupContext.padding}`,
Вот [тут](https://github.com/VKCOM/VKUI/pull/2259#discussion_r811156446) задал вопрос как мне быть отступом, который задали произвольно

2022-02-21 14:55 UTC, inomdzhon commented on src/components/Button/Button.tsx
> +          `Button--in-group Button--in-group-${buttonGroupContext.mode}-${buttonGroupContext.padding}`,
Вообще я стараюсь использовать меньше каскада и делаю шаг в будущее "Отказ от обращений из одного блока к другому"

![image](https://user-images.githubusercontent.com/5850354/154978394-35dfc155-8532-4b88-be6a-fdc3f4f06e4e.png)

Задача проста, а контекст делает её решение ещё проще, а не усложняет её. Тем более, отказываемся от перебивания пропсов (хотя не вижу, что в этом есть проблема)

2022-02-21 15:32 UTC, inomdzhon commented on src/components/ButtonGroup/ButtonGroup.css
> +.ButtonGroup--vertical-padding-medium:not(:first-child) {
@ArthurStam можешь плиз описать подробней, что имеется ввиду?

У нас поведение `padding` завязан на `mode`

Этот когд решает вот эту задачу

```jsx
<ButtonGroup mode="vertical" padding="medium"> // <= нет отступа, так как вне контекста
   <Button></Button>
   <ButtonGroup mode="horizontal" padding="small">  // <= отступ 'margin-top' на 'medium'
        <Button></Button>
        <Button></Button>
   </ButtonGroup>
   <Button></Button>   // <= отступ 'margin-top' на 'medium'
</ButtonGroup>
```

2022-02-21 22:45 UTC, NekR commented on src/components/Button/Button.tsx
> +          ["Button--stretched"]: buttonGroupContext?.stretched || stretched,
Кажется, вся суть этого контейнера в том, что бы предоставить стандартизированный отступ между кнопками. Если отступ кастомный, то люди могут просто сами сверстать контейнер. Вроде не рокет-саенс. Ну и отступы как раз можно перебить переменными, если сильно захотеть

2022-02-22 09:43 UTC, inomdzhon commented on src/components/Button/Button.tsx
> +          ["Button--stretched"]: buttonGroupContext?.stretched || stretched,
Вчера, на дизайнерском синке, предлагал не использовать передачу числа, но сказали, что такую возможность оставить надо

А так смогли расширить enum'ы, чтобы покрыть необходимые кейсы

2022-03-05 15:26 UTC, ArthurStam approved these changes

2022-03-10 08:59 UTC, merged

2022-04-20 12:55 UTC, inomdzhon commented
close https://github.com/VKCOM/VKUI/issues/885