HorizontalScroll.tsx: default getScrollPosition
VKCOM/VKUI pull request #2300
Opened 2022-03-16 07:47 UTC by SevereCloud

Добавляет стандартную прокрутку для стрелок, равную `offsetWidth`

This closed #2032

2022-04-11 10:31 UTC, eugpoloz commented on src/components/HorizontalScroll/HorizontalScroll.tsx
> +              ((i: number) => i - scrollerRef.current!.offsetWidth);
Все супер, есть предложение вытащить `getScrollPosition` здесь и ниже наверх как `scrollPositionLeft` и `scrollPositionRight`, чтобы в onClick только `onClick={() => scrollTo(scrollPositionLeft)}` и `onClick={() => scrollTo(scrollPositionRight)}` оставались. 😉

2022-04-11 11:56 UTC, SevereCloud commented on src/components/HorizontalScroll/HorizontalScroll.tsx
> +              ((i: number) => i - scrollerRef.current!.offsetWidth);
Готово

2022-04-11 12:01 UTC, eugpoloz approved these changes

2022-04-13 15:20 UTC, stoope requested changes

2022-04-13 15:20 UTC, stoope commented on src/components/HorizontalScroll/HorizontalScroll.tsx
> +          onClick={() => scrollTo(scrollPositionRight)}
Давай обернем в `useCallback` что бы `HorizontalScrollArrow` лишний раз не рендерился, там внутри тяжелый `Tappable`

2022-04-13 15:23 UTC, inomdzhon requested changes

2022-04-13 15:23 UTC, inomdzhon commented on src/components/HorizontalScroll/HorizontalScroll.tsx
> +  const scrollPositionLeft =
Если в пропах указать вот так
```
getScrollToLeft = ((i: number) => i - scrollerRef.current!.offsetWidth),
getScrollToRight = ((i: number) => i + scrollerRef.current!.offsetWidth),
```
то не сработает?

2022-04-13 16:04 UTC, stoope approved these changes

2022-04-13 16:06 UTC, inomdzhon approved these changes

2022-04-13 16:09 UTC, merged

2022-04-14 06:06 UTC, fedorov-xyz commented on src/components/HorizontalScroll/HorizontalScroll.tsx
> +          onClick={() => scrollTo(scrollPositionRight)}
А разве компонент стрелки мемоизированный?