Text: tokenized
VKCOM/VKUI pull request #2331
Opened 2022-03-31 07:32 UTC by ArthurStam

- Перевод на токены
- Переход на именованные экспорты

2022-03-31 16:22 UTC, inomdzhon approved these changes

2022-04-11 10:45 UTC, inomdzhon commented on src/components/Button/Button.tsx
> +        return <Text weight="1" {...restProps} />;
А разве не `weight="2"`?

Типа `"medium" === "2"`

2022-04-11 10:45 UTC, inomdzhon commented on src/components/Button/Button.tsx
> +      return <Text weight="1" {...restProps} />;
А разве не `weight="2"`?

Типа `"medium" === "2"`

2022-04-11 10:45 UTC, inomdzhon commented on src/components/Typography/Text/Text.tsx
> +   * > ⚠️ Начертания `"semibold"`, `medium` и `"regular"` устарели и будут удалены в 5.0.0. Используйте значения `"1"`, `"2"` и `"3"`.
```suggestion
   * > ⚠️ Начертания `"regular"`, `medium` и `"semibold"` устарели и будут удалены в 5.0.0. Используйте значения `"1"`, `"2"` и `"3"`.
```

чтобы было соответствие

2022-04-11 10:45 UTC, inomdzhon commented on src/components/Typography/Text/Text.e2e.tsx
> +        weight: ["3", "2", "1"],
Так как было `"regular", "medium", "semibold"`, кажется должно быть `"1", "2", "3"`

2022-04-11 10:45 UTC, inomdzhon commented on src/components/Counter/Counter.tsx
> +    <Text weight="1" {...restProps} />
А разве не `weight="2"`?

Типа `"medium" === "2"`

2022-04-11 10:45 UTC, inomdzhon commented on src/components/Typography/Text/Text.css
> +  font-weight: var(--vkui--font_weight_accent1);
У меня голова взорвалась...

В `vkui-tokens`

- `--vkui--font_weight_accent1` это `600`
- `--vkui--font_weight_accent2` это `500`
- `--vkui--font_weight_accent3` это `400` 

Разве не должно быть тогда

```
.Text--w-1 {
  font-weight: var(--vkui--font_weight_accent3);
}

.Text--w-2 {
  font-weight: var(--vkui--font_weight_accent2);
}

.Text--w-3 {
  font-weight: var(--vkui--font_weight_accent1);
}
```
?

Ещё момент, что `--vkui--font_text--font_weight--regular` тоже `400`, получается в `.Text--w-1` смысла нет, не?

2022-04-11 10:45 UTC, inomdzhon commented on src/components/MiniInfoCell/MiniInfoCell.tsx
> +        weight={mode === "more" ? "1" : undefined}
Если `"medium" === "2"`, то должно быть `"2"`

2022-04-11 10:45 UTC, inomdzhon commented on src/components/PanelHeader/PanelHeader.tsx
> +          <Text weight="1">{children}</Text>
А разве не `weight="2"`?

Типа `"medium" === "2"`

2022-04-11 10:45 UTC, inomdzhon commented on src/components/PanelHeaderContent/PanelHeaderContent.tsx
> +      <Text Component="div" weight="1">
А разве не `weight="2"`?

Типа `"medium" === "2"`

2022-04-11 10:45 UTC, inomdzhon commented on src/components/RichCell/RichCell.tsx
> +        <Text weight="1" vkuiClass="RichCell__content">
А разве не `weight="2"`?

Типа `"medium" === "2"`

2022-04-11 10:45 UTC, inomdzhon commented on src/components/SegmentedControl/SegmentedControlOption/SegmentedControlOption.tsx
> +      <Text vkuiClass="SegmentedControlOption__content" weight="1">
А разве не `weight="2"`?

Типа `"medium" === "2"`

2022-04-11 10:45 UTC, inomdzhon commented on src/components/SliderSwitch/SliderSwitchButton.tsx
> +      <Text weight="1">{children}</Text>
А разве не `weight="2"`?

Типа `"medium" === "2"`

2022-04-11 10:45 UTC, inomdzhon commented on src/components/PanelHeaderButton/PanelHeaderButton.tsx
> +  return <Text weight={platform === VKCOM ? undefined : "1"}>{children}</Text>;
Если `"medium" === "2"`, то должно быть `"2"`

2022-04-11 10:59 UTC, eugpoloz commented on src/components/Typography/Text/Text.css
> +  font-weight: var(--vkui--font_weight_accent1);
> Разве не должно быть тогда

Оййй, не-не, если в токене числа `accent` и `weight` в компоненте не будут соответствовать, мы вообще кукухой поедем все коллективно.))) Так что пусть `weight="1"` остается самым жирным и дальше по ниспадающей.

> Ещё момент, что `--vkui--font_text--font_weight--regular` тоже `400`, получается в `.Text--w-1` смысла нет, не?

По идее каждый из этих токенов может поменяться, так что я бы оставила (по аналогии с другими типографическими компонентами).

2022-04-11 12:00 UTC, inomdzhon commented on src/components/Typography/Text/Text.css
> +  font-weight: var(--vkui--font_weight_accent1);
Ааа, теперь понял в чём прикол
Спасибо за разъяснение)

2022-04-11 14:14 UTC, inomdzhon submitted a review, later dismissed

2022-04-12 09:55 UTC, SevereCloud commented
В некоторых компонентах используются старые `weight`:
- `NativeSelect`
- `SelectMimicry`
- `Radio`
- `TabsItem`

2022-04-14 11:39 UTC, eugpoloz commented
@SevereCloud спасибо тебе за внимательность! Это потому что там используется `Headline`, который пока не переехал на новые веса.

2022-04-15 14:32 UTC, inomdzhon commented
Судя по скриншотным тестам, для `ios` и `android` размер шрифта изменился
А для `vkcom` в некоторых местах начертание

Это ок?

2022-04-15 14:35 UTC, eugpoloz commented
@inomdzhon по дизайн-ревью Валера сказал, что проблема только с шапкой календаря. Я думала, что внедрение Paragraph ее решит, но почему-то нет. Буду разбираться. 🤪

2022-04-19 11:53 UTC, inomdzhon approved these changes

2022-04-19 15:19 UTC, eugpoloz commented
Поняла наконец, в чем проблема с календарем, жду консультации дизайна.

2022-05-25 11:53 UTC, SevereCloud commented on src/components/PanelHeader/PanelHeader.tsx
> -      {separator && platform === VKCOM && <Separator wide />}
Сепаратор потерялся

2022-05-25 12:00 UTC, eugpoloz commented on src/components/PanelHeader/PanelHeader.tsx
> -      {separator && platform === VKCOM && <Separator wide />}
Вернула его пониже:

https://github.com/VKCOM/VKUI/pull/2331/files#diff-1a3a5df92455a585abe47669967863981e1148c5742bfe68d5d1368faeb2dd2dR127-R131

2022-05-25 12:06 UTC, SevereCloud commented
https://github.com/VKCOM/VKUI/blob/6a1dc13776677cf5d8eb22eb4bcb1fcd8a12d74a/src/components/CustomSelect/Readme.md?plain=1#L232-L238

2022-05-25 19:54 UTC, stoope submitted a review, later dismissed

2022-05-25 20:10 UTC, SevereCloud requested changes
Сломался сепаратор для VKCOM в <PanelHeader fixed />

2022-05-25 20:10 UTC, SevereCloud commented on src/components/PanelHeader/PanelHeader.tsx
> -      {separator && platform === VKCOM && <Separator wide />}
Нужно вернуть назад -- в VKCOM сепаратор при фиксированном заголовке тоже зафиксирован

2022-05-25 20:10 UTC, SevereCloud commented on src/components/Typography/Text/Text.css
> -  font-weight: 500;
А что насчет обратной совместимости

2022-05-25 21:39 UTC, eugpoloz commented on src/components/PanelHeader/PanelHeader.tsx
> -      {separator && platform === VKCOM && <Separator wide />}
Ууу, этот сепаратор. 😡

2022-05-25 21:57 UTC, eugpoloz commented on src/components/Typography/Text/Text.css
> -  font-weight: 500;
Это платформенный стиль, по чеклисту мы их убираем.

2022-05-25 22:15 UTC, eugpoloz commented on src/components/PanelHeader/PanelHeader.tsx
> -      {separator && platform === VKCOM && <Separator wide />}
➕

2022-05-26 04:55 UTC, SevereCloud approved these changes

2022-05-26 07:04 UTC, inomdzhon approved these changes

2022-05-26 10:09 UTC, merged