Move from date-fns to dayjs
VKCOM/VKUI pull request #2353
Opened 2022-04-05 15:15 UTC by NekR

2022-04-06 06:44 UTC, inomdzhon commented on src/lib/date.ts
> +  // @ts-ignore
а на что жалуется?

2022-04-06 06:44 UTC, inomdzhon commented on src/lib/calendar.ts
> +  const start = startOfWeek(startOfMonth(viewDate), weekStartsOn);
У https://date-fns.org/v2.28.0/docs/startOfWeek объектом сделано, чтобы была возможность локаль передавать

Может тоже сохранить такую возможность?

2022-04-06 06:44 UTC, inomdzhon commented on src/lib/date.ts
> +  day.$locale().weekStart = weekStart;
в доке не смог найти эту тему 🤔 

вот тут https://day.js.org/docs/en/customization/customization только про `weekStart` упоминание

2022-04-06 06:44 UTC, inomdzhon commented on src/components/Calendar/Readme.md
> +          {format(value, "YYYY-MM-DD HH:mm:ss")}
Если придерживаться ISO 8601, то надо и `HH` прописными указывать `hh`

2022-04-06 12:43 UTC, stoope requested changes

2022-04-06 12:43 UTC, stoope commented on src/lib/date.ts
> +}
Разобраться сложно, надеюсь на тесты)

2022-04-06 14:56 UTC, NekR commented on src/lib/date.ts
> +  // @ts-ignore
Нет такого типа, внутреннее свойство. Там подписано что hacks

2022-04-06 14:57 UTC, NekR commented on src/lib/calendar.ts
> +  const start = startOfWeek(startOfMonth(viewDate), weekStartsOn);
Там в каждом методе можно. У нас нет такой потребности. Локаль рулится отдельно всегда. Так что эти функции ничего не учитывают о локале

2022-04-06 14:57 UTC, NekR commented on src/lib/date.ts
> +  day.$locale().weekStart = weekStart;
Видимо не описывают свои внутренности)

2022-04-06 14:58 UTC, NekR commented on src/components/Calendar/Readme.md
> +          {format(value, "YYYY-MM-DD HH:mm:ss")}
У каждой либы свой подход к этим символом. Если сильно хочется, то можно поменять на hh

2022-04-06 15:25 UTC, NekR commented on src/components/Calendar/Readme.md
> +          {format(value, "YYYY-MM-DD HH:mm:ss")}
У dayjs формат HH для 24 часов. Думаю будет только хуже если будет отличаться от либы что используем. https://day.js.org/docs/en/display/format
Но да, по спеке было бы идеально.

2022-04-06 15:39 UTC, stoope approved these changes

2022-04-07 10:11 UTC, inomdzhon approved these changes

2022-04-13 15:50 UTC, satandyh approved these changes
only to package.json and yarn.lock

2022-04-14 12:28 UTC, merged