Deprecate Separator
VKCOM/VKUI pull request #2359
Opened 2022-04-07 07:54 UTC by SevereCloud

## Примеры

Замена `<Separator />` на `<Spacing />`

- [x]  [CardGrid](https://vkcom.github.io/VKUI/#/CardGrid)
- [x]  [MiniInfoCell](https://vkcom.github.io/VKUI/#/MiniInfoCell)
- [x]  [Placeholder](https://vkcom.github.io/VKUI/#/Placeholder)
- [x]  [SplitLayout](https://vkcom.github.io/VKUI/#/SplitLayout)

В примерах которые использовали `<Separator wide />`, был добавлен border

- [x]  [FixedLayout](https://vkcom.github.io/VKUI/#/FixedLayout)
- [x]  [WriteBar](https://vkcom.github.io/VKUI/#/WriteBar)

## Компоненты

Замена `<Separator />` на `<Spacing />`

- [x]  [Group](https://vkcom.github.io/VKUI/#/Group)
- Сепаратор между элементами был высотой `17`, стал `16`
- [x]  [Search](https://vkcom.github.io/VKUI/#/Search)
- [x]  [PanelHeader](https://vkcom.github.io/VKUI/#/PanelHeader)
- Высота PanelHeader была `61`, стала `60`, по дизайну `56` :thinking: 
- [x]  [ModalPageHeader](https://vkcom.github.io/VKUI/#/ModalPageHeader)

## Прочее

- [x]  TableOfContets
- Убраны лишние классы

---

#2322

2022-04-07 12:18 UTC, SevereCloud commented
![image](https://user-images.githubusercontent.com/14944123/162188263-61b1b638-2d7e-4d5c-a8b0-d03906d23b5e.png)
Думаю, что высоту надо бы подправить

2022-04-07 12:48 UTC, eugpoloz commented
@SevereCloud да, хорошо бы подогнать!

2022-04-08 08:29 UTC, inomdzhon commented
Можешь, плиз, сразу поправить `// eslint-disable-next-line vkui/no-object-expression-in-arguments` в файлах, которые ты затронул? По diff'у я 8 вхождения насчитал

2022-04-08 09:43 UTC, inomdzhon requested changes

2022-04-08 09:43 UTC, inomdzhon commented on src/components/ModalPageHeader/ModalPageHeader.tsx
>        // eslint-disable-next-line vkui/no-object-expression-in-arguments
Забыль удалить 😃

2022-04-08 09:43 UTC, inomdzhon commented on src/components/Search/Search.tsx
>        // eslint-disable-next-line vkui/no-object-expression-in-arguments
И туть

2022-04-08 09:47 UTC, SevereCloud commented
Насчитал 6 + 3 класса в стайлгаде

2022-04-08 09:50 UTC, inomdzhon commented
Сейчас на стайлгад не распространяется это правило `vkui/no-object-expression-in-arguments`, поэтому там не обязательно менять в дальнейшем
Но обсуждаемо

2022-04-12 20:24 UTC, eugpoloz requested changes
Склонна согласиться с комментом Игоря из предыдущего PR: замена `<Separator wide />` на `border` не выглядит полноценной. Предлагаю посоветоваться с дизайнерами.

2022-04-12 20:24 UTC, eugpoloz commented on src/components/Separator/Separator.tsx
> +const Separator: React.FC<SeparatorProps> = React.memo(
Предлагаю не переносить обертку в `React.memo()` сюда. Мы все равно вынесем компонент в следующей итерации библиотеки, смысла как-то его улучшать нет, засунуть варнинг — более чем достаточно. 😉

2022-04-12 20:32 UTC, fedorov-xyz commented
А напомните, почему решили отказаться от `<Separator />`? Кажется, что оба этих компонента могут существовать рядом. К тому же Separator более легковесный, чем `<Spacing />` с какой-то логикой и даже `flex`-контейнером внутри.

2022-04-12 20:38 UTC, eugpoloz commented
@fedorov-xyz я не в курсе, к сожалению, только увидела, что в доке его уже не советуют использовать и что на его замену должен прийти `Spacing`. Поэтому и предлагаю сходить к дизайну и поднять вопрос, мне тоже кажется, что сейчас они как-то не очень взаимозаменяемы.

2022-04-12 20:40 UTC, fedorov-xyz commented
Пока что выглядит, будто в доку написали случайно (?). И хотя уже много работы сделано в этом PR, я бы предложил не спешить с выпиливанием сепаратора.

2022-05-19 11:36 UTC, eugpoloz commented on src/components/Spacing/Spacing.css
> +  padding-right: var(--vkui--size_base_padding_horizontal--regular);
А зачем `Spacing` паддинги? Может, ну их?

2022-05-19 11:36 UTC, eugpoloz commented on src/components/Separator/Separator.css
> +}
Если избавимся от паддингов внутри `Spacing`, то это все не нужно будет. 😉

2022-05-19 11:36 UTC, eugpoloz commented on src/components/Separator/Separator.tsx
> +      vkuiClass={classNames("Separator", wide && "Separator--wide")}
```suggestion
      vkuiClass={classNames("Separator", !wide && "Separator--padded")}
```

Тогда мы сможем в стилях избавиться от `:not`. Что скажешь?

2022-05-19 11:36 UTC, eugpoloz commented on src/components/Separator/Separator.tsx
> +export const Separator: React.FC<SeparatorProps> = React.memo(
А для чего мы вообще заворачиваем `Separator` в `React.memo`? Не лишняя ли это оптимизация?

2022-05-19 11:46 UTC, SevereCloud commented on src/components/Spacing/Spacing.css
> +  padding-right: var(--vkui--size_base_padding_horizontal--regular);
Нужны для свойства separator в Spacing. В v5 избавимся от них

2022-05-19 11:51 UTC, eugpoloz commented on src/components/Spacing/Spacing.css
> +  padding-right: var(--vkui--size_base_padding_horizontal--regular);
Точно! Давай тогда комменты с TODO тут и в `Separator` ниже накинем, чтобы не забыть?

2022-05-19 11:59 UTC, SevereCloud commented on src/components/Separator/Separator.tsx
> +      vkuiClass={classNames("Separator", wide && "Separator--wide")}
- добавил `Separator--padded`
- `Separator--wide` оставил, выпилим в v5

2022-05-19 11:59 UTC, SevereCloud commented on src/components/Separator/Separator.css
> +}
Избавился от этого куска кода

2022-05-19 12:00 UTC, SevereCloud commented on src/components/Spacing/Spacing.css
> +  padding-right: var(--vkui--size_base_padding_horizontal--regular);
Выделил отступы для класса `.Spacing--separator`. Класс уйдет вместе со свойством в v5

2022-05-19 14:48 UTC, inomdzhon approved these changes

2022-05-23 07:42 UTC, eugpoloz approved these changes

2022-05-23 07:42 UTC, merged