Docs typo
VKCOM/VKUI pull request #2369
Opened 2022-04-10 08:57 UTC by SevereCloud

2022-04-11 08:42 UTC, inomdzhon submitted a review, later dismissed

2022-04-15 12:38 UTC, inomdzhon submitted a review, later dismissed

2022-04-15 12:42 UTC, eugpoloz requested changes

2022-04-15 12:42 UTC, eugpoloz commented on src/lib/classNames.test.ts
> +  it("filters out false values", () =>
```suggestion
  it("filters out falsy values", () =>
```

См. https://developer.mozilla.org/en-US/docs/Glossary/Falsy

2022-04-15 12:42 UTC, eugpoloz commented on src/components/Button/Button.css
> + * TODO Сейчас стиль сохранён для обратной совместимости. Удалить в следующей мажорной версии.
```suggestion
 * TODO Сейчас стиль сохранён для обратной совместимости. Удалить в 5.0.0.
```
Раз уж влезли сюда, предлагаю поменять еще и вот эту штуку, чтобы можно было грепнуть потом всё по `5.0.0`. 😉

2022-04-15 12:42 UTC, eugpoloz commented on src/components/CustomSelect/CustomSelect.tsx
> +            // TODO Ожидается, что клик поймает нативный select, но его перехватывает Input. К сожалению, это приводит конфликтам типизации.
```suggestion
            // TODO Ожидается, что клик поймает нативный select, но его перехватывает Input. К сожалению, это приводит к конфликтам типизации.
```

2022-04-15 14:26 UTC, inomdzhon approved these changes

2022-04-18 10:46 UTC, eugpoloz approved these changes

2022-04-18 10:46 UTC, merged