fix: add onlyVariablesLocal.css for vkBase
VKCOM/VKUI pull request #2404
Opened 2022-04-17 10:58 UTC by SevereCloud

Fixes #2393

2022-04-18 07:27 UTC, inomdzhon requested changes

2022-04-18 07:27 UTC, inomdzhon commented on src/styles/themes.css
> +@import "../../node_modules/@vkontakte/vkui-tokens/themes/vkBase/cssVars/declarations/onlyVariablesLocal.css";
На `0.5%` увеличивается размер бандла

Как на счёт вот тут

https://github.com/VKCOM/VKUI/blob/29e99ec2620fd4e4a64e193ca006b206b5c0e0d5/postcss.config.js#L31-L40

указать `customPropRoot: ":root, .vkui__root, .vkui__portal-root"`?

2022-04-18 07:45 UTC, SevereCloud commented on src/styles/themes.css
> +@import "../../node_modules/@vkontakte/vkui-tokens/themes/vkBase/cssVars/declarations/onlyVariablesLocal.css";
Оно тут по другой причине

2022-04-18 07:59 UTC, inomdzhon commented on src/styles/themes.css
> +@import "../../node_modules/@vkontakte/vkui-tokens/themes/vkBase/cssVars/declarations/onlyVariablesLocal.css";
Риал ток!
Поторопился с предложением, сорри

2022-04-18 08:38 UTC, inomdzhon commented on src/styles/themes.css
> +@import "../../node_modules/@vkontakte/vkui-tokens/themes/vkBase/cssVars/declarations/onlyVariablesLocal.css";
@SevereCloud раз ты пишешь плагин, как тебе вот такое упрощение

```js
extendSelectorsWith({
  newSelectors: [":root"],
  cssFilePath: [path.resolve( "./node_modules/@vkontakte/vkui-tokens/themes/vkBase/cssVars/declarations/onlyVariablesLocal.css" )],
});
```

Который делает так
```
// before
.vkui--vkBase--light { ... }

// after
:root, .vkui--vkBase--light { ... }
```

2022-05-23 20:27 UTC, SevereCloud commented on src/styles/themes.css
> +@import "../../node_modules/@vkontakte/vkui-tokens/themes/vkBase/cssVars/declarations/onlyVariablesLocal.css";
Path | Size
-- | --
CSS (gzip) | 37.79 KB (-0.01% 🔽)
CSS (brotli) | 30.67 KB (+0.07% 🔺)

fix

2022-05-24 07:39 UTC, inomdzhon approved these changes
🚀

2022-05-24 07:40 UTC, inomdzhon commented
Интересно, почему brotli увеличился))

2022-05-24 07:40 UTC, merged