feat(ConfigProvider): add color-scheme
VKCOM/VKUI pull request #2437
Opened 2022-04-25 16:53 UTC by SevereCloud

Добавляем `color-scheme` на документ для окрашивания скроллбаров

2022-04-26 09:40 UTC, inomdzhon commented on src/components/ConfigProvider/ConfigProvider.tsx
> +  }, [derivedAppearance]);
Почему бы в предыдущий `useEffect` не перенести?

2022-04-26 11:36 UTC, SevereCloud commented on src/components/ConfigProvider/ConfigProvider.tsx
> +  }, [derivedAppearance]);
Он получается запутанным, поэтому сделал отдельно

2022-04-26 11:37 UTC, stoope requested changes

2022-04-26 11:37 UTC, stoope commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    document?.documentElement.style.setProperty(
В `useEffect` можно использовать `document!.documentElement` что бы не раздувать бандл

2022-04-26 11:41 UTC, stoope submitted a review, later dismissed

2022-04-26 12:36 UTC, inomdzhon approved these changes

2022-04-26 14:28 UTC, SevereCloud commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    document!.documentElement.style.setProperty(
Хм, думаю да. Добавлю еще на .vkui__root `color-scheme: var(--vkui--colors_scheme)`

2022-04-26 14:33 UTC, SevereCloud commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    document!.documentElement.style.setProperty(
Хотя с другой стороны здесь же мы устанавливаем схему и классы на `body`, что также может конфликтовать

2022-04-26 14:35 UTC, fedorov-xyz commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    document!.documentElement.style.setProperty(
Кажется, color-scheme на vkui_root не очень поможет покрасить скроллбары на документе, если полное встраивание. Покрасит только всякие элементы форм.

2022-04-26 14:42 UTC, SevereCloud commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    document!.documentElement.style.setProperty(
color-scheme действительно нужно ставить на документ. Просто я думаю еще про переопределение темы

2022-04-27 06:39 UTC, SevereCloud commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    document!.documentElement.style.setProperty(
Перетащил в [AppRoot.tsx](https://github.com/VKCOM/VKUI/pull/2437/files#diff-299fcdd669d66db53e39043ceb322b86bc59fd5947bb2cc64b7f81be11e4a4bf) и сделал проверку на полное встраивание

2022-04-29 11:27 UTC, merged