Перевод англоязычных варнингов на русски
VKCOM/VKUI pull request #2439
Opened 2022-04-26 16:08 UTC by SevereCloud

- [x] ActionSheet
- [x] ActionSheetDropdownDesktop
- [x] AppRoot
- [x] ConfigProvider
- [x] CustomSelect
- [x] Epic
- [x] ModalRoot
- [x] useModalManager
- [x] SimpleCheckbox
- [x] Tooltip
- [x] Text
- [x] lib/getNavId

Closed #2312

2022-04-26 16:23 UTC, stoope commented on src/components/Epic/Epic.tsx
> +      "При viewWidth < SMALL_TABLET в Epic всегда должен быть передан Tabbar"
Давай напишем `при ширине окна менее 768px` вместо `viewWidth < SMALL_TABLET`

2022-04-26 16:23 UTC, stoope commented on src/components/AppRoot/AppRoot.tsx
> +        warn(`mode="${mode}" отменяет embedded режим`);
Мне кажется больше подходит `перезаписывает` вместо `отменяет`

2022-04-26 16:23 UTC, stoope commented on src/components/ActionSheet/ActionSheet.tsx
> +    warn("требуется передать onClose для обработки закрытия изнутри", "error");
Давай напишем с заглавной буквы для консистентности.
И наверное понятнее будет  `Требуется передать onClose для возможности закрытия ActionSheet`

2022-04-26 16:24 UTC, SevereCloud commented on src/components/Epic/Epic.tsx
> +      "При viewWidth < SMALL_TABLET в Epic всегда должен быть передан Tabbar"
У нас это прямо в документации так написано

2022-04-26 16:34 UTC, eugpoloz requested changes
Кайф!

2022-04-26 16:34 UTC, eugpoloz commented on src/components/Epic/Epic.tsx
> +      "При viewWidth < SMALL_TABLET в Epic всегда должен быть передан Tabbar"
```suggestion
      "При viewWidth < SMALL_TABLET использование Epic без Tabbar не рекомендуется"
```

2022-04-26 16:34 UTC, eugpoloz commented on src/components/ModalRoot/ModalRoot.tsx
> +          `closeActiveModal: модальное окно(страница) ${id} не существует`,
```suggestion
          `closeActiveModal: модальное окно (страница) ${id} не существует`,
```

2022-04-26 16:34 UTC, eugpoloz commented on src/components/ModalRoot/useModalManager.tsx
> +        `Переход невозможен - модальное окно(страница) ${activeModal} не существует`,
```suggestion
        `Переход невозможен - модальное окно (страница) ${activeModal} не существует`,
```

2022-04-26 16:34 UTC, eugpoloz commented on src/components/Typography/Text/Text.tsx
> +    warn("getRootRef может использоваться только с DOM компонентами", "error");
```suggestion
    warn('"getRootRef" может использоваться только с компонентами DOM', "error");
```

2022-04-26 16:34 UTC, eugpoloz commented on src/components/AppRoot/AppRoot.tsx
> +          `scroll=${scroll} поддерживается только в embedded режиме`,
```suggestion
          `scroll=${scroll} поддерживается только в режиме embedded`,
```

2022-04-26 16:34 UTC, eugpoloz commented on src/components/AppRoot/AppRoot.tsx
> +        warn(`mode="${mode}" отменяет embedded режим`);
Здесь все-таки не совсем про отмену, а про то, что если `mode` и `embedded` переданы одновременно, то `mode` победит.

```suggestion
        warn(`Свойство "mode=${mode}" приоритетнее, чем "embedded"`);
```

2022-04-26 16:34 UTC, eugpoloz commented on src/components/ActionSheet/ActionSheet.tsx
> +    warn("требуется передать onClose для обработки закрытия изнутри", "error");
Тут наоборот — про то, что без `onClose` закрытие по клику _вне_ `ActionSheet` не сработает.

```suggestion
    warn('Без "onClose" нельзя закрыть ActionSheet по клику вне компонента', "error");
```

2022-04-26 16:34 UTC, eugpoloz commented on src/components/ActionSheet/ActionSheet.tsx
> +    warn("Требуется передать onClose для обработки закрытия изнутри", "error");
Тут скорее про то, что по клику снаружи нельзя закрыть.
```suggestion
    warn('Без "onClose" нельзя закрыть ActionSheet по клику вне компонента', "error");
```

2022-04-26 16:34 UTC, eugpoloz commented on src/components/AppRoot/AppRoot.tsx
> +        warn(`mode="${mode}" перезаписывает embedded режим`);
Здесь не совсем про режимы, скорее про то, что одно свойство перебивает другое.
```suggestion
        warn(`Свойство "mode=${mode}" приоритетнее, чем "embedded"`);
```

2022-04-26 16:34 UTC, eugpoloz commented on src/components/CustomSelect/CustomSelect.tsx
> +      "Некоторые значения ваших опций имеют разные типы. CustomSelect onChange всегда возвращает строковый тип.",
Кажется, что тут нет смысла дважды повторять про то, что это `CustomSelect`.
```suggestion
      "Некоторые значения ваших опций имеют разные типы. onChange всегда возвращает строковый тип.",
```

2022-04-26 16:34 UTC, eugpoloz commented on src/components/Epic/Epic.tsx
> +      "При ширине окна менее 768px в Epic всегда должен быть передан Tabbar"
Все-таки не всегда, мы просто не рекомендуем. (%

```suggestion
      `Не рекомендуется использовать Epic без Tabbar при ширине окна меньше ${ViewWidth.SMALL_TABLET}px`
```

2022-04-27 10:27 UTC, eugpoloz approved these changes

2022-04-27 11:07 UTC, merged