Move SizeX to css media queries
VKCOM/VKUI pull request #2444
Opened 2022-04-27 09:38 UTC by stoope

Планирую потихоньку отказываться от вычислений относительно `window`, в этом пр переделал SizeX.
Спорные моменты:

1. В некоторых местах получилось не очень "красиво", я думаю этого можно избежать в будущем если делать компоненты изначально на `css media queries`
2. В `css` получилось некоторое дублирование стилей, это ок или можно как то избежать? Например, заюзать что-то вроде `@mixin scss`?
3. Насколько хороший способ перебивать адаптивность через классы `Component--sizeX-...`? Может есть другая идея как можно форсить адаптивность переданную через 'AdaptivityProvider'?

2022-04-27 09:39 UTC, fedorov-xyz commented
> Например, заюзать что-то вроде @mixin scss

Нет, давайте, пожалуйста, без препроцессоров. В vk.com от них избавиться не можем.

2022-04-27 10:29 UTC, eugpoloz commented
По скринам ActionSheet поломался.

2022-04-27 17:15 UTC, eolme commented on src/helpers/getSizeXClassName.ts
> +  return `${base}--sizeX-${sizeX}`;
`sizeX || 'none'`

2022-05-04 12:00 UTC, inomdzhon commented
Может [custom-media-queries](https://preset-env.cssdb.org/features/#custom-media-queries) сразу завести?

Вот media queries на примере рефактора `AdaptivityProvider` #2311 ([инициализация](https://github.com/VKCOM/VKUI/blob/3e7672f4e4180fffb5966f709a672bd7cbbaf9ac/src/components/AdaptivityProvider/AdaptivityProvider.tsx#L51-L61), [константы](https://github.com/VKCOM/VKUI/blob/3e7672f4e4180fffb5966f709a672bd7cbbaf9ac/src/components/AdaptivityProvider/constants.ts));

```
@custom-media --desktop-only (min-width: 1280px);

@custom-media --tablet-only (min-width: 1024px) and (max-width: 1279px);

@custom-media --small-tablet-only (min-width: 768px) and (max-width: 1023px);

@custom-media --mobile-only (min-width: 320px) and (max-width: 767px);

@custom-media --medium-height (min-height: 720px);

@custom-media --mobile-landscape-height (min-height: 415px) and (orientation: landscape);

@media (--small-tablet-only) {}
```

2022-05-04 13:31 UTC, stoope commented
> Может [custom-media-queries](https://preset-env.cssdb.org/features/#custom-media-queries) сразу завести?
> 
> Вот media queries на примере рефактора `AdaptivityProvider` #2311 ([инициализация](https://github.com/VKCOM/VKUI/blob/3e7672f4e4180fffb5966f709a672bd7cbbaf9ac/src/components/AdaptivityProvider/AdaptivityProvider.tsx#L51-L61), [константы](https://github.com/VKCOM/VKUI/blob/3e7672f4e4180fffb5966f709a672bd7cbbaf9ac/src/components/AdaptivityProvider/constants.ts));
> 
> ```
> @custom-media --desktop-only (min-width: 1280px);
> 
> @custom-media --tablet-only (min-width: 1024px) and (max-width: 1279px);
> 
> @custom-media --small-tablet-only (min-width: 768px) and (max-width: 1023px);
> 
> @custom-media --mobile-only (min-width: 320px) and (max-width: 767px);
> 
> @custom-media --medium-height (min-height: 720px);
> 
> @custom-media --mobile-landscape-height (min-height: 415px) and (orientation: landscape);
> 
> @media (--small-tablet-only) {}
> ```

Перевел, спасибо)

2022-05-04 14:09 UTC, stoope commented
link #2350

2022-05-05 11:18 UTC, saakovv approved these changes
+

2022-05-05 14:16 UTC, inomdzhon reviewed
Необходима документация как делать адаптивность через `css media queries` 🤔 

Не совсем это норм, что

встречается вот такое
```css
@media (--size-x-compact) {
  .block {}
}
```

и такое
```css
@media (--size-x-compact) {
  .block--sizeY-none {}
}
```

поэтому пока текущие комменты засабмичу, чтобы разобраться

Заранее спасибо за пояснение всех моментов 🙏

2022-05-05 14:16 UTC, inomdzhon commented on src/components/Card/Card.css
> +  .Group--none .CardScroll--l .Card:last-of-type {
Похоже, что не хватает `Group--sizeX-none` 🤔

2022-05-05 14:16 UTC, inomdzhon commented on src/components/CardGrid/CardGrid.css
> +  .CardGrid--sizeX-none {
Не совсем понял этот момент

`*--sizeX-none` работает и для `@media (--size-x-compact)`, и для `@media (--size-x-regular)`?

2022-05-05 14:16 UTC, inomdzhon commented on src/components/CardGrid/CardGrid.css
> +  .CardGrid--android:not(.CardGrid--sizeX-regular) {
если `.CardGrid--sizeX-none`, то `:not` не нужен, не?

2022-05-05 14:16 UTC, inomdzhon commented on src/components/CardScroll/CardScroll.css
> +  .Group--none .CardScroll--withSpaces {
`.Group--sizeX-none`?

2022-05-05 15:44 UTC, stoope commented on src/components/PanelHeaderBack/PanelHeaderBack.tsx
> -    platform === VKCOM || (platform === IOS && sizeX === SizeType.REGULAR);
Здесь и ниже я удалил любое использование `sizeX` через `js`. Всю логику я перенес на `css`, местами получилось не очевидно но другого выхода я не нашел

2022-05-05 15:49 UTC, stoope commented
> Необходима документация как делать адаптивность через `css media queries` 🤔
> 
> Не совсем это норм, что
> 
> встречается вот такое
> 
> ```css
> @media (--size-x-compact) {
>   .block {}
> }
> ```
> 
> и такое
> 
> ```css
> @media (--size-x-compact) {
>   .block--sizeX-none {}
> }
> ```
> 
> поэтому пока текущие комменты засабмичу, чтобы разобраться
> 
> Заранее спасибо за пояснение всех моментов 🙏

У нас сейчас нет четких правил как использовать `css media queries`, где то есть `--sizeX-none` а где-то нет. Так получилось потому что пришлось переписывать старую логику использования `sizeX` из `js` на `css`, получилось не везде очевидно и однородно. при разработке новых компонентов таких проблем быть не должно если изначально разрабатывать с помощью `css`

2022-05-05 15:52 UTC, stoope commented on src/components/PanelHeaderBack/PanelHeaderBack.css
> +  .PanelHeaderBack--ios.PanelHeaderBack--has-label:not(.PanelHeaderBack--sizeX-compact) {
Нет, тут проверяется именно что не была принудительно задана `sizeX=compact`

2022-05-05 15:53 UTC, stoope commented on src/components/CardGrid/CardGrid.css
> +  .CardGrid--android:not(.CardGrid--sizeX-regular) {
Нет, тут проверяется именно что не была принудительно задана `sizeX=regular`

2022-05-05 15:55 UTC, stoope commented on src/components/CardGrid/CardGrid.css
> +  .CardGrid--sizeX-none {
`*--sizeX-none` означает что `sizeX` не переопределена через `AdaptivityProvider`

2022-05-05 16:06 UTC, inomdzhon commented on src/components/PanelHeader/PanelHeader.tsx
> -  const needShadow = shadow && sizeX === SizeType.REGULAR;
потому что https://github.com/VKCOM/VKUI/pull/2444#discussion_r866051691

2022-05-05 16:14 UTC, inomdzhon commented on src/components/PanelHeaderBack/PanelHeaderBack.tsx
> -    platform === VKCOM || (platform === IOS && sizeX === SizeType.REGULAR);
Ааа вот оно где

https://github.com/VKCOM/VKUI/blob/1106fd7d8365c6eae978d0f2d6bbe0ffda895b72/src/components/PanelHeaderButton/PanelHeaderButton.css#L104-L109

Что-то, конечно, пока ломает голову подход через `css media queries`. Ещё в текущем кейсе условия зависимости от платформы дублируются в JS и в CSS, при том они в разных файлах. Кроме как документить это не вижу вариантов сохранению консистентности 🤔 

Можешь, плиз, добавить коммент в этом месте, которая ведёт на CSS в `PanelHeaderButton`?

PS: Я вчера поторопился с выводами, что всё нравится 😣

2022-05-05 20:20 UTC, stoope commented on src/components/CardGrid/CardGrid.css
> +  .CardGrid--android:not(.CardGrid--sizeX-regular) {
Да, ты прав, давай писать для консистентности `--sizeX-none` а не `:not(.--sizeX-regular)`. Но на практике это одно и тоже, обе записи означают что `sizeX` не установлена в `regular`

2022-05-05 21:02 UTC, stoope commented on src/components/CardGrid/CardGrid.css
> +  .CardGrid--sizeX-none {
> Другой вопрос про текущий кейс. Вижу, что если переда sizeX="compact" в AdaptivityProvider, то мы ещё зависимы от платформы .CardGrid--ios.CardGrid--sizeX-compact
> 
> Почему варианте через media query у нас нет такой зависимости?

Недоглядел, поправил.

С `.Group--none`:
Раньше было 

```ts
  if (!mode) {
    computedMode =
      sizeX === SizeType.COMPACT || isInsideModal ? "plain" : "card";
  }
```
а стало

```ts
  if (!mode) {
    computedMode = isInsideModal ? "plain" : "none";
  }
```
 Поэтому появился `.Group--none` который нужно при `sizeX=regular` должен становиться `.Group--card` 😣

2022-05-05 21:07 UTC, stoope commented
@inomdzhon добавил доку по написанию адаптивности, так и правда легче, спасибо!)

2022-05-06 10:55 UTC, inomdzhon requested changes
Извини за очередные вопросы 😣 Теперь понял, что к чему и по другому смотрю на изменения

И спасибо, что разобрался и зафигачил такой рефактор 🙏

2022-05-06 10:55 UTC, inomdzhon commented on src/components/CardGrid/CardGrid.css
> +  .CardGrid--android:not(.CardGrid--sizeX-regular) {
А, ну в этом и был вопрос, т.к. я думал, что есть разница) Пон

2022-05-06 10:55 UTC, inomdzhon commented on src/components/CardGrid/CardGrid.css
> +  .CardGrid--sizeX-none {
😓 ох уже эти сложные компоненты со сложными кейсами 😭

...ну вроде бы вдуплил...

---

Ты написал

> В некоторых местах получилось не очень "красиво", я думаю этого можно избежать в будущем если делать компоненты изначально на css media queries

Я так понимаю это то такое самое место. Ты мог бы эти места собрать, например, в том же `ADAPTIVITY_GUIDE`? В конце документа создать "Примечание" и описать эти моменты? Почему появился `Group--none` и т.п. (это можно допом комментом прописать в TSX файле)

Чем больше инфы сейчас оставим, тем легче будет рефакторить. Хочется избежать ошибок в прошлом, где оставляли мало хлебных крошек, ибо на текущий момент приходится бегать по issues, по аннотациям в git, по чатам, по конфлюенс, чтобы разобраться почему так сделали

2022-05-06 10:57 UTC, inomdzhon commented on src/components/CardGrid/CardGrid.css
> +  .CardGrid--sizeX-none {
😓 ох уже эти сложные компоненты со сложными кейсами 😭

...ну вроде бы вдуплил...

---

Ты написал

> В некоторых местах получилось не очень "красиво", я думаю этого можно избежать в будущем если делать компоненты изначально на css media queries

Я так понимаю это то такое самое место. Ты мог бы эти места собрать, например, в том же `ADAPTIVITY_GUIDE`? В конце документа создать "Примечание" и описать эти моменты? Почему появился `Group--none` и т.п. (это можно допом комментом прописать в TSX файле)

Чем больше инфы сейчас оставим, тем легче будет рефакторить. Хочется избежать ошибок в прошлом, где оставляли мало хлебных крошек, ибо на текущий момент приходится бегать по issues, по аннотациям в git, по чатам, по конфлюенс, чтобы разобраться почему так сделали

2022-05-06 12:51 UTC, stoope commented on src/components/CardGrid/CardGrid.css
> +  .CardGrid--sizeX-none {
Добавил в `ADAPTIVITY_GUIDE` про `Group--none`

2022-05-06 12:52 UTC, stoope commented on ADAPTIVITY_GUIDE.md
> +```
Done

2022-05-06 12:54 UTC, stoope commented on ADAPTIVITY_GUIDE.md
> +Изначально писать адаптивность стоит через `css media queries` но так же следует учитывать то что параметры адаптивности можно переопределить через `AdaptivityProvider`, например:
Done

2022-05-06 12:56 UTC, stoope commented on ADAPTIVITY_GUIDE.md
> +};
Done

2022-05-06 12:57 UTC, stoope commented on ADAPTIVITY_GUIDE.md
> +}
Done

2022-05-06 13:00 UTC, stoope commented on ADAPTIVITY_GUIDE.md
> +# Гайд по написанию адаптивных компонентов
Добавил

2022-05-06 13:07 UTC, stoope commented on src/components/Group/Group.css
> +  .Group--plain.Group--sizeX-none > .Group__separator {
Давай `sizeX` класс будет в начале, поправил во всех местах

2022-05-06 15:11 UTC, stoope commented on src/components/PanelHeaderBack/PanelHeaderBack.tsx
> -    platform === VKCOM || (platform === IOS && sizeX === SizeType.REGULAR);
Добавил

2022-05-06 16:03 UTC, inomdzhon approved these changes

2022-05-06 16:04 UTC, merged