Add auto detection appearance
VKCOM/VKUI pull request #2471
Opened 2022-05-07 19:04 UTC by SevereCloud

Добавляем автоопределение appearance по умолчанию

- [x] Проверяем системную тему через медиа запрос
- [x] Проверяем appearance через vk-bridge
- [ ] Необходимо придумать как **правильно** определять, что мы внутри VK Mini Apps
- [ ] Использовать useAutoAppearance когда это нужно и не нарушать правило хуков

2022-05-08 11:16 UTC, eolme commented on src/hooks/useAppearance.ts
> +const isVKMiniApps = vkBridge.supports("VKWebAppGetConfig");
`bridge.isEmbedded()`

2022-05-08 11:19 UTC, eolme commented
Во избежание мигания лучше отрефачить: сначала показываем по prefers, потом по bridge, и не устанавливать в light по-умолчанию, а только если мы не можем никакими другими способами определить

2022-05-12 02:47 UTC, worldwidebaby commented
Чтобы избежать мигание, лучше запрашивать первоначальное состояние через [VKWebAppGetConfig](https://dev.vk.com/bridge/VKWebAppGetConfig), и вне тела функции. Не у всех пользователей стоит автоматическое определение темы.

2022-05-12 06:00 UTC, worldwidebaby commented on src/hooks/usePrefersColorScheme.ts
> +  const check = useCallback((event: MediaQueryList | MediaQueryListEvent) => {
Зачем кешировать функцию, если она вызывается только внутри эффекта? Предлагаю перенести прямо туда и избавиться от useCallback.

2022-05-19 15:26 UTC, inomdzhon requested changes

2022-05-19 15:26 UTC, inomdzhon commented on src/components/ConfigProvider/ConfigProvider.tsx
> +  appearance: _appearance,
```suggestion
  appearance: appearanceProp,
```
для консистентности

2022-05-19 15:26 UTC, inomdzhon commented on src/components/ConfigProvider/ConfigProvider.tsx
> +  }, [window, _appearance, contextAppearance]);
изменение `contextAppearance` лишь вызывает вызов эффекта, так и задумано?

2022-05-19 15:26 UTC, inomdzhon commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    return autoAppearance(window, setAppearance);
Я бы всё, начиная с `const contextAppearance = useAppearance()` вынес в отдельный файл с хуком `useAutoDetectAppearance()`

2022-05-19 15:26 UTC, inomdzhon commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    .send("VKWebAppGetConfig")
Хммм то, что предложил Антон резонно

> Во избежание мигания лучше отрефачить: сначала показываем по prefers, потом по bridge, и не устанавливать в light по-умолчанию, а только если мы не можем никакими другими способами определить

2022-05-19 15:26 UTC, inomdzhon commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    })
Можно было бы вынести функцию и передать сюда, а в 44 строчке вызывать

2022-05-19 17:21 UTC, worldwidebaby commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    .send("VKWebAppGetConfig")
> то, что предложил Антон резонно

Первый запуск будет мигать для пользователей, у которых клиентская тема расходится с системной. С появлением сплешскрина на вебе, лучше тянуть через VKWebAppGetConfig и потом инициализировать приложение, чтобы избавиться от мигания

2022-05-19 17:47 UTC, SevereCloud commented on src/components/ConfigProvider/ConfigProvider.tsx
> +  }, [window, _appearance, contextAppearance]);
Забыл убрать

2022-05-19 19:07 UTC, SevereCloud commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    })
✅

2022-05-19 19:07 UTC, SevereCloud commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    return autoAppearance(window, setAppearance);
✅

2022-05-19 19:07 UTC, SevereCloud commented on src/components/ConfigProvider/ConfigProvider.tsx
> +  appearance: _appearance,
✅

2022-05-19 19:37 UTC, eolme commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    .send("VKWebAppGetConfig")
Как минимум, vkcom и mvk покрывает

2022-05-20 02:04 UTC, worldwidebaby commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    .send("VKWebAppGetConfig")
> Если привязываться на бридж, то все равно на темной теме может спокойно мигнуть белый экран, если разработчик отправит init раньше, чем VKWebAppGetConfig придет.

Просто нужно поддержать callback, например `<ConfigProvider onAppearanceInit={...} />`.

> И все же, мы так и так через бридж запрашиваем, почему бы не покрыть большинство кейсов?

Можно и нужно для приложений вне фрейма, но опять же, в мини-приложениях это не работает. Маленькое уточнение для того, чтобы не выпили текущее.

2022-05-20 11:25 UTC, inomdzhon commented on src/hooks/useAutoDetectAppearance.tsx
> +  }
как на счёт переместить эту проверку в `useEffect()`?

кмк более явно видим что происходит

```js
if (vkBridge.isEmbedded()) {
    return autoDetectAppearanceBridge(setAppearance);
} esle {
    return autoDetectAppearance(window, setAppearance);
}
```

\+ можно было бы переименовать `autoDetectAppearanceBridge` -> `autoDetectAppearanceByBridge`

2022-05-24 11:40 UTC, ilyapishchulin commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    .send("VKWebAppGetConfig")
Если разработчик вызывает VKWebAppInit слишком рано -- это плохо и решать нужно другим способом, например, выносом инициализации в useEffect или куда-то глубже. На вебе и мвк планируется добавление сплеш скрина, чтобы повторить поведение с клиентами и избежать мигания

2022-05-24 11:49 UTC, SevereCloud commented on src/hooks/useAutoDetectAppearance.tsx
> +  }
Готово

2022-05-24 13:54 UTC, SevereCloud commented on src/hooks/useAutoDetectAppearance.tsx
> +  .finally(noop);
✅

2022-05-31 14:54 UTC, SevereCloud commented on src/components/ConfigProvider/ConfigProvider.tsx
> +    .send("VKWebAppGetConfig")
Добавил callback `onDetectAppearanceByBridge`

2022-05-31 15:44 UTC, SevereCloud commented on src/hooks/useAutoDetectAppearance.tsx
> +  .catch(noop);
✅

2022-05-31 15:46 UTC, inomdzhon approved these changes
🔥 👍 🚀

2022-05-31 15:56 UTC, merged