fix(FixedLayout): revert to 1364 PR number
VKCOM/VKUI pull request #2472
Opened 2022-05-11 13:04 UTC by inomdzhon

<details>
  <summary>Старое описание</summary>

  Поправил центровку при фиксированной ширине.
  
  Здесь #2414 (коммит https://github.com/VKCOM/VKUI/pull/2414/commits/230b4dceacd3b8aa0d66af4db767763cd0130f4e) не учёл это.
  
  Использовал старый добрый метод 😄 
  ```
  left: 0;
  right: 0;
  margin-left: auto;
  margin-right: auto;
  ```

</details>

**UPD**

После изменения https://github.com/VKCOM/VKUI/pull/2414 (коммит https://github.com/VKCOM/VKUI/commit/230b4dceacd3b8aa0d66af4db767763cd0130f4e) в `v4.29.1` сломалась:

1. центровка при фиксированной ширине
    <details>
      <summary>Демо</summary>        

      **Было**
      ![before](https://user-images.githubusercontent.com/5850354/167853306-fc4f704f-fa20-45b1-9ca1-0f7e2726b37f.jpeg)
      
      **Стало**
      ![after](https://user-images.githubusercontent.com/5850354/167853318-cd9335fa-2554-4d14-a8b9-1853b369c2f4.jpeg)
    
    </details>
2. #2475

поэтому ревертнул коммит https://github.com/VKCOM/VKUI/commit/230b4dceacd3b8aa0d66af4db767763cd0130f4e

---

fix #2475

2022-05-11 14:37 UTC, fedorov-xyz commented
Согласен с Антоном. Не хватает скриншотного теста на такое отображение шапки и других FixedLayout'ов.

2022-05-12 12:20 UTC, SevereCloud requested changes
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/14944123/168073077-2eb6e386-754d-4020-b086-726f20334ec9.png">

2022-05-12 18:03 UTC, inomdzhon commented
Ревертнул изменение (поправил описание), т.к. не нашёл способа поправить ситуацию #2475 без брейкинг чендж.

Проблема #2422 не критична.

2022-05-12 18:13 UTC, SevereCloud approved these changes

2022-05-13 09:53 UTC, stoope approved these changes

2022-05-13 09:59 UTC, merged