Move SizeX to css media queries
VKCOM/VKUI pull request #2477
Opened 2022-05-13 08:24 UTC by stoope

link #2350

2022-05-16 10:37 UTC, stoope commented
Скриншотные тесты посмотрел, поведение ожидаемое.

2022-05-18 08:24 UTC, inomdzhon reviewed
Стёпа – ты мощь! 💪

2022-05-18 08:24 UTC, inomdzhon commented on src/components/Button/Button.tsx
> -const ButtonTypography: React.FC<ButtonTypographyProps> = (
`Typography` будем стараться не использовать внутри компонентов, правильно понимаю?

2022-05-18 12:10 UTC, stoope commented on src/components/Button/Button.css
> +.Button--sizeY-regular.Button--sz-s.Button--ios .Button__content {
Спасибо, так лучше) Поправил

2022-05-18 12:11 UTC, stoope commented on src/components/ActionSheetItem/ActionSheetItem.css
> +  margin: 0;
Потому что у типографики в стилях был прописан `margin: 0`. Возможно он не везде нужен но я не добавил на всякий случай)

2022-05-18 12:13 UTC, stoope commented on src/components/Button/Button.tsx
> -const ButtonTypography: React.FC<ButtonTypographyProps> = (
Использование типографики сокращает размер `css` на выходе, поэтому отказываться не вижу смысла. Там где необходимо менять типографику в зависимости от адаптивности пишем токенами

2022-05-18 12:18 UTC, stoope commented on src/components/Separator/Separator.css
> +.PanelHeader--sizeX-regular:not(.PanelHeader--vkcom) .Separator__in {
Пишем `:not(.PanelHeader--vkcom)` когда не нужно менять для платформы `vkcom`) Это место появилось после подлива мастера, после мержа #2479 может поменяться. Не вижу смысла писать такие вещи, если нужно где то исключить `vkcom` то разработчик сам напишет такой селектор.

2022-05-18 12:24 UTC, inomdzhon commented on src/components/ActionSheetItem/ActionSheetItem.css
> +  margin: 0;
Там ожидались теги `h1` и `p` прост)
Тут не вижу смысла их дополнительно прописывать, т.к. `div` и `span` используется

2022-05-18 12:27 UTC, inomdzhon requested changes

2022-05-18 12:27 UTC, inomdzhon commented on src/components/Button/Button.css
> +}
надо поменять местами `sizeY-none` и `sizeY-regular`

2022-05-18 12:39 UTC, stoope commented on src/components/ActionSheetItem/ActionSheetItem.css
> +  margin: 0;
Убрал `margin: 0;` из PR)

2022-05-18 12:44 UTC, eolme commented
Можно объяснить зачем по 2 раза проверяется высота: и на уровне JS, и на уровне CSS -- это какое-то временное решение?

2022-05-18 12:53 UTC, eolme commented
А чем это лучше текущего решения? Мы получили только дублирование кода по сути

2022-05-18 12:54 UTC, stoope commented
> А чем это лучше текущего решения? Мы получили только дублирование кода по сути

Это все ради SSR. В текущей решении оно не работает из-за вычислений относительно window

2022-05-18 13:52 UTC, inomdzhon approved these changes

2022-05-18 13:54 UTC, merged