Switcher: vkui tokens
VKCOM/VKUI pull request #2484
Opened 2022-05-16 08:00 UTC by littlemyx

2022-05-18 11:38 UTC, inomdzhon requested changes
Спасибо за PR 🙏  Оставил пару комментов

2022-05-18 11:38 UTC, inomdzhon commented on package.json
> +    "@vkontakte/vkui-tokens": "^4.10.0",
Подтяни, пожалуйста, мастер, сегодня смержили изменения где уже подняли версию этого пакета

2022-05-18 11:38 UTC, inomdzhon commented on src/components/Switch/Switch.css
> +  background: var(--vkui--color_icon_accent);
Здесь и в 129 строчке нужно сохранить цвета из `appearance`

Подробней в доке [VKUI_TOKENS_MIGRATION_GUIDE -> Промежуточный вариант
](https://github.com/VKCOM/VKUI/blob/v4.31.0/VKUI_TOKENS_MIGRATION_GUIDE.md#%D0%BF%D1%80%D0%BE%D0%BC%D0%B5%D0%B6%D1%83%D1%82%D0%BE%D1%87%D0%BD%D1%8B%D0%B9-%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82)

2022-05-19 06:42 UTC, littlemyx commented on package.json
> +    "@vkontakte/vkui-tokens": "^4.10.0",
готово

2022-05-19 06:42 UTC, littlemyx commented on src/components/Switch/Switch.css
> +  background: var(--vkui--color_icon_accent);
готово

2022-05-19 10:01 UTC, inomdzhon approved these changes

2022-05-19 12:25 UTC, merged

2022-05-19 12:59 UTC, inomdzhon commented
Поторопился с мержем...

@littlemyx меня коллега поправил, что не до конца на `vkui-tokens` перевели :(

Подробности тут https://github.com/VKCOM/VKUI/issues/2498#issuecomment-1131652242