feat(Headline): add vkui-tokens
VKCOM/VKUI pull request #2502
Opened 2022-05-19 16:43 UTC by SevereCloud

Добавлены новые свойства

- `weight: "1" | "2" | "3"`
- `level?: "1" | "2"`

---

Чеклист перевода компонента на vkui-tokens

- [x] В стилях компонента не осталось платформенных селекторов(оставлен для обратной совместимости)
- [x] Если в стилях встречаются токены из Appearance, то их нужно не удалять, а дополнять фоллбэком на соответствующий токен из vkui-tokens
- [x] В tsx компонента не осталось логики, которая зависит от платформы(оставлено для обратной совместимости)
- [x] Компонент добавлен в src/tokenized/index.ts (в src/index.ts он так же должен быть)
- [x] Имя компонента добавлено в массив из styleguide/tokenized.js

---

Компоненты которые имеют Headline внутри

- [ActionSheetItem](https://vkcom.github.io/VKUI/pull/2502/#/ActionSheetItem) ([master](https://vkcom.github.io/VKUI/#/ActionSheetItem))
- [Alert](https://vkcom.github.io/VKUI/pull/2502/#/Alert) ([master](https://vkcom.github.io/VKUI/#/Alert))
- [Banner](https://vkcom.github.io/VKUI/pull/2502/#/Banner) ([master](https://vkcom.github.io/VKUI/#/Banner))
- [Button](https://vkcom.github.io/VKUI/pull/2502/#/Button) ([master](https://vkcom.github.io/VKUI/#/Button))
- [Checkbox](https://vkcom.github.io/VKUI/pull/2502/#/Checkbox) ([master](https://vkcom.github.io/VKUI/#/Checkbox))
- [FormStatus](https://vkcom.github.io/VKUI/pull/2502/#/FormStatus) ([master](https://vkcom.github.io/VKUI/#/FormStatus))
- [Header](https://vkcom.github.io/VKUI/pull/2502/#/Header) ([master](https://vkcom.github.io/VKUI/#/Header))
- [InfoRow](https://vkcom.github.io/VKUI/pull/2502/#/InfoRow) ([master](https://vkcom.github.io/VKUI/#/InfoRow))
- [ModalCardBase](https://vkcom.github.io/VKUI/pull/2502/#/ModalCardBase) ([master](https://vkcom.github.io/VKUI/#/ModalCardBase))
- [NativeSelect](https://vkcom.github.io/VKUI/pull/2502/#/NativeSelect) ([master](https://vkcom.github.io/VKUI/#/NativeSelect))
- [PanelHeaderContent](https://vkcom.github.io/VKUI/pull/2502/#/PanelHeaderContent) ([master](https://vkcom.github.io/VKUI/#/PanelHeaderContent))
- [Placeholder](https://vkcom.github.io/VKUI/pull/2502/#/Placeholder) ([master](https://vkcom.github.io/VKUI/#/Placeholder))
- [Radio](https://vkcom.github.io/VKUI/pull/2502/#/Radio) ([master](https://vkcom.github.io/VKUI/#/Radio))
- [Search](https://vkcom.github.io/VKUI/pull/2502/#/Search) ([master](https://vkcom.github.io/VKUI/#/Search))
- [SelectMimicry](https://vkcom.github.io/VKUI/pull/2502/#/SelectMimicry) ([master](https://vkcom.github.io/VKUI/#/SelectMimicry))
- [SimpleCell](https://vkcom.github.io/VKUI/pull/2502/#/SimpleCell) ([master](https://vkcom.github.io/VKUI/#/SimpleCell))
- [TabsItem](https://vkcom.github.io/VKUI/pull/2502/#/TabsItem) ([master](https://vkcom.github.io/VKUI/#/TabsItem))

---

- closed #2501

2022-05-19 17:11 UTC, eolme commented
Может сделаем weight тоже необязательным?

2022-05-20 10:20 UTC, stoope commented on src/components/ActionSheetItem/ActionSheetItem.tsx
> -                  <Headline weight={mode === "cancel" ? "medium" : "regular"}>
А не `"2" : "3"` как выше?

2022-05-20 10:23 UTC, stoope requested changes

2022-05-20 10:23 UTC, stoope commented on src/components/Header/Header.tsx
> +        return <Headline weight="2" {...restProps} />;
`weight="3"`

2022-05-20 10:34 UTC, SevereCloud commented on src/components/ActionSheetItem/ActionSheetItem.tsx
> -                  <Headline weight={mode === "cancel" ? "medium" : "regular"}>
Да, верно

2022-05-20 10:34 UTC, SevereCloud commented on src/components/Header/Header.tsx
> +        return <Headline weight="2" {...restProps} />;
✅

2022-05-20 10:34 UTC, SevereCloud commented on src/components/ActionSheetItem/ActionSheetItem.tsx
> -                  <Headline weight={mode === "cancel" ? "medium" : "regular"}>
✅

2022-05-20 11:16 UTC, inomdzhon submitted a review, later dismissed

2022-05-20 11:56 UTC, stoope submitted a review, later dismissed

2022-05-20 15:01 UTC, inomdzhon submitted a review, later dismissed

2022-05-20 15:48 UTC, stoope submitted a review, later dismissed

2022-05-23 08:05 UTC, merged