[refactor] File
VKCOM/VKUI pull request #2527
Opened 2022-05-20 12:02 UTC by eugpoloz

Посмотрела я на `File` и решила, что пора его причесать.

- [x] перевела на именованный экспорт (#2191)
- [x] убрала `defaultProps` (#1586)
- [x] отметила в доке как токенизированный (fixes #2526)
- [x] заэкспортила из tokenized-энтрипоинта
- [x] задепрекейтила `controlSize` в пользу обычного `size` из `Button`
- [x] навела порядок в типах
- [x] подкрутила доступность
- [x] убрала ставший лишним css-файл
- [x] обновила пример

2022-05-20 12:26 UTC, inomdzhon requested changes

2022-05-20 12:26 UTC, inomdzhon commented on src/components/File/File.tsx
> +        onClick={(e) => onClick?.(e)}
можно удалить `onClick`, т.к. он есть в `{...restProps}`

2022-05-20 12:29 UTC, inomdzhon commented
> @stoope @inomdzhon Есть вопрос про `onClick`: не будет ли то, что я его перенесла непосредственно на `Input`, breaking change?

кмк в идеальном мире это минор
даже с учётом `Component={label}`

2022-05-20 12:29 UTC, SevereCloud commented on src/components/File/File.tsx
> +      <VisuallyHiddenInput
Что насчет добавить `aria-hidden="true"`

До
<img width="840" alt="image" src="https://user-images.githubusercontent.com/14944123/169528271-c8f99d78-07bb-4064-adfe-63bceed2a8a3.png">


После:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/14944123/169528136-1f7cd179-bc8b-454a-ba0a-d1d92e0d658f.png">

2022-05-20 12:34 UTC, stoope commented on src/components/File/File.tsx
> +        onClick={(e) => onClick?.(e)}
`onClick={onClick}`

2022-05-23 11:05 UTC, eugpoloz commented on src/components/File/File.tsx
> +      <VisuallyHiddenInput
Мы скрываем компонент визуально, а не от скринридеров.

2022-05-23 11:08 UTC, eugpoloz commented on src/components/File/File.tsx
> +        onClick={(e) => onClick?.(e)}
@stoope я вообще в итоге выкинула, потому что [Ином справедливо заметил](https://github.com/VKCOM/VKUI/pull/2527#discussion_r878089853):
> можно удалить `onClick`, т.к. он есть в `{...restProps}`
❤️

2022-05-23 11:17 UTC, inomdzhon approved these changes

2022-05-23 11:25 UTC, SevereCloud commented on src/components/File/File.tsx
> +      <VisuallyHiddenInput
Зачем пользователю два раз говорить, что эта кнопка обозначает выбор файла?

<img width="937" alt="image" src="https://user-images.githubusercontent.com/14944123/169808426-3ce624e5-390a-45a5-a2e7-ae73f6800917.png">

А если внутрь кнопки зайти, то вообще можно сойти с ума

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/14944123/169808236-33b2888b-5933-45c5-b394-bafe16dcda92.png">

2022-05-23 12:00 UTC, merged

2022-05-23 12:04 UTC, SevereCloud commented on src/components/File/File.tsx
> +      <VisuallyHiddenInput
> Скрывать инпут вообще не вариант, потому что без инпута пользователь сейчас имя прикрепленного файла никак не узнает

Так мы и визуально не показываем название файла