feat(FormItem): tokenized
VKCOM/VKUI pull request #2600
Opened 2022-05-24 11:03 UTC by SevereCloud

Перевод на токены FormItem и FormLayoutGroup
---

Чеклист перевода компонента на vkui-tokens

- [x] В стилях компонента не осталось платформенных селекторов(_оставлен для обратной совместимости_)
- [x] Если в стилях встречаются токены из Appearance, то их нужно не удалять, а дополнять фоллбэком на соответствующий токен из vkui-tokens
- [x] В tsx компонента не осталось логики, которая зависит от платформы(_оставлено для обратной совместимости_)
- [x] Компонент добавлен в src/tokenized/index.ts (в src/index.ts он так же должен быть)
- [x] Имя компонента добавлено в массив из styleguide/tokenized.js

---

### Разное

<details>
  <summary>Борьба за 2 пикселя</summary>
  
  
До|После
-|-
<img width="891" alt="image" src="https://user-images.githubusercontent.com/14944123/170010988-d028088e-3403-4773-8320-1a7731459531.png">|<img width="888" alt="image" src="https://user-images.githubusercontent.com/14944123/170020043-55dc19ed-de42-4d43-85c4-cd262f495215.png">

</details>

<details>
  <summary>Выравнивание компонентов</summary>
  
До|После
-|-
<img width="319" alt="image" src="https://user-images.githubusercontent.com/14944123/170019263-a242aab0-699c-4a04-be81-0a50b51be292.png">|<img width="317" alt="image" src="https://user-images.githubusercontent.com/14944123/170019520-3bfb8d0f-0b3f-4706-b354-68d3a688eb70.png">

</details>

---

- [ ] ⛔️ blocked by VKCOM/vkui-tokens#122
- [x] #2191
- [x] closed #2542

2022-05-24 17:03 UTC, SevereCloud commented
Дизайн ревью ✅ (by @Fliqle)

2022-05-24 18:30 UTC, eugpoloz commented
А задачи для `FormLayoutGroup` у нас отдельной нет?

2022-05-24 18:36 UTC, SevereCloud commented
> А задачи для `FormLayoutGroup` у нас отдельной нет?

Неа

2022-05-24 18:42 UTC, eugpoloz commented
@SevereCloud а сделай тогда тоже или дополни задачку про `FormItem`, чтоб было видно, какие компоненты учлись.

2022-05-24 19:04 UTC, eugpoloz requested changes
Давай разделим сущности и оставим сейчас в этом пулле только токенизацию и переезд на именованные экспорты. 

Доступность в этом случае надо бы очень внимательно проверить, `aria`-метки — это часто показатель, что мы делаем что-то неправильно; а токенизация и именованные экспорты нужны как можно быстрее.

2022-05-26 14:50 UTC, inomdzhon submitted a review, later dismissed

2022-05-31 11:12 UTC, inomdzhon submitted a review, later dismissed

2022-06-02 12:00 UTC, SevereCloud commented on src/components/FormItem/FormItem.css
> +  min-width: 1px;
<img width="669" alt="image" src="https://user-images.githubusercontent.com/14944123/171623253-9bebbe37-3a3b-494c-bd64-239b37cba831.png">

2022-06-09 14:36 UTC, inomdzhon approved these changes

2022-06-09 14:52 UTC, inomdzhon submitted a review, later dismissed

2022-06-10 10:18 UTC, inomdzhon approved these changes

2022-06-10 15:55 UTC, eugpoloz commented on src/components/Removable/Removable.tsx
> +      <span vkuiClass="Removable__offset" aria-hidden />
Я тут подумала и поняла, что вообще этот offset нам нужен только для `FormLayoutGroup`. Может, туда и перенесем?

2022-06-10 15:57 UTC, eugpoloz commented on src/components/FormItem/FormItem.css
> +  min-width: 1px;
@SevereCloud все еще не очень поняла, раскрой мысль, пожалуйста. х)

2022-06-10 15:58 UTC, eugpoloz approved these changes

2022-06-10 15:59 UTC, eugpoloz commented
@SevereCloud короче! Все теперь вполне ок, а на следующей неделе я в отпуске, поэтому лайк тебе авансом, но если ответишь на мои вопросики и комменты — буду признательна. 😆

2022-06-10 17:20 UTC, SevereCloud commented on src/components/FormItem/FormItem.css
> +  min-width: 1px;
https://user-images.githubusercontent.com/14944123/173118472-a6a5b327-0376-405b-bc0e-145ceabdcc15.mov

2022-06-10 17:26 UTC, SevereCloud commented on src/components/Removable/Removable.tsx
> +      <span vkuiClass="Removable__offset" aria-hidden />
Он еще в `FormItem` нужен

2022-06-14 06:55 UTC, merged