Ejects ScrollArrow component from HorizontalScroll
VKCOM/VKUI pull request #2634
Opened 2022-05-31 08:05 UTC by r-lubimov-corp-mail-ru

Ejects ScrollArrow component to make it possible to use it properly inside new VerticalScroll component

2022-05-31 08:31 UTC, SevereCloud requested changes
### vkuiClass

Для свойства классов мы используем `vkuiClass`, они не перезаписываются, а добавляются к className с префиксом `vkui`. Добавил комментариев к коду

### Обратная совместимость

Думаю изменять классы `HorizontalScrollArrow` на `ScrollArrow` немного плохая идея

### Что-то пошло не так

<img width="370" alt="image" src="https://user-images.githubusercontent.com/14944123/171128646-eebaed83-6d71-4d47-8343-2f24a5970557.png">

В HorizontalScroll стрелочки и вовсе пропали(

2022-05-31 08:31 UTC, SevereCloud commented on src/components/ScrollArrow/ScrollArrow.tsx
>    direction,
```suggestion
  onClick,
  direction,
  ...restProps
```

2022-05-31 08:31 UTC, SevereCloud commented on src/components/ScrollArrow/ScrollArrow.tsx
>      >
```suggestion
      onClick={onClick}
      {...restProps}
    >
```

2022-05-31 09:50 UTC, r-lubimov-corp-mail-ru commented
К задаче https://github.com/VKCOM/VKUI/issues/2499

2022-05-31 10:01 UTC, SevereCloud commented on src/components/Gallery/Gallery.css
> +
```suggestion

.Gallery__arrow--left {
  padding-left: var(--vkui--size_base_padding_horizontal--regular, 16px);
  left: 0;
}

.Gallery__arrow--right {
  padding-right: var(--vkui--size_base_padding_horizontal--regular, 16px);
  right: 0;
}

```

2022-06-02 11:28 UTC, inomdzhon requested changes

2022-06-03 14:26 UTC, r-lubimov-corp-mail-ru commented on src/components/VerticalScroll/Readme.md
> +                    <HorizontalCell key={item.id} header={item.first_name}>
Не думаю что пользователи будут так размещаться в этом компоненте
Могу просто картинки вставить, чтобы никого не смущать

2022-06-15 09:31 UTC, r-lubimov-corp-mail-ru commented on src/components/VerticalScroll/Readme.md
> +import { useEffect, useState, Fragment } from "react";
Убрал

2022-06-15 09:31 UTC, r-lubimov-corp-mail-ru commented on src/components/VerticalScroll/Readme.md
> +  const [recentFriends] = useState(getRandomUsers(20));
Убрал

2022-06-16 17:00 UTC, inomdzhon commented
@r-lubimov-corp-mail-ru тесты упали + подтяни мастер плиз

2022-06-17 10:09 UTC, r-lubimov-corp-mail-ru commented
> @r-lubimov-corp-mail-ru тесты упали + подтяни мастер плиз

Готово

2022-06-20 12:53 UTC, stoope commented on src/components/VerticalScroll/Readme.md
> +<VerticalScrollExample />;
<img width="355" alt="Screenshot 2022-06-20 at 15 52 15" src="https://user-images.githubusercontent.com/17287557/174605759-2a76ebe1-407d-4748-9119-ec2bd2db7108.png">
При первом наведении мышкой (до первого скролла) не показывается кнопка скролла

2022-06-20 13:24 UTC, r-lubimov-corp-mail-ru commented on src/components/VerticalScroll/Readme.md
> +  const [commonFriends, setCommonFriends] = useState([]);
Выше @inomdzhon писал, что нужно удалить, потому что импорты автоматически работают

2022-06-20 15:06 UTC, inomdzhon commented on src/components/VerticalScroll/Readme.md
> +  const [commonFriends, setCommonFriends] = useState([]);
Сорри, проглядел, надо написать так `React.`

2022-06-21 09:59 UTC, r-lubimov-corp-mail-ru commented on src/components/VerticalScroll/Readme.md
> +<VerticalScrollExample />;
Отцентрировал

2022-06-21 09:59 UTC, r-lubimov-corp-mail-ru commented on src/components/VerticalScroll/Readme.md
> +  const [commonFriends, setCommonFriends] = useState([]);
Поправил

2022-06-23 17:53 UTC, SevereCloud commented on src/components/VerticalScroll/VerticalScroll.tsx
> +      roundUpElementScrollLeft(scrollElement) !== Math.max(0, endTop) &&
```suggestion
      roundUpElementScrollTop(scrollElement) !== Math.max(0, endTop) &&
```
Чуть выше забыл изменить функцию

2022-06-27 10:07 UTC, r-lubimov-corp-mail-ru commented on src/components/VerticalScroll/VerticalScroll.tsx
> +      roundUpElementScrollLeft(scrollElement) !== Math.max(0, endTop) &&
Применил твои изменения просто)

2022-07-04 11:08 UTC, inomdzhon commented
К сожалению, со стороны дизайна возникли вопросы стоит ли всё же на уровне VKUI это хранить. Ждём пока разберутся. Извини, что так затянулось :(

2022-07-04 14:15 UTC, SevereCloud commented
<img width="365" alt="Снимок экрана 2022-07-04 в 17 14 05" src="https://user-images.githubusercontent.com/14944123/177172329-5ca06e9f-5c2b-4b63-b445-20653c967813.png">

Первый элемент съезжает вправо

2022-07-04 14:59 UTC, r-lubimov-corp-mail-ru commented
> <img alt="Снимок экрана 2022-07-04 в 17 14 05" width="365" src="https://user-images.githubusercontent.com/14944123/177172329-5ca06e9f-5c2b-4b63-b445-20653c967813.png">
> 
> Первый элемент съезжает вправо

Готово

2022-07-04 14:59 UTC, r-lubimov-corp-mail-ru commented
> К сожалению, со стороны дизайна возникли вопросы стоит ли всё же на уровне VKUI это хранить. Ждём пока разберутся. Извини, что так затянулось :(

Ну как минимум стрелочки должны быть одинаковые

2022-07-20 14:38 UTC, inomdzhon commented
> К сожалению, со стороны дизайна возникли вопросы стоит ли всё же на уровне VKUI это хранить. Ждём пока разберутся. Извини, что так затянулось :(

@r-lubimov-corp-mail-ru `VerticalScroll` в дизайн-системе VKUI не планируется. Надо будет хранить его реализацию у себя в проекте.

> Ну как минимум стрелочки должны быть одинаковые

Правильно понял, что нужно экспортнуть `ScrollArrow`?

2022-07-22 10:05 UTC, r-lubimov-corp-mail-ru commented
> > К сожалению, со стороны дизайна возникли вопросы стоит ли всё же на уровне VKUI это хранить. Ждём пока разберутся. Извини, что так затянулось :(
> 
> @r-lubimov-corp-mail-ru `VerticalScroll` в дизайн-системе VKUI не планируется. Надо будет хранить его реализацию у себя в проекте.
> 
> > Ну как минимум стрелочки должны быть одинаковые
> 
> Правильно понял, что нужно экспортнуть `ScrollArrow`?

Фигово
Тогда мб все хуки и утилки тоже вместо со ScrollArrow?

2022-12-20 06:30 UTC, inomdzhon commented
> > > К сожалению, со стороны дизайна возникли вопросы стоит ли всё же на уровне VKUI это хранить. Ждём пока разберутся. Извини, что так затянулось :(
> > 
> > 
> > @r-lubimov-corp-mail-ru `VerticalScroll` в дизайн-системе VKUI не планируется. Надо будет хранить его реализацию у себя в проекте.
> > > Ну как минимум стрелочки должны быть одинаковые
> > 
> > 
> > Правильно понял, что нужно экспортнуть `ScrollArrow`?
> 
> Фигово Тогда мб все хуки и утилки тоже вместо со ScrollArrow?

Сорри за долгий ответ. По поводу выноса хуков и утилок создай плиз ишью с фича реквест 🙏

2022-12-20 06:30 UTC, closed without merging