feat(MiniInfoCell): Tokenize
VKCOM/VKUI pull request #2695
Opened 2022-06-10 13:03 UTC by BlackySoul

## Чеклист перевода компонента на vkui-tokens
- [ ] Компонент добавлен в `src/tokenized/index.ts` (в `src/index.ts` он так же должен быть)
- [ ] Если в стилях встречаются токены из Appearance, то их нужно не удалять, а дополнять фоллбэком на соответствующий токен из vkui-tokens (пример такого PR [#2647](https://togithub.com/VKCOM/VKUI/pull/2647)) 
- [ ] Исключаем проверки типа `platform === ANDROID` (пример такого PR [#2653](https://togithub.com/VKCOM/VKUI/pull/2653))
- [ ] В стилях компонента не осталось платформенных селекторов (_осталось для обратной совместимости_)
- [ ] В tsx компонента не осталось логики, которая зависит от платформы 

---

- resolve #2553

2022-06-10 15:07 UTC, inomdzhon commented on src/components/MiniInfoCell/MiniInfoCell.css
>    margin-right: 12px;
Правый и левый отступ задан через `var(--vkui--size_base_padding_horizontal--regular)`, надо и здесь получается их же применить?

PS: также в 41 строчке

2022-06-10 15:07 UTC, inomdzhon commented on src/components/MiniInfoCell/MiniInfoCell.tsx
> +        getClassName("MiniInfoCell", platform), // TODO: v5 remove
Учитывая, что уже повсеместно везде `getClassName` удаляется, если он не нужен, то можно и тут сразу убрать 😅

2022-06-10 15:14 UTC, eugpoloz requested changes

2022-06-10 15:14 UTC, eugpoloz commented on src/components/MiniInfoCell/MiniInfoCell.css
> +  padding: 6px var(--vkui--size_base_padding_horizontal--regular);
Для верхнего паддинга токен не нужен, верно?

2022-06-10 15:14 UTC, eugpoloz commented on src/components/MiniInfoCell/MiniInfoCell.tsx
> +  children?: React.ReactNode;
[В документации](https://vkcom.github.io/VKUI/pull/2695/#/MiniInfoCell) это выглядит вот так:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/22026957/173096464-336f3f55-b5dc-40d6-86b2-7606c035fd1d.png">

И все же — точно ли нам нужно здесь отдельно прописывать `children`, автоматом они в пропсы не добавятся, если мы не заявим `React.FC`?

2022-06-14 07:19 UTC, BlackySoul commented on src/components/MiniInfoCell/MiniInfoCell.css
>    margin-right: 12px;
Не уверена, что эти отступы между иконками и аватарами должны зависеть от платформы. Или на [макете](https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library-(Alpha)?node-id=23649%3A180479) эту зависимость можно как-то увидеть?)

2022-06-14 07:26 UTC, BlackySoul commented on src/components/MiniInfoCell/MiniInfoCell.css
> +  padding: 6px var(--vkui--size_base_padding_horizontal--regular);
Токена для такого паддинга нет, думаю, он статичный)

2022-06-14 07:53 UTC, BlackySoul commented on src/components/MiniInfoCell/MiniInfoCell.tsx
> +  children?: React.ReactNode;
А что с документацией не так?) Тут это скорее для того, чтобы дать справку, что можно в кач-ве `children` использовать. И разве для `React.FC` это поле автоматом генерится?

2022-06-14 09:27 UTC, inomdzhon commented on src/components/MiniInfoCell/MiniInfoCell.css
>    margin-right: 12px;
Ааа, извини, я не так понял 😞  Теперь вижу, что это отступ между иконкой и аватарами
Всё ок 👌

2022-06-14 09:27 UTC, inomdzhon approved these changes

2022-06-22 09:53 UTC, eugpoloz commented on src/components/MiniInfoCell/MiniInfoCell.tsx
> +  children?: React.ReactNode;
Текст коммента весь парсится в доку. `TODO` точно не должно отображаться, а тут оно подхватывается. 😉

Вообще обычно мы советы по тому, что передавать в `children`, пишем в самом `README.md`.

2022-06-23 09:01 UTC, inomdzhon approved these changes

2022-06-24 10:21 UTC, merged