feat(CardGrid): Tokenize
VKCOM/VKUI pull request #2713
Opened 2022-06-16 11:25 UTC by BlackySoul

## Чеклист перевода компонента на vkui-tokens
- [x] Компонент добавлен в `src/tokenized/index.ts` (в `src/index.ts` он так же должен быть)
- [x] Если в стилях встречаются токены из Appearance, то их нужно не удалять, а дополнять фоллбэком на соответствующий токен из vkui-tokens (пример такого PR [#2647](https://togithub.com/VKCOM/VKUI/pull/2647)) 
- [x] Исключаем проверки типа `platform === ANDROID` (пример такого PR [#2653](https://togithub.com/VKCOM/VKUI/pull/2653)) 
- [x] В стилях компонента не осталось платформенных селекторов 
- [x] В tsx компонента не осталось логики, которая зависит от платформы 

---

- close #2191
- resolve #2511

2022-06-16 11:56 UTC, inomdzhon requested changes

2022-06-16 11:56 UTC, inomdzhon commented on src/components/CardGrid/CardGrid.tsx
> -export default withAdaptivity(CardGrid, { sizeX: true });
К сожалению, надо вернуть `withAdaptivity`, а то сейчас это брейкинг чендж изменение – HOC позволяет передавать `sizeY` компоненту напрямую

При мержу в `v5.0.0` можно будет на хук заменить

2022-06-23 08:57 UTC, inomdzhon commented on src/components/CardGrid/CardGrid.tsx
> +   * @default false
`react-styleguidist` сам подхватывает ведь значение по умолчанию

2022-06-23 08:57 UTC, inomdzhon commented on src/components/CardGrid/CardGrid.tsx
> +CardGridComponent.displayName = "CardGrid";
```suggestion
CardGrid.displayName = "CardGrid";
```

и под 44 строчку

PS: это хак для `v4`, чтобы при оборачивании `withAdaptivity` не терялось название компонента, при мерже в `v5` удаляю

2022-06-23 08:57 UTC, inomdzhon commented on src/components/CardGrid/CardGrid.css
> +  margin-top: 16px;
Зашиваем, прально понимаю?

2022-06-24 10:24 UTC, BlackySoul commented on src/components/CardGrid/CardGrid.css
> +  margin-top: 16px;
Ну отдельных токенов пока нет)

2022-06-24 10:28 UTC, inomdzhon commented on src/components/CardGrid/CardGrid.tsx
> +CardGridComponent.displayName = "CardGrid"; // TODO: v5 remove
```suggestion
CardGrid.displayName = "CardGrid"; // TODO: v5 remove
```
вот так вот только :)

2022-06-28 15:02 UTC, inomdzhon approved these changes

2022-07-05 14:33 UTC, merged