feat(Tabs,TabsItem): tokenized
VKCOM/VKUI pull request #2781
Opened 2022-07-01 15:24 UTC by inomdzhon

## Чеклист перевода компонента на vkui-tokens
- [x] Компонент добавлен в `src/tokenized/index.ts` (в `src/index.ts` он так же должен быть)
- [x] Если в стилях встречаются токены из Appearance, то их нужно не удалять, а дополнять фоллбэком на соответствующий токен из vkui-tokens (пример такого PR [#2647](https://togithub.com/VKCOM/VKUI/pull/2647))

## Дополнительно

Появились новые пропы (см. подробности в PR)
- `before`
- `count`
- `badge`

---

- Close #2584
- Close #2585

2022-07-06 09:11 UTC, BlackySoul commented
Кажется, изменения в ветке ещё поправили вот это:
- fixed #2536

2022-07-19 12:35 UTC, inomdzhon commented
> > Кажется, изменения в ветке ещё поправили вот это:
> > 
> > * fixed [[Bug] Переполнение текста Tabs работает неверно Firefox #2536](https://github.com/VKCOM/VKUI/issues/2536)
> 
> Выглядит намного лучше, но с иконкой нет многоточия
> 
> Chrome	Firefox
> <img alt="image" width="341" src="https://user-images.githubusercontent.com/14944123/178955540-8a2dbe4e-402a-4e36-b5bd-cecb07d77952.png">	<img alt="image" width="350" src="https://user-images.githubusercontent.com/14944123/178955352-bebc0680-0ba4-48ff-9268-e7c3188adde6.png">

Выглядит как баг **Firefox**

<details>
<summary>Видео 1</summary>

Изменял вот этот пример http://jsfiddle.net/QNJnw/

https://user-images.githubusercontent.com/5850354/179749073-bb50efb7-fd8e-4742-94ac-447dd07147c2.mov
</details>

<details>
<summary>Видео 2</summary>

Изменял вот этот пример https://codepen.io/chriscoyier/full/zqedEr

https://user-images.githubusercontent.com/5850354/179751137-2caa92a1-e5d7-43e2-aa85-1014b9a20df1.mov
</details>

Поиски issue и игра со св-ами ни привели к результату.

---

Вообще баг не выглядит критичным. Раз это проблема **Firefox**, то надо ждать фикса от них. И чтобы кто-нибудь открыл им issue 😄

2022-07-19 12:55 UTC, inomdzhon commented
blocked by #2860

2022-07-29 12:38 UTC, eugpoloz requested changes

2022-07-29 12:38 UTC, eugpoloz commented on src/components/Counter/Counter.css
> +  background-color: var(--panel_tab_inactive_text);
А тут не токенизируем цвета?

2022-07-29 12:38 UTC, eugpoloz commented on src/components/Tabs/Tabs.tsx
> +   * > ⚠️ Значения `"buttons"`, `"segmented"` устарели и будет удалены в 5.0.0. Используйте `"secondary"` и [`SegmentedControl`](https://vkcom.github.io/VKUI#/SegmentedControl).
Не совсем поняла этот комментарий, можешь пояснить? В режиме `"secondary"` вместо `TabsItem` мы будем передавать в `children` [`SegmentedControl`](https://vkcom.github.io/VKUI#/SegmentedControl)?

И опечатка тут еще:
```suggestion
   * > ⚠️ Значения `"buttons"`, `"segmented"` устарели и будет удалены в 5.0.0. Используйте `"secondary"` и [`SegmentedControl`](https://vkcom.github.io/VKUI/#/SegmentedControl).
```

2022-07-29 12:38 UTC, eugpoloz commented on src/components/TabsItem/TabsItem.css
> +.TabsItem--sizeX-compact.TabsItem {
`.TabsItem--sizeX-compact` должно быть достаточно.

2022-07-29 12:38 UTC, eugpoloz commented on src/components/TabsItem/TabsItem.css
> +  border-radius: var(--vkui--size_border_radius--regular);
Точно ли тут должен быть этот токен? На 10-й строчке точно такой же.

2022-07-29 12:38 UTC, eugpoloz commented on src/components/TabsItem/TabsItem.tsx
>    }
```suggestion
```

2022-07-29 12:38 UTC, eugpoloz commented on src/components/TabsItem/TabsItem.tsx
> +      {statusComponent}
```suggestion
      {status &&
        <Subhead
            Component="span"
            vkuiClass="TabsItem__status"
            weight="2"
          >
            {status}
          </Subhead>
        }
```

Внутри каунтера по идее есть свой собственный типографический компонент, который будет перебивать все эти определения.

2022-07-29 13:58 UTC, inomdzhon commented on src/components/TabsItem/TabsItem.tsx
> +      {statusComponent}
Я бы всё-равно не стал бы в лишний раз оборачивать в `Subhead`, чтобы исключить в дальнейшем проблемы
Сегодня `Counter` и `Badge`, а завтра чего ещё придумают передавать

2022-07-29 14:02 UTC, inomdzhon commented on src/components/Tabs/Tabs.tsx
> +   * > ⚠️ Значения `"buttons"`, `"segmented"` устарели и будет удалены в 5.0.0. Используйте `"secondary"` и [`SegmentedControl`](https://vkcom.github.io/VKUI#/SegmentedControl).
Нет, отдельно от этого компонента использовать

Вот так напишу
```suggestion
   * > ⚠️ Значения `"buttons"`, `"segmented"` устарели и будет удалены в 5.0.0. Вместо `"buttons"` используйте `"secondary"`. Режим `"segmented"` переехал в отдельный компонент [`SegmentedControl`](https://vkcom.github.io/VKUI#/SegmentedControl), поэтому используйте его вместо `Tabs`.
```

Спасибо 🙏

2022-07-29 14:10 UTC, inomdzhon commented on src/components/Counter/Counter.css
> +  background-color: var(--panel_tab_inactive_text);
Относится к депрекейтит `mode="segmented"`, в `v5.0.0` удаляем – добавил TODO

Спасибо, что за замечание 🙏  А то забыл про TODO написать)

2022-08-01 07:21 UTC, BlackySoul commented on src/components/Tabs/Tabs.tsx
> +        (platform === IOS || platform === VKCOM) && `Tabs--${platform}`,
А зачем дубли `IOS` и `ANDROID`, когда можно просто `Platform.IOS`?

2022-08-01 07:36 UTC, inomdzhon commented on src/components/Tabs/Tabs.tsx
> +        (platform === IOS || platform === VKCOM) && `Tabs--${platform}`,
Ни поняль... Ты про сто конкретно?

В данном месте нужно завязаться на `Tabs--ios` и `Tabs--vkcom`

2022-08-01 07:39 UTC, BlackySoul commented on src/components/Tabs/Tabs.tsx
> +        (platform === IOS || platform === VKCOM) && `Tabs--${platform}`,
> Ни поняль... Ты про сто конкретно?
> В данном месте нужно завязаться на `Tabs--ios` и `Tabs--vkcom`

Я про то, в чем профит использовать отдельные константы
`import { IOS, VKCOM } from "../../lib/platform";`

А не вот так:

```
import { Platform } from "../../lib/platform";
Platform.IOS;
```

2022-08-01 07:53 UTC, BlackySoul submitted a review, later dismissed

2022-08-01 08:50 UTC, inomdzhon commented on src/components/Tabs/Tabs.tsx
> +        (platform === IOS || platform === VKCOM) && `Tabs--${platform}`,
Я ориентировался как везде сделано `Platform.*` только в тестах и в нескольких компонентах есть 🤔 
Хороший вопрос 👍  Надо поднять эту тему сегодня на синке в 15:00. Здесь пока оставлю отдельный импорт.

2022-08-01 08:57 UTC, eugpoloz approved these changes

2022-08-01 09:30 UTC, eugpoloz approved these changes

2022-08-01 09:43 UTC, merged