feat(SimpleCell): Tokenize
VKCOM/VKUI pull request #2810
Opened 2022-07-07 16:33 UTC by BlackySoul

## Чеклист перевода компонента на vkui-tokens
- [ ] Компонент добавлен в `src/tokenized/index.ts` (в `src/index.ts` он так же должен быть)
- [ ] Если в стилях встречаются токены из Appearance, то их нужно не удалять, а дополнять фоллбэком на соответствующий токен из vkui-tokens (пример такого PR [#2647](https://togithub.com/VKCOM/VKUI/pull/2647)) 
- [ ] Исключаем проверки типа `platform === ANDROID` (пример такого PR [#2653](https://togithub.com/VKCOM/VKUI/pull/2653)) 
- [ ] В стилях компонента не осталось платформенных селекторов 
- [ ] В tsx компонента не осталось логики, которая зависит от платформы 

---

- resolve #2574

2022-07-18 12:36 UTC, eugpoloz requested changes

2022-07-18 12:36 UTC, eugpoloz commented on src/components/SimpleCell/SimpleCell.tsx
> +  subtitleLeftBadge?: React.ReactNode;
Подскажи, пожалуйста, откуда у нас взялись все эти параметры? Если это какой-то рефакторинг, я бы разнесла его с токенизацией, чтобы было проще ревьюить. `SimpleCell` и так достаточно сложный чувак, несмотря на название. 😉

2022-07-18 13:43 UTC, BlackySoul commented on src/components/SimpleCell/SimpleCell.tsx
> +  subtitleLeftBadge?: React.ReactNode;
Просто начала сравнивать с тем, что на макетах, и у нас не хватало функциональности, могу все выпилить, перевести на токены только то, что есть :)

2022-07-18 21:16 UTC, SevereCloud reviewed
Что насчет e2e для новых параметров?

---

Примеры которые содержат SimpleCell с устаревшим свойством `description`

- Avatar
- Gradient
- Group
- PromoBanner
- Tooltip

(поиск по запросу `<SimpleCell(.|\n)*?description(.|\n)*?/>`)

2022-07-22 08:09 UTC, BlackySoul commented on src/components/SimpleCell/SimpleCell.tsx
> +  subtitleLeftBadge?: React.ReactNode;
> Подскажи, пожалуйста, откуда у нас взялись все эти параметры? Если это какой-то рефакторинг, я бы разнесла его с токенизацией, чтобы было проще ревьюить. `SimpleCell` и так достаточно сложный чувак, несмотря на название. 😉

Оставила только токенизацию x)

2022-07-26 10:38 UTC, inomdzhon approved these changes

2022-07-29 11:51 UTC, eugpoloz approved these changes

2022-07-29 11:57 UTC, eugpoloz commented
> Может, нам и не стоит пытаться их "угадывать" по названием классов, оставить это на откуп пользователя?

Было бы огонь, да! Но это скорее на шестую версию уже задел.

2022-08-01 05:34 UTC, merged