feat(HorizontalScroll): add `arrowSize` prop
VKCOM/VKUI pull request #2844
Opened 2022-07-14 14:47 UTC by inomdzhon

`HorizontalScrollArrow`
* добавил `size`
* поправил значение в `opacity` при наведении на токен
* добавил пропущенный селектор `HorizontalScrollArrow--ios`

---

- close #2842

2022-07-14 15:00 UTC, eugpoloz requested changes

2022-07-14 15:00 UTC, eugpoloz commented on src/components/HorizontalScroll/HorizontalScrollArrow.tsx
> +  }
```suggestion
  let Component: React.ElementType = direction === "left" ? Icon24ChevronLeft : Icon24Chevron;

  if (size === "m") {
    Component = direction === "left" ? Icon16ChevronLeft : Icon16Chevron;
  }
```

2022-07-14 15:00 UTC, eugpoloz commented on src/components/HorizontalScroll/HorizontalScrollArrow.tsx
> +        `HorizontalScrollArrow--size-${size}`,
Сократим до `HorizontalScrollArrow--${size}`?

2022-07-14 15:04 UTC, inomdzhon commented on src/components/HorizontalScroll/HorizontalScrollArrow.tsx
> +        `HorizontalScrollArrow--size-${size}`,
у нас же по БЭМ'у `--<key>-<value>`, не?

2022-07-14 15:04 UTC, inomdzhon commented on src/components/HorizontalScroll/HorizontalScrollArrow.tsx
> +        `HorizontalScrollArrow--size-${size}`,
а для булевых `--<boolean>`

2022-07-14 15:17 UTC, eugpoloz commented on src/components/HorizontalScroll/HorizontalScrollArrow.tsx
> +        `HorizontalScrollArrow--size-${size}`,
У нас нет жесткого правила про `--<key>-<value>`, зато выкидывание `size-` сократит размер и так длинного класса. 😉

2022-07-14 15:25 UTC, inomdzhon commented on src/components/HorizontalScroll/HorizontalScrollArrow.tsx
> +        `HorizontalScrollArrow--size-${size}`,
@eugpoloz  если сделать так `HorizontalScrollArrow--${size}`, то будет сложней читать

<img width="498" alt="image" src="https://user-images.githubusercontent.com/5850354/179018213-878a5b28-e54f-47fb-a7a7-0eeb1a0a442a.png">

типа бьёт по DX

когда начнём в `v5` (или `v6`) сокращать классы на этапе сборки, проблема с размером должна кануть в лету

2022-07-15 16:17 UTC, eugpoloz approved these changes

2022-07-15 16:49 UTC, merged