feat(ChipsSelect, CustomSelect): Сворачивать список при повторном нажатии на стрелочку
VKCOM/VKUI pull request #2845
Opened 2022-07-14 15:28 UTC by BlackySoul

- resolve #1673 

- resolve #2896

- Добавила поворот стрелочки в зависимости от раскрытия списка в соответствие с дизайном в фигме

2022-07-18 12:55 UTC, eugpoloz requested changes

2022-07-18 12:55 UTC, eugpoloz commented on src/components/DropdownIcon/DropdownIcon.tsx
> +  flipped?: boolean;
Скажу тут сразу за всё. 😉 

Мне очень нравится сам пулл — давно пора было пофиксить эту штуку! — но я бы сделала более универсальное решение, которое не будет требовать копипастить код. Навскидку: 
- засунула бы всю логику "переворота" в `<DropdownIcon/>`,
- включала бы ее по свойству, например, `flippable` (которое по дефолту было бы `true` для всех новых компонентов, например),
- не использовала бы переворот через css, а меняла бы иконку, как у нас сделано в других местах.

Что скажешь?

2022-07-18 12:55 UTC, eugpoloz commented on src/components/CustomSelect/CustomSelect.tsx
> +
Кмк, если юзер либы передает сюда свою иконку, то и решать, вертит он ее или нет — его задача, и навешивать за него такую логику не стоит. Лучше сделать более умный `<DropdownIcon/>`.

2022-07-18 14:08 UTC, BlackySoul commented on src/components/DropdownIcon/DropdownIcon.tsx
> +  flipped?: boolean;
1. А что значит засунуть все логику переворота?) И про какой копипаст речь?) Предлагаешь через какое-то внутреннее состояние в `DropdownIcon` управлять "стрелка вниз/вверх"? Тогда нужно будет это состояние синхронить со всеми родительскими компонентами, потому что там свернуться список может по нажатию на Esc или развернуться при фокусе input'а. Или я не так поняла?)
2. -
3. Тогда нужно будет просить дизайнеров ещё кнопку рисовать, у Icon20Dropdown нет товарища

2022-07-21 14:58 UTC, eugpoloz commented on src/components/DropdownIcon/DropdownIcon.tsx
> +  flipped?: boolean;
1. Попыталась сформулировать словами, потом поэкспериментировала и поняла, что вообще функция не нужна, надо просто `opened` передавать из селектов. Сделаю пулл к тебе в ветку, покажу, раз уже заморочилась.
3. Йеп, все так! Пошли просить у Вани или у Леши.

2022-08-18 13:52 UTC, eugpoloz commented
Чтобы не забыть: вместе со стрелочкой в мастер еще #2896 заедет.

2022-08-19 13:49 UTC, eugpoloz commented
Ждем https://github.com/VKCOM/VKUI/pull/3024 для обновленной иконки.

2022-08-19 14:35 UTC, eugpoloz approved these changes

2022-08-19 16:25 UTC, eugpoloz approved these changes

2022-08-23 11:11 UTC, inomdzhon reviewed
👍 

Единствено `ChipsSelect.e2e.tsx` удалили, а скриншот остался – надо бы тоже удалить

2022-08-24 10:48 UTC, eugpoloz commented
@inomdzhon, спасибо за внимательность!
✅

2022-08-25 11:55 UTC, inomdzhon approved these changes
🤝

2022-08-25 11:57 UTC, merged