feat(TabbarItem): Tokenize
VKCOM/VKUI pull request #2847
Opened 2022-07-15 06:35 UTC by BlackySoul

## Чеклист перевода компонента на vkui-tokens
- [ ] Компонент добавлен в `src/tokenized/index.ts` (в `src/index.ts` он так же должен быть)
- [ ] Если в стилях встречаются токены из Appearance, то их нужно не удалять, а дополнять фоллбэком на соответствующий токен из vkui-tokens (пример такого PR [#2647](https://togithub.com/VKCOM/VKUI/pull/2647)) 
- [ ] Исключаем проверки типа `platform === ANDROID` (пример такого PR [#2653](https://togithub.com/VKCOM/VKUI/pull/2653)) (остались iOS и Android)
- [ ] В стилях компонента не осталось платформенных селекторов (остались iOS и Android)
- [ ] В tsx компонента не осталось логики, которая зависит от платформы (остались iOS и Android)

---

- resolve #2583

2022-07-18 12:28 UTC, eugpoloz commented on src/components/TabbarItem/TabbarItem.css
>    margin-left: 8px;
А не должно ли тут все тоже быть на токенах?

2022-07-18 12:28 UTC, eugpoloz commented on src/components/TabbarItem/TabbarItem.tsx
> +        platform === Platform.ANDROID && "TabbarItem--android",
Мне казалось, мы отходим от отдельных стилей для андроида?

2022-07-19 04:21 UTC, BlackySoul commented on src/components/TabbarItem/TabbarItem.tsx
> +        platform === Platform.ANDROID && "TabbarItem--android",
В соответствии с макетами, для андроида нужны отдельные стили, чтобы ripple эффект был не кривой :)

2022-07-19 04:22 UTC, BlackySoul commented on src/components/TabbarItem/TabbarItem.css
>    margin-left: 8px;
На макетах для текстового элемента не заипользован никакой типографический элемент, просто хардкод

2022-07-19 06:28 UTC, SevereCloud commented on src/components/TabbarItem/TabbarItem.css
>    margin-left: 8px;
> Footnote🔧500 · Medium

2022-07-19 07:02 UTC, BlackySoul commented on src/components/TabbarItem/TabbarItem.css
>    margin-left: 8px;
> Footnote🔧500 · Medium

А для горизонтального режима же нет?

2022-07-19 07:10 UTC, SevereCloud commented on src/components/TabbarItem/TabbarItem.css
>    margin-left: 8px;
Думаю нужно у дизайнеров спросить насчет использования там `Caption`

2022-07-19 09:47 UTC, BlackySoul commented on src/components/TabbarItem/TabbarItem.css
>    margin-left: 8px;
https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC?node-id=27137:216928#230444363

Просят кастом оставить, для горизонтального режима тогда на Footnote переделать, для вертикального с кастомным классом?

2022-07-19 10:19 UTC, SevereCloud commented on src/components/TabbarItem/TabbarItem.css
>    margin-left: 8px;
Да

2022-07-20 14:03 UTC, inomdzhon commented on src/components/Tabbar/Tabbar.tsx
> +  const _itemsLayout = getItemsLayout(itemsLayout, children);
Стоит по аналогии с другими местами использовать вот такой нейминг

```suggestion
  const itemsLayout = getItemsLayout(itemsLayoutProp, children);
```

2022-07-21 09:35 UTC, SevereCloud approved these changes

2022-07-21 14:05 UTC, eugpoloz requested changes

2022-07-21 14:05 UTC, eugpoloz commented on src/components/Tabbar/Tabbar.tsx
> +export const TabbarItemsLayoutContext =
Может, сократить до `TabbarLayoutContext`? Вроде и так понятно, что айтемы в соответствии с лэйаутом таббара будет располагаться.

Чисто на подумать: я бы еще предложила тут задепрекейтить `itemsLayout` в пользу `layout` (или `mode`, как в `FormLayoutGroup`) и в v5 выпилить `itemsLayout`, соответственно. Больше единообразия богам единообразия!

2022-07-22 03:59 UTC, BlackySoul commented on src/components/TabbarItem/TabbarItem.tsx
> +          ))}
О, да, так будет лучше, даже со специфичностью проблем не должно возникнуть 🙂

2022-07-26 10:29 UTC, inomdzhon approved these changes

2022-07-29 11:48 UTC, eugpoloz approved these changes

2022-08-01 05:37 UTC, merged