feat(ActionSheet, ActionSheetItem): Tokenize
VKCOM/VKUI pull request #2852
Opened 2022-07-18 06:54 UTC by BlackySoul

## Чеклист перевода компонента на vkui-tokens
- [ ] Компонент добавлен в `src/tokenized/index.ts` (в `src/index.ts` он так же должен быть)
- [ ] Если в стилях встречаются токены из Appearance, то их нужно не удалять, а дополнять фоллбэком на соответствующий токен из vkui-tokens (пример такого PR [#2647](https://togithub.com/VKCOM/VKUI/pull/2647)) 
- [ ] Исключаем проверки типа `platform === ANDROID` (пример такого PR [#2653](https://togithub.com/VKCOM/VKUI/pull/2653)) (остались, есть платформенные отличия)
- [ ] В стилях компонента не осталось платформенных селекторов (остались, есть платформенные отличия)
- [ ] В tsx компонента не осталось логики, которая зависит от платформы (остались, есть платформенные отличия)

---

- resolve #2504 
- resolve #2505

2022-07-18 12:29 UTC, eugpoloz commented
@BlackySoul а что со скриншотами?

2022-07-20 09:45 UTC, BlackySoul commented
> @BlackySoul а что со скриншотами?

Обновила

2022-07-20 09:52 UTC, eugpoloz requested changes

2022-07-20 09:52 UTC, eugpoloz commented on src/components/ActionSheetItem/ActionSheetItem.tsx
> +  multiline?: boolean;
Выглядит как отдельная фича, давай на будущее их все-таки выносить отдельными пуллами, чтобы и ревьюить было легче, и в мастер/релизы оно быстрее попадало. 😉

2022-07-20 09:52 UTC, eugpoloz commented on src/components/ActionSheetItem/ActionSheetItem.tsx
> +          !multiline && "ActionSheetItem--text-ellipsis"
Вижу, что у нас сделано похожим образом в `RichCell`, но в основном все-таки используется такой подход:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/22026957/179951013-93ab81b2-4746-413c-9b73-761c8339ff77.png">

У меня два варианта того, как поступить:
1. переписать тут "как везде" и отрицание вносить уже в стилях через `:not(.ActionSheetItem--multiline)` 😉
```suggestion
          multiline && "ActionSheetItem--multiline"
```

2. оставить как есть, разве что я бы предложила класс подсократить, и накинуть задачку порефачить везде, где есть, `multiline`, на `!multiline && "Component--ellipsis"`. Профит вижу в том, что мы чутка сократим стили.
```suggestion
          !multiline && "ActionSheetItem--ellipsis"
```

2022-07-20 09:52 UTC, eugpoloz commented on src/components/ActionSheetItem/ActionSheetItem.tsx
> +      {selectable && !restProps.disabled && (
А если вариант выбран за пользователя (на основе другого селекта) и сам селект мы можем открыть, но перевыбрать не можем — все опции задизаблены?

2022-07-20 10:26 UTC, BlackySoul commented on src/components/ActionSheetItem/ActionSheetItem.tsx
> +          !multiline && "ActionSheetItem--text-ellipsis"
Наверное, нужно ещё подождать мнения других, но, мне кажется, что проще накинуть парочку свойств через новый класс, чем париться со специфичностью и "занулять" свойства, т.е. я за вариант 2

2022-07-20 10:27 UTC, BlackySoul commented on src/components/ActionSheetItem/ActionSheetItem.tsx
> +      {selectable && !restProps.disabled && (
По-моему, это какая-то дичь случайная, верну, как было - тогда выбранный элемент будет задизейбленным просто

2022-07-20 11:20 UTC, inomdzhon commented on src/components/ActionSheetItem/ActionSheetItem.tsx
> +          !multiline && "ActionSheetItem--text-ellipsis"
Да, лучше по второму пути

Правда в сокращении имен модификаторов, т.к. теряется семантика, `ellipsis` слишком обобщённо. Мне нравится подход в БЭМ с `<key>-<value>`.

2022-07-21 05:06 UTC, BlackySoul commented on src/components/ActionSheetItem/ActionSheetItem.tsx
> +          !multiline && "ActionSheetItem--text-ellipsis"
> Я за первый вариант. `multiline` выглядит как особый кейс элемента поэтому логичнее будет сделать стили по умолчанию для `ellipsis` и добавлять `multiline`

Тут с какой стороны посмотреть, с точки зрения дизайна это особый кейс, но в вебе по умолчанию `multiline`, а `ellipsis` нужно дополнительно прикручивать 🙂

2022-07-29 12:08 UTC, eugpoloz approved these changes

2022-08-18 12:23 UTC, merged