feat(Panel, PanelHeader): Tokenize
VKCOM/VKUI pull request #2959
Opened 2022-08-10 09:55 UTC by BlackySoul

## Чеклист перевода компонента на vkui-tokens
- [ ] Компонент добавлен в `src/tokenized/index.ts` (в `src/index.ts` он так же должен быть)
- [ ] Если в стилях встречаются токены из Appearance, то их нужно не удалять, а дополнять фоллбэком на соответствующий токен из vkui-tokens (пример такого PR [#2647](https://togithub.com/VKCOM/VKUI/pull/2647)) 
- [ ] Исключаем проверки типа `platform === ANDROID` (пример такого PR [#2653](https://togithub.com/VKCOM/VKUI/pull/2653)) (остались)
- [ ] В стилях компонента не осталось платформенных селекторов  (остались)
- [ ] В tsx компонента не осталось логики, которая зависит от платформы (остались)

---

- resolve #2558

---

Не стала делать правки с типографическими элементами (непонятно, что там с токенами шрифтов), в целом только на существующие appearance токены были сделаны соответствующие vkui tokens

2022-08-15 14:01 UTC, stoope requested changes

2022-08-15 16:37 UTC, BlackySoul commented on src/components/PanelHeaderEdit/PanelHeaderEdit.tsx
> +      {platform !== IOS ? <AndroidIcon /> : iOSText}
+

2022-08-15 16:37 UTC, BlackySoul commented on src/components/PanelHeaderContext/PanelHeaderContext.tsx
> +        (platform !== IOS || (platform === IOS && isDesktop)) &&
+

2022-08-15 16:37 UTC, BlackySoul commented on src/components/Panel/Panel.tsx
> +          `Panel--sizeX-${sizeX}`,
+

2022-08-16 07:09 UTC, stoope approved these changes

2022-08-16 07:52 UTC, merged