feat(SubnavigationButton): tokenized
VKCOM/VKUI pull request #3023
Opened 2022-08-19 12:10 UTC by SevereCloud

## Чеклист перевода компонента на vkui-tokens

- [x] Компонент добавлен в `src/tokenized/index.ts` (в `src/index.ts` он так же должен быть)
По возможности выполняем следующие пункты:
- [x] Если в стилях встречаются токены из Appearance, то их нужно не удалять, а дополнять фоллбэком на соответствующий токен из vkui-tokens
- [x] Исключаем проверки типа `platform === ANDROID`
- [x] В стилях компонента не осталось платформенных селекторов
- [x] В tsx компонента не осталось логики, которая зависит от платформы

---

- closed #2581

2022-08-19 12:25 UTC, eugpoloz commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        {before && (
А куда исчез `hasReactNode`, почему?

2022-08-19 12:32 UTC, eugpoloz requested changes

2022-08-19 12:32 UTC, eugpoloz commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        `SubnavigationButton--mode-${mode}`,
Я бы предложила сократить до `SubnavigationButton--${mode}`, вряд ли `mode` с чем-то еще по значениям пересечется.

2022-08-19 12:32 UTC, eugpoloz commented on src/components/SubnavigationButton/SubnavigationButton.css
> +  color: var(--vkui--color_icon_accent);
Думаю, тут стоит опереться на силу каскада. 😉 

```suggestion
.SubnavigationButton--selected {
  background-color: var(
    --button_primary_background,
    var(--vkui--color_background_accent)
  );
  color: var(--button_primary_foreground, var(--vkui--color_text_contrast));
  box-shadow: none;
  border: none;
}

.SubnavigationButton--selected .SubnavigationButton__before,
.SubnavigationButton--selected .SubnavigationButton__expandableIcon {
  color: inherit;
}

.SubnavigationButton--selected.SubnavigationButton--mode-tertiary {
  background-color: var(--vkui--color_transparent--active);
  color: var(--vkui--color_text_primary);
}

.SubnavigationButton--selected.SubnavigationButton--mode-tertiary 
.SubnavigationButton__expandableIcon {
  color: var(--vkui--color_icon_accent);
```

2022-08-19 13:39 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        {before && (
hasReactNode не нужен, будем от него потихоньку избавляться 

> Польза от `hasReactNode()` только тогда, когда мы возвращаем ноду
>
> ```tsx
> const Component = ({ children }) => hasReactNode(children) ? children : null
> ```

by @inomdzhon

2022-08-19 13:41 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        `SubnavigationButton--mode-${mode}`,
Мне нравится идея @inomdzhon чтобы привести все такие классы к одному стандарту. На размер бандла не должно сильно влиять

2022-08-19 13:51 UTC, fedorov-xyz commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        {before && (
Артур вводил эту функцию, когда были кейсы передачи в свойства значений, которые реакт интерпретировал как элементы и выводил их. Обычный тернарник `before && ()` не работал. Тогда надо `before ? () : null`.

2022-08-19 13:54 UTC, eugpoloz commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        `SubnavigationButton--mode-${mode}`,
Идея хорошая, но на вес версии без хеширования классов влиять длинные имена классов точно будут, поэтому я за то, чтобы максимально сокращать их по возможности без потери смысла.

2022-08-19 14:02 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        {before && (
Но сейчас это бесполезно и приводит к [ошибкам](https://togithub.com/VKCOM/VKUI/issues/1649), я правильно понимаю?

2022-08-19 14:03 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        `SubnavigationButton--mode-${mode}`,
Мне кажется, что когда нибудь мы все таки случайно пересечемся и запутаемся

2022-08-19 14:06 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.css
> +  color: var(--vkui--color_icon_accent);
✅

2022-08-19 14:07 UTC, eugpoloz commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        `SubnavigationButton--mode-${mode}`,
Тогда, может, `SubnavigationButton--md-${mode} `?

<img width="245" alt="image" src="https://user-images.githubusercontent.com/22026957/185636562-e8d89564-ac89-4a99-b549-c2d6ad0c5ecc.png">

И текущие `--mode-${mode}` классы тоже заменить на `--md-${mode}` (не здесь, отдельным пуллом).

2022-08-19 14:19 UTC, inomdzhon commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        {before && (
@fedorov-xyz может это была проблема React < 16? Сейчас не вижу смысла в этой функции.

Касаемо [#1649](https://togithub.com/VKCOM/VKUI/issues/1649), продублирую ответ, который писал в общий чат когда-то

> Тут как раз из-за `hasReactNode()` это issue возникло. В функции не хватало проверки на пустую строку.
>
> ![image](https://user-images.githubusercontent.com/5850354/185637490-9c8903a2-fab8-48e9-bde0-ed7835a1af5a.png)
>
> Если бы написали `bottom && ...`, то проблемы бы не было.

2022-08-19 14:29 UTC, inomdzhon commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        `SubnavigationButton--mode-${mode}`,
Я тут подумал, учитывая `gzip`/`brotli`, нет большого смысла сокращать имена в ущерб DX.

Все эти `--mode` схлопнутся в ссылку на одну единственную строку благодаря алгоритму сжатия **LZ77**.

Если говорить про сокращение `md`, то его лучше не использовать – обычно так сокращают размер `medium` в брейкпоинтах

<img width="455" alt="image" src="https://user-images.githubusercontent.com/5850354/185640781-39f0ca93-c8f8-4cdb-956c-decfc751128b.png">

2022-08-19 14:31 UTC, eugpoloz commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        `SubnavigationButton--mode-${mode}`,
@inomdzhon вот это хороший аргумент.)

2022-08-19 14:40 UTC, inomdzhon commented on src/components/Counter/Counter.css
> +}
А нельзя это заменить на коммент в параметре 

> Используйте [Counter](#/Counter) с параметром `mode="primary"`

?

2022-08-19 14:40 UTC, inomdzhon commented on src/components/SubnavigationButton/SubnavigationButton.css
>  }
давай перенесём на 12 строку под объявление `.SubnavigationButton__in`?

2022-08-19 14:40 UTC, inomdzhon commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +  size?: "s" | "m" | "l";
Надо добавить красивый комментарий для параметров.

Недавно обращались с темой, что не все параметры у нас имеют описание... 😞 Поэтому стоит сразу описывать новые параметры и, по возможности, добавлять описание к текущим

2022-08-19 14:49 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        `SubnavigationButton--mode-${mode}`,
Заменил все `--sz-` и `--md-` на `--size-` и `--mode-`, 

css вырос на 138 байт
css gzip вырос на 7 байт
css brotli **уменьшился** на 21 байт

2022-08-19 15:00 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +  size?: "s" | "m" | "l";
Если у нас будет много избыточных комментариев, то мы можем приучить разработчиков пропускать все комментарии до единого, и из-за этого, не будут прочитаны те, которые действительно важны (by дядюшка боб)

Эти свойства понятны и не имеют каких-то неожиданных поведений

2022-08-19 15:05 UTC, inomdzhon commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +  size?: "s" | "m" | "l";
Тоже верно)

2022-08-22 08:25 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.css
>  }
✅

2022-08-22 08:25 UTC, SevereCloud commented on src/components/Counter/Counter.css
> +}
Убрал этот код

2022-08-23 07:25 UTC, inomdzhon commented on src/components/SubnavigationButton/SubnavigationButton.css
> +.SubnavigationButton--selected:not(.SubnavigationButton--mode-tertiary).SubnavigationButton--mode-tertiary
Тут ошибка – этот селектор никогда не сработает

2022-08-23 07:25 UTC, inomdzhon commented on src/components/SubnavigationButton/SubnavigationButton.css
> +  height: var(--vkui--size_button_small_height--regular);
Вижу у этого токена есть `--compact` – не нужно ли применять?

2022-08-23 08:51 UTC, eugpoloz commented on src/components/SubnavigationButton/SubnavigationButton.css
> +  height: var(--vkui--size_button_small_height--regular);
@inomdzhon `--compact` по идее для `sizeY`, а тут просто `small`-размер.

2022-08-23 09:47 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.css
> +  height: var(--vkui--size_button_small_height--regular);
Да, нужен compact. Я не туда посмотрел

2022-08-23 11:06 UTC, inomdzhon commented on src/components/SubnavigationButton/SubnavigationButton.css
> +  height: var(--vkui--size_button_small_height--regular);
@SevereCloud 

Забахаешь сразу так плиз
```css
/* TODO v5.0.0 поправить под новую адаптивность */
.SubnavigationButton--sizeY-compact.SubnavigationButton--s .SubnavigationButton__in {}
```

2022-08-23 11:07 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.css
> +  height: var(--vkui--size_button_small_height--regular);
ок

2022-08-23 14:08 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.css
> +.SubnavigationButton--selected:not(.SubnavigationButton--mode-tertiary).SubnavigationButton--mode-tertiary
Убрал

2022-08-23 14:08 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.css
> +  height: var(--vkui--size_button_small_height--regular);
✅

2022-08-26 09:29 UTC, Zaycevq approved these changes
👍🏽

2022-08-26 10:50 UTC, inomdzhon approved these changes

2022-08-30 11:36 UTC, eugpoloz commented on src/components/SubnavigationButton/SubnavigationButton.css
> +.SubnavigationButton--selected:not(.SubnavigationButton--mode-tertiary)
Все еще не нравится вот этот селектор, точно никак не можем его облегчить?

2022-08-30 11:36 UTC, eugpoloz commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +        {before && (
Ладно, вроде бы действительно работает и без нее сейчас. 😌

2022-08-30 11:36 UTC, eugpoloz commented on src/components/SubnavigationButton/SubnavigationButton.tsx
> +            aria-hidden
❤️

2022-08-30 14:15 UTC, SevereCloud commented on src/components/SubnavigationButton/SubnavigationButton.css
> +.SubnavigationButton--selected:not(.SubnavigationButton--mode-tertiary)
Есть предложения?

2022-09-01 09:45 UTC, eugpoloz approved these changes

2022-09-01 09:45 UTC, merged