Создание хука `useAdaptivityWithMediaQueries()` для всплывающих окон
VKCOM/VKUI pull request #3062
Opened 2022-08-24 11:43 UTC by inomdzhon

Создал хук `useAdaptivityWithMediaQueries()`, который слушает изменения вьюпорта, в отличии от `useAdaptivity()`.

## Дополнительно

- Вынес все константы, касаемые адаптива, в отдельный файл `adaptivity.ts`.
- Объединил константы с брейкпоинтами (`DESKTOP_SIZE`, `TABLET_SIZE` и т.п.) в `enum Breakpoints`.

## Чеклист

- [x] Проверил, что работает в SSR

## Нюанс

- `Alert`, `ActionSheet`, `ActionSheetItem`, `ModalDisimissButton` сравнивал с `master`

---

- close #3031

2022-08-24 11:50 UTC, stoope commented on src/lib/adaptivity.ts
> +export const MEDIA_QUERIES = {
Было бы круто и [тут](https://github.com/VKCOM/VKUI/blob/issue3031-AdaptivityProvider-revert-js-math-media/postcss.config.js#L81) завязаться на эти константы)
Такая возможность вроде [есть](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-custom-media)

2022-08-25 12:06 UTC, stoope commented on src/lib/browser.ts
> +    dispatchEvent() {
Давай добавим `warn` что не следует вызывать эти методы в nodejs, скорее всего ошибка

2022-08-25 12:22 UTC, stoope commented on src/components/ActionSheet/ActionSheetDropdown.tsx
> +        `ActionSheet--sizeY-${sizeY}`
Тут можно использовать `getSizeYClassName` )

2022-08-25 12:26 UTC, stoope commented on src/components/ActionSheet/ActionSheetDropdownDesktop.tsx
> +        `ActionSheet--sizeY-${sizeY}`
`getSizeYClassName`

2022-08-25 12:46 UTC, stoope requested changes

2022-08-25 12:46 UTC, stoope commented on src/components/ActionSheetItem/ActionSheetItem.tsx
> +        `ActionSheetItem--sizeY-${sizeY}`,
`getSizeYClassName`

2022-08-25 12:46 UTC, stoope commented on src/components/ModalPage/ModalPage.tsx
> +        sizeX && `ModalPage--${sizeX}`,
`getSizeXClassName("ModalPage", sizeX)`

2022-08-25 12:46 UTC, stoope commented on src/hooks/useIsDesktop.ts
> +export const useIsDesktop = (deviceType: DeviceType) => {
Это не хук получается, просто isDesktop

2022-08-25 12:46 UTC, stoope commented on src/hooks/useMediaQueries.ts
> +    function initializeStoreOrUpdateStoreIfWindowChanges() {
Не вижу здесь смысла использовать `useMemo` и отдельную функцию, это больше похоже на деоптимизацию)

2022-08-25 12:48 UTC, inomdzhon commented on src/hooks/useMediaQueries.ts
> +    function initializeStoreOrUpdateStoreIfWindowChanges() {
`useMemo` как раз помогает обновить `window`, чтобы избежать проблемы, о которой ты говорил

![image](https://user-images.githubusercontent.com/5850354/186668543-73ff64c7-3a40-488d-9a9d-7fe5e33bd902.png)

2022-08-25 12:53 UTC, inomdzhon commented on src/hooks/useIsDesktop.ts
> +export const useIsDesktop = (deviceType: DeviceType) => {
`isDesktop` я бы оставил под названия переменной

А то странно получается
```
const isDesktopVariable = isDesktop(deviceType);
```
\* постфикс `Variable` от балды, чтобы валидный пример был

Использовать `use` ничего плохого нет ведь

2022-08-25 12:54 UTC, inomdzhon commented on src/components/ActionSheet/ActionSheetDropdown.tsx
> +        `ActionSheet--sizeY-${sizeY}`
Не стал использовать, т.к. `none` не будет), но для единообразия давай заюзаем

2022-08-25 12:54 UTC, inomdzhon commented on src/lib/adaptivity.ts
> +export const MEDIA_QUERIES = {
✅

2022-08-25 12:59 UTC, inomdzhon commented on src/components/ActionSheet/ActionSheetDropdown.tsx
> +        `ActionSheet--sizeY-${sizeY}`
✅

2022-08-25 12:59 UTC, inomdzhon commented on src/components/ActionSheet/ActionSheetDropdownDesktop.tsx
> +        `ActionSheet--sizeY-${sizeY}`
✅

2022-08-25 13:24 UTC, stoope commented on src/hooks/useIsDesktop.ts
> +export const useIsDesktop = (deviceType: DeviceType) => {
К нему применяются правила хуков `eslint`. Можно checkIsDesktop)

2022-08-25 13:26 UTC, inomdzhon commented on src/lib/browser.ts
> +    dispatchEvent() {
✅

2022-08-25 13:30 UTC, stoope commented on src/components/ModalPage/ModalPage.tsx
> +        sizeX && `ModalPage--${sizeX}`,
Обрати плз внимание что здесь было `ModalPage--${sizeX}` а не `ModalPage--sizeX--${sizeX}`, возможно еще стили нужно поправить

2022-08-25 14:00 UTC, inomdzhon commented on src/hooks/useIsDesktop.ts
> +export const useIsDesktop = (deviceType: DeviceType) => {
Сделал ещё проще)) 

```diff
- const { deviceType } = useAdaptivityWithMediaQueries();
- const isDesktop = useIsDesktop(deviceType);
+ const { isDesktop } = useAdaptivityWithMediaQueries();
```

А `getDeviceType()` переименовал в  `checkIsDesktop()`

2022-08-25 14:04 UTC, inomdzhon commented on src/hooks/useMediaQueries.ts
> +    function initializeStoreOrUpdateStoreIfWindowChanges() {
Я изначально таки написал, но есть проблема при переключении экрана, вот демо

https://user-images.githubusercontent.com/5850354/186685930-643951dd-9437-4ab5-889f-414676e0bcd5.mov

2022-08-26 06:31 UTC, stoope commented on src/hooks/useMediaQueries.ts
> +    function initializeStoreOrUpdateStoreIfWindowChanges() {
Хм, странно, ладно)

2022-08-26 06:33 UTC, stoope commented
Скриншоты actionsheet сломались

2022-08-26 12:14 UTC, stoope approved these changes

2022-08-26 14:37 UTC, merged