feat(UsersStack): add `count`
VKCOM/VKUI pull request #3079
Opened 2022-08-26 10:55 UTC by SevereCloud

- closed #2699

2022-08-26 11:00 UTC, stoope requested changes

2022-08-26 11:00 UTC, stoope commented on src/components/UsersStack/UsersStack.tsx
> +  const othersCount = count || Math.max(0, photos.length - visibleCount);
`??` на случай `count=0`

2022-08-26 11:03 UTC, stoope commented on src/components/UsersStack/UsersStack.tsx
> +  count,
Можно даже прямо тут написать
`count = Math.max(0, photos.length - visibleCount)`

2022-08-26 11:32 UTC, SevereCloud commented on src/components/UsersStack/UsersStack.tsx
> +  const othersCount = count || Math.max(0, photos.length - visibleCount);
✅

2022-08-26 11:34 UTC, stoope commented
Может стоит предусмотреть кейс когда слишком большое число и писать, например, 99+?

2022-08-26 12:05 UTC, SevereCloud commented on src/components/UsersStack/UsersStack.tsx
> +  count,
✅

2022-08-29 11:45 UTC, SevereCloud commented
> Может стоит предусмотреть кейс когда слишком большое число и писать, например, 99+?

Это будет отдельной задачей

2022-08-29 12:09 UTC, stoope approved these changes

2022-08-29 12:09 UTC, merged