fix(Link): use `pointer: fine`
VKCOM/VKUI pull request #3470
Opened 2022-10-18 16:52 UTC by SevereCloud

Воспроизводится на Samsung A6+, но не воспроизводится на A12. Не зависит от браузера

- Fixes #3469

После исправления бага:

https://user-images.githubusercontent.com/14944123/196494535-dc2a6086-d95a-4931-b9fb-bc1ba64b20c9.mp4

2022-10-18 17:06 UTC, BlackySoul approved these changes

2022-10-18 17:10 UTC, inomdzhon requested changes

2022-10-18 17:10 UTC, inomdzhon commented on src/components/Link/Link.css
> +@media (pointer: fine) {
Есть такой нюанс, что `pointer: fine` это не обязательно мышь

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/196498785-3481db1d-121e-4bf2-aa1d-dff50a2e9e16.png">

2022-10-18 17:13 UTC, inomdzhon commented on src/components/Link/Link.css
> +@media (pointer: fine) {
Компонент использует `Tappable` – можно передать `hoverMode="Link--hover"`

2022-10-19 06:56 UTC, SevereCloud commented on src/components/Link/Link.css
> +@media (pointer: fine) {
Добавил hover: hover

2022-10-19 11:28 UTC, inomdzhon commented on src/components/Link/Link.css
> +@media (pointer: fine) {
А это не возвращает баг на Samsung?

2022-10-19 11:37 UTC, SevereCloud commented on src/components/Link/Link.css
> +@media (pointer: fine) {
`(hover: hover)` = true
`(pointer: fine)` = false

`true` and `false` = `false`

2022-10-19 13:30 UTC, inomdzhon approved these changes

2022-10-19 13:31 UTC, merged