fix(Calendar): Fix stacking context issue
VKCOM/VKUI pull request #3833
Opened 2022-12-16 17:15 UTC by BlackySoul

Т.к. мы [переопределяем](https://github.com/VKCOM/VKUI/blob/5.0-stable/src/components/Tappable/Tappable.module.css#L22) `z-index` для всех потомков `Tappable`, необходимо поднять `z-index` для шапки календаря, т.к. в ней инлайнится выпадашка с выбором месяца и года
_____

- адекватное решение будет в #3633

2022-12-16 18:20 UTC, SevereCloud approved these changes

2022-12-16 18:22 UTC, SevereCloud requested changes
А давай зададим Tappable `isolation: isolate`

2022-12-17 07:41 UTC, BlackySoul commented
> А давай зададим Tappable `isolation: isolate`

Изящно х)

2022-12-17 08:08 UTC, SevereCloud approved these changes
Нужно ещё скриншоты обновить

2022-12-19 09:31 UTC, inomdzhon approved these changes

2022-12-20 09:51 UTC, SevereCloud approved these changes

2022-12-20 10:55 UTC, inomdzhon approved these changes

2022-12-21 08:45 UTC, merged