fix Touch click handler after slide
VKCOM/VKUI pull request #3932
Opened 2022-12-31 10:35 UTC by bbonch

- vk.com/bbonch
- closed #3892

2023-01-09 06:08 UTC, BlackySoul commented
Привет! Спасибо за PR 🙂 
Стоит обратить внимание, что хак с `preventDefault` лечил вот [эту](https://github.com/VKCOM/VKUI/issues/1977) багу, кажется, что довольно частая ситуация, когда слайд в галерее оборачивают в ссылку

2023-01-18 14:57 UTC, inomdzhon commented
> > Привет! Спасибо за PR 🙂 Стоит обратить внимание, что хак с `preventDefault` лечил вот [эту](https://github.com/VKCOM/VKUI/issues/1977) багу, кажется, что довольно частая ситуация, когда слайд в галерее оборачивают в ссылку
> 
> Так пойдет?

Проверил в песочнице https://codesandbox.io/s/button-href-in-scroll-slrgjn – фикс работает 🎉 
#1977 также не воспроизводится 👍

2023-01-18 14:59 UTC, inomdzhon commented on packages/vkui/src/components/Touch/Touch.test.tsx
> -    });
Хм, эти тесты не выглядят лишними 🤔 
Почему решил удалить?

2023-01-18 15:00 UTC, inomdzhon commented on packages/vkui/src/components/Touch/Touch.tsx
> +      if ((e.target as HTMLElement).closest('a')) {
```suggestion
      // https://github.com/VKCOM/VKUI/issues/1977
      // https://github.com/VKCOM/VKUI/issues/3892
      if ((e.target as HTMLElement).closest('a')) {
```
давай добавим ссылки на issues, которые чинит это условие

2023-01-18 21:41 UTC, bbonch commented on packages/vkui/src/components/Touch/Touch.tsx
> +      if ((e.target as HTMLElement).closest('a')) {
Добавил.

2023-01-19 09:15 UTC, inomdzhon requested changes

2023-01-19 09:15 UTC, inomdzhon commented on packages/vkui/src/components/Touch/Touch.test.tsx
> +    it('does not prevent click of a button after slide of a parent on mobile', () => {
Правильней было бы назвать
```suggestion
    it('should not prevent click to link after scroll with touch', () => {
```

Но вообще тест на текущий момент не покрывает кейс, он работает что до, что и после.

Надо переписать тест так, чтобы он падал при старой реализации `Touch` (до изменений).

2023-01-19 09:15 UTC, inomdzhon commented on packages/vkui/src/components/Touch/Touch.tsx
> +      if ((e.target as HTMLElement).closest('a')) {
Кстати, проверять на ссылку уже не нужно, поэтому давай удалим условие

2023-01-19 22:18 UTC, bbonch commented on packages/vkui/src/components/Touch/Touch.tsx
> +      if ((e.target as HTMLElement).closest('a')) {
Убрал

2023-01-19 22:18 UTC, bbonch commented on packages/vkui/src/components/Touch/Touch.test.tsx
> -    });
Вернул

2023-01-19 22:19 UTC, bbonch commented on packages/vkui/src/components/Touch/Touch.test.tsx
> +    it('does not prevent click of a button after slide of a parent on mobile', () => {
Тест исправил

2023-01-20 08:16 UTC, inomdzhon reviewed
Отлично! Спасибо за правки 🙏 

`lint:prettier` упал. Надо натравить `prettier` на файлик https://github.com/VKCOM/VKUI/actions/runs/3962836290/jobs/6789990357

2023-01-24 11:10 UTC, inomdzhon commented
> Я каждый день запускал перед комитом. У вас проблемы с prettier.

Подскажи, плиз, ты имеешь ввиду, что запускал `test:ci`?

Проверил локально упавшую проверку на файле `рackages/vkui/src/components/Touch/Touch.test.tsx`

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/214274818-836ae57a-f200-4f37-b96a-c07aa39af008.png">

Он ругается, что не хватает скобок для `typeof keys` в 124 строчке

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/214274337-704da8b5-c7fe-4605-b2bc-ca4faa51d178.png">

Вот эти ([ссылка](https://github.com/VKCOM/VKUI/pull/3932/files#diff-cbc0791a28aac79202fc4b041d79abf9146dcf02b156303a1924f439fe9723dcR124)) изменения на 124 строчке не ты вручную, получается, внёс?

---

PS: как ты мог заметить, у нас **e2e** тесты не проходят. Это [git lfs](https://git-lfs.com/) переполнил лимит на объем хранилища выделяемое GitHub. Пока все PR встали. Разбираемся.

2023-01-24 15:10 UTC, bbonch commented
> > Я каждый день запускал перед комитом. У вас проблемы с prettier.
> 
> Подскажи, плиз, ты имеешь ввиду, что запускал `test:ci`?
> 
> Проверил локально упавшую проверку на файле `рackages/vkui/src/components/Touch/Touch.test.tsx`
> 
> <img alt="image" width="320" src="https://user-images.githubusercontent.com/5850354/214274818-836ae57a-f200-4f37-b96a-c07aa39af008.png">
> 
> Он ругается, что не хватает скобок для `typeof keys` в 124 строчке
> 
> <img alt="image" width="320" src="https://user-images.githubusercontent.com/5850354/214274337-704da8b5-c7fe-4605-b2bc-ca4faa51d178.png">
> 
> Вот эти ([ссылка](https://github.com/VKCOM/VKUI/pull/3932/files#diff-cbc0791a28aac79202fc4b041d79abf9146dcf02b156303a1924f439fe9723dcR124)) изменения на 124 строчке не ты вручную, получается, внёс?
> 
> PS: как ты мог заметить, у нас **e2e** тесты не проходят. Это [git lfs](https://git-lfs.com/) переполнил лимит на объем хранилища выделяемое GitHub. Пока все PR встали. Разбираемся.

Я запускал вручную yarn prettier -write ....Touch.tsx/Touch.test.tsx. Без этого не мог коммитить.
124 я не трогал.
Так, что мне нужно сделать или запустить чтобы заработали тесты?

2023-01-24 15:26 UTC, inomdzhon commented
> > > Я каждый день запускал перед комитом. У вас проблемы с prettier.
> > 
> > 
> > Подскажи, плиз, ты имеешь ввиду, что запускал `test:ci`?
> > Проверил локально упавшую проверку на файле `рackages/vkui/src/components/Touch/Touch.test.tsx`
> > <img alt="image" width="320" src="https://user-images.githubusercontent.com/5850354/214274818-836ae57a-f200-4f37-b96a-c07aa39af008.png">
> > Он ругается, что не хватает скобок для `typeof keys` в 124 строчке
> > <img alt="image" width="320" src="https://user-images.githubusercontent.com/5850354/214274337-704da8b5-c7fe-4605-b2bc-ca4faa51d178.png">
> > Вот эти ([ссылка](https://github.com/VKCOM/VKUI/pull/3932/files#diff-cbc0791a28aac79202fc4b041d79abf9146dcf02b156303a1924f439fe9723dcR124)) изменения на 124 строчке не ты вручную, получается, внёс?
> > PS: как ты мог заметить, у нас **e2e** тесты не проходят. Это [git lfs](https://git-lfs.com/) переполнил лимит на объем хранилища выделяемое GitHub. Пока все PR встали. Разбираемся.
> 
> Я запускал вручную yarn prettier -write ....Touch.tsx/Touch.test.tsx. Без этого не мог коммитить. 124 я не трогал. Так, что мне нужно сделать или запустить чтобы заработали тесты?

Запусти, пожалуйста, вот так:
```sh
yarn lint:prettier --write
```

Или ты именно так и запускаешь?

2023-01-31 15:01 UTC, inomdzhon commented
Так и не получил ответа https://github.com/VKCOM/VKUI/pull/3932#issuecomment-1402133855 😞

2023-01-31 15:13 UTC, bbonch commented
> Так и не получил ответа [#3932 (comment)](https://github.com/VKCOM/VKUI/pull/3932#issuecomment-1402133855) 😞

Я писал выше, как запускал. Зачем мне запускать для всех файлов если только 2 изменял?
Запустил `yarn lint:prettier --write`. Он изменил 900+ файлов. Что это? Попробую еще раз запустить вручную для 2 файлов, которые менял.

2023-01-31 16:07 UTC, inomdzhon commented
> > Так и не получил ответа [#3932 (comment)](https://github.com/VKCOM/VKUI/pull/3932#issuecomment-1402133855) 😞
> 
> Я писал выше, как запускал. Зачем мне запускать для всех файлов если только 2 изменял? Запустил `yarn lint:prettier --write`. Он изменил 900+ файлов. Что это? Попробую еще раз запустить вручную для 2 файлов, которые менял.

А ты какое OC используешь? Коллега говорит, что на Windows могут быть проблемы :( (https://prettier.io/docs/en/options.html#end-of-line)

2023-01-31 16:10 UTC, bbonch commented
> > > Так и не получил ответа [#3932 (comment)](https://github.com/VKCOM/VKUI/pull/3932#issuecomment-1402133855) 😞
> > 
> > 
> > Я писал выше, как запускал. Зачем мне запускать для всех файлов если только 2 изменял? Запустил `yarn lint:prettier --write`. Он изменил 900+ файлов. Что это? Попробую еще раз запустить вручную для 2 файлов, которые менял.
> 
> А ты какое OC используешь? Коллега говорит, что на Windows могут быть проблемы :( (https://prettier.io/docs/en/options.html#end-of-line)

Windows + VS Code.

2023-02-05 18:04 UTC, bbonch commented
`git config core.autocrlf true`
Зачем это запускать? Оно по умолчанию `true`.
Я запустил 
`$ C:\Users\dmitr\source\repos\VKUI\node_modules\.bin\prettier --check packages/vkui/src/components/Touch/Touch.tsx
Checking formatting...
All matched files use Prettier code style!
Done in 0.65s.`
`$ C:\Users\dmitr\source\repos\VKUI\node_modules\.bin\prettier --check packages/vkui/src/components/Touch/Touch.test.tsx
Checking formatting...
All matched files use Prettier code style!
Done in 0.74s.`
Оба файла Unix(LF). Что я должен сделать чтобы Pull Request / test / test (pull_request_target) заработал?
`[1] [lint:prettier] [warn] packages/vkui/src/components/Touch/Touch.test.tsx`
`[1] [lint:prettier] [warn] Code style issues found in the above file. Forgot to run Prettier?`
What issues? Он не показывает, что именно не правильно.
https://github.com/bbonch/VKUI/blob/fix-3892/packages/vkui/src/components/Touch/Touch.tsx
https://github.com/bbonch/VKUI/blob/fix-3892/packages/vkui/src/components/Touch/Touch.test.tsx
Оба Unix(LF).

2023-02-06 15:08 UTC, inomdzhon commented on packages/vkui/src/components/Touch/Touch.test.tsx
> +    const makeHandlers = (): { [k in typeof keys[number]]: jest.Mock } => {
```suggestion
    const makeHandlers = (): { [k in (typeof keys)[number]]: jest.Mock } => {
```

2023-02-07 15:20 UTC, inomdzhon commented
> `git config core.autocrlf true` Зачем это запускать? Оно по умолчанию `true`. Я запустил `$ C:\Users\dmitr\source\repos\VKUI\node_modules\.bin\prettier --check packages/vkui/src/components/Touch/Touch.tsx Checking formatting... All matched files use Prettier code style! Done in 0.65s.` `$ C:\Users\dmitr\source\repos\VKUI\node_modules\.bin\prettier --check packages/vkui/src/components/Touch/Touch.test.tsx Checking formatting... All matched files use Prettier code style! Done in 0.74s.` Оба файла Unix(LF). Что я должен сделать чтобы Pull Request / test / test (pull_request_target) заработал? `[1] [lint:prettier] [warn] packages/vkui/src/components/Touch/Touch.test.tsx` `[1] [lint:prettier] [warn] Code style issues found in the above file. Forgot to run Prettier?` What issues? Он не показывает, что именно не правильно. https://github.com/bbonch/VKUI/blob/fix-3892/packages/vkui/src/components/Touch/Touch.tsx https://github.com/bbonch/VKUI/blob/fix-3892/packages/vkui/src/components/Touch/Touch.test.tsx Оба Unix(LF).

Закоммитил сброс изменения 124 строчки. Теперь тест проходит ✅ 

Вот тут писал, что не так в 124 строчке https://github.com/VKCOM/VKUI/pull/3932#issuecomment-1401752508

Почему `prettier --fix` у тебя форматирует по другому пока не поняли 🤔  Коллега проверила команду на Windows – у неё не воспроизвелось.

2023-02-07 15:21 UTC, inomdzhon approved these changes
Апрув ✅

Ещё раз спасибо за фикс 🙏

Ты внёс фикс по программе [fix bounty](https://github.com/VKCOM/VKUI/labels/%F0%9F%94%A5%20fix%20bounty). После мержа в течение суток или двух тебе начисляться баллы.

2023-02-08 04:51 UTC, BlackySoul approved these changes

2023-02-08 07:28 UTC, merged

2023-02-08 07:30 UTC, vkcom-publisher commented
## ⚠️ Patch (forked repo)

Необходимо вручную перенести исправление в стабильную ветку.

> Дальнейшие действия выполняют контрибьютеры из группы @VKCOM/vkui-core

Чтобы исправление попало в стабильную ветку, выполните следующие действия:

1. Создайте новую ветку от стабильной и примените исправления используя cherry-pick

```bash
git stash # опционально
git fetch origin 5.1-stable
git checkout -b patch/pr3932 origin/5.1-stable
git cherry-pick 2b0e809e00094b2236dc3698a08c2e4b8b6a4135 2d97263523c5089a001e8402cd83770c230b0348 9b9eb71b71e2727bef1d600ba909aac78d2ce347 9c7707d71b0984bba0ff9b148e6a8c8d0053b235 7e8aa14537fedf42a790bdd9170e5db49ccc7b6d 73304ecda5293fa3fdaed5bce5e4ee3d60d93c5d 1bfb371fba28c212e0d5b2a559bc41b6368c7581 17a6b73d43a68483873a95e20e3655800df7cdb5 0690c3b1aff4e42dfe05bb3e753774f14b6a612b b40bb276134eef1c66fc9b0008045325cf6b1103 2e65727f53d637d33da4671758ea80b4250e3717 7d06cf35c8256a46044b8952380d21aad428bbfa d4ec619ae2763ad8d3bb8542f61f2c4d4d30cd99
```

2. Исправьте конфликты, следуя инструкциям из терминала
3. Отправьте ветку на GitHub и создайте новый PR с последней стабильной веткой (метка patch не нужна)

```bash
git push --set-upstream origin patch/pr3932
gh pr create --base 5.1-stable --title "patch: pr3932" --body "- patch #3932"
```