ci(deps): bump JamesIves/github-pages-deploy-action from 3.7.1 to 4.4.1
VKCOM/VKUI pull request #4046
Opened 2023-01-25 15:42 UTC by inomdzhon

### Дополнительно

Отключил выгрузку `styleguide` в артифакты если это PR от `dependabot`, т.к. мы не запускаем `deploy_styleguide` для него

2023-01-25 16:04 UTC, SevereCloud requested changes
Необходимо еще обновить в publish.yml
  
  https://github.com/VKCOM/VKUI/blob/63820ea5876be268f06f16750ac5a02e84e4120b/.github/workflows/publish.yml#L85-L91

2023-01-25 16:04 UTC, SevereCloud commented on .github/workflows/pull_request.yml
> +          clean: true
```suggestion
          clean: true
          force: false
```

2023-01-26 09:30 UTC, SevereCloud submitted a review, later dismissed

2023-01-28 08:36 UTC, SevereCloud commented on .github/workflows/pull_request.yml
> +      - uses: actions/checkout@v3
Зачем необходим чекаут?

2023-01-29 10:53 UTC, inomdzhon commented on .github/workflows/pull_request.yml
> +      - uses: actions/checkout@v3
А иначе падает с ошибкой

```sh
Configuring git…
/usr/bin/git config user.name inomdzhon
fatal: not in a git directory
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌
```

Из этой дискуссии https://github.com/JamesIves/github-pages-deploy-action/discussions/651 узнал, что нужен чекаут.

Вот ещё скрин из доки:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/215321253-f8ae9fb8-a1a9-4709-9891-7193041203a5.png">

2023-01-29 10:53 UTC, SevereCloud approved these changes

2023-01-29 10:57 UTC, merged