docs(Select): fix missing Select doc page
VKCOM/VKUI pull request #4052
Opened 2023-01-26 15:29 UTC by inomdzhon

Вынес `SelectTypography` в саб-компонент.

---

- fix #4051

2023-01-26 21:25 UTC, eugpoloz approved these changes
❤️

2023-01-31 12:01 UTC, SevereCloud requested changes

2023-01-31 16:27 UTC, inomdzhon commented on packages/vkui/src/components/Select/Select.tsx
> +Select.Typography = SelectTypography;
✅

2023-02-01 14:05 UTC, SevereCloud approved these changes

2023-02-01 14:10 UTC, BlackySoul approved these changes

2023-02-01 14:12 UTC, merged