feat(warnOnce): add COMMON_WARNINGS object
VKCOM/VKUI pull request #4111
Opened 2023-02-02 13:32 UTC by eugpoloz

И снова вытаскиваю всякое из https://github.com/VKCOM/VKUI/pull/3803.

Что сделала:
- добавила объект `COMMON_WARNINGS`, чтобы не переписывать одни и те же варнинги по несколько раз
- `WriteBarIcon`: исправила текст варнинга на текст из `COMMON_WARNINGS` внутри 
- `IconButton`: добавила a11y-варнинг
- `TabbarItem`: добавила a11y-варнинг

2023-02-07 14:34 UTC, inomdzhon approved these changes
👍

оставил необязательный комменик

2023-02-07 14:34 UTC, inomdzhon commented on packages/vkui/src/lib/warnOnce.ts
> +  return 'https://dequeuniversity.com/rules/axe/' + AXE_CORE_MINOR_VERSION + '/' + ruleName;
Тут можно было бы тоже использовать **Template literals** как ниже :)

2023-02-08 13:38 UTC, SevereCloud requested changes

2023-02-08 13:38 UTC, SevereCloud commented on packages/vkui/src/components/ContentCard/ContentCard.tsx
> +  if (process.env.NODE_ENV === 'development' && (src || srcSet) && !alt) {
**issue:** Что насчет `aria-label` и `aria-labelledby`

В [документации](https://dequeuniversity.com/rules/axe/4.5/image-alt) эти атрибуты указываются как одно из решений

2023-02-08 13:38 UTC, SevereCloud commented on packages/vkui/src/components/TabbarItem/TabbarItem.tsx
> +  if (process.env.NODE_ENV === 'development' && !restProps['aria-label'] && !text) {
**issue:** нужно добавить проверку `aria-labelledby` и ролей

В [документации](https://dequeuniversity.com/rules/axe/4.5/button-name) сообщается о возможности использования `aria-labelledby` (и `title`?)

2023-02-09 16:46 UTC, eugpoloz commented on packages/vkui/src/components/ContentCard/ContentCard.tsx
> +  if (process.env.NODE_ENV === 'development' && (src || srcSet) && !alt) {
Смотрела-смотрела на это и поняла, что все слишком усложняю. 😆

+ Утащила `ContentCard` в https://github.com/VKCOM/VKUI/pull/4188

2023-02-09 16:48 UTC, eugpoloz commented on packages/vkui/src/lib/warnOnce.ts
> +  return 'https://dequeuniversity.com/rules/axe/' + AXE_CORE_MINOR_VERSION + '/' + ruleName;
✔️ 

Раз все равно фиксила замечания Дани, то и тут тоже пофиксила!

2023-02-09 16:48 UTC, eugpoloz commented on packages/vkui/src/components/ContentCard/ContentCard.tsx
> +  if (process.env.NODE_ENV === 'development' && (src || srcSet) && !alt) {
- Тоже уехало в https://github.com/VKCOM/VKUI/pull/4188

2023-02-09 16:50 UTC, eugpoloz commented on packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx
>    if (process.env.NODE_ENV === 'development' && !restProps['aria-label'] && !ariaLabel) {
✔️ `aria-labelledby`

Про роли обсудили, что не хотим так делать, чтобы не поощрять дичь в верстке; `title` здесь тоже не даст нужного эффекта по идее.

2023-02-09 16:50 UTC, eugpoloz commented on packages/vkui/src/components/TabbarItem/TabbarItem.tsx
> +  if (process.env.NODE_ENV === 'development' && !restProps['aria-label'] && !text) {
✔️ `aria-labelledby`

2023-02-09 16:51 UTC, SevereCloud approved these changes

2023-02-13 12:31 UTC, inomdzhon approved these changes

2023-02-13 12:34 UTC, merged