Imirdzhamolov/4112/ci/optimizing branch test worflow
VKCOM/VKUI pull request #4113
Opened 2023-02-02 16:27 UTC by inomdzhon

Заодно изменил названия файлов, а для переиспользуемых воркфлоу добавил `name` с префиксом `Reusable workflow`, чтобы они выделялись в списке экшенов

---

- close #4112

2023-02-02 17:44 UTC, SevereCloud requested changes

2023-02-02 17:44 UTC, SevereCloud commented on .github/workflows/reusable_workflow_test_e2e.yml
> +        run: yarn workspaces run test:e2e:ci
> error Command "test:e2e:ci" not found.

2023-02-02 20:35 UTC, inomdzhon commented on .github/workflows/reusable_workflow_test_e2e.yml
> +        run: yarn workspaces run test:e2e:ci
Вернул как было)) Забыл, что e2e тесты подточены чисто под `@vkontakte/vkui`

🙏 🙏 🙏

2023-02-07 04:39 UTC, BlackySoul approved these changes

2023-02-07 13:18 UTC, eugpoloz commented on .github/workflows/reusable_workflow_test.yml
> +        description: 'Run test for concrete workspace'
```suggestion
        description: 'Workspace to run tests in (if empty, runs tests for all workspaces)'
```

2023-02-07 13:18 UTC, eugpoloz commented on .github/workflows/reusable_workflow_test.yml
> +      - name: Run tests for concrete workspace
```suggestion
      - name: Run tests for the specified workspace
```

2023-02-07 13:28 UTC, inomdzhon commented on .github/workflows/reusable_workflow_test.yml
> +        description: 'Run test for concrete workspace'
✅

2023-02-07 13:28 UTC, inomdzhon commented on .github/workflows/reusable_workflow_test.yml
> +      - name: Run tests for concrete workspace
✅

2023-02-07 13:39 UTC, BlackySoul approved these changes

2023-02-07 16:29 UTC, merged