fix(HorizontalCell): fix design review notes
VKCOM/VKUI pull request #4199
Opened 2023-02-10 11:58 UTC by BlackySoul

- fix #4168 

+ добавление возможности использовать прямоугольные `Image` пойдет отдельной фичой

2023-02-10 13:15 UTC, SevereCloud requested changes

2023-02-10 13:15 UTC, SevereCloud commented on packages/vkui/src/components/HorizontalCell/HorizontalCell.module.css
> +.HorizontalCell--ios:first-child::before,
Давайте токенами сделаем, мы максимально уходим от платформенных стилей

2023-02-10 13:15 UTC, SevereCloud commented on packages/vkui/src/components/HorizontalCell/Readme.md
> +      <Avatar size={56} src={user.photo_100} />
Чуть выше нужно const platform = usePlatform(); удалить

2023-02-27 09:01 UTC, SevereCloud commented on packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx
> +        platform === Platform.IOS && styles['HorizontalCell--ios'],
Нужно убрать

2023-02-28 11:51 UTC, SevereCloud submitted a review, later dismissed

2023-03-01 14:38 UTC, eugpoloz commented on packages/vkui/src/components/ImageBase/ImageBase.tsx
> +        {withBorder && <div role="presentation" className={styles['ImageBase__border']} />}
```suggestion
        {withBorder && <div aria-hidden className={styles['ImageBase__border']} />}
```

2023-03-01 14:38 UTC, eugpoloz commented on packages/vkui/src/components/HorizontalCell/HorizontalCell.module.css
> +  min-width: calc(var(--vkui--size_base_padding_horizontal--regular) - 6px);
Немного смущают магические цифры, которые мы вычитаем, здесь и чуть ниже для `--size-s`,  с ними нельзя ничего сделать? Договориться с дизайном, например, что `:before` и `:after` у нас будут 1/2 от `--vkui--size_base_padding_horizontal--regular`.

Что скажешь?

2023-03-01 14:38 UTC, eugpoloz commented on packages/vkui/src/components/HorizontalCell/HorizontalCell.module.css
> +  min-width: calc(var(--vkui--size_base_padding_horizontal--regular) - 8px);
Тут точно правильный токен? Не должно ли на этом месте быть что-то вроде `--vkui--size_base_padding_horizontal--small`?

2023-04-06 15:05 UTC, SevereCloud approved these changes

2023-04-07 13:00 UTC, SevereCloud submitted a review, later dismissed

2023-04-10 12:17 UTC, eugpoloz approved these changes

2023-04-17 12:39 UTC, inomdzhon approved these changes

2023-04-17 12:54 UTC, SevereCloud approved these changes

2023-05-17 13:28 UTC, Zaycevq approved these changes

2023-05-17 13:39 UTC, merged