feature(UsersStack): add align prop + fix counter text token
VKCOM/VKUI pull request #4416
Opened 2023-03-07 08:47 UTC by BlackySoul

- resolve #4415

2023-03-07 08:50 UTC, SevereCloud reviewed
Что насчет скриншотных тестов?

2023-03-07 08:57 UTC, BlackySoul commented on packages/vkui/src/components/UsersStack/UsersStack.tsx
> +  align?: 'left' | 'right';
Ну или если соответствовать дизайну, то `align=top`, ещё спросила у дизайнеров, не нужно ли добавлять `bottom` 🙂 
Добавлю для `v6` коммент

2023-03-07 10:52 UTC, SevereCloud commented on packages/vkui/src/components/UsersStack/UsersStack.tsx
> +  align = 'left',
Что насчет скриншотных тестов для `align`?

2023-03-07 11:08 UTC, SevereCloud approved these changes

2023-03-07 11:20 UTC, SevereCloud requested changes

2023-03-07 11:20 UTC, SevereCloud commented on packages/vkui/src/components/UsersStack/UsersStack.module.css
> +  color: var(--vkui--color_text_contrast_themed);
В макетах неверный цвет, правильный просто contrast

```suggestion
  color: var(--vkui--color_text_contrast);
```

2023-03-14 11:54 UTC, SevereCloud approved these changes

2023-03-20 11:16 UTC, SevereCloud submitted a review, later dismissed

2023-03-20 13:56 UTC, inomdzhon commented on packages/vkui/src/components/UsersStack/UsersStack.tsx
> +  align?: 'left' | 'right';
@BlackySoul @SevereCloud может обсудить с дизигном на счёт изменения нейминга на `direction`?

Как во флексах
```
type Direction = "row" | "column" | "row-reverse";
```

`align` про выравнивание

2023-03-27 10:05 UTC, BlackySoul commented on packages/vkui/src/components/UsersStack/UsersStack.tsx
> +  align?: 'left' | 'right';
Поговорила с Лешей, он дал добро х)

2023-03-27 11:41 UTC, SevereCloud approved these changes

2023-03-27 11:56 UTC, eugpoloz commented on packages/vkui/src/components/UsersStack/UsersStack.tsx
> +   * @deprecated
**suggestion:** давай добавим варнинг в консоль через `warnOnce` для тех, кто использует этот проп?

2023-03-27 14:18 UTC, inomdzhon approved these changes

2023-03-28 08:21 UTC, merged