feat(Form): добавляем новый компонент Form на замену FormLayout
VKCOM/VKUI pull request #4576
Opened 2023-03-23 15:19 UTC by eugpoloz

Описание из связанной задачи:

> Сначала мы хотели добавить доступность скрытой кнопке сабмита внутри FormLayout (см. https://github.com/VKCOM/VKUI/pull/4005).
>
> Потом пришли к выводу, что скрытой кнопки не должно быть вообще — в форме всегда должна быть какая-то очевидная и доступная всем кнопка с type="submit". В итоге решили, что лучше всего будет сделать новый компонент, а старый задепрекейтить.

### Что сделала:
- [x] создала компонент `Form` без скрытого инпута
  - [x] добавила примеры использования этого компонента
  - [x] добавила историю в storybook
- [x] заменила везде в примерах `FormLayout` на `Form`
- [x] задепрекейтила `FormLayout`

-----
- Closes https://github.com/VKCOM/VKUI/issues/4004

2023-03-31 13:22 UTC, SevereCloud commented on packages/vkui/src/components/Form/Form.tsx
> +      ref={getRef}
Нужен getRootRef

2023-03-31 13:22 UTC, SevereCloud commented on packages/vkui/src/components/FormLayout/FormLayout.tsx
> + * @deprecated since v5.4.0
Нужно описание

2023-03-31 13:22 UTC, SevereCloud commented on packages/vkui/src/components/Popover/Readme.md
> +      <Button style={{ margin: '20px 0 0 0' }}>Кликни, чтобы открыть форму</Button>
Мб Spacing вместо margin-а

2023-04-03 11:58 UTC, eugpoloz commented on styleguide/deprecated.js
>  // styleguidist должен парсить @deprecated-компоненты автоматически,
О, кстати, надо бы проверить!

2023-04-03 12:22 UTC, eugpoloz commented on packages/vkui/src/components/FormLayout/FormLayout.tsx
> + * @deprecated since v5.3.0
Резолвлю сама в пользу более нового комментария!

2023-04-04 14:41 UTC, eugpoloz commented on styleguide/deprecated.js
>  // styleguidist должен парсить @deprecated-компоненты автоматически,
✔️ 

- https://github.com/VKCOM/VKUI/pull/4701

2023-04-04 14:42 UTC, eugpoloz commented on packages/vkui/src/components/Form/Form.tsx
> +      ref={getRef}
✔️

2023-04-04 14:43 UTC, eugpoloz commented on packages/vkui/src/components/Popover/Readme.md
> +      <Button style={{ margin: '20px 0 0 0' }}>Кликни, чтобы открыть форму</Button>
✔️

2023-04-07 13:17 UTC, SevereCloud commented on styleguide/Components/Table/TableRenderer.js
> +                        <span>Скрыть дополнительные свойства и методы</span>
Методов у нас нет, только свойства

2023-04-07 13:28 UTC, eugpoloz commented on styleguide/Components/Table/TableRenderer.js
> +                        <span>Скрыть дополнительные свойства и методы</span>
Точно, спасибо! Случайно остался непофикшенный коммит из ветки со стайлгайдом. Моя внимательность на этой неделе в окно вышла.)))
✔️

2023-04-07 13:29 UTC, SevereCloud approved these changes

2023-04-07 16:33 UTC, SevereCloud approved these changes

2023-04-11 08:04 UTC, BlackySoul commented on packages/vkui/src/components/Form/Form.stories.tsx
> +export const Playground = Template.bind({});
Нужно переписать на csf3 сторю x)

2023-04-11 08:26 UTC, eugpoloz commented on packages/vkui/src/components/Form/Form.stories.tsx
> +export const Playground = Template.bind({});
✔️

2023-04-11 08:26 UTC, SevereCloud approved these changes

2023-04-11 08:47 UTC, BlackySoul approved these changes

2023-04-11 09:10 UTC, inomdzhon requested changes

2023-04-11 09:10 UTC, inomdzhon commented on packages/vkui/src/components/Form/Form.tsx
Может нам и не нужен компонент `Form`? Ведь формы это уже что-то посложнее и от проекта к проекту отличаются

С нашей стороны мы отдаём `FormLayoutGroup`, который помогает настроить визуальную часть, а всё остальное уже не задача ui кита

Пользователь сам своей стороне оборачивает в `<form>` или использует готовую библиотеку для работы с формами (например, `react-final-form`)

---

И вот задепрейкить `FormLayout` точно надо 👍

2023-04-26 10:04 UTC, closed without merging