feat(Group): add ExpandedContent
VKCOM/VKUI pull request #4669
Opened 2023-03-31 12:11 UTC by SevereCloud

Добавляем компонент для растягивания контента на всю ширину,
игнорируя боковые отступы.

2023-03-31 12:15 UTC, fedorov-xyz requested changes

2023-03-31 12:23 UTC, fedorov-xyz commented on packages/vkui/src/components/Group/Group.tsx
> +Group.ExpandedContent = ExpandedContent;
Надо именно через Object.assign делать, иначе TS кривые типы генерирует.

2023-04-19 09:10 UTC, SevereCloud commented on packages/vkui/src/components/Group/Group.tsx
> +Group.ExpandedContent = ExpandedContent;
Проверил, все генерирует нормально

2023-04-19 09:24 UTC, inomdzhon commented on packages/vkui/src/components/Group/Readme.md
Обновишь ещё доку в Storybook?

2023-04-19 09:24 UTC, inomdzhon commented on packages/vkui/src/components/Group/ExpandedContent/ExpandedContent.tsx
> +export const ExpandedContent = ({
Учитывая, что параметр в `Group` называется `padding`, то семантичней назвать `ExcludedHorizontalPaddingContent` или `ExcludedXPaddingContent`. Да, в ущерб короткому названию. В общем, хотелось бы название, которое говорит о том, что "вот того самого `padding` по горизонтали не будет".

`Expanded` ассоциируется с аккордеоном или селектом

2023-04-20 08:41 UTC, SevereCloud commented on packages/vkui/src/components/Group/Readme.md
Добавил

2023-06-13 07:57 UTC, SevereCloud commented on packages/vkui/src/components/Group/ExpandedContent/ExpandedContent.tsx
> +export const ExpandedContent = ({
✅

2023-06-28 10:04 UTC, closed without merging