chore: Upgrade storybook to v7
VKCOM/VKUI pull request #4746
Opened 2023-04-06 06:45 UTC by BlackySoul

Что изменилось:
- мигрированы стори с `csf2`-формата на новый `csf3` (меньше кода нужно, типы выводятся лучше)
- подняты версии некоторых зависимостей (должны уйти `security` алерты от `dependabot`)

2023-04-06 07:05 UTC, SevereCloud approved these changes

2023-04-06 07:13 UTC, SevereCloud requested changes
А сделай yarn install. Там лишние зависимости не удалились

2023-04-07 12:49 UTC, eugpoloz commented on packages/vkui/package.json
> +    "build-storybook": "cross-env SANDBOX=\\.storybook FROM_STORYBOOK=1 storybook build"
```suggestion
    "storybook:build": "cross-env SANDBOX=\\.storybook FROM_STORYBOOK=1 storybook build"
```

2023-04-07 12:49 UTC, eugpoloz commented on packages/vkui/.storybook/addons/pointer/HasPointer.tsx
> +    <IconButton active={hasPointer} nonce={undefined} key="pointer" onClick={toggleHasPointer}>
Вопрос: а что такое этот `nonce`? 🙈

2023-04-07 12:50 UTC, eugpoloz commented
@BlackySoul и тут конфликты еще какие-то нарисовались, подтянешь мастер?

2023-04-07 14:05 UTC, SevereCloud approved these changes

2023-04-07 14:18 UTC, eugpoloz approved these changes
Ну красивое же 🚀 
<img width="163" alt="image" src="https://user-images.githubusercontent.com/22026957/230623982-976c6dee-f0e5-4732-a4da-4196633518d5.png">

2023-04-10 05:32 UTC, SevereCloud approved these changes

2023-04-10 05:53 UTC, merged