feat(ModalPage, PanelHeader): upgrade a11y
VKCOM/VKUI pull request #4808
Opened 2023-04-11 12:47 UTC by knenkne

Относится к https://github.com/VKCOM/VKUI/issues/3041, ориентировался на [WCAG пример](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/).

Возможно, изменение `PanelHeader` в таком явном виде не нужно (как я понял, компонент используется не только внутри модалок?), а следует трогать `ModalPageHeader`, передавая `PanelHeader` новые пропсы   - нужно ваше мнение.

Помимо `ModalPage` могу помочь и с `ModalCard` в рамках новой задачи.

2023-04-11 12:59 UTC, SevereCloud requested changes

2023-04-11 13:01 UTC, knenkne commented on packages/vkui/src/components/PanelHeader/PanelHeader.tsx
> Давай действительно лучше потрогаем ModalPageHeader вместо PanelHeader
Окей, но в `PanelHeader` в любом случае придется лезть посредством новых пропов, чтобы менять тег заголовка на `h2`, одобряете такое или есть лучше идеи?

2023-04-12 11:37 UTC, knenkne commented on packages/vkui/src/components/ModalPage/ModalPage.tsx
> +  const contextValue = React.useMemo(() => ({ labelId: id ? `${id}-label` : void '' }), [id]);
> Давай если нет id, то сгенерируем его используя useId()

А действительно ли это имеет смысл? Разве модальное окно без `id`  может существовать? Как оно в таком случае будет открываться?

2023-04-12 11:38 UTC, SevereCloud commented on packages/vkui/src/components/ModalPage/ModalPage.tsx
> +  const contextValue = React.useMemo(() => ({ labelId: id ? `${id}-label` : void '' }), [id]);
Да, используя `nav`

2023-04-12 14:02 UTC, SevereCloud approved these changes

2023-04-12 14:05 UTC, eugpoloz approved these changes

2023-04-14 10:34 UTC, merged