feat(ButtonGroup): align button group buttons in horizontal mode
VKCOM/VKUI pull request #5125
Opened 2023-05-22 15:11 UTC by mendrew

fix #4651 

- [x] пример в документации обновлен.

## Changeset
- добавлена возможность выравнивания по правому/левому краю в режиме mode="horizontal".
- по умолчанию в `mode="horizontal"` `align-items` теперь `"center"`. Неявно оно было `"flex-start"` если `align` проп не передан, так как умолчанию он устанавливался в значение "left", или `"flex-end"` если `align="right"`.
- обновлен пример в документации.

2023-05-23 08:35 UTC, inomdzhon requested changes
<img width="222" alt="image" src="https://github.com/VKCOM/VKUI/assets/5850354/e5aaff23-883a-45bd-9bd0-376e7fbe15e6">

Из того, что улучшить:
1. _см. комменты_
2. Надо JSDoc параметра `align` поправить

2023-05-23 08:35 UTC, inomdzhon commented on packages/vkui/src/components/ButtonGroup/ButtonGroup.module.css
> +  align-items: center;
Учитывая, что изначально `align="left"` было, думаю как раз `flex-start` нужен

Вот, например, сравним две доки:

<img width="320" alt="image" src="https://github.com/VKCOM/VKUI/assets/5850354/9f302026-8353-40c5-bc9d-dd9a4f571eab">

**Рис. 1** Это https://vkcom.github.io/VKUI/5.4.2/#/ButtonGroup

<img width="320" alt="image" src="https://github.com/VKCOM/VKUI/assets/5850354/6ea25a8e-cc50-4adb-906f-a5bb01e5a9c7">

**Рис. 2** Это этот PR

2023-05-23 08:35 UTC, inomdzhon commented on packages/vkui/src/components/ButtonGroup/Readme.md
> +    align: 'undefined',
с `left` ведь тоже норм

в самом компоненте по умолчанию `left` в параметра

2023-05-23 08:35 UTC, inomdzhon commented on packages/vkui/src/components/ButtonGroup/Readme.md
> +      {((mode === 'vertical' && isNested) || !isNested) && (
Давай удалим проверку, чтобы `align` теперь был всегда, это ведь раньше была привилегия только `mode="vertical"`)

Ну и тогда `isNested` можно удалить

2023-05-23 08:35 UTC, inomdzhon commented on packages/vkui/src/components/ButtonGroup/Readme.md
> +      <div>The change to see on the page</div>
```suggestion
      <Div>The change to see on the page</Div>
```

чтобы добавить падинги, а то выравнивание поехало

<img width="490" alt="image" src="https://github.com/VKCOM/VKUI/assets/5850354/d0c79aed-c7b2-40f6-b823-4181c0c9d2d6">

2023-05-23 10:28 UTC, mendrew commented on packages/vkui/src/components/ButtonGroup/ButtonGroup.module.css
> +  align-items: center;
Согласен, так будет более ожидаемо. ⚡ https://github.com/VKCOM/VKUI/pull/5125/commits/88aed19b67cbec98ab1dd1452c5a5b1096c0577a

Также поправил JSDoc.

2023-05-23 10:28 UTC, mendrew commented on packages/vkui/src/components/ButtonGroup/Readme.md
> +    align: 'undefined',
Да, так как это был draft то я экспериментировал с тем как лучше всего выравнивание в доке показать. Особенно в примере со вложенной ButtonGroup.

2023-05-23 10:28 UTC, mendrew commented on packages/vkui/src/components/ButtonGroup/Readme.md
> +      {((mode === 'vertical' && isNested) || !isNested) && (
Удалил, и правда не нужно, достаточно просто всегда показывать этот `align` селект. ⚡ [Remove debug code](https://github.com/VKCOM/VKUI/pull/5125/commits/7d6e457a6819c16f553ad56beec78accd39d79ff)

2023-05-23 10:28 UTC, mendrew commented on packages/vkui/src/components/ButtonGroup/Readme.md
> +      <div>The change to see on the page</div>
Это вообще лишняя строчка, попала сюда пока я пытался понять что не так со сборкой. 🙂 Убрал!

2023-05-25 15:15 UTC, SevereCloud submitted a review, later dismissed

2023-05-26 12:35 UTC, mendrew commented
@inomdzhon разделил состояния у примера с Nested ButtonGroup ⚡ ee37776591b47c58bc6e92169a787d672224c1be

2023-05-26 16:29 UTC, inomdzhon approved these changes
🔥

2023-05-26 16:34 UTC, SevereCloud approved these changes

2023-05-29 10:00 UTC, merged