fix(PullToRefresh): Center spinner related to content
VKCOM/VKUI pull request #5279
Opened 2023-06-15 13:34 UTC by mendrew

Относится к #5220

- [ ] - Добавить скриншотные тесты для `FixedLayout` и `PullToRefresh` ?

## Изменения
Основные изменения в `FixedLayout`.
- Так как `PullToRefresh` оборачивает спиннер в `FixedLayout` компонент, который имеет `position: fixed` то и значение `width` в процентном соотношении берется относительно окна, а не прямого родителя в DOM дереве.
`FixedLayout` здесь нужен скорее всего, чтобы спиннер выезжал чуть выше родителя и струтура DOM не влияла на его позиционирование.

  В качестве решения добавлен проп `useParentWidth` в компонент `FixedLayout`, который заставляет компонет брать `width` родителя и применять к  `FixedLayout`. 
Похожая логика уже реализована для случая когда `FixedLayout` находится внутри `SplitCol`, но сама по себе она имеет в себе те же недостатки, что и баг в #5220, если родитель `PullToRefresh` имеет внутри отступы, которые смещают контент вместе с `PullToRefresh`, то спиннер не учитывает этого, и не центрирован относительно контента.

- `PullToRefresh` просто использует `FixedLayout` с пропом `useParentWidth`.

2023-06-20 14:40 UTC, SevereCloud submitted a review, later dismissed

2023-06-21 08:10 UTC, inomdzhon commented on packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e-playground.tsx
> +    <ComponentPlayground {...playgroundProps} platform={Platform.VKCOM} propSets={[]}>
Думаю лучше отдельно собрать этот пример, через `ConfigProvider`, `AdaptivityProvider` и `AppRoot`

Задача `ComponentPlayground` комбинировать пропсы переданные в `propsSets`

2023-06-21 08:12 UTC, inomdzhon commented on packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e.tsx
> +  test('PullToRefresh: renders spinner properly in default environment', async ({
Тут можно опустить PullToRefresh в названии, мы же уже указали название компонента в `test.describe`

![image](https://github.com/VKCOM/VKUI/assets/5850354/a078c576-ad1f-4e94-b115-54e7eee0c25f)

2023-06-21 08:52 UTC, mendrew commented on packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e-playground.tsx
> +    <ComponentPlayground {...playgroundProps} platform={Platform.VKCOM} propSets={[]}>
А по-моему как раз `ComponentPlayground` идеально тут подходит. Мне он очень понравился тем, что как раз создаёт всё что нужно компоненту: и `ConfigProvider`, и `AdaptivityProvider`, и `AppRoot`, и `Panel`, и `View`.
А то, что я не пользуюсь его фичей для комбинирования пропсов просто явно показывает, что он мне нужен для оберток и выставления platform.
Тем более, что `propSets` вообще необязательный проп, что говорит, о том, что это вполне правильное использование.
Скорее его можно было бы совсем убрать.

Вот если бы мне нужно было что-то, что он не поддерживает, тогда да, нужно было бы все объявлять.
А тут, как мне кажется, только лишним будет указывать всё то же что `ComponentPlayground` делает за нас, тест замылит, добавит больше шума, из виду потеряется использование padding.

2023-06-21 08:57 UTC, mendrew commented on packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e-playground.tsx
> +    <ComponentPlayground {...playgroundProps} platform={Platform.VKCOM} propSets={[]}>
Но если ты настаиваешь, то я добавлю, в этом что-то есть

2023-06-21 08:58 UTC, mendrew commented on packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e.tsx
> +  test('PullToRefresh: renders spinner properly in default environment', async ({
Точно, я добавил describe и забыл потом убрать из test!
⚡ https://github.com/VKCOM/VKUI/pull/5279/commits/4a7584acd68b0882904e0ff7ccbf4061db671714

2023-06-21 10:48 UTC, inomdzhon commented on packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e-playground.tsx
> +    <ComponentPlayground {...playgroundProps} platform={Platform.VKCOM} propSets={[]}>
Не настаиваю)

`ComponentPlayground` создавал на основе того, что уже было, не то, чтобы от него надо избавиться, просто не уверен, что его структура надёжна для тестов, где мы проверяем некий юз-кейс, а не строим сетку с комбинация пропсов

2023-06-21 11:01 UTC, mendrew commented on packages/vkui/src/components/PullToRefresh/PullToRefresh.e2e-playground.tsx
> +    <ComponentPlayground {...playgroundProps} platform={Platform.VKCOM} propSets={[]}>
На сколько я вижу у него текущая структура просто отлично подходит для таких вот кейсов, где просто нужны обертки.

2023-06-21 11:53 UTC, inomdzhon submitted a review, later dismissed

2023-06-21 12:18 UTC, SevereCloud requested changes
упал playwright + подлей плиз свежий мастер

2023-06-22 06:14 UTC, mendrew commented on packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-pulltorefresh-renders-spinner-properly-in-default-environment-vkcom-chromium-light-1-snap.png
Ого, а почему мы тогда пишем в PR, что все проверки прошли, хотя e2e тесты упали. Пока не заглянешь в Playwright report не узнаешь. 🤔

2023-06-22 07:06 UTC, mendrew commented on packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-pulltorefresh-renders-spinner-properly-in-default-environment-vkcom-chromium-light-1-snap.png
@SevereCloud Спасибо, что заметил!
 скриншоты поправил ⚡ https://github.com/VKCOM/VKUI/pull/5279/commits/3aaf06bb0de94f3ee738f005da0d2690cbb4887c
И мастер подлил.

2023-06-22 07:07 UTC, SevereCloud commented on packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-pulltorefresh-renders-spinner-properly-in-default-environment-vkcom-chromium-light-1-snap.png
> Ого, а почему мы тогда пишем в PR, что все проверки прошли, хотя e2e тесты упали. Пока не заглянешь в Playwright report не узнаешь. 🤔

@inomdzhon глянешь?

2023-06-22 07:08 UTC, SevereCloud approved these changes

2023-06-22 07:26 UTC, inomdzhon commented on packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-pulltorefresh-renders-spinner-properly-in-default-environment-vkcom-chromium-light-1-snap.png
> > Ого, а почему мы тогда пишем в PR, что все проверки прошли, хотя e2e тесты упали. Пока не заглянешь в Playwright report не узнаешь. 🤔
> 
> @inomdzhon глянешь?

Оки

2023-06-22 07:31 UTC, inomdzhon commented on packages/vkui/src/components/PullToRefresh/__image_snapshots__/pulltorefresh-pulltorefresh-renders-spinner-properly-in-default-environment-vkcom-chromium-light-1-snap.png
> > Ого, а почему мы тогда пишем в PR, что все проверки прошли, хотя e2e тесты упали. Пока не заглянешь в Playwright report не узнаешь. 🤔
> 
> @inomdzhon глянешь?

Оки

@mendrew пока что можно ориентироваться на аннотацию на странице экшена (https://github.com/VKCOM/VKUI/actions/runs/5342450024)

Если какой-то из тестов не пройдёт, то появится сообщение

<img width="320" src="https://github.com/VKCOM/VKUI/assets/5850354/4758fd12-5041-42f6-bbac-f16cf9125f54" />

_https://playwright.dev/docs/ci-intro#viewing-test-logs_

2023-06-22 07:31 UTC, inomdzhon approved these changes

2023-06-22 09:30 UTC, merged

2023-06-22 09:31 UTC, vkcom-publisher commented
## ❌ Patch

Не удалось автоматически применить исправление на стабильной ветке.

> Дальнейшие действия выполняют контрибьютеры из группы @VKCOM/vkui-core

Чтобы исправление попало в стабильную ветку, выполните следующие действия:

1. Создайте новую ветку от стабильной и примените исправления используя cherry-pick

```bash
git stash # опционально
git fetch origin 5.5-stable
git checkout -b patch/pr5279 origin/5.5-stable

git cherry-pick --no-commit 6b54302bf71ab0cc9b3cb1d8c349ba7ca40d925c
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit

git cherry-pick --no-commit 18d1bffdb853be8b25e1c46b3f8a89bcaa3db3a0
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit

git cherry-pick --no-commit 617eb037f8340c46259124bda7abb4ce00aedd9f
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit

git cherry-pick --no-commit edec8f4c536b1eb4a89428a41361e6d6c5f097d2
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit

git cherry-pick --no-commit 9e765747576962e7dae9a649ec3d0af3f311e7a0
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit

git cherry-pick --no-commit 0ccee50b89fbe757f6a0c15a6610a1831e84edfd
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit

git cherry-pick --no-commit e27ed398724f416e039e19fa54ac67558391b201
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit

git cherry-pick --no-commit ea4b3923727b92535f09ab49a5fff8578e4edf4e
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit

git cherry-pick --no-commit 52344804802754223030b4ea33b7f74545c27005
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit

git cherry-pick --no-commit 08adbc31082ebe4357782105a67ab574ea47a951
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit

git cherry-pick --no-commit e469d8e797e3f3d6a26e0c0820e960668f0e26ca
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit

git cherry-pick --no-commit 3aaf06bb0de94f3ee738f005da0d2690cbb4887c
git checkout HEAD --no-commit '**/__image_snapshots__/*.png'
git commit --no-verify --no-edit
```

2. Исправьте конфликты, следуя инструкциям из терминала
3. Отправьте ветку на GitHub и создайте новый PR с последней стабильной веткой (метка patch не нужна)

```bash
git push --set-upstream origin patch/pr5279
gh pr create --base 5.5-stable --title "patch: pr5279" --body "- patch #5279"
```