fix(Math.ts): updated `decimatedClamp` implementation
VKCOM/VKUI pull request #5284
Opened 2023-06-17 15:23 UTC by scffs

2023-07-07 10:01 UTC, scffs commented
а можно ревью пж

2023-07-11 10:32 UTC, inomdzhon requested changes
К сожалению, текущие изменения в PR ломают тесты, которые должны проходить без изменений (с одним исключением, см. **п.3** в комментарии к коду https://github.com/VKCOM/VKUI/pull/5284#discussion_r1259537022).

Ниже ссылка на песочницу, которая запускает две версии `rescale()`:

1. То, что предложил в комментарии к коду https://github.com/VKCOM/VKUI/pull/5284#discussion_r1259537022
2. То, что сейчас в VKUI 5.5.5

[Ссылка на песочницу](https://www.typescriptlang.org/play?#code/PQKhCgAIUwCEEVhBASIPQvCCA4QelCCIILhBB8IIPwgagAiB6BMIIAwgKekgjCDyDsIJGg4DwgqqagnCCSDCIJAFkAqgEkAXFBgALAC4yADgGcxwYAHMAljKkBXAEYA6AMYB7ALbAzOjZYCGMgKYAnDbYA2AWmvA9bk3uAANwBWAwBGAGYDAHZgeVsjAGtbNQdFS2sPPVtFB2BFJyNgHVyAZTcNABNnYrKK6qcDGUUAYgAZAA4ATg82sIAGYMlgcAAzHQA7IxkNEwnIVJkAEQcjDTN3AAUnVY1FWYmACgmdMzFIE7M9ZwBKSABvKEhVSAAVKT3IKVsJyrc0yDaByQIw5YEAdykDnml0gn0CzgAnpBFBs3G5IId+gZ+ri8f0wjcADSQABWikg4I06MBOic820nw0ExkJkgYQcHg6BieLwA6lCYac4RS9Bo1KknIDvvMwpATFL-ooKdofpAPHKtJS5gByGQLBz60wTBFORyVQFsxkUiYmGT2A4otlaHUU0bMhw8yBw0aYgT2KQGWx6RTHU53AA87Luj293uNin18TNFIAvBdTk0TABRAAe8jm0Jm7kONwMinkFRkhx1nJ1NwA3E943NE5ANjNlbYVms0ZtbGbIOnk80ANr9AC65crWhrBnro7CE6bccgOxkdPmhw7e0U3d2fYH+oA-O2HV2e+stkeDP8JmptJBzv07gBqSDJ3IiFmHEeKRcTiSAyNk8AC+4BPAm+rVL216DumlxZqUMguPepbTlWc4LkuK5roam6QDBV5uP2g6nkRh5mre0IPlIT6QP0TbgWMkzTI6TgmJMlQAGruDoDivCYyEOPIhyBHxDjnJc1xOCSiYiVJpwySSZjMopVy3A8kGtvqEwOAOaT6um-raAYHFcYcYkSeq7bMncwAoo48h3DA8nyJA76qRMuHrgRABySnOMc+k7ImWYAGIaLmDiVIciyXn2OxrPscyHG5NwZUxEFQSCbi2GY7nplZbj8epym2RMZXOCpti5lVTh3KmAB8TwmYGGy5tuzIkm1BhecV-E1bmmUQeMUwzHMhEHvYMUAMJ5QVxX1SpakZhpslnnVa3lW5x71TGTwaL6aVOUOCE6DSAA+l2OSJkARumL5aauvn0rl+WieJbgrRMQ0gd64EthMbbmb8MW8SVwLpqDPESYJwmfe4clOT9-14Rub1GAtokw+DEk-X9WUseN7FpKC-yHE8X2ldt1VPKMHFnJAo7SdVtNOIBTysucLOBRtrMc0STwmPIE3A+c9y3fIe3s5AoFDg8oFCwdQNtoo5MxQrlnU8CHiQAz5jjhO9mYgbZgATZZtGxl0CYqyFt6-bk5vpaRs+fhb0UTNlTzR9aUa5UJJO4BrtLiSIti4o5ZOSBzGgBAtuQIA6CAUAQvC4BQ8CsJAgAiIB4aBoMMxNsZNoUa24ABCdpSJT3o68t9OMzzAskgLnPetzzMt+z7fyqLBzKA8UsywLcsK-cSvgCrII6XhigXUZc8awNDgkmbQcmOH-etmjOWhQvADybgWtDZPuA4R+xTra+MxvW+Rzch3Hfvbj6gAhKmp-z6-l-T6rJj-AMM4DiThDgvxkCScBv9cLywcG4XIz04wJgAZ6PwagwFpAXpAzBP9j5o3AsxZBgCsYhVLE2cAZdz6V2rocAY-QSTjiAriEOo4ABMwR6GQFYfiEOks3LnDCGEYIcsQKUP+NQ7QWJwgMOxGEEkUQw7M1kfI8IvCpbPnCCIpsYi4FV0kZwxh7JmEMI8NifEeJggkjMeYxRfCnIaPMbiYRoEQJjAVJif4+oNAK0YnCe6RjfHeNfOmQkiCdESJrhoGRTDJwyOkeyNR-CGKaJcUTCC8dJBwHgBQQA3CAsAoIAMRA0CAHkQSAZBIDcQANKiEgKEOpRcxol3mDoy+tdID13ZkLb0Ztm581bnzXundebrX6etXuEcB4S2HvVMe6YJ7K0QTlLGH0tYdO7l5Zam19pDhaquXqHUuq-UEAGPqzIV5-Vcd01iYsPxJT2AcAASpxX4YZ1qbPkHclK8wQl-0gJ4-WCRWRSmMicgs4JaGcI+bsL5aNvSvXmL1GGryZK21GIChUJs0XTAVDAiCVySaTShclA4yLnDbNjHGeFmIAAGAASe4AtQLUowrOHU84bgW2upAHU9ZqL3m0Li+m1zHRe3NL7RaX1NkbM6VsmVu1yXNh9JiNyZ0MxXRuiqh6DFflwo9vMZZEqkYVUJoqwGSDZ5EoVkS+5qV0q4W9C8J5XF2nWVZBcEKhkKoeUgIkOUrknKKpyqKmKB9RijFyIva1XynUvMRc82KxUbJeRNulW2bkSREthc8ByMaLROB+KkP5NFHwAH1KgmHBBMEtlp3UGTbF5b1iRWFpoDauIN01zQPILVDW50LHnxsOL1UYfgFSWQ6kmuyzwpYuSlhmpKWaqUNvfAa0SwbKihvDYaKxJI11dvvA4fBeKZ7A31Orc+J9MQr0toza2U7DhWyXNew2zsZ2HHto+x2Jhb3vmDu7DG8w13itEme-4gdXaxNDiHCZrZo4iVjuAIAA)

2023-07-11 10:32 UTC, inomdzhon commented on packages/vkui/src/helpers/math.ts
> +  return precisionRound(decimatedValue, precision(step));
```suggestion
  const roundedValue = roundValueToStep(val, step, min);
  return clamp(roundedValue, min, max);
```

Далее:

1. Эти функции:
    ```diff
    - export function precisionRound(number: number, precision = 1) {
    - let factor = Math.pow(10, precision);
    -   return Math.round(number * factor) / factor;
    - }
    - function precision(number: number) {
    -   return (`${number}`.split('.')[1] || '').length;
    - }
    ```
    заменяем на:
    ```tsx
    /**
     * Решение скопировано без изменений у MUI:
     * https://github.com/mui/material-ui/blob/v5.13.7/packages/mui-base/src/useSlider/useSlider.ts#L89-L105
     */
    function getDecimalPrecision(num: number) {
      // This handles the case when num is very small (0.00000001), js will turn this into 1e-8.
      // When num is bigger than 1 or less than -1 it won't get converted to this notation so it's fine.
      if (Math.abs(num) < 1) {
        const parts = num.toExponential().split('e-');
        const matissaDecimalPart = parts[0].split('.')[1];
        return (matissaDecimalPart ? matissaDecimalPart.length : 0) + parseInt(parts[1], 10);
      }
    
      const decimalPart = num.toString().split('.')[1];
      return decimalPart ? decimalPart.length : 0;
    }
    
    function roundValueToStep(value: number, step: number, min: number) {
      const nearest = Math.round((value - min) / step) * step + min;
      return Number(nearest.toFixed(getDecimalPrecision(step)));
    }
    ```
2. Тесты на `precisionRound` соотвественно удаляем.
3. Этот тест
    https://github.com/VKCOM/VKUI/blob/ca312e58df945e2fa33c66624b624d6b4099e764/packages/vkui/src/helpers/math.test.ts#L42-L44

    будет падать

    <img width="320" alt="image" src="https://github.com/VKCOM/VKUI/assets/5850354/5ca3ffea-3355-4366-a57f-d0447b83eec6">

    что неверно – должен возвращать **3**.

    Вижу этот тест добавили в рамках #1684 из-за бага #1677, но этот бан не воспроизводиться, вот видео:

    <details><summary>Видео</summary>
    <p>
    
    https://github.com/VKCOM/VKUI/assets/5850354/b4c86d9c-e9e1-4305-8cdd-7a94ab26c047
    
    </p>
    </details> 

    тест результат в тесте поправим на **3**. Но описание будет неверное. Сможешь обозвать иначе?

2023-07-11 11:24 UTC, scffs commented on packages/vkui/src/helpers/math.ts
> +  return precisionRound(decimatedValue, precision(step));
Не поможешь с описанием для теста?)

2023-07-11 12:44 UTC, inomdzhon commented on packages/vkui/src/helpers/math.ts
> +  return precisionRound(decimatedValue, precision(step));
Давай так

```diff
- describe('non-divisor step', () => {
-     it('rounds to min + k * step when min != n * step', () => {
-       expect(rescale(0.1, [0.1, 3.1], [0.1, 3.1], { step: 2 })).toBe(0.1);
-       expect(rescale(3, [1, 5], [1, 5], { step: 2 })).toBe(3);
-     });
-     it('clamps to min + min(max, min + k * step) when max != min + n * step', () => {
-       expect(rescale(3, [0, 3], [0, 3], { step: 2 })).toBe(3);
-     });
- });

+ it('rounds to min when min != n * step', () => {
+   expect(rescale(0.1, [0.1, 3.1], [0.1, 3.1], { step: 2 })).toBe(0.1);
+ }
+
+ it('rounds to max when max != n * step', () => {
+   expect(rescale(3, [1, 5], [1, 5], { step: 2 })).toBe(3);
+   expect(rescale(3, [0, 3], [0, 3], { step: 2 })).toBe(3);
+ }
+
+ describe('check use cases', () =>
+   // см. https://github.com/VKCOM/VKUI/pull/5284
+   it('should return 20000', () => {
+     expect(rescale(100, [0, 100], [250, 20000], { step: 115 }).toBe(20000);
+   }
+ });
```

2023-07-11 14:03 UTC, inomdzhon approved these changes

2023-07-12 14:31 UTC, SevereCloud approved these changes

2023-07-12 15:11 UTC, merged

2023-07-12 15:12 UTC, vkcom-publisher commented
## ⚠️ Patch (forked repo)

Необходимо вручную перенести исправление в стабильную ветку.

> Дальнейшие действия выполняют контрибьютеры из группы @VKCOM/vkui-core

Чтобы исправление попало в стабильную ветку, выполните следующие действия:

1. Создайте новую ветку от стабильной и примените исправления используя cherry-pick

```bash
git stash # опционально
git fetch origin 5.6-stable
git checkout -b patch/pr5284 origin/5.6-stable

git cherry-pick --no-commit dab7f3819bbbaa13d2b10527a4baf79b2f63e20b
git checkout HEAD **/__image_snapshots__/*.png
git commit --no-verify --no-edit

git cherry-pick --no-commit 30b88f950e8455aae10241f9297a84191c2ef785
git checkout HEAD **/__image_snapshots__/*.png
git commit --no-verify --no-edit

git cherry-pick --no-commit 76829ce53dfc74d6bbea3159de34642aef2cb1cc
git checkout HEAD **/__image_snapshots__/*.png
git commit --no-verify --no-edit

git cherry-pick --no-commit ec1bef7bc19d831a6e66802aa3cbddbfa204904d
git checkout HEAD **/__image_snapshots__/*.png
git commit --no-verify --no-edit
```

2. Исправьте конфликты, следуя инструкциям из терминала
3. Отправьте ветку на GitHub и создайте новый PR с последней стабильной веткой (метка patch не нужна)

```bash
git push --set-upstream origin patch/pr5284
gh pr create --base 5.6-stable --title "patch: pr5284" --body "- patch #5284"
```