fix(fix-TextTooltip): add `useEventListener` on `wheel` event
VKCOM/VKUI pull request #5401
Opened 2023-07-02 04:37 UTC by scffs

- fixes #5393 

Возможно `pointerleave` вызывается при изменении положения курсора, а при скролле курсор может быть статичен. Обработка ивента `wheel` спасает.

2023-07-03 07:57 UTC, scffs commented
> Баг все еще воспроизводится

Можешь попробовать вернуть обработку wheel, как в моем первом коммите?

2023-07-03 09:02 UTC, scffs commented
> Если прокручивать туда сюда, то onTargetLeave будет постоянно вызываться. При этом TextTooltip не будет скрываться

Есть пример воспроизведения? Потому что у меня не очень получается туда сюда прокручивать

https://github.com/VKCOM/VKUI/assets/67464545/c98c083d-e69d-44de-b4c1-3dc2f5b8e1c2

2023-07-03 09:54 UTC, SevereCloud commented
на тачпаде можно легко воспроизвести
https://github.com/VKCOM/VKUI/assets/14944123/3082a924-8275-46b7-8dea-21821fcabb42

2023-07-03 13:38 UTC, scffs commented
> Если прокручивать туда сюда, то onTargetLeave будет постоянно вызываться. При этом TextTooltip не будет скрываться

Может

> на тачпаде можно легко воспроизвести
> 
>  2023-07-03.12.52.25.2.mov

Насколько это вообще юзеркейс ?)..

2023-07-03 13:43 UTC, scffs commented
Одно из решений - обнулить `hideDelay` или сделать его максимально низким, чтобы он успел отработать при таком скролле, но это решение явно не аппрувнут)

2023-07-05 07:34 UTC, SevereCloud commented
> Можно насильно скрывать без таймаутов, тогда hideDelay будет потерян только при скролле, что не так обидно

Давай скрывать сразу

2023-07-10 06:44 UTC, SevereCloud requested changes
Нужно еще на сам Popper повесить события, так как при прокрутке над всплывашкой, она не скрывается

2023-07-11 16:54 UTC, scffs commented
А почему драфт? Нашли решение лучше?

2023-07-12 12:57 UTC, inomdzhon commented
> А почему драфт? Нашли решение лучше?

см. https://github.com/VKCOM/VKUI/issues/5393#issuecomment-1629199236

2023-07-12 12:58 UTC, scffs commented
> > А почему драфт? Нашли решение лучше?
> 
> см. [#5393 (comment)](https://github.com/VKCOM/VKUI/issues/5393#issuecomment-1629199236)

Эх) https://github.com/VKCOM/VKUI/pull/5401#issuecomment-1618283526

2023-07-12 12:59 UTC, inomdzhon commented
> > > А почему драфт? Нашли решение лучше?
> > 
> > 
> > см. [#5393 (comment)](https://github.com/VKCOM/VKUI/issues/5393#issuecomment-1629199236)
> 
> Эх) [#5401 (comment)](https://github.com/VKCOM/VKUI/pull/5401#issuecomment-1618283526)

Решение хорошее, просто оно для кейса, когда тултип бы вообще не закрывался

Сейчас это оверхед

2023-07-12 13:00 UTC, scffs commented
> Сейчас это оверхед

Закрою PR?

2023-07-12 13:11 UTC, inomdzhon commented
> > Сейчас это оверхед
> 
> Закрою PR?

Да, давай пока закроем 👌

2023-07-12 13:11 UTC, closed without merging