feat(Cell): add auto scroll for draggable mode
VKCOM/VKUI pull request #5833
Opened 2023-09-19 17:19 UTC by inomdzhon

- close #5368
- [ ] Unit-тесты
- [ ] e2e-тесты
- [ ] Дизайн-ревью

## Описание

TODO

## Изменения

TODO

2023-10-25 10:31 UTC, mendrew reviewed
Потрясающая работа! 👏 👏 👏

Работает прекрасно! Очень непростая задача, как по мне!
Сделано классно! 🔥🔥🔥 Спасибо за тесты 💯 

Единственное, что стоит внимательнее посмотреть, это факт того, что иногда тригерится несколько `recalculation style` в коде, отвечающем за сдвиг элементов при драге. От того, что для определения необходимости сдвига мы читаем размеры и позицию элементов, потом меняем стили, а затем снова читаем размеры того же или уже других элементов и снова устанавливаем стили. 
В идеале мы должны сначала все значения прочитать, а потом уже сразу для всех элементов поменять стили, иначе браузеру, для того, чтобы в очередной раз прочитать размеры элемента после изменения стилей приходится пересчитывать геометрию, чтоб понять затронули ли последние изменения элемент и предоставить актуальные размеры.

Возможно, что это nitpick и не стоит тратить время, потому что результаты и так хорошие, в большинстве вызовом dramove `recalculation style` вызывается один раз, но мне сложно представить как это будет в более сложном реальном примере.

2023-10-25 10:31 UTC, mendrew commented on packages/vkui/src/components/Cell/useDraggable.tsx
> +    shiftDraggableEl(draggableEl, preservedDragShiftYRef.current);
А если чуть переделать и сначала читать, а потом писать, то `recalculate style` вызывается лишь раз в конце.
<img width="1518" alt="Снимок экрана 2023-10-25 в 13 00 55" src="https://github.com/VKCOM/VKUI/assets/5443359/22074c2a-84f1-489e-848f-c2ebefc04f0f">
И сама задача выполняется вместо ~4ms примерно ~2.5-3ms

2023-10-25 10:31 UTC, mendrew commented on packages/vkui/src/components/Cell/useDraggable.tsx
> +    shiftDraggableEl(draggableEl, preservedDragShiftYRef.current);
У меня получилось такого добиться, но в моём коде в итоге при достижении края scrollEl draggableElement чуть трясёт, наверное из-за неправильно просчитанных значений для DOMRect. Но мне кажется, что у нас есть все данные, чтобы это правильно высчитать.
<details>
<summary>
Вот diff на всякий случай как пример, хоть и не полностью рабочий.
</summary>

```diff
diff --git a/packages/vkui/src/components/Cell/useDraggable.tsx b/packages/vkui/src/components/Cell/useDraggable.tsx
index ea5fc4612..425dc2579 100644
--- a/packages/vkui/src/components/Cell/useDraggable.tsx
+++ b/packages/vkui/src/components/Cell/useDraggable.tsx
@@ -106,12 +106,18 @@ export const useDraggable = <T extends HTMLElement>({
   };
   const shiftOrUnshiftItems = (draggableElRect: DOMRect) => {
     itemEndIndexRef.current = itemStartIndexRef.current;
+    const itemElemRectList: DOMRect[] = [];
+    itemsRef.current.forEach((item) => {
+      const itemElRect = getBoundingClientRect(item.el);
+      itemElemRectList.push(itemElRect);
+    });
+
     itemsRef.current.forEach((item, itemIndex) => {
       if (itemStartIndexRef.current === itemIndex) {
         return;
       }
 
-      const itemElRect = getBoundingClientRect(item.el);
+      const itemElRect = itemElemRectList[itemIndex];
       const itemElRectHalfHeight = itemElRect.height / 2;
       const targetOverItem = draggableElRect.bottom >= itemElRect.top + itemElRectHalfHeight;
       const targetUnderItem = draggableElRect.top <= itemElRect.bottom - itemElRectHalfHeight;
@@ -218,10 +224,9 @@ export const useDraggable = <T extends HTMLElement>({
       lastDragDirectionRef.current = 'up';
     }
 
-    shiftDraggableEl(draggableEl, preservedDragShiftYRef.current);
+    const draggableElRect = getBoundingClientRect(draggableEl);
 
     const yEdgesOfViewport = getYEdgesOfViewport(window!, scrollElRect);
-    let draggableElRect = getBoundingClientRect(draggableEl);
     const { isOutside, shiftYOffset } = getElOverflowData(
       draggableElRect,
       offsetParentRect,
@@ -231,13 +236,13 @@ export const useDraggable = <T extends HTMLElement>({
     draggableElIsOutsideViewport.current = isOutside;
     lastDragShiftYRef.current = preservedDragShiftYRef.current + shiftYOffset;
 
+    shiftOrUnshiftItems(draggableElRect);
+
     if (draggableElIsOutsideViewport.current) {
       shiftDraggableEl(draggableEl, lastDragShiftYRef.current);
-      draggableElRect = getBoundingClientRect(draggableEl);
+    } else {
+      shiftDraggableEl(draggableEl, preservedDragShiftYRef.current);
     }
-
-    shiftOrUnshiftItems(draggableElRect);
-
     return { draggableElRect, yEdgesOfViewport };
   };
```
</details>

2023-10-25 10:31 UTC, mendrew commented on packages/vkui/src/components/Cell/useDraggable.tsx
> +    shiftDraggableEl(draggableEl, preservedDragShiftYRef.current);
Не знаю на сколько это критично будет в более сложных примерах. Может быть и не проблема, раз сейчас мы и так выдаём достаточное количество кадров в секунду. Но хотя бы `shiftOrUnshiftItems` я бы оптимизировал и посмотрел бы под этим углом на остальной код, но и не слишком заморачивался бы.

2023-10-26 18:18 UTC, inomdzhon commented on packages/vkui/src/components/Cell/Cell.e2e.tsx
> +      expect(await checkIfElementIsInsideYEdgesOfViewport('bottom', cellRootLocator, scrollElLocator, isGlobalScroll)).toBeTruthy(); // prettier-ignore
Угу, чтобы не громоздить

2023-11-15 09:26 UTC, SevereCloud requested changes
Попадали тесты

2023-11-16 08:25 UTC, inomdzhon commented on packages/vkui/src/lib/dom.tsx
✅

2023-11-16 08:28 UTC, inomdzhon commented on packages/vkui/src/components/Cell/utils.ts
✅

2023-11-16 08:33 UTC, inomdzhon commented on packages/vkui/src/components/HorizontalScroll/HorizontalScroll.tsx
> -function now() {
👍 

предполагаю версии браузеров в браузерлист были плачевней 🤔  

Вообще ревертнул это изменение, т.к. `now()` для задачи уже не нужен ⚡ dfc44aa1c8a492681da8ee21ca897567d93eb6ee

Отдельным PR удалим полифил

2023-11-16 12:07 UTC, SevereCloud approved these changes
👍

2023-11-16 12:15 UTC, inomdzhon commented on packages/vkui/src/components/Cell/CellDragger/CellDragger.tsx
>      </Touch>
⚡ a926a801563f212596f229c72ec3a9b5785147d2

ps: не смог закоммтить сажест 🤔

2023-11-16 12:15 UTC, SevereCloud approved these changes

2023-11-16 12:16 UTC, inomdzhon commented on packages/vkui/src/lib/dom.test.ts
> +
⚡ 0e30d8ffebfeebdb13b031daf562c5be05b21483

2023-11-16 15:06 UTC, mendrew approved these changes
Потрясающая работа 👏 👏 👏 

Спасибо!

2023-11-20 08:16 UTC, merged