BREAKING CHANGE: [Headlline] change default Component to span
VKCOM/VKUI pull request #6130
Opened 2023-11-22 14:07 UTC by mendrew

- close #4698 

---

- [x] Документация фичи

## Описание
Меняем тэг, в котором контент рендерится по-умолчанию , на `span`, потому что `Headline` в первую очередь визуальный компонент. Если надо поменять тэг, можно воспользоваться свойством `Component`.

2023-11-24 13:45 UTC, SevereCloud approved these changes

2023-11-24 13:45 UTC, SevereCloud requested changes
Нужна документация в мигрейшон гайд

2023-11-29 10:41 UTC, mendrew commented
@SevereCloud Обновил migration guide: https://github.com/VKCOM/VKUI/pull/6130/commits/7be5c7c56431c514de1fc15459a8e91fa53243d6

2023-11-29 10:47 UTC, inomdzhon approved these changes

2023-11-29 12:22 UTC, merged