BREAKING CHANGE: [Subhead] change default component to span
VKCOM/VKUI pull request #6133
Opened 2023-11-24 11:37 UTC by mendrew

- close #4697

---
- [x] Документация фичи

## Описание

Меняем тэг, в котором контент рендерится по-умолчанию , на `span`, потому что `Subhead` в первую очередь визуальный компонент. Если надо поменять тэг, можно воспользоваться свойством `Component`.

2023-11-24 11:39 UTC, eugpoloz commented on packages/vkui/src/components/Typography/Subhead/Readme.md
> +Тег элемента, в котором будет рендерится контент можно переопределить с помощью свойства `Component`.
```suggestion
Тег элемента, в котором будет рендериться контент, переопределяем с помощью свойства `Component`.
```

2023-11-24 11:50 UTC, mendrew commented on packages/vkui/src/components/Typography/Subhead/Readme.md
> +Тег элемента, в котором будет рендерится контент можно переопределить с помощью свойства `Component`.
🙈 С `ться` я согласен, спасибо, а вот с `тэг элемента..., переопределяем` не согласен.

Потому что это как раз возможность, а не призыв, требование.

2023-11-24 12:04 UTC, eugpoloz commented on packages/vkui/src/components/Typography/Subhead/Readme.md
> +Тег элемента, в котором будет рендерится контент можно переопределить с помощью свойства `Component`.
Я в целом не уверена, что нужно такое замечание отдельное, как будто у нас Component сейчас везде дает возможность переопределить тег, в котором будет рендериться контент.

Еще тесты завалились.(

2023-11-24 12:07 UTC, mendrew commented on packages/vkui/src/components/Typography/Subhead/Readme.md
> +Тег элемента, в котором будет рендерится контент можно переопределить с помощью свойства `Component`.
Я согласен, что это есть везде, но хочется это сделать более очевидным на этом конкретном этапе. Раз это появится как breaking change, то стоит рассказать как можно вернуться к старому поведению, если оно более приемлемое.

Потом можно будет убрать или перенести на отдельную страницу, где мы бы описали общие для всех компонентов свойства.

2023-11-24 13:44 UTC, SevereCloud approved these changes

2023-11-24 13:45 UTC, SevereCloud requested changes
Нужна документация в мигрейшон гайд

2023-11-29 12:54 UTC, mendrew commented
@SevereCloud обновли migration guide ⚡ https://github.com/VKCOM/VKUI/pull/6133/commits/6e8bf4bab141be90de2f8f6b7b8fed9c1ff4bf35

2023-11-29 12:57 UTC, inomdzhon approved these changes

2023-11-29 12:58 UTC, SevereCloud approved these changes

2023-11-29 12:59 UTC, merged