fix(README.md): update doc links to v6.0.0-beta.3
VKCOM/VKUI pull request #6324
Opened 2023-12-21 12:25 UTC by inomdzhon

## Описание

В https://www.npmjs.com/package/@vkontakte/vkui/v/beta сейчас не релевантные ссылки.

Перед релизом `v6` надо будет удалить пути до `v6.0.0-beta.*` (оставил **TODO**).

---

- related to #6257

2023-12-21 12:34 UTC, mendrew approved these changes

2023-12-21 12:35 UTC, SevereCloud approved these changes

2023-12-21 13:52 UTC, eugpoloz requested changes
С такими ссылками дока сейчас, до релиза 6.0.0-beta.3, ведет в никуда, а сам README висит не только в npm, но еще и на главной репозитория.

Надо либо переводить этот пулл в черновик пока и мерджить прямо перед запуском релизного workflow, или хотя бы ссылки на -beta.2 поставить.

2023-12-29 09:47 UTC, eugpoloz approved these changes

2023-12-29 09:57 UTC, merged