feat(snackbar): make the same vertical margin by bottom offset
VKCOM/VKUI pull request #6659
Opened 2024-03-05 00:04 UTC by akcent1132

- close #6306

---

- [ ] Unit-тесты
- [ ] e2e-тесты
- [ ] Дизайн-ревью
- [ ] Документация фичи

## Описание
Скомпенсировать снизу отступ action внутри snackbar
 

## Изменения
Выровнял отступ
![загруженное](https://github.com/VKCOM/VKUI/assets/14023577/524cb4dc-af91-4c00-bc77-fdae6c193b3c)

2024-03-07 09:57 UTC, inomdzhon reviewed
Спасибо за правку ✨ 

Решение имеет место быть, но из-за того, что у нас значения отступов "динамичные" и параметр `action` может быть не передан, нужно более универсальное решение.

2024-03-07 09:57 UTC, inomdzhon commented on packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.module.css
> +}
параметр `action` может быть не передан, посему стоит задать отрицательный нижний `margin` у `.Snackbar__action`

При но это при параметре адаптивности `<AdaptivityProvider sizeY="compact" />`, у `<Button size="s" />` высота `28px`, а высота текста `16px`. Отсюда `(28 - 16) / 2 = 6`, значит на `margin-block-end: -6px`.

<img width="372" alt="image" src="https://github.com/VKCOM/VKUI/assets/5850354/a57144b1-885f-45c4-ac1e-7766109b0a39">

А при `<AdaptivityProvider sizeY="regular" />`, у `<Button size="s" />` высота `30px`, а высота текста `18px`. Вертикальный отступ будет так же `6px`.

Но есть нюанс, что все эти значения под токенами, а токены пользователь может шатать. Посему нам нужно универсальное решение. 

```css
.Snackbar__action {
  margin-block-end: calc(-1 * (var(--vkui--size_button_small_height--compact) - var(--vkui--font_subhead--line_height--compact)) / 2);
}

.Snackbar--sizeY-regular .Snackbar__action {
  margin-block-end: calc(-1 * (var(--vkui--size_button_small_height--regular) - var(--vkui--font_subhead--line_height--regular)) / 2);
}
```

Тут для тебя челендж как в `Snackbar.tsx` выставлять `.Snackbar--sizeY-regular`, вот [документация по Адаптивности](https://github.com/VKCOM/VKUI/blob/master/docs/ADAPTIVITY_GUIDE.md).

<details><summary>Подсказка</summary>
<p>

Хук `useAdaptivityWithJSMediaQueries` уже применяется `Snackbar.tsx`. Нужно лишь получить параметр, проверять на него и выставлять только селектор `styles['Snackbar--sizeY-regular']`.

`.Snackbar--sizeY-compact` нам не нужен.

Пример можно найти тут https://github.com/VKCOM/VKUI/blob/v6.0.1/packages/vkui/src/components/ModalPage/ModalPage.tsx#L137

</p>
</details>

2024-03-12 18:07 UTC, akcent1132 commented on packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.module.css
> +}
спасибо за  ресёрч и решение. Стало сильно понятнее по адаптивности. Я просто и не понял что захардкодил так как кейс без action в примерах не ломался. 
![1710266733345](https://github.com/VKCOM/VKUI/assets/14023577/c92428fa-1c12-4e22-8e4a-d4f052b8fc95)

2024-03-13 07:26 UTC, inomdzhon reviewed
🤝 

PS: закрался пустой блок с комментариям – можешь нажать на "Apply suggestion", чтобы быстрей зарезолвить коммент

2024-03-13 07:26 UTC, inomdzhon commented on packages/vkui/src/components/Snackbar/Snackbar.tsx
> +  //
```suggestion

```

2024-03-14 09:25 UTC, inomdzhon approved these changes
👍

2024-03-14 10:00 UTC, mendrew submitted a review, later dismissed
🔥

2024-03-14 10:06 UTC, SevereCloud requested changes
Нужно поправить пару моментов

2024-03-14 10:46 UTC, SevereCloud requested changes

2024-03-14 10:46 UTC, SevereCloud commented on packages/vkui/src/components/Snackbar/Snackbar.tsx
> +          sizeY === 'regular' && styles['Snackbar--sizeY-regular'],
Для правильной работы медиавыражений нужно добавить переменную на ~16 строчку

```ts
const sizeYClassNames = {
  none: styles['Snackbar--sizeY-none'],
  ['regular']: styles['Snackbar--sizeY-regular'],
};
```

А тут требуется изменить на

```suggestion
          sizeY !== 'compact' && sizeYClassNames[sizeY],
```

2024-03-14 13:27 UTC, SevereCloud commented on packages/vkui/src/components/Snackbar/Snackbar.tsx
В данном файле менять ничего не нужно

2024-03-14 13:27 UTC, SevereCloud commented on packages/vkui/src/components/Snackbar/Snackbar.module.css
> +
В данном файле менять ничего не нужно

```suggestion
```

2024-03-14 13:27 UTC, SevereCloud commented on packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.tsx
> +  sizeY?: SizeTypeValues | 'none';
Параметр не нужен, используй хук `const { sizeY } = useAdaptivity();`

```suggestion
```

2024-03-15 07:38 UTC, inomdzhon reviewed
Сорри, проглядел, что надо было в **Snackbar.Basic** манипуляции делать :(

Спасибо @ SevereCloud, что заметил

2024-03-15 07:38 UTC, inomdzhon commented on packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.tsx
> +  const { sizeY } = useAdaptivity();
```suggestion
  const { sizeY = 'none' } = useAdaptivity();
```

по умолчанию приходит `undefined`

2024-03-15 07:38 UTC, inomdzhon commented on packages/vkui/src/components/Snackbar/subcomponents/Basic/Basic.tsx
> +        sizeY && sizeY !== 'compact' && sizeYClassNames[sizeY],
```suggestion
        sizeY !== 'compact' && sizeYClassNames[sizeY],
```

с учётом `sizeY = 'none'`

2024-03-19 09:12 UTC, inomdzhon approved these changes
👍 🙏

2024-03-19 10:38 UTC, merged

2024-03-20 06:15 UTC, akcent1132 commented
> 👍 🙏

@inomdzhon @SevereCloud  спасибо за подробные пояснительные комменты.