patch(v5): pr6663
VKCOM/VKUI pull request #6666
Opened 2024-03-07 10:08 UTC by mendrew

- cherry-pick #6663

2024-03-07 10:23 UTC, inomdzhon requested changes
см. https://github.com/VKCOM/VKUI/pull/6663#issuecomment-1983200842

2024-03-11 08:07 UTC, SevereCloud approved these changes

2024-03-12 10:39 UTC, inomdzhon approved these changes

2024-03-12 12:21 UTC, merged

2024-08-09 10:39 UTC, inomdzhon commented
<!-- disable_global_notification -->✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.2" target="_blank">v5.10.2</a> 🎉