feat(Calendar): check min and max date in head select
VKCOM/VKUI pull request #6937
Opened 2024-05-21 08:25 UTC by struchkov

- close #6936

## Описание
- related to #6936

## Изменения
Добавлены свойства minDateTime и maxDateTime в компонент CalendarHeader. Реализация ограничения выбора месяца и года, если последние выходят за допустимый интервал.

2024-05-21 09:58 UTC, mendrew reviewed
Огромное спасибо за отличный код! 🎉 

Несколько моментов, о которых стоит подумать.
Думаю, что стоит ещё поддержать свойства Calendar такие как` disablePast/disableFuture`, так как они тоже ограничивают доступность дат, и ожидается, что они также повлияют на опции селектов.

https://github.com/VKCOM/VKUI/blob/a4855167ce5e279e95a8af3b02ed49b4405e43a1/packages/vkui/src/hooks/useCalendar.ts#L31-L32


А также обновить компонент `CalendarRange`, который также использует `CalendarHeader` внутри.
https://github.com/VKCOM/VKUI/blob/a4855167ce5e279e95a8af3b02ed49b4405e43a1/packages/vkui/src/components/CalendarRange/CalendarRange.tsx#L56

Ещё, но это только в качестве идеи, возможно что и не стоит, так как навеяно лишь необходимостью прередавать 4 новых пропа в `CalendarHeader`.
можно было бы рассмотреть использование хука `useCalendar` для хранения логики, как сейчас сделано просто для дней календаря и передавать в `CalendarHeader` функцию, которая бы умела (по флагу) определять `disabled` состояние как для года, так и для месяца. (возможно лишнее)
https://github.com/VKCOM/VKUI/blob/a4855167ce5e279e95a8af3b02ed49b4405e43a1/packages/vkui/src/hooks/useCalendar.ts#L67-L86

2024-05-22 11:14 UTC, struchkov commented
- перенес логику проверки доступности месяца и года в хук `useCalendar`
- добавил поддержку свойств Calendar `disablePast/disableFuture`
- аналогичные  изменения внес в компонент `CalendarRange`
- в компоненте `CalendarHeader` добавил логику в проверки показа компонентов переключения предыдущего и последующего месяцев `nextMonthHidden` `prevMonthHidden`

Если подход правильный, могу покрыть тестами.

2024-05-22 13:37 UTC, mendrew requested changes

2024-05-22 13:37 UTC, mendrew commented on packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx
> +    (isMonthDisabled && isMonthDisabled(currentMonth === 11 ? 0 : currentMonth + 1));
Очень здорово!

Единственное, что смущает, это тернарный оператор и передаваемое тут значение.
Ведь если предположить, что у нас включен проп `disableFuture` и текущая дата 22.12.2024, то `isMonthDisabled(0) === false`, хотя следующий месяц январь 2025 и кнопка перехода на следующий месяц должна быть спрятана.
Сравнивать лишь месяц в таком случае недостаточно. 
https://github.com/struchkov/VKUI/blob/7cb9aaae94532a086fe7b9b45044c7bee7035a1f/packages/vkui/src/hooks/useCalendar.ts#L104

2024-05-24 17:40 UTC, struchkov commented on packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx
> +    (isMonthDisabled && isMonthDisabled(currentMonth === 11 ? 0 : currentMonth + 1));
Добавил параметр `year` в функцию `isMonthDisabled` - это позволило исправить логику. Поправил ошибки на крайних датах, тернариники постарался упростить для читаемости.

2024-05-27 08:32 UTC, mendrew reviewed
Выглядит шикарно, отличная работа! 🔥 🏅 

Покрой, пожалуйста, тестами.

2024-05-27 09:05 UTC, BlackySoul commented
Возможно, стоит обработать ещё вот такой вариант:

https://github.com/VKCOM/VKUI/assets/7431217/7c1a5efe-549e-4cc1-8ed8-2c7adabac9ff

2024-05-27 09:57 UTC, mendrew commented
> Возможно, стоит обработать ещё вот такой вариант:
> 2024-05-27.16.02.30.mov

А как бы ты это обработала? Не дала бы выбрать 24 год?
Я тоже это заметил, но посчитал, что это может вводить в заблуждение, что в целом 24 год не выбрать, не очень будет понятно, что год нельзя выбрать только потому, что месяц не тот стоит и он в 24 году недоступен.

Или сбрасывала бы в последний доступный месяц?

2024-05-27 10:02 UTC, BlackySoul commented
> > Возможно, стоит обработать ещё вот такой вариант:
> > 2024-05-27.16.02.30.mov
> 
> Или сбрасывала бы в последний доступный месяц?

Ага, у нас сейчас поведение такое, что сбрасываем до ближайшего доступного 🤔

2024-05-27 10:16 UTC, mendrew commented
> > > Возможно, стоит обработать ещё вот такой вариант:
> > > 2024-05-27.16.02.30.mov
> > 
> > 
> > Или сбрасывала бы в последний доступный месяц?
> 
> Ага, у нас сейчас поведение такое, что сбрасываем до ближайшего доступного 🤔

Даже не знаю. Легко незаметить что месяц поменялся вместе с годом. Я бы разозлился)

2024-05-27 10:41 UTC, mendrew commented
> > > > Возможно, стоит обработать ещё вот такой вариант:
> > > > 2024-05-27.16.02.30.mov
> > > 
> > > 
> > > Или сбрасывала бы в последний доступный месяц?
> > 
> > 
> > Ага, у нас сейчас поведение такое, что сбрасываем до ближайшего доступного 🤔
> 
> Даже не знаю. Легко незаметить что месяц поменялся вместе с годом. Я бы разозлился)

Обсудили с дизайном. Лучшим вариантом было бы сделать как в андройде. Где ты сначала год выбираешь, потом видишь все доступные месяца и выбираешь месяц, но это значит, что надо много переделывать.

Вариант дисейблить 24 год запутает пользователя, так как ему может быть не понятно по какой причине 24 год нельзя выбрать и он может начать перебирать месяца.

Вариант сбрасывать месяц до ближайшего доступного тоже может запутать, так как вроде бы пользователь меняет только год, а у него ещё и автоматом меняется месяц.

Решили, что лучше оставить так как есть.

2024-06-10 19:47 UTC, struchkov commented
@mendrew  Возвращаюсь, были неотложные дела. На неделе постараюсь разобраться со скриншотными тестами. Юнит тесты нужны? Вы покрываете ими хуки например?

2024-06-11 09:12 UTC, mendrew commented
> @mendrew Возвращаюсь, были неотложные дела. На неделе постараюсь разобраться со скриншотными тестами. Юнит тесты нужны? Вы покрываете ими хуки например?

Прекрасно!)
Да, юнит-тесты нужны, для хука `useCalendar` было бы здорово добавить хотя бы для новых функций.
И для `CalendarHeader` проверку на кнопок переключения месяцев. Наверное тут тоже лучше юнит тестами, так как на все варианты с датами показывать скриншотами может быть жирновато.
В общем на твоё усмотрение.

Сейчас скриншоты падают, потому что в пограничном варианте теперь нету кнопок переключения месяцев.
В общем-то валидно, я бы просто обновил скриншоты.

По тестированию, в том числе и по скриншотному, можно почитать [тут](https://github.com/VKCOM/VKUI/blob/master/docs/TESTING.md).

2024-06-17 06:11 UTC, struchkov commented
@mendrew  Немного изменил `isMonthDisabled` в `useCalendar` для значений вне промежутка между годами (такое наверное не может быть, но так правильнее). Добавил юнит тесты и обновил скриншоты для e2e.

2024-06-18 10:36 UTC, mendrew reviewed
Отличная работа, большое спасибо! 🥇 💯 

Только линтеры падают.

Ещё оставил пару коментариев, но они не обязательные, по желанию.
Если есть мысли, пиши!

2024-06-18 10:36 UTC, mendrew commented on packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx
> +  });
Тут я бы тоже не привязывался к селекторам. И постарался бы искать по тексту, при этом проверив, что это работает без `isYearDisabled`.

```suggestion
  it('does not fire onChange when click on year dropdown item if isYearDisabled return true', async () => {
    const onChange = jest.fn();
    jest.useFakeTimers();
    const component = render(
      <CalendarHeader viewDate={targetDate} onChange={onChange} changeYearLabel="Изменить год" />,
    );

    await userEvent.click(screen.getByLabelText('Изменить год'));
    await userEvent.click(screen.getByText('2020'));
    expect(onChange).toHaveBeenCalled();

    onChange.mockReset();

    component.rerender(
      <CalendarHeader
        isYearDisabled={() => true}
        viewDate={targetDate}
        onChange={onChange}
        changeYearLabel="Изменить год"
      />,
    );

    await userEvent.click(screen.getByLabelText('Изменить год'));
    await userEvent.click(screen.getByText('2020'));

    expect(onChange).not.toHaveBeenCalled();
  });

```

2024-06-18 10:36 UTC, mendrew commented on packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx
> +    [locale, currentYear, isMonthDisabled, isYearDisabled],
```suggestion
    [locale, isMonthDisabled],
```

Вроде бы лишние зависимости. Или это намеренно?

2024-06-18 12:56 UTC, struchkov commented on packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx
> +  });
Подумаю. Поиск по тексту мне показался не очень удачным, т.к. он завязан на локаль.

2024-06-18 13:04 UTC, struchkov commented on packages/vkui/src/components/CalendarHeader/CalendarHeader.tsx
> +    [locale, currentYear, isMonthDisabled, isYearDisabled],
https://github.com/VKCOM/VKUI/pull/6937/commits/8d73f12ca4b6d8601d405ae9fc6b602b9fc7a351

2024-06-18 13:06 UTC, mendrew commented on packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx
> +  });
Да, есть такое дело, лучше по testid но тут мы не даём их прокидывать, хотя могли бы, и даже стоило бы, опять же, чтобы пользователи библиотеки могли не звисеть от локали и приватных классов в e2e тестах.

2024-06-19 10:00 UTC, mendrew submitted a review, later dismissed
👍

2024-06-26 10:37 UTC, inomdzhon submitted a review, later dismissed
Спасибо 🙏 

Запустишь ещё раз [Update screenshot](https://github.com/struchkov/VKUI/actions/workflows/update_screens.yml), плиз, а то конфликт в скриншотных файлах.

2024-06-26 15:55 UTC, struchkov commented on packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx
> +    ).not.toBeTruthy();
Делаю с data-testid. Думаю, отдам это в отдельном PR, т.к. этот уже принят.

2024-06-26 15:56 UTC, struchkov commented on packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx
> +  });
Добавлю отдельным PR.

2024-06-26 16:53 UTC, mendrew commented on packages/vkui/src/components/CalendarHeader/CalendarHeader.test.tsx
> +    ).not.toBeTruthy();
Спасибо! Ждём-с обновления скриншотов, из-за конфликта.

2024-06-27 06:02 UTC, struchkov commented
Помержил с мастером, т.к. в мастере было обновление скриншотных тестов. После мержа обновил еще раз новые скриншоты для календаря. @mendrew  @inomdzhon

2024-06-27 06:08 UTC, mendrew approved these changes
💅

2024-06-27 09:23 UTC, inomdzhon approved these changes
🙏

2024-06-27 12:16 UTC, merged