feat: replace background modal token to contrast_themed
VKCOM/VKUI pull request #7044
Opened 2024-06-21 11:21 UTC by EldarMuhamethanov

- close #6956

---

- [x] e2e-тесты
- [ ] Дизайн-ревью

## Описание

Цвет Modal у нас используется не только для модалки, и мы сталкиваемся с проблемой: компоненты с модальным цветом теряются, когда расположены в модальном окне.

## Изменения

Заменил токен в следующих компонентах:
Calendar
Card
Popover
ScreenSpinner
SubnavigationButton
TabsItem
TooltipBase
WriteBar

2024-06-21 13:14 UTC, qurle requested changes
Спасибо! 
Кажется, не хватает изменений в `CalendarRange` и `CustomSelectDropdown`
Обсуждали остальные элементы, которые используют модальный цвет?

2024-06-21 13:57 UTC, inomdzhon commented on packages/vkui/src/components/TooltipBase/TooltipBase.module.css
> +/* Непонятно нужно ли заменять так как нет reversed стиля */
ааа, тьпу, наоборот заменять не нужно)

@qurle в **Tooltip**'ах и других плавающих элементах ведь не надо менять?

2024-06-21 14:04 UTC, qurle commented on packages/vkui/src/components/TooltipBase/TooltipBase.module.css
> +/* Непонятно нужно ли заменять так как нет reversed стиля */
> @qurle в Tooltip'ах и других плавающих элементах ведь не надо менять?

На мой взгляд замена уместна, потому что тултипы могут быть в модалках
Кроме того, они станут хуже читаться на обычном фоне, когда мы будем затеменять цвет `colorBackgroundModal`

Но, правда, про `reversed` я сам не очень понял.

2024-06-21 14:49 UTC, EldarMuhamethanov commented on packages/vkui/src/components/TooltipBase/TooltipBase.module.css
> +/* Непонятно нужно ли заменять так как нет reversed стиля */
В общем я этот коммент оставил для себя, на подумать и забыл убрать) Там ниже используется токен --vkui--color_background_modal_inverse, я думал, нужно ли его заменять на что-то но поскольку не нашел токена --vkui--color_background_contrast_themed_inverse оставил как есть

2024-06-21 15:11 UTC, qurle commented on packages/vkui/src/components/TooltipBase/TooltipBase.module.css
> +/* Непонятно нужно ли заменять так как нет reversed стиля */
А, понял
Да, давай оставим так пока что.

2024-06-21 15:12 UTC, qurle approved these changes

2024-06-24 07:30 UTC, SevereCloud approved these changes

2024-06-24 14:49 UTC, merged