feat(CustomScrollView): improve customScrollView code
VKCOM/VKUI pull request #7281
Opened 2024-08-01 14:26 UTC by EldarMuhamethanov

---

- [x] Unit-тесты

## Описание

Заметил, что хук useDetectScrllDirection можно оптимизировать. А именно убрать логику сброса scrollDirection по таймеру.

## Изменения

- Переписал логику хука useDetectScrollDirection без использования setTimeout. Проверил, что все работает также.
- В других файлах поменял логику if-ов, чтобы в будущем не покрывать кейс с `return`

2024-08-01 14:32 UTC, inomdzhon submitted a review, later dismissed
    🚀 
🔥

2024-08-01 14:32 UTC, inomdzhon commented on packages/vkui/src/components/CustomScrollView/useDetectScrollDirection.ts
> +    return scrollDirection;
nit:

```ts
    if (scrollTop !== lastScrollTop.current) {
      lastScrollTop.current = scrollTop;
      return 'vertical';
    }
    
    if (scrollLeft !== lastScrollLeft.current) {
      lastScrollLeft.current = scrollLeft;
      return 'horizontal';
    }
    
    return null;
```

2024-08-01 14:48 UTC, inomdzhon approved these changes

2024-08-01 14:58 UTC, inomdzhon submitted a review, later dismissed

2024-08-05 13:24 UTC, SevereCloud requested changes
От изменении логики if-а на самом деле покрытие не поменяется(если только на одну строку будет меньше). 

Такое изменение также убивает паттерн early return. Стоит вернуть if-ы назад

2024-08-05 13:40 UTC, EldarMuhamethanov commented
> От изменении логики if-а на самом деле покрытие не поменяется(если только на одну строку будет меньше).
> 
> Такое изменение также убивает паттерн early return. Стоит вернуть if-ы назад

Вернул if-ы назад

2024-08-05 13:46 UTC, SevereCloud approved these changes

2024-08-05 14:03 UTC, inomdzhon approved these changes

2024-08-05 14:17 UTC, merged