docs: use local path
VKCOM/VKUI pull request #7834
Opened 2024-10-24 13:54 UTC by SevereCloud

## Описание

Удалил ссылки на гитхаб мастера, для более удобной навигации внутри IDE и чтобы не ломались при изменении в мастере

## Release notes
-

2024-10-25 08:10 UTC, andrey-medvedev-vk approved these changes
💯

2024-10-25 08:34 UTC, inomdzhon approved these changes

2024-10-25 08:35 UTC, inomdzhon requested changes

2024-10-25 08:35 UTC, inomdzhon commented on README.md
> +С подробным списком можно ознакомиться в файле [.browserslistrc](.browserslistrc)
не сломает ссылки в NPM https://www.npmjs.com/package/@vkontakte/vkui ?

2024-10-25 08:47 UTC, SevereCloud commented on README.md
> +С подробным списком можно ознакомиться в файле [.browserslistrc](.browserslistrc)
Не сломает, npm будет ссылаться на https://github.com/VKCOM/VKUI/blob/HEAD/.browserslistrc

2024-10-25 12:30 UTC, inomdzhon submitted a review, later dismissed

2024-10-29 10:43 UTC, andrey-medvedev-vk approved these changes

2024-10-29 10:48 UTC, inomdzhon approved these changes

2024-10-29 10:48 UTC, merged