Better displayName for HOCs
VKCOM/VKUI pull request #965
Opened 2020-08-20 18:11 UTC by eolme-fallback

See: [Convention](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging)

2020-08-20 18:18 UTC, NekR requested changes

2020-08-20 18:18 UTC, NekR commented on src/hoc/withContext.tsx
> +  WithContext.displayName = `withContext{displayName})`;
Пропущено `($`

2020-08-20 18:18 UTC, NekR commented on src/hoc/withInsets.tsx
> +  WithInsets.displayName = `withInsets{displayName})`;
Пропущено `($`

2020-08-20 18:18 UTC, NekR commented on src/hoc/withPlatform.tsx
> +  WithPlatform.displayName = `withPlatform{displayName})`;
Пропущено `($`

2020-08-20 18:18 UTC, NekR commented on src/hoc/withAdaptivity.tsx
> +  AdaptivityConsumer.displayName = `withAdaptivity{displayName})`;
Пропущено `($`

2020-08-20 18:18 UTC, NekR commented on src/hoc/withAdaptivity.tsx
> +  const displayName = Component.displayName || Component.name || 'Component';
Может тоже в хелпер воткнуть, как в доке на которую этот PR ссылается?

2020-08-20 22:09 UTC, eolme-fallback commented
В общем, поправил тайпинги заодно, но нужно проверить, не поломал чего

2020-08-24 07:56 UTC, fedorov-xyz commented on src/helpers/getDisplayName.ts
> +export default function getDisplayName<T>(WrappedComponent: ComponentType<T>): string {
Мы будем отходить от дефолтных экспортов в пользу именованных.

2020-08-24 12:15 UTC, eolme-fallback commented on src/helpers/getDisplayName.ts
> +export default function getDisplayName<T>(WrappedComponent: ComponentType<T>): string {
Переименовал в componentUtils

2020-08-24 12:18 UTC, eolme-fallback commented
@fedorov-xyz, потом можно будет `getClassName` перенести в `componentUtils`

2020-08-24 15:10 UTC, ArthurStam commented
Нужно проверить, что дока собирается с такими хоками. Там были проблемы, что дока, с приходом TS, спотыкалась о компоненты, обернутые в хоки.

2020-08-25 00:03 UTC, eolme-fallback commented
Так и не удалось пофиксить до конца build - там проблема с конфликтом `prop-types` и `@react/types`. Как починить, так и не нашел, если вдруг кто знает решение - подскажите.

<details><summary>Логи</summary><p>

```
yarn run v1.22.4
$ yarn tsc && yarn babel && yarn tsc-es6 && yarn babel-es6 && yarn postcss && yarn copy-default-scheme
$ NODE_ENV=production tsc --emitDeclarationOnly --declaration
src/components/FixedLayout/FixedLayout.tsx(126,16): error TS2345: Argument of type 'typeof FixedLayout' is not assignable to parameter of type 'ComponentType<FixedLayoutProps>'.
  Type 'typeof FixedLayout' is not assignable to type 'ComponentClass<FixedLayoutProps, any>'.
    Types of property 'contextTypes' are incompatible.
      Type 'FixedLayoutContext' is not assignable to type 'ValidationMap<any>'.
        Index signature is missing in type 'FixedLayoutContext'.
src/components/FixedLayout/FixedLayout.tsx(128,3): error TS2345: Argument of type '"panelContext"' is not assignable to parameter of type 'never'.
src/components/FixedLayout/FixedLayout.tsx(129,18): error TS2345: Argument of type '"splitCol"' is not assignable to parameter of type 'never'.
src/components/PopoutRoot/PopoutRoot.tsx(61,31): error TS2345: Argument of type 'typeof PopoutRoot' is not assignable to parameter of type 'ComponentType<PopoutRootProps>'.
  Type 'typeof PopoutRoot' is not assignable to type 'ComponentClass<PopoutRootProps, any>'.
    Types of property 'contextTypes' are incompatible.
      Type 'PopoutRootContext' is not assignable to type 'ValidationMap<any>'.
        Index signature is missing in type 'PopoutRootContext'.
src/components/PullToRefresh/PullToRefresh.tsx(302,29): error TS2345: Argument of type 'typeof PullToRefresh' is not assignable to parameter of type 'ComponentType<PullToRefreshProps>'.
  Type 'typeof PullToRefresh' is not assignable to type 'ComponentClass<PullToRefreshProps, any>'.
    Types of property 'contextTypes' are incompatible.
      Type 'PullToRefreshContext' is not assignable to type 'ValidationMap<any>'.
        Index signature is missing in type 'PullToRefreshContext'.
src/components/Root/Root.tsx(211,16): error TS2345: Argument of type 'typeof Root' is not assignable to parameter of type 'ComponentType<RootProps>'.
  Type 'typeof Root' is not assignable to type 'ComponentClass<RootProps, any>'.
    Types of property 'contextTypes' are incompatible.
      Type 'RootContext' is not assignable to type 'ValidationMap<any>'.
        Index signature is missing in type 'RootContext'.
src/components/Root/Root.tsx(213,3): error TS2345: Argument of type '"splitCol"' is not assignable to parameter of type 'never'.
src/components/Root/Root.tsx(214,27): error TS2345: Argument of type '"configProvider"' is not assignable to parameter of type 'never'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</p></details>

2020-09-28 16:48 UTC, ArthurStam commented
Тут очень много разношерстных изменений, некоторые из которых я считаю ненужными, некоторые — недоработанными. Предлагаю подход "один pr — один фикс". Иначе сложно ревьювить и откатывать.

2020-09-28 20:12 UTC, eolme-fallback commented
Было бы проще, если бы библиотека не собиралось какой-то магией)
Ладно, как руки дойдут - разобью на отдельные.

2020-09-28 20:12 UTC, closed without merging