Feature/chips select
VKCOM/VKUI pull request #983
Opened 2020-08-27 20:59 UTC by korambo

2020-08-28 09:36 UTC, antoxxxa-2 commented on src/components/AsyncChipsSelect/AsyncChipsSelect.tsx
> +const AsyncChipsSelect: FC<AsyncChipsSelectProps<ChipsInputOption>> = <Option extends ChipsInputOption>({
а почему ChipsInputOption? скорее же этот компонент ближе к ChipsSelect

2020-08-28 09:36 UTC, antoxxxa-2 commented on src/components/AsyncChipsSelect/AsyncChipsSelect.tsx
> +const AsyncChipsSelect: FC<AsyncChipsSelectProps<ChipsInputOption>> = <Option extends ChipsInputOption>({
а это одна опция, понял

2020-08-28 09:38 UTC, antoxxxa-2 commented on src/components/AsyncChipsSelect/AsyncChipsSelect.tsx
> +          if (request === lastRequest) {
так не должно работать, надо или делать через useRef или вне компоннента делать глобальнгую для файла переменную

2020-08-28 09:42 UTC, antoxxxa-2 commented on src/components/ChipsInput/ChipsInput.tsx
> +    if (e.key === 'Backspace' && !e.defaultPrevented && !fieldValue && selectedOptions.length) {
мне кажется надо чуть более кроссбраузерно сделать. вроде key не все кидают

2020-08-28 09:43 UTC, antoxxxa-2 commented on src/components/ChipsInput/ChipsInput.tsx
> +    if (e.key === 'Backspace' && !e.defaultPrevented && !fieldValue && selectedOptions.length) {
хотя, вижу, что так и раньше было, оставим и посомтрим что VKUIщики скажут

2020-08-28 09:44 UTC, korambo commented on src/components/AsyncChipsSelect/AsyncChipsSelect.tsx
> +          if (request === lastRequest) {
с помощью useMemo я создаю замыкание связанное с конкретным обработчиком dataSource, при каждом запросе я обращаюсь к нему и сохраняю там идентификатор последнего запроса

2020-08-28 09:44 UTC, antoxxxa-2 commented on src/components/ChipsSelect/ChipsSelect.tsx
> +        focusOption(focusedOptionIndex, 'prev');
prev - next наверно надо в константы вынести

2020-08-28 09:50 UTC, antoxxxa-2 commented on src/components/AsyncChipsSelect/AsyncChipsSelect.tsx
> +          if (request === lastRequest) {
так суть в том, что когда придет ответ на конкретное замыкание, то lastRequest будет всегда равен request. как иначе? 

lastRequest должен быть глобальным, чтобы при каждом новом запросе его значени менялось, а в момент ответа исполняющий код имел текущее актуальное состояние.

2020-08-28 09:51 UTC, korambo commented on src/components/AsyncChipsSelect/AsyncChipsSelect.tsx
> +          if (request === lastRequest) {
24 строка

2020-08-28 10:23 UTC, antoxxxa-2 commented on src/components/AsyncChipsSelect/AsyncChipsSelect.tsx
> +          if (request === lastRequest) {
ааа) так да, кажется будет работать, но ты проверял на практике?)

2020-08-28 10:25 UTC, korambo commented on src/components/AsyncChipsSelect/AsyncChipsSelect.tsx
> +          if (request === lastRequest) {
конечно)

2020-09-03 08:31 UTC, NekR commented on src/components/ChipsInput/ChipsInput.tsx
> +    if (e.key === 'Backspace' && !e.defaultPrevented && !fieldValue && selectedOptions.length) {
Такое можно только если компонент десктоп онли. И старых браузеров только мобилки. То есть если он таки и мобильный, то нужно старым способом.

2020-09-04 05:53 UTC, NekR requested changes
В общем tl;dr ревью:
- Надо убрать AsyncChipsSelect
- MobileChipsSelect вроде ничего не делает. Если не нужен пока, давайте тоже уберём
- Нужно убрать лишние useCallback
- Отдельные types.ts файлы не нужны
- С CustomSelect/CustomSelectOption -- в идеале выносить весь выпадающий список, а не половину выносить и половину копипастить. Но может для unstable подойдёт и так
- Стало слишком много noop и дефолтных значений

2020-09-04 05:53 UTC, NekR commented on src/components/ChipsInput/ChipsInput.tsx
> +    if (e.key === 'Enter' && !e.defaultPrevented && fieldValue) {
Если этот код не только для десктопа, то нужно использовать более старый метод определения кнопки

2020-09-04 05:53 UTC, NekR commented on src/components/ChipsSelect/ChipsSelect.tsx
> +      dropdown.scrollTop = itemTop;
Есть вариант не копипастить эту логику из селекта, а вынести во что-то отдельное?

2020-09-04 05:53 UTC, NekR commented on src/components/ChipsSelect/ChipsSelect.tsx
> +                  <div className="ChipsSelect__empty">Ничего не найдено</div>
Текст нельзя, это библиотека

2020-09-04 05:53 UTC, NekR commented on src/components/ChipsSelect/ChipsSelect.tsx
> +                    label="Создать значение"
Текст нельзя

2020-09-04 05:53 UTC, NekR commented on src/components/ChipsSelect/ChipsSelect.tsx
> +    if (!hasMouse) {
Почему такие проверки?
Компонент уже весь завязан на мышку и вообще не будет работать нормально в других кейсах.

2020-09-04 05:53 UTC, NekR commented on src/components/ChipsSelect/ChipsSelect.tsx
> +    if (!hasMouse) {
Почему такие проверки?
Компонент уже весь завязан на мышку и вообще не будет работать нормально в других кейсах.

2020-09-04 05:53 UTC, NekR commented on src/components/ChipsSelect/types.ts
> +export interface ChipsSelectProps<Option extends ChipsInputOption> extends ChipsInputProps<Option> {
Можно ведь типы прямо в основном файле объявить

2020-09-04 05:53 UTC, NekR commented on src/components/ChipsSelect/useChipsSelect.ts
> +    const filteredSet = new window.Set(filteredOptions);
`window.` не обязателен тут

2020-09-04 05:53 UTC, NekR commented on src/components/CustomSelect/CustomSelect.css
> +s.CustomSelect__selectedIcon {
`s.`

2020-09-04 05:53 UTC, NekR commented on src/components/CustomSelect/CustomSelect.tsx
> +import { CustomSelectOptionProps } from '../CustomSelectOption/types';
Отдельный файл типов не нужен

2020-09-04 05:53 UTC, NekR commented on src/components/CustomSelect/CustomSelect.tsx
> +import CustomSelectOption from '../CustomSelectOption/CustomSelectOption';
В идеале нужно выносить не CustomSelectOptions, а весь выпадающий список, так как вы много всего из него используете.

2020-09-04 05:53 UTC, NekR commented on src/components/CustomSelect/CustomSelect.tsx
> +    renderOption({ index, label, ...otherProps }: CustomSelectOptionProps): ReactNode {
Почему это должна быть настраиваемая опция в случае CustomSelect?

2020-09-04 05:53 UTC, NekR commented on src/components/CustomSelectOption/CustomSelectOption.tsx
> +  onMouseEnter: noop,
Что-то слишком много таких noop и дефолтных свойств. Их можно просто не указывать, ко во всей остальной библиотеке

2020-09-04 05:53 UTC, NekR commented on src/components/FormField/FormField.css
> +  border-radius: 6px;
Почему в этом PR задеты стили для FormField?

2020-09-04 05:53 UTC, NekR commented on src/index.ts
> +export { default as CustomSelectOption } from './components/CustomSelectOption/CustomSelectOption';
Для какого кейса нужен этот экспорт?

2020-09-04 05:53 UTC, NekR commented on src/styles/styles.css
> +@import '../components/ChipsSelect/ChipsSelect.css';
Если ChipsSelect unstable то для него нужно отдельный файл стилей собирать тогда

2020-09-04 05:53 UTC, NekR commented on styleguide/Components/PlatformSelect.js
> +      <option value={OS.VKCOM}>{OS.VKCOM}</option>
Кажется это не относится к этому PR

2020-09-04 09:09 UTC, korambo commented on src/components/ChipsSelect/ChipsSelect.tsx
> +      dropdown.scrollTop = itemTop;
нужно менять логику CustomSelect, я не стал этого делать

2020-09-04 09:09 UTC, korambo commented on src/components/ChipsInput/ChipsInput.tsx
> +    if (e.key === 'Enter' && !e.defaultPrevented && fieldValue) {
только десктоп

2020-09-04 09:12 UTC, korambo commented on src/index.ts
> +export { default as CustomSelectOption } from './components/CustomSelectOption/CustomSelectOption';
Для работы с ChipSelect, a так как этот компонент совместим с CustomSelect - я вынес его в рутовый index.ts

2020-09-04 09:13 UTC, korambo commented on styleguide/Components/PlatformSelect.js
> +      <option value={OS.VKCOM}>{OS.VKCOM}</option>
отельным PR сделать или вы сами разберетесь?

2020-09-04 09:15 UTC, korambo commented on src/components/FormField/FormField.css
> +  border-radius: 6px;
Потому что обновленный дизайн филдов для `--vkcom` не сходится с тем что уже реализовано

2020-09-10 11:59 UTC, nickbullock commented on src/components/ChipsSelect/ChipsSelect.tsx
> +    if (!hasMouse) {
Изначально же планировалось что будет и десктоп и мобильная версия. Собственно конкретно эта проверка делает следующее: при клике мышкой открывает кастомную выпадаху (как в CustomSelect), а при клике пальцем превентит это дело, тк ожидается что будем работать с другим отображением для мобилки (как у SelectMimicry, например, отроется панель на весь размер вьюпорта). Но если компос desktop-only - неактуально.

2020-09-10 16:17 UTC, NekR commented on src/components/ChipsSelect/ChipsSelect.tsx
> +    if (!hasMouse) {
Проверка не до конца верная всё равно. Например, когда будет и мышка и тач, будет открываться всегда версия для мышки, даже если ткнули пальцем.

2020-10-09 08:34 UTC, ArthurStam reviewed
Нужно в доке как-то помечать, что компонент unstable. Щас это непонятно

2020-10-09 08:34 UTC, ArthurStam commented on src/styles/unstable.css
> +@import '../components/ChipsInput/ChipsInput.css';
Почему css подключается, в `unstable/index.ts` соответствующего экспорта нет?

2020-10-09 08:34 UTC, ArthurStam commented on src/components/CustomSelectOption/Readme.md
> +<View activePanel="сustomSelect">
Пример на практике выглядит непонятным. Почему бы не отрисовать тут юзкейсы с CustomSelect и ChipsSelect?

2020-10-09 08:34 UTC, ArthurStam commented on src/components/CustomSelectOption/CustomSelectOption.tsx
> +const CustomSelectOption: FC<CustomSelectOptionProps> = ({
Тут не реализован `...restProps`. Если мы экспортим этот компонент наружу, то у разработчиков точно появится запрос на `restProps`

2020-10-09 08:34 UTC, ArthurStam commented on src/components/ChipsSelect/ChipsSelect.tsx
> +      className={classNames('ChipsSelect CustomSelect__container', className)}
Чот тут совсем какой-то караул с классами. Я против использования классов одного компонента в другом.

2020-10-09 10:11 UTC, ArthurStam commented on src/components/ChipsSelect/ChipsSelect.tsx
> +import { SizeType } from '../..';
из index.ts импортить ничего нельзя, иначе будет import loop

2020-10-20 08:09 UTC, korambo commented on src/components/CustomSelect/CustomSelect.tsx
> +    renderOption({ index, label, ...otherProps }: CustomSelectOptionProps): ReactNode {
Недокументированная фича? Подумал раз уж есть возможность расширить функционал по примеру с ChipsSelect - почему бы и не добавить такую возможность в CustomSelect. Если это не нужно я уберу.

2020-10-20 08:11 UTC, korambo commented on src/components/CustomSelect/CustomSelect.tsx
> +import CustomSelectOption from '../CustomSelectOption/CustomSelectOption';
Это выглядит слегка усложненным, думаю такого функционала должно хватить

2020-10-20 08:47 UTC, korambo commented on src/components/ChipsSelect/useChipsSelect.ts
> +    const filteredSet = new window.Set(filteredOptions);
Добавил поддержку глобальных переменных es6 в eslint

2020-10-20 08:47 UTC, korambo commented on src/components/CustomSelect/CustomSelect.css
> +s.CustomSelect__selectedIcon {
+

2020-10-20 09:41 UTC, ArthurStam commented on src/components/CustomSelectOption/CustomSelectOption.tsx
> +      {...restProps}
restProps нужно пихать в начале. Щас у разработчика масса возможность сломать компонент. Например, прописав className, затерев наш.

2020-10-20 09:44 UTC, korambo commented on src/components/CustomSelectOption/CustomSelectOption.tsx
> +      {...restProps}
я наоборот думал что нужно давать возможность затереть все что уже определенно, сломал - сам виноват

2020-10-20 09:46 UTC, ArthurStam commented on src/components/CustomSelectOption/CustomSelectOption.tsx
> +      {...restProps}
Нет. `className` точно таким образом нельзя давать ломать.

2020-10-20 09:46 UTC, korambo commented on src/components/CustomSelectOption/CustomSelectOption.tsx
> +      {...restProps}
ок

2020-10-20 10:13 UTC, ArthurStam commented on src/components/CustomSelect/CustomSelect.tsx
> +      selected: !!selected,
Зачем тут преобразование в boolean, если это и так boolean?

2020-10-20 10:13 UTC, ArthurStam commented on src/components/CustomSelectOption/Readme.md
> +                    <ChipsSelect
тут явно не 2 пробела

2020-10-20 10:13 UTC, ArthurStam commented on src/components/CustomSelectOption/Readme.md
> +                          return (
и тут

2020-10-20 10:13 UTC, ArthurStam commented on src/components/ChipsSelect/Readme.md
> +      <Root activeView={activeView}>
Опять что-то с пробелами. У нас везде отступ в 2 пробела в доке.

2020-10-20 10:13 UTC, ArthurStam commented on src/components/ChipsSelect/ChipsSelect.tsx
> +        {...restProps}
Тут restProps нужно повыше

2020-10-20 10:13 UTC, ArthurStam commented on src/components/ChipsSelect/ChipsSelect.tsx
> +            [`ChipsSelect__options--sizeY-${sizeY}`]: !!sizeY,
Тут можно вынести этот класс из объекта и вставить в classNames вторым аргументом строкой `ChipsSelect__options--sizeY-${sizeY}`

2020-10-20 15:14 UTC, korambo commented on src/components/ChipsSelect/ChipsSelect.tsx
> +            [`ChipsSelect__options--sizeY-${sizeY}`]: !!sizeY,
пропс опциональный

2020-10-20 15:14 UTC, korambo commented on src/components/ChipsSelect/ChipsSelect.tsx
> +        {...restProps}
перетащил

2020-10-20 15:15 UTC, korambo commented on src/components/CustomSelect/CustomSelect.tsx
> +      selected: !!selected,
+, криво перенес

2020-10-20 15:16 UTC, korambo commented on src/components/CustomSelectOption/Readme.md
> +<View activePanel="сustomSelect">
Обновил

2020-10-20 15:21 UTC, korambo commented on src/components/CustomSelectOption/Readme.md
> +                    <ChipsSelect
+

2020-10-20 15:21 UTC, korambo commented on src/components/CustomSelectOption/Readme.md
> +                          return (
+

2020-10-20 15:21 UTC, korambo commented on src/components/ChipsSelect/Readme.md
> +      <Root activeView={activeView}>
+

2020-10-21 07:40 UTC, korambo commented on src/components/ChipsSelect/useChipsSelect.ts
> +  const handleInputChange = useCallback((e: ChangeEvent<HTMLInputElement>) => {
убрал

2020-10-21 13:09 UTC, NekR commented on src/components/CustomSelect/CustomSelect.tsx
> +    renderOption({ index, label, ...otherProps }: CustomSelectOptionProps): ReactNode {
Ладно, давай оставим, может пригодится)

2020-10-21 13:09 UTC, NekR submitted a review, later dismissed

2020-10-21 16:11 UTC, korambo commented on src/components/ChipsSelect/ChipsSelect.tsx
> +  inputClass?: string;
+

2020-10-21 16:11 UTC, korambo commented on src/components/ChipsSelect/ChipsSelect.tsx
> +  creatableText?: string;
\+

2020-10-21 16:13 UTC, korambo commented on src/components/ChipsSelect/ChipsSelect.tsx
> +        className={classNames(inputClass, {
привычка после работы с css-модулями, убрал

2020-10-21 16:14 UTC, korambo commented on src/components/ChipsSelect/ChipsSelect.tsx
> +        style={style}
\+

2020-10-21 16:19 UTC, korambo commented on src/components/ChipsSelect/ChipsSelect.tsx
> +  creatable?: boolean;
\+

2020-10-21 16:30 UTC, ArthurStam commented on src/components/ChipsSelect/Readme.md
> +                renderOption={({ index, label, option: { src }, ...otherProps }) => {
Тут index уже не нужен, вроде

2020-10-21 16:30 UTC, ArthurStam commented on src/components/CustomSelect/CustomSelect.tsx
> +          index,
Сюда index тоже не нужно передавать

2020-10-21 16:30 UTC, ArthurStam commented on src/components/CustomSelectOption/CustomSelectOption.tsx
> +  index?: number;
Тут нужен index?

2020-10-21 16:55 UTC, ArthurStam approved these changes

2020-10-21 16:58 UTC, merged