[Search] Fix unclickable zone on IOS
VKCOM/VKUI pull request #999
Opened 2020-09-05 06:39 UTC by Mkolba

Из-за того, что Search__after рисовался даже без фокуса, выделенная на скриншоте часть строки поиска была некликабельной на IOS
![image](https://user-images.githubusercontent.com/58112106/92299502-3309ad00-ef6c-11ea-8233-086f56934c40.png)

2020-09-28 13:56 UTC, ArthurStam commented
Привет. Спасибо за MR. Проблема в том, что твой фикс ломает анимацию скрытия "отмены". Попробуй сфокусироваться на поиске, а потом убрать фокус. "Отмена" моментально пропадет, а должна уезжать с анимацией.

2020-09-28 13:56 UTC, ArthurStam requested changes
Привет. Спасибо за MR. Проблема в том, что твой фикс ломает анимацию скрытия "отмены". Попробуй сфокусироваться на поиске, а потом убрать фокус. "Отмена" моментально пропадет, а должна уезжать с анимацией.

2020-10-01 20:19 UTC, eolme commented
@Mkolba, думаю `pointer-events: none` должен решить проблему

2021-07-15 09:16 UTC, ArthurStam commented
Закрываю, так как фикс некорректный. Добавил `pointer-events` по совету eolme #1737

2021-07-15 09:16 UTC, closed without merging